// Current target committed-copy operation slots only. Web writer: admincopy.js37-50/101-110,
// metadata.js115-146/159-168. Reservation stays permanent; metadata result is NOT copy receipt.
import {fail} from './security.js';
function rows(sql,query,...values){try{const result=sql.exec(query,...values).toArray();if(!Array.isArray(result)||result.length>2)fail(503,'DELETE_COPY_OPERATION_QUERY');return result;}catch{fail(503,'DELETE_COPY_OPERATION_QUERY');}}
function markers(sql,query,...values){const result=rows(sql,query,...values);for(const row of result)if(!row||Object.keys(row).length!==1||row.binding!==1)fail(503,'DELETE_COPY_OPERATION_QUERY');return result.length;}
export function inspectCopyOperationLinks(sql,gameId){
 if(typeof gameId!=='string'||!/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/.test(gameId))fail(503,'DELETE_COPY_OPERATION_TARGET');
 let size;try{size=sql.databaseSize;}catch{fail(503,'DELETE_COPY_OPERATION_QUERY');}if(!Number.isSafeInteger(size)||size<0)fail(503,'DELETE_COPY_OPERATION_QUERY');if(size>32*1024*1024)fail(503,'DELETE_COPY_OPERATION_BUDGET');
 const count=markers(sql,'SELECT 1 AS binding FROM copy_requests NOT INDEXED WHERE game_id=? LIMIT 2',gameId);if(count===0)return true;if(count!==1)fail(503,'DELETE_COPY_OPERATION_ROWS');
 for(const table of ['content_reservations','content_operations'])if(markers(sql,`SELECT 1 AS binding FROM ${table} AS o NOT INDEXED WHERE EXISTS(SELECT 1 FROM copy_requests AS r NOT INDEXED WHERE r.game_id=? AND o.actor COLLATE BINARY=r.actor COLLATE BINARY AND o.op_key COLLATE BINARY=r.op_key COLLATE BINARY) LIMIT 2`,gameId)!==1)fail(503,'DELETE_COPY_OPERATION_ROWS');
 const bad=markers(sql,`SELECT 1 AS binding FROM copy_requests AS r NOT INDEXED WHERE r.game_id=? AND NOT(
 typeof(r.game_id)='text' AND typeof(r.actor)='text' AND typeof(r.op_key)='text' AND typeof(r.request_digest)='text' AND typeof(r.auth_epoch)='integer' AND typeof(r.state)='text' AND r.state COLLATE BINARY='committed'
 AND EXISTS(SELECT 1 FROM content_games AS g NOT INDEXED WHERE typeof(g.game_id)='text' AND typeof(g.owner_id)='text' AND g.game_id COLLATE BINARY=r.game_id COLLATE BINARY AND g.owner_id COLLATE BINARY=r.actor COLLATE BINARY)
 AND EXISTS(SELECT 1 FROM content_reservations AS o NOT INDEXED WHERE typeof(o.actor)='text' AND typeof(o.op_key)='text' AND typeof(o.method)='text' AND typeof(o.target)='text' AND typeof(o.request_digest)='text' AND typeof(o.auth_epoch)='integer' AND o.actor COLLATE BINARY=r.actor COLLATE BINARY AND o.op_key COLLATE BINARY=r.op_key COLLATE BINARY AND o.method COLLATE BINARY='create' AND o.target COLLATE BINARY='new' AND o.request_digest COLLATE BINARY=r.request_digest COLLATE BINARY AND o.auth_epoch=r.auth_epoch)
 AND EXISTS(SELECT 1 FROM content_operations AS o NOT INDEXED WHERE typeof(o.actor)='text' AND typeof(o.op_key)='text' AND typeof(o.method)='text' AND typeof(o.target)='text' AND typeof(o.request_digest)='text' AND typeof(o.auth_epoch)='integer' AND typeof(o.result_json)='text' AND o.actor COLLATE BINARY=r.actor COLLATE BINARY AND o.op_key COLLATE BINARY=r.op_key COLLATE BINARY AND o.method COLLATE BINARY='create' AND o.target COLLATE BINARY='new' AND o.request_digest COLLATE BINARY=r.request_digest COLLATE BINARY AND o.auth_epoch=r.auth_epoch)
 ) LIMIT 1`,gameId);if(bad)fail(503,'DELETE_COPY_OPERATION_ROWS');
 if(markers(sql,`SELECT 1 AS binding FROM content_operations AS o NOT INDEXED WHERE EXISTS(SELECT 1 FROM copy_requests AS r NOT INDEXED WHERE r.game_id=? AND o.actor COLLATE BINARY=r.actor COLLATE BINARY AND o.op_key COLLATE BINARY=r.op_key COLLATE BINARY) AND length(CAST(o.result_json AS BLOB))>8192 LIMIT 1`,gameId))fail(503,'DELETE_COPY_OPERATION_BUDGET');
 const result=rows(sql,`SELECT o.result_json AS receipt,r.actor AS owner,length(CAST(o.result_json AS BLOB)) AS bytes FROM copy_requests AS r NOT INDEXED JOIN content_operations AS o NOT INDEXED ON o.actor COLLATE BINARY=r.actor COLLATE BINARY AND o.op_key COLLATE BINARY=r.op_key COLLATE BINARY WHERE r.game_id=? LIMIT 2`,gameId);
 if(result.length!==1)fail(503,'DELETE_COPY_OPERATION_ROWS');const row=result[0];if(!row||Object.keys(row).length!==3||typeof row.receipt!=='string'||typeof row.owner!=='string'||!Number.isSafeInteger(row.bytes)||row.bytes<0||row.bytes>8192)fail(503,'DELETE_COPY_OPERATION_QUERY');let value;try{value=JSON.parse(row.receipt);}catch{fail(503,'DELETE_COPY_OPERATION_ROWS');}
 if(!value||typeof value!=='object'||Array.isArray(value)||value.gameId!==gameId||value.ownerId!==row.owner||value.draftRevision!=='1'||value.rowRevision!=='1')fail(503,'DELETE_COPY_OPERATION_ROWS');return true;
}
