// Current target copy SQL provenance/receipt links only; NOT pinned policy, Source bytes or deletion authority.
// AdminFullCopy #source35/#write79/#execute89-111/#result54; profile.digest22/verify75; SnapshotVerifier63.
import {fail} from './security.js';
function query(sql,q,values,max=10001){let rows;try{rows=sql.exec(q,...values).toArray();}catch{fail(503,'DELETE_COPY_ORIGIN_QUERY');}if(!Array.isArray(rows)||rows.length>max||rows.some(r=>!r||typeof r!=='object'))fail(503,'DELETE_COPY_ORIGIN_QUERY');return rows;}
function markers(sql,q,values,max=10001){const rows=query(sql,q,values,max);if(rows.some(r=>Object.keys(r).length!==1||r.binding!==1))fail(503,'DELETE_COPY_ORIGIN_QUERY');return rows.length;}
export function inspectCopyOriginLinks(sql,gameId){
 if(typeof gameId!=='string'||!/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/.test(gameId))fail(503,'DELETE_COPY_ORIGIN_TARGET');
 let size;try{size=sql.databaseSize;}catch{fail(503,'DELETE_COPY_ORIGIN_QUERY');}if(!Number.isSafeInteger(size)||size<0)fail(503,'DELETE_COPY_ORIGIN_QUERY');if(size>32*1024*1024)fail(503,'DELETE_COPY_ORIGIN_BUDGET');
 const requests=markers(sql,'SELECT 1 AS binding FROM copy_requests NOT INDEXED WHERE game_id=? COLLATE BINARY LIMIT 2',[gameId],2),origins=markers(sql,'SELECT 1 AS binding FROM copy_origins NOT INDEXED WHERE game_id=? COLLATE BINARY LIMIT 2',[gameId],2);
 if(!requests&&!origins)return Object.freeze({copyOriginLinksVerified:true,copyReceiptLinksVerified:true});
 if(requests!==1||origins!==1)fail(503,'DELETE_COPY_ORIGIN_ROWS');let total=requests+origins;
 for(const table of ['copy_objects','content_snapshots']){const count=markers(sql,'SELECT 1 AS binding FROM '+table+' NOT INDEXED WHERE game_id=? COLLATE BINARY LIMIT 10001',[gameId]);total+=count;if(count>10000||total>20000)fail(503,'DELETE_COPY_ORIGIN_BUDGET');}
 const catalogs=markers(sql,'SELECT 1 AS binding FROM installed_sources AS c NOT INDEXED WHERE EXISTS(SELECT 1 FROM copy_requests AS r NOT INDEXED WHERE r.game_id=? COLLATE BINARY AND r.registry_id COLLATE BINARY=c.registry_id COLLATE BINARY) LIMIT 2',[gameId],2);total+=catalogs;if(total>20000)fail(503,'DELETE_COPY_ORIGIN_BUDGET');if(catalogs!==1)fail(503,'DELETE_COPY_ORIGIN_ROWS');
 const originText=['game_id','registry_id','definition_digest','catalog_root','profile_revision','baseline_root','baseline_digest','source_digest','dependency_digest'].map(f=>`typeof(o.${f})='text'`).join(' AND '),requestText=['game_id','actor','registry_id','definition_digest','catalog_root','profile_revision','state','result_json'].map(f=>`typeof(r.${f})='text'`).join(' AND '),hashes=['definition_digest','catalog_root','baseline_root','baseline_digest','source_digest','dependency_digest'].map(f=>`length(o.${f})=64 AND o.${f} NOT GLOB '*[^0-9a-f]*'`).join(' AND ');
 const valid=markers(sql,`SELECT 1 AS binding FROM copy_origins AS o NOT INDEXED JOIN copy_requests AS r NOT INDEXED ON r.game_id COLLATE BINARY=o.game_id COLLATE BINARY JOIN content_games AS g NOT INDEXED ON g.game_id COLLATE BINARY=o.game_id COLLATE BINARY JOIN installed_sources AS c NOT INDEXED ON c.registry_id COLLATE BINARY=o.registry_id COLLATE BINARY JOIN content_snapshots AS s NOT INDEXED ON s.game_id COLLATE BINARY=o.game_id COLLATE BINARY AND s.revision COLLATE BINARY='1' WHERE o.game_id=? COLLATE BINARY AND ${originText} AND ${requestText} AND ${hashes} AND typeof(g.game_id)='text' AND typeof(g.owner_id)='text' AND r.actor COLLATE BINARY=g.owner_id COLLATE BINARY AND r.state COLLATE BINARY='committed' AND r.registry_id COLLATE BINARY=o.registry_id COLLATE BINARY AND r.definition_digest COLLATE BINARY=o.definition_digest COLLATE BINARY AND r.catalog_root COLLATE BINARY=o.catalog_root COLLATE BINARY AND r.profile_revision COLLATE BINARY=o.profile_revision COLLATE BINARY AND typeof(c.registry_id)='text' AND typeof(c.definition_digest)='text' AND typeof(c.root_digest)='text' AND c.definition_digest COLLATE BINARY=o.definition_digest COLLATE BINARY AND c.root_digest COLLATE BINARY=o.catalog_root COLLATE BINARY AND typeof(s.game_id)='text' AND typeof(s.revision)='text' AND typeof(s.source_digest)='text' AND typeof(s.dependency_digest)='text' AND s.source_digest COLLATE BINARY=o.source_digest COLLATE BINARY AND s.dependency_digest COLLATE BINARY=o.dependency_digest COLLATE BINARY AND typeof(o.baseline_length)='integer' AND o.baseline_length BETWEEN 1 AND 16777216 AND EXISTS(SELECT 1 FROM copy_objects AS b NOT INDEXED WHERE b.game_id COLLATE BINARY=o.game_id COLLATE BINARY AND typeof(b.game_id)='text' AND typeof(b.sha256)='text' AND b.sha256 COLLATE BINARY=o.baseline_root COLLATE BINARY AND typeof(b.byte_length)='integer' AND b.byte_length=o.baseline_length AND typeof(b.state)='text' AND b.state COLLATE BINARY='committed') LIMIT 2`,[gameId],2);
 if(valid!==1||markers(sql,"SELECT 1 AS binding FROM copy_objects NOT INDEXED WHERE game_id=? COLLATE BINARY AND (typeof(state)<>'text' OR state COLLATE BINARY<>'committed') LIMIT 1",[gameId],1))fail(503,'DELETE_COPY_ORIGIN_ROWS');
 if(markers(sql,'SELECT 1 AS binding FROM copy_requests NOT INDEXED WHERE game_id=? COLLATE BINARY AND length(CAST(result_json AS BLOB))>8192 LIMIT 1',[gameId],1))fail(503,'DELETE_COPY_ORIGIN_BUDGET');
 const receipt=query(sql,'SELECT r.result_json AS receipt,o.source_digest AS source,o.baseline_digest AS baseline FROM copy_requests AS r NOT INDEXED JOIN copy_origins AS o NOT INDEXED ON r.game_id COLLATE BINARY=o.game_id COLLATE BINARY WHERE r.game_id=? COLLATE BINARY LIMIT 2',[gameId],2);
 if(receipt.length!==1||Object.keys(receipt[0]).length!==3||Object.values(receipt[0]).some(v=>typeof v!=='string'))fail(503,'DELETE_COPY_ORIGIN_QUERY');let value;try{value=JSON.parse(receipt[0].receipt);}catch{fail(503,'DELETE_COPY_RECEIPT_ROWS');}
 if(!value||Array.isArray(value)||typeof value!=='object'||Object.keys(value).sort().join(',')!=='baselineDigest,draftRevision,gameId,sourceDigest'||value.gameId!==gameId||value.draftRevision!=='1'||value.sourceDigest!==receipt[0].source||value.baselineDigest!==receipt[0].baseline)fail(503,'DELETE_COPY_RECEIPT_ROWS');
 return Object.freeze({copyOriginLinksVerified:true,copyReceiptLinksVerified:true});
}
