// Web SQL relationship contract: metadata.#insertSnapshot/#save/#snapshotReference; jobs.#enqueue/#owned.
// Root key digest and source digest are NOT necessarily equal (metadata.prepareSnapshot95-97).
// Pure current target checks only. No Source/body/permission/delete certificate.
import {fail} from './security.js';
function rows(sql,query,...values){let out;try{out=sql.exec(query,...values).toArray();}catch{fail(503,'DELETE_SAVED_JOB_QUERY');}if(!Array.isArray(out))fail(503,'DELETE_SAVED_JOB_QUERY');return out;}
function bounded(sql,table,id){const out=rows(sql,`SELECT 1 AS member FROM ${table} NOT INDEXED WHERE typeof(game_id)='text' AND game_id COLLATE BINARY=? LIMIT 10001`,id);if(out.some(r=>!r||Object.keys(r).length!==1||r.member!==1))fail(503,'DELETE_SAVED_JOB_QUERY');if(out.length>10000)fail(503,'DELETE_SAVED_JOB_BUDGET');return out.length;}
function none(sql,query,id){const out=rows(sql,query,id);if(out.length>1||out.some(r=>!r||Object.keys(r).length!==1||r.bad!==1))fail(503,'DELETE_SAVED_JOB_QUERY');if(out.length)fail(503,'DELETE_SAVED_JOB_ROWS');}
export function inspectSavedJobSnapshotLinks(sql,gameId){
 if(typeof gameId!=='string')fail(503,'DELETE_SAVED_JOB_ROWS');let size;try{size=sql.databaseSize;}catch{fail(503,'DELETE_SAVED_JOB_QUERY');}if(!Number.isSafeInteger(size)||size<0)fail(503,'DELETE_SAVED_JOB_QUERY');if(size>32*1024*1024)fail(503,'DELETE_SAVED_JOB_BUDGET');
 const count=bounded(sql,'content_snapshots',gameId)+bounded(sql,'compile_jobs',gameId)+bounded(sql,'content_games',gameId);if(count>20000)fail(503,'DELETE_SAVED_JOB_BUDGET');
 const current=rows(sql,"SELECT 1 AS member FROM content_games NOT INDEXED WHERE typeof(game_id)='text' AND game_id COLLATE BINARY=? LIMIT 2",gameId);if(current.length!==1||current[0]?.member!==1||Object.keys(current[0]).length!==1)fail(503,'DELETE_SAVED_JOB_ROWS');
 none(sql,"SELECT 1 AS bad FROM content_games g NOT INDEXED WHERE typeof(g.game_id)='text' AND g.game_id COLLATE BINARY=? AND (typeof(g.draft_revision)<>'text' OR NOT EXISTS(SELECT 1 FROM content_snapshots s NOT INDEXED WHERE typeof(s.game_id)='text' AND typeof(s.revision)='text' AND s.game_id COLLATE BINARY=g.game_id COLLATE BINARY AND s.revision COLLATE BINARY=g.draft_revision COLLATE BINARY)) LIMIT 1",gameId);
 none(sql,"SELECT 1 AS bad FROM compile_jobs j NOT INDEXED WHERE typeof(j.game_id)='text' AND j.game_id COLLATE BINARY=? AND (typeof(j.actor_id)<>'text' OR typeof(j.draft_revision)<>'text' OR typeof(j.root_key)<>'text' OR typeof(j.source_digest)<>'text' OR typeof(j.dependency_digest)<>'text' OR NOT EXISTS(SELECT 1 FROM content_games g NOT INDEXED JOIN content_snapshots s NOT INDEXED ON s.game_id COLLATE BINARY=g.game_id COLLATE BINARY WHERE typeof(g.game_id)='text' AND typeof(g.owner_id)='text' AND typeof(s.game_id)='text' AND typeof(s.revision)='text' AND typeof(s.root_key)='text' AND typeof(s.source_digest)='text' AND typeof(s.dependency_digest)='text' AND g.game_id COLLATE BINARY=j.game_id COLLATE BINARY AND g.owner_id COLLATE BINARY=j.actor_id COLLATE BINARY AND s.revision COLLATE BINARY=j.draft_revision COLLATE BINARY AND s.root_key COLLATE BINARY=j.root_key COLLATE BINARY AND s.source_digest COLLATE BINARY=j.source_digest COLLATE BINARY AND s.dependency_digest COLLATE BINARY=j.dependency_digest COLLATE BINARY)) LIMIT 1",gameId);
 return Object.freeze({savedJobSnapshotLinksVerified:true});
}
