// SQL links of current target TEXT committed PrivateDrafts receipts ONLY. NOT whole receipt DTO/Source/deletion authority.
// Primary writers/readers: drafts.js #receipt129-132/save156-197; metadata.js transaction115-146/#save169-179.
import {fail} from './security.js';
function query(sql,q,values,max=10001){let rows;try{rows=sql.exec(q,...values).toArray();}catch{fail(503,'DELETE_DRAFT_RECEIPT_QUERY');}if(!Array.isArray(rows)||rows.length>max||rows.some(r=>!r||typeof r!=='object'))fail(503,'DELETE_DRAFT_RECEIPT_QUERY');return rows;}
function markers(sql,q,values,max=10001){const rows=query(sql,q,values,max);if(rows.some(r=>Object.keys(r).length!==1||r.binding!==1))fail(503,'DELETE_DRAFT_RECEIPT_QUERY');return rows.length;}
export function inspectCommittedDraftReceiptLinks(sql,gameId){
 if(typeof gameId!=='string'||!/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/.test(gameId))fail(503,'DELETE_DRAFT_RECEIPT_TARGET');
 let size;try{size=sql.databaseSize;}catch{fail(503,'DELETE_DRAFT_RECEIPT_QUERY');}if(!Number.isSafeInteger(size)||size<0)fail(503,'DELETE_DRAFT_RECEIPT_QUERY');if(size>32*1024*1024)fail(503,'DELETE_DRAFT_RECEIPT_BUDGET');
 let total=0;for(const table of ['draft_requests','content_snapshots']){const count=markers(sql,'SELECT 1 AS binding FROM '+table+' NOT INDEXED WHERE game_id=? COLLATE BINARY LIMIT 10001',[gameId]);total+=count;if(count>10000||total>20000)fail(503,'DELETE_DRAFT_RECEIPT_BUDGET');}
 const committed="r.game_id=? COLLATE BINARY AND typeof(r.state)='text' AND r.state COLLATE BINARY='committed'";
 const operations=markers(sql,`SELECT 1 AS binding FROM content_operations AS o NOT INDEXED WHERE EXISTS(SELECT 1 FROM draft_requests AS r NOT INDEXED WHERE ${committed} AND r.actor COLLATE BINARY=o.actor COLLATE BINARY AND r.op_key COLLATE BINARY=o.op_key COLLATE BINARY) LIMIT 10001`,[gameId]);total+=operations;if(operations>10000||total>20000)fail(503,'DELETE_DRAFT_RECEIPT_BUDGET');
 const typed=['game_id','actor','op_key','request_digest','expected_revision','result_revision','result_json','root_key','source_digest','dependency_digest'].map(f=>`typeof(r.${f})='text'`).join(' AND ');
 const validOperation="typeof(o.actor)='text' AND typeof(o.op_key)='text' AND typeof(o.request_digest)='text' AND typeof(o.auth_epoch)='integer' AND typeof(o.method)='text' AND typeof(o.target)='text' AND typeof(o.result_json)='text' AND o.actor COLLATE BINARY=r.actor COLLATE BINARY AND o.op_key COLLATE BINARY=r.op_key COLLATE BINARY AND o.request_digest COLLATE BINARY=r.request_digest COLLATE BINARY AND o.auth_epoch=r.auth_epoch AND o.method COLLATE BINARY='save' AND o.target COLLATE BINARY=r.game_id COLLATE BINARY AND o.result_json COLLATE BINARY=r.result_json COLLATE BINARY";
 const snapshot="typeof(s.game_id)='text' AND typeof(s.revision)='text' AND typeof(s.root_key)='text' AND typeof(s.source_digest)='text' AND typeof(s.dependency_digest)='text' AND s.game_id COLLATE BINARY=r.game_id COLLATE BINARY AND s.revision COLLATE BINARY=r.result_revision COLLATE BINARY AND s.root_key COLLATE BINARY=r.root_key COLLATE BINARY AND s.source_digest COLLATE BINARY=r.source_digest COLLATE BINARY AND s.dependency_digest COLLATE BINARY=r.dependency_digest COLLATE BINARY";
 if(markers(sql,`SELECT 1 AS binding FROM draft_requests AS r NOT INDEXED WHERE ${committed} AND (NOT(${typed}) OR typeof(r.auth_epoch)<>'integer' OR NOT EXISTS(SELECT 1 FROM content_games AS g NOT INDEXED WHERE typeof(g.game_id)='text' AND typeof(g.owner_id)='text' AND g.game_id COLLATE BINARY=r.game_id COLLATE BINARY AND g.owner_id COLLATE BINARY=r.actor COLLATE BINARY) OR NOT EXISTS(SELECT 1 FROM content_operations AS o NOT INDEXED WHERE ${validOperation}) OR NOT EXISTS(SELECT 1 FROM content_snapshots AS s NOT INDEXED WHERE ${snapshot})) LIMIT 1`,[gameId],1))fail(503,'DELETE_DRAFT_RECEIPT_ROWS');
 if(markers(sql,`SELECT 1 AS binding FROM draft_requests AS r NOT INDEXED WHERE ${committed} AND length(CAST(r.result_json AS BLOB))>8192 LIMIT 1`,[gameId],1))fail(503,'DELETE_DRAFT_RECEIPT_BUDGET');
 const receipts=query(sql,`SELECT r.result_json AS receipt,r.expected_revision AS expected,r.result_revision AS revision,length(CAST(r.result_json AS BLOB)) AS bytes FROM draft_requests AS r NOT INDEXED WHERE ${committed} LIMIT 10001`,[gameId]);let bytes=0;
 for(const row of receipts){if(Object.keys(row).length!==4||typeof row.receipt!=='string'||typeof row.expected!=='string'||typeof row.revision!=='string'||!Number.isSafeInteger(row.bytes)||row.bytes<0)fail(503,'DELETE_DRAFT_RECEIPT_QUERY');bytes+=row.bytes;if(row.bytes>8192||bytes>8*1024*1024)fail(503,'DELETE_DRAFT_RECEIPT_BUDGET');if(!/^[1-9][0-9]{0,63}$/.test(row.expected))fail(503,'DELETE_DRAFT_RECEIPT_ROWS');let value;try{value=JSON.parse(row.receipt);}catch{fail(503,'DELETE_DRAFT_RECEIPT_ROWS');}if(!value||Array.isArray(value)||typeof value!=='object'||value.gameId!==gameId||value.draftRevision!==row.revision||![row.expected,String(BigInt(row.expected)+1n)].includes(row.revision))fail(503,'DELETE_DRAFT_RECEIPT_ROWS');}
 return Object.freeze({draftReceiptLinksVerified:true});
}
