// Bound copy HTTP associations only. Allocation target is an actor/key pair, NOT a job UUID or execution receipt.
import {createHmac,timingSafeEqual} from 'node:crypto';
import {fail} from './security.js';
const uuid=value=>typeof value==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/.test(value);
const hex=value=>typeof value==='string'&&/^[a-f0-9]{64}$/.test(value);
const key=value=>typeof value==='string'&&/^[A-Za-z0-9_-]{16,128}$/.test(value);
const targetWhere="typeof(t.kind)='text' AND t.kind COLLATE BINARY='copy' AND (t.game_id COLLATE BINARY=? OR EXISTS(SELECT 1 FROM copy_requests j NOT INDEXED WHERE typeof(j.game_id)='text' AND j.game_id COLLATE BINARY=? AND j.actor COLLATE BINARY=t.actor COLLATE BINARY AND j.op_key COLLATE BINARY=t.target_id COLLATE BINARY))";
const proofWhere="typeof(p.kind)='text' AND p.kind COLLATE BINARY='copy' AND (p.game_id COLLATE BINARY=? OR EXISTS(SELECT 1 FROM copy_requests j NOT INDEXED WHERE typeof(j.game_id)='text' AND j.game_id COLLATE BINARY=? AND j.actor COLLATE BINARY=p.actor COLLATE BINARY AND j.op_key COLLATE BINARY=p.target_id COLLATE BINARY))";
function query(sql,statement,args,columns,max=10001){let result;try{result=sql.exec(statement,...args).toArray();}catch{fail(503,'DELETE_COPY_COMMAND_QUERY');}if(!Array.isArray(result)||result.length>max)fail(503,'DELETE_COPY_COMMAND_QUERY');for(const row of result)if(!row||typeof row!=='object'||Array.isArray(row)||Object.keys(row).length!==columns.length||!columns.every(column=>Object.hasOwn(row,column)))fail(503,'DELETE_COPY_COMMAND_QUERY');return result;}
function markers(sql,statement,args){const result=query(sql,statement,args,['marker']);if(result.some(row=>row.marker!==1))fail(503,'DELETE_COPY_COMMAND_QUERY');return result.length;}
export function inspectCopyCommandLinks(sql,gameId,requestKey){
 if(!uuid(gameId))fail(503,'DELETE_COPY_COMMAND_TARGET');let size;try{size=sql.databaseSize;}catch{fail(503,'DELETE_COPY_COMMAND_QUERY');}if(!Number.isSafeInteger(size)||size<0)fail(503,'DELETE_COPY_COMMAND_QUERY');if(size>32*1024*1024)fail(503,'DELETE_COPY_COMMAND_BUDGET');
 const requests=markers(sql,"SELECT 1 AS marker FROM copy_requests NOT INDEXED WHERE typeof(game_id)='text' AND game_id COLLATE BINARY=? LIMIT 10001",[gameId]);
 const targets=query(sql,'SELECT t.kind,t.actor,t.op_key,t.game_id,t.target_id FROM content_http_command_targets t NOT INDEXED WHERE '+targetWhere+' LIMIT 10001',[gameId,gameId],['kind','actor','op_key','game_id','target_id']);
 const proofs=query(sql,'SELECT p.kind,p.actor,p.op_key,p.game_id,p.target_id,p.binding_mac FROM content_http_command_proofs p NOT INDEXED WHERE '+proofWhere+' LIMIT 10001',[gameId,gameId],['kind','actor','op_key','game_id','target_id','binding_mac']);
 const commands=markers(sql,'SELECT 1 AS marker FROM copy_http_commands c NOT INDEXED WHERE EXISTS(SELECT 1 FROM content_http_command_targets t NOT INDEXED WHERE t.actor COLLATE BINARY=c.actor COLLATE BINARY AND t.op_key COLLATE BINARY=c.op_key COLLATE BINARY AND '+targetWhere+') OR EXISTS(SELECT 1 FROM content_http_command_proofs p NOT INDEXED WHERE p.actor COLLATE BINARY=c.actor COLLATE BINARY AND p.op_key COLLATE BINARY=c.op_key COLLATE BINARY AND '+proofWhere+') LIMIT 10001',[gameId,gameId,gameId,gameId]);
 const counts=[requests,targets.length,proofs.length,commands];if(counts.some(n=>n>10000)||counts.reduce((a,b)=>a+b,0)>20000)fail(503,'DELETE_COPY_COMMAND_BUDGET');
 if((targets.length||proofs.length)&&!hex(requestKey))fail(503,'DELETE_COPY_COMMAND_KEY');let unsealed=0;
 for(const relation of targets){
  if(relation.kind!=='copy'||typeof relation.actor!=='string'||!relation.actor||!key(relation.op_key)||relation.game_id!==gameId||!key(relation.target_id))fail(503,'DELETE_COPY_COMMAND_ROWS');
  const parent=markers(sql,"SELECT 1 AS marker FROM copy_requests j NOT INDEXED JOIN content_games g NOT INDEXED ON j.game_id COLLATE BINARY=g.game_id COLLATE BINARY WHERE typeof(j.op_key)='text' AND typeof(j.actor)='text' AND typeof(j.game_id)='text' AND typeof(g.owner_id)='text' AND j.op_key COLLATE BINARY=? AND j.actor COLLATE BINARY=? AND j.game_id COLLATE BINARY=? AND g.owner_id COLLATE BINARY=? LIMIT 2",[relation.target_id,relation.actor,gameId,relation.actor]);if(parent!==1)fail(503,'DELETE_COPY_COMMAND_ROWS');
  const rows=query(sql,'SELECT actor,op_key,request_digest,auth_epoch FROM copy_http_commands NOT INDEXED WHERE actor COLLATE BINARY=? AND op_key COLLATE BINARY=? LIMIT 2',[relation.actor,relation.op_key],['actor','op_key','request_digest','auth_epoch'],2);const command=rows[0];if(rows.length!==1||command.actor!==relation.actor||command.op_key!==relation.op_key||!hex(command.request_digest)||!Number.isSafeInteger(command.auth_epoch)||command.auth_epoch<1)fail(503,'DELETE_COPY_COMMAND_ROWS');
  const bound=query(sql,"SELECT kind,actor,op_key,game_id,target_id,binding_mac FROM content_http_command_proofs NOT INDEXED WHERE kind COLLATE BINARY='copy' AND actor COLLATE BINARY=? AND op_key COLLATE BINARY=? LIMIT 2",[relation.actor,relation.op_key],['kind','actor','op_key','game_id','target_id','binding_mac'],2);if(bound.length>1)fail(503,'DELETE_COPY_COMMAND_PROOF');if(!bound.length){unsealed++;continue;}
  const proof=bound[0];if(['kind','actor','op_key','game_id','target_id'].some(field=>proof[field]!==relation[field])||!hex(proof.binding_mac))fail(503,'DELETE_COPY_COMMAND_PROOF');
  // Original JSON-array MAC binds stored HTTP epoch, NOT the allocation epoch/current owner or missing method/path/expected preimage.
  const encoded=JSON.stringify(['http-command-target-1',relation.kind,relation.actor,relation.op_key,relation.game_id,relation.target_id,command.request_digest,command.auth_epoch]);if(Buffer.byteLength(encoded)>8192)fail(503,'DELETE_COPY_COMMAND_BUDGET');const expected=createHmac('sha256',Buffer.from(requestKey,'hex')).update(encoded).digest();if(!timingSafeEqual(expected,Buffer.from(proof.binding_mac,'hex')))fail(503,'DELETE_COPY_COMMAND_PROOF');
 }
 for(const proof of proofs){if(proof.game_id!==gameId)fail(503,'DELETE_COPY_COMMAND_PROOF');const relation=query(sql,"SELECT kind,actor,op_key,game_id,target_id FROM content_http_command_targets NOT INDEXED WHERE kind COLLATE BINARY='copy' AND actor COLLATE BINARY=? AND op_key COLLATE BINARY=? LIMIT 2",[proof.actor,proof.op_key],['kind','actor','op_key','game_id','target_id'],2);if(relation.length!==1||['kind','actor','op_key','game_id','target_id'].some(field=>relation[0][field]!==proof[field]))fail(503,'DELETE_COPY_COMMAND_PROOF');}
 return Object.freeze({unsealedTargets:unsealed});
}
