// Configured Root-family STRUCTURAL absence for current selected keys only. NOT normal origin/full history/permission.
import {fail} from './security.js';
const selections=Object.freeze([
 ['copy','content_reservations','actor',"EXISTS(SELECT 1 FROM copy_requests p NOT INDEXED WHERE typeof(p.game_id)='text' AND p.game_id COLLATE BINARY=? AND typeof(p.actor)='text' AND typeof(p.op_key)='text' AND p.actor COLLATE BINARY=r.actor COLLATE BINARY AND p.op_key COLLATE BINARY=r.op_key COLLATE BINARY)"],
 ['draft','draft_requests','actor',"typeof(r.game_id)='text' AND r.game_id COLLATE BINARY=?"],
 ['compile','compile_operations','actor_id',"EXISTS(SELECT 1 FROM compile_jobs j NOT INDEXED WHERE typeof(j.game_id)='text' AND j.game_id COLLATE BINARY=? AND typeof(j.job_id)='text' AND j.job_id COLLATE BINARY=r.job_id COLLATE BINARY)"],
 ['command','copy_http_commands','actor',"EXISTS(SELECT 1 FROM content_http_command_targets t NOT INDEXED WHERE typeof(t.game_id)='text' AND t.game_id COLLATE BINARY=? AND typeof(t.kind)='text' AND t.kind COLLATE BINARY='copy' AND typeof(t.actor)='text' AND typeof(t.op_key)='text' AND t.actor COLLATE BINARY=r.actor COLLATE BINARY AND t.op_key COLLATE BINARY=r.op_key COLLATE BINARY)"],
 ['stage-command','stage_http_commands','actor',"EXISTS(SELECT 1 FROM content_http_command_targets t NOT INDEXED WHERE typeof(t.game_id)='text' AND t.game_id COLLATE BINARY=? AND typeof(t.kind)='text' AND t.kind COLLATE BINARY='stage' AND typeof(t.actor)='text' AND typeof(t.op_key)='text' AND t.actor COLLATE BINARY=r.actor COLLATE BINARY AND t.op_key COLLATE BINARY=r.op_key COLLATE BINARY)"],
 ['delete','content_deletion_operations','actor',"typeof(r.game_id)='text' AND r.game_id COLLATE BINARY=?"]
].map(x=>Object.freeze(x)));
const families=Object.freeze([['auth','operations','actor'],['source','source_operations','actor'],['copy','content_reservations','actor'],['command','copy_http_commands','actor'],['draft','draft_requests','actor'],['compile','compile_operations','actor_id'],['stage-command','stage_http_commands','actor'],['delete','content_deletion_operations','actor']].map(x=>Object.freeze(x)));
function query(sql,statement,gameId){try{const rows=sql.exec(statement,gameId).toArray();if(!Array.isArray(rows))fail(503,'DELETE_KEY_NAMESPACE_QUERY');return rows;}catch{fail(503,'DELETE_KEY_NAMESPACE_QUERY');}}
export function inspectSelectedKeyNamespaces(sql,gameId){
 if(typeof gameId!=='string'||!/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/.test(gameId))fail(503,'DELETE_KEY_NAMESPACE_TARGET');let size;try{size=sql.databaseSize;}catch{fail(503,'DELETE_KEY_NAMESPACE_QUERY');}if(!Number.isSafeInteger(size)||size<0)fail(503,'DELETE_KEY_NAMESPACE_QUERY');if(size>32*1024*1024)fail(503,'DELETE_KEY_NAMESPACE_BUDGET');let total=0;
 for(const[family,table,actorColumn,predicate]of selections){const rows=query(sql,`SELECT ${actorColumn} AS actor,op_key AS key,typeof(${actorColumn}) AS actorType,typeof(op_key) AS keyType FROM ${table} r NOT INDEXED WHERE ${predicate} LIMIT 10001`,gameId);total+=rows.length;if(rows.length>10000||total>20000)fail(503,'DELETE_KEY_NAMESPACE_BUDGET');for(const row of rows){if(!row||Object.keys(row).length!==4)fail(503,'DELETE_KEY_NAMESPACE_QUERY');if(row.actorType!=='text'||row.keyType!=='text'||typeof row.actor!=='string'||!row.actor||typeof row.key!=='string'||!/^[A-Za-z0-9_-]{16,128}$/.test(row.key))fail(503,'DELETE_KEY_NAMESPACE_ROWS');}
  for(const[other,foreign,otherActor]of families){if(other===family)continue;const collision=query(sql,`SELECT 1 AS collision FROM ${table} r NOT INDEXED WHERE (${predicate}) AND EXISTS(SELECT 1 FROM ${foreign} c WHERE c.${otherActor} COLLATE BINARY=r.${actorColumn} COLLATE BINARY AND c.op_key COLLATE BINARY=r.op_key COLLATE BINARY) LIMIT 1`,gameId);if(collision.length>1||collision.some(row=>!row||Object.keys(row).length!==1||row.collision!==1))fail(503,'DELETE_KEY_NAMESPACE_QUERY');if(collision.length)fail(503,'DELETE_KEY_NAMESPACE_COLLISION');}
 }
 return Object.freeze({selectedKeyNamespaceConflictsAbsent:true,normalRootOriginVerified:false});
}
