// Web Q20/product §5.1: administrator unlist locks; clear stays unlisted. No publish/list/content authority.
import {fail, fields} from './security.js';
const uuid=v=>typeof v==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/.test(v);
const revision=v=>typeof v==='string'&&v.length<=8192&&/^[1-9][0-9]*$/.test(v);
const key=v=>typeof v==='string'&&/^[A-Za-z0-9_-]{16,128}$/.test(v);
const methods=Object.freeze({'unlist':'admin-unlist','clear-restriction':'admin-clear-restriction'});
function parsed(value){try{return JSON.parse(value);}catch{fail(503,'MANAGEMENT_RECEIPT_CORRUPT');}}
export class GameManagement {
 #storage;#sql;#principal;#guard;
 constructor({storage,principal,operationGuard}){if(!storage?.sql||typeof storage.transactionSync!=='function'||typeof principal!=='function'||typeof operationGuard!=='function')throw new TypeError('same SQLite and trusted Root principal/reservation guard required');this.#storage=storage;this.#sql=storage.sql;this.#principal=principal;this.#guard=operationGuard;}
 #one(q,...v){return this.#sql.exec(q,...v).toArray()[0];}
 #actor(h){const a=this.#principal(h);if(a.must_change)fail(403,'PASSWORD_CHANGE_REQUIRED');if(a.role!=='admin')fail(403,'ADMIN_REQUIRED');return Object.freeze({id:a.id,epoch:a.epoch,role:a.role});}
 #session(h,a){const r=this.#one('SELECT u.id,u.epoch,u.role,u.disabled,u.must_change,s.epoch AS session_epoch,s.absolute_until,s.idle_until FROM sessions s JOIN users u ON s.user_id=u.id WHERE s.token_hash=?',h),now=Date.now();if(!r||r.disabled!==0||r.must_change!==0||!Number.isSafeInteger(r.absolute_until)||!Number.isSafeInteger(r.idle_until)||!Number.isSafeInteger(r.epoch)||!Number.isSafeInteger(r.session_epoch)||r.id!==a.id||r.epoch!==a.epoch||r.session_epoch!==a.epoch||r.role!=='admin'||now>=r.absolute_until||now>=r.idle_until)fail(401,'SESSION_INVALID');}
 #target(id){if(id==='wolong-builtin')fail(403,'BUILTIN_PROTECTED');if(!uuid(id))fail(422,'MANAGEMENT_GAME_ID');const r=this.#one('SELECT game_id,row_revision,listed,restricted FROM content_games WHERE game_id=? COLLATE BINARY',id);if(!r)fail(404,'GAME_NOT_FOUND');if(this.#one('SELECT game_id FROM content_deletion_fences WHERE game_id=? COLLATE BINARY',id))fail(409,'GAME_DELETING');if(r.game_id!==id||!revision(r.row_revision)||![0,1].includes(r.listed)||![0,1].includes(r.restricted)||!this.#one('SELECT game_id FROM content_used_ids WHERE game_id=? COLLATE BINARY',id))fail(503,'MANAGEMENT_ROW_CORRUPT');return r;}
 // Root's legacy guard skips optional tables without configured copies. Check retained known families too.
 #keySpace(actor,operationKey){this.#guard(actor,operationKey);for(const[table,column]of [['operations','actor'],['source_operations','actor'],['copy_http_commands','actor'],['draft_requests','actor'],['compile_operations','actor_id'],['stage_http_commands','actor'],['content_deletion_operations','actor']]){if(this.#one("SELECT name FROM sqlite_master WHERE type='table' AND name=?",table)&&this.#one('SELECT op_key FROM '+table+' WHERE '+column+'=? COLLATE BINARY AND op_key=? COLLATE BINARY',actor,operationKey))fail(409,'IDEMPOTENCY_CONFLICT');}}
 #receipt(a,id,row){if(row.auth_epoch!==a.epoch)fail(409,'OPERATION_REVOKED');if(row.actor!==a.id||row.target!==id||!Object.values(methods).includes(row.method)||typeof row.result_json!=='string'||Buffer.byteLength(row.result_json)>16384)fail(503,'MANAGEMENT_RECEIPT_CORRUPT');const reserved=this.#one('SELECT * FROM content_reservations WHERE actor=? COLLATE BINARY AND op_key=? COLLATE BINARY',a.id,row.op_key);if(!reserved||reserved.method!==row.method||reserved.target!==id||reserved.request_digest!==row.request_digest||reserved.auth_epoch!==row.auth_epoch)fail(503,'MANAGEMENT_RECEIPT_CORRUPT');const value=parsed(row.result_json);if(!value||Array.isArray(value)||Object.keys(value).sort().join(',')!=='action,eventAt,gameId,listed,restricted,rowRevision'||value.gameId!==id||typeof value.action!=='string'||!Object.hasOwn(methods,value.action)||methods[value.action]!==row.method||value.listed!==false||typeof value.restricted!=='boolean'||!revision(value.rowRevision)||typeof value.eventAt!=='string'||!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(value.eventAt)||(value.action==='unlist'&&!value.restricted)||(value.action==='clear-restriction'&&value.restricted))fail(503,'MANAGEMENT_RECEIPT_CORRUPT');return Object.freeze(value);}
 apply(h,operation,input){fields(input,['gameId','action','expectedRowRevision']);const v=Object.freeze({gameId:input.gameId,action:input.action,expectedRowRevision:input.expectedRowRevision}),op=Object.freeze({actor:operation?.actor,key:operation?.key,digest:operation?.digest,epoch:operation?.epoch});if(typeof v.action!=='string'||!Object.hasOwn(methods,v.action)||!revision(v.expectedRowRevision)||!key(op.key)||typeof op.digest!=='string'||!/^[a-f0-9]{64}$/.test(op.digest))fail(422,'MANAGEMENT_INPUT');return this.#storage.transactionSync(()=>{
  const a=this.#actor(h);if(a.id!==op.actor||a.epoch!==op.epoch)fail(401,'SESSION_INVALID');this.#keySpace(a.id,op.key);this.#session(h,a);const row=this.#target(v.gameId),method=methods[v.action],old=this.#one('SELECT * FROM content_operations WHERE actor=? COLLATE BINARY AND op_key=? COLLATE BINARY',a.id,op.key),reservation=this.#one('SELECT * FROM content_reservations WHERE actor=? COLLATE BINARY AND op_key=? COLLATE BINARY',a.id,op.key);
  for(const prior of [old,reservation]){if(prior&&(prior.method!==method||prior.target!==v.gameId||prior.request_digest!==op.digest))fail(409,'IDEMPOTENCY_CONFLICT');if(prior&&prior.auth_epoch!==a.epoch)fail(409,'OPERATION_REVOKED');}if(old){const result=this.#receipt(a,v.gameId,old);this.#session(h,a);return result;}if(reservation)fail(503,'MANAGEMENT_RECEIPT_CORRUPT');if(row.row_revision!==v.expectedRowRevision)fail(409,'GAME_CHANGED');
  const restricted=Number(v.action==='unlist'),changed=row.listed!==0||row.restricted!==restricted,next=changed?String(BigInt(row.row_revision)+1n):row.row_revision,eventAt=new Date().toISOString();if(next.length>8192)fail(503,'MANAGEMENT_REVISION_BUDGET');if(changed){const updated=this.#one('UPDATE content_games SET listed=0,restricted=?,row_revision=? WHERE game_id=? COLLATE BINARY AND row_revision=? COLLATE BINARY RETURNING game_id',restricted,next,v.gameId,row.row_revision);if(!updated)fail(409,'GAME_CHANGED');}
  const result={gameId:v.gameId,action:v.action,listed:false,restricted:Boolean(restricted),rowRevision:next,eventAt};this.#sql.exec('INSERT INTO content_reservations VALUES(?,?,?,?,?,?)',a.id,op.key,method,v.gameId,op.digest,a.epoch);this.#sql.exec('INSERT INTO content_operations VALUES(?,?,?,?,?,?,?,?)',a.id,op.key,method,v.gameId,op.digest,a.epoch,JSON.stringify(result),eventAt);this.#sql.exec('INSERT INTO content_audits VALUES(?,?,?,?,?,?,?)',crypto.randomUUID(),a.id,method,v.gameId,row.row_revision,next,eventAt);
  this.#keySpace(a.id,op.key);const current=this.#target(v.gameId);if(current.row_revision!==next||current.listed!==0||current.restricted!==restricted)fail(409,'GAME_CHANGED');this.#session(h,a);return Object.freeze(result);
 });}
 query(h,id,operationKey){if(!key(operationKey))fail(422,'IDEMPOTENCY_KEY');return this.#storage.transactionSync(()=>{const a=this.#actor(h);this.#target(id);const row=this.#one('SELECT * FROM content_operations WHERE actor=? COLLATE BINARY AND op_key=? COLLATE BINARY',a.id,operationKey);if(!row||row.target!==id||!Object.values(methods).includes(row.method))fail(404,'MANAGEMENT_OPERATION_NOT_FOUND');const result=this.#receipt(a,id,row);this.#session(h,a);return result;});}
}
