// Fixed local adoption with single coherent tuple switch. No saves/drafts/deployment.
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {join} from 'node:path';
import {BUILTIN_ENTITY_HISTORY} from '../web/src/editor/builtinentityhistory.generated.js';
import {checkDateDisplayInheritance,DATE_BASE_REVISION,DATE_BASE_SOURCE} from './date_display_inheritance.mjs';
import {decodeEntitySource} from '../web/src/editor/entitysource.js';
import {readInstalledEditorSource} from './editor_builtin_source.mjs';
import {installCoherentBuiltinRelease,RELEASE_WRAPPERS} from './atomic_builtin_release.mjs';
const root=fileURLToPath(new URL('../',import.meta.url)),[first,second]=process.argv.slice(2);assert.equal(process.argv.length,4);assert.equal(first,'date-adoption-r1');assert.equal(second,'date-adoption-r2');
const base='.dragon-analysis/editor-phase/',sha=b=>createHash('sha256').update(b).digest('hex'),inputs={};
function read(p){assert.ok(!/save\.dat/i.test(p));const bytes=readFileSync(join(root,p));inputs[p]=sha(bytes);return bytes;}
function json(bytes){try{return JSON.parse(bytes.toString('utf8'));}catch(cause){throw new TypeError('invalid fixed date install proof',{cause});}}
const oldPrefix=`content/builtin/compiled/${DATE_BASE_REVISION}/`,oldManifest=json(read('web/'+oldPrefix+'manifest.json')),oldAssets=new Map(oldManifest.assets.map(e=>[e.path,read('web/'+e.url)]));
const oldTuple=BUILTIN_ENTITY_HISTORY.find(t=>t.sourceRevision===DATE_BASE_REVISION);assert.ok(oldTuple);assert.equal(oldTuple.dataURL,oldPrefix+'data.json');
const baseResources={catalogURL:oldPrefix+'catalog.json',dataURL:oldTuple.dataURL,world:json(oldAssets.get('world-definition.json')),sourceURL:oldPrefix+'game-source.json',sourceDigest:DATE_BASE_SOURCE,geographyReview:'APPROVED'};
const a=json(read(base+first+'/receipt.json')),b=json(read(base+second+'/receipt.json'));assert.deepEqual(a,b);assert.equal(a.result,'PASS-DATE-MAP-INHERITANCE-STAGED-NOT-INSTALLED');
const proof=json(read(base+'date-adoption-session-r1/verify-r1.log'));assert.equal(proof.revision,a.revision);assert.equal(proof.result,'PASS-DATE-MAP-INHERITANCE-NOT-INSTALLED');assert.equal(proof.negativeControls,12);assert.equal(proof.productionFreshJsonRestore,20);assert.equal(proof.wrongPriorIdentityRejections,20);
const candidateFiles=['receipt.json','resources.json','author-descriptor.json','author-input/entity-source.json','author-input/manifest.json','package/manifest.json',...oldManifest.assets.map(e=>'package/'+e.path)];
const toolNames=['tools/stage_editor_date_adoption.mjs','tools/date_display_inheritance.mjs','tools/stage_editor_date_candidate.mjs','tools/editor_builtin_source.mjs','tools/editor_entity_source.mjs','web/src/content/builtinresources.generated.js','web/src/editor/builtinentitysource.generated.js','web/src/editor/entitysource.js','web/src/content/authoring/gamesource.js','web/src/content/authoring/trialcompile.js','web/src/content/authoring/mapcompile.js','web/src/content/authoring/maplayers.js','web/src/content/authoring/fixedcitybindings.js','web/src/content/authoring/roadedit.js','tools/verify_editor_date_candidate.mjs','web/src/game/scenarioassembly.js','web/src/game/world.js','web/src/game/worldresources.js','web/src/content/catalog.js','tools/verify_editor_date_app.mjs','tools/browser_test_server.mjs','web/src/main.js','web/src/game/clock.js','web/src/ui/hud.js','web/src/ui/gamebar.js','web/src/editor/trialpolicy.js','tools/verify_editor_date_adoption.mjs'];
const allowed=new Set(['web/'+oldPrefix+'manifest.json',...oldManifest.assets.map(e=>'web/'+e.url),'web/'+oldTuple.descriptor.manifestURL,'web/'+oldTuple.descriptor.resourceURL,'../Dragon/KI.EXE','docs/data/current-map-display-acceptance.json','docs/editor-date-adoption-contract.md','web/index.html',base+'date-app-session-r1/candidate-verify.log',base+'date-app-browser-r1/receipt.json',...toolNames,...['date-candidate-r3','date-candidate-r4'].flatMap(r=>candidateFiles.map(p=>base+r+'/'+p))]);
const files=new Map();for(const[p,h]of Object.entries(a.artifactHashes)){assert.match(p,/^(?:package\/(?:[A-Za-z0-9_-]+\.(?:json|bin|png)|chapters\/[A-Za-z0-9_-]+\.json)|author-input\/(?:entity-source|manifest)\.json|release\.json|builtinrelease\.generated\.js)$/);const bytes=read(base+first+'/'+p);assert.equal(sha(bytes),h);assert.deepEqual(bytes,read(base+second+'/'+p));files.set(p,bytes);for(const r of[first,second])allowed.add(base+r+'/'+p);}
for(const r of[first,second])allowed.add(base+r+'/receipt.json');
for(const[p,h]of Object.entries({...a.inputs,...proof.inputs,...proof.toolHashes})){assert.ok(allowed.has(p),'undeclared install input '+p);const bytes=read(p),relative=p.startsWith('web/')?p.slice(4):null;if(relative&&Object.hasOwn(RELEASE_WRAPPERS,relative)&&bytes.equals(Buffer.from(RELEASE_WRAPPERS[relative])))continue;assert.equal(sha(bytes),h,p);}
const release=json(files.get('release.json'));assert.deepEqual(release,a.release);const resources=release.resources,manifest=json(files.get('package/manifest.json')),assets=new Map(manifest.assets.map(e=>[e.path,files.get('package/'+e.path)]));
const certificate=checkDateDisplayInheritance({baseResources,baseManifest:oldManifest,baseAssets:oldAssets,resources:{...resources,geographyReview:'PENDING-DATE-DELTA'},manifest,assets,acceptanceBytes:read('docs/data/current-map-display-acceptance.json')});assert.deepEqual(manifest.displayAcceptanceInheritance,{...certificate,evidence:a.certificate.evidence});assert.equal(Object.hasOwn(manifest,'displayAcceptance'),false);assert.equal(manifest.dateCorrection.status,'APPLIED-ORIGINAL-WORD-IMPORT');
const observed=readInstalledEditorSource(resources,url=>{if(url.endsWith('/manifest.json'))return files.get('package/manifest.json');const prefix=`content/builtin/compiled/${a.revision}/`;assert.ok(url.startsWith(prefix));const p=url.slice(prefix.length);assert.ok(assets.has(p));return assets.get(p);});assert.equal(observed.revision,a.revision);
const d=release.entitySource,body=files.get('author-input/entity-source.json'),authorManifest=files.get('author-input/manifest.json');assert.equal(d.runtimeDataSha256,sha(assets.get('data.json')));assert.equal(d.resource.sha256,sha(body));assert.equal(d.manifestSha256,sha(authorManifest));assert.equal(d.manifestByteLength,authorManifest.length);
const authorPrefix=`content/builtin/authoring/entities-${sha(body)}/`;assert.equal(d.resourceURL,authorPrefix+'entity-source.json');assert.equal(d.manifestURL,authorPrefix+'manifest.json');
const author=await decodeEntitySource(json(authorManifest),body,d,sha),oldAuthor=json(read('web/'+oldTuple.descriptor.resourceURL)),probeAuthor=structuredClone(author);probeAuthor.runtimeDataSha256=oldAuthor.runtimeDataSha256;assert.deepEqual(probeAuthor,oldAuthor);
const moduleBytes=value=>Buffer.from('// Generated coherent resources/author-input tuple. One atomic switch point.\nfunction freeze(value) { if (value && typeof value === "object") { for (const child of Object.values(value)) freeze(child); Object.freeze(value); } return value; }\nexport const BUILTIN_RELEASE = freeze('+JSON.stringify(value)+');\n');
const newModuleBytes=moduleBytes(release);assert.deepEqual(newModuleBytes,files.get('builtinrelease.generated.js'));
const baseModuleBytes=moduleBytes({schemaVersion:1,resources:baseResources,entitySource:oldTuple.descriptor});
const atomicProof=json(read(base+'date-adoption-session-r1/atomic-r1.log'));assert.equal(atomicProof.result,'PASS-OWNED-ATOMIC-SWITCH-FAULTS');assert.equal(atomicProof.interruptionPoints,5);assert.equal(atomicProof.cases,12);assert.deepEqual(Object.keys(atomicProof.toolHashes),['tools/verify_atomic_builtin_release.mjs','tools/atomic_builtin_release.mjs']);for(const[p,h]of Object.entries(atomicProof.toolHashes))assert.equal(sha(read(p)),h);
for(const[p,h]of Object.entries(inputs))assert.equal(sha(readFileSync(join(root,p))),h,'input changed before controlled install');
const installed=installCoherentBuiltinRelease(join(root,'web'),{baseModuleBytes,newModuleBytes,assets:[...assets].map(([p,bytes])=>({path:`content/builtin/compiled/${a.revision}/`+p,bytes})).concat([{path:`content/builtin/compiled/${a.revision}/manifest.json`,bytes:files.get('package/manifest.json')},{path:authorPrefix+'entity-source.json',bytes:body},{path:authorPrefix+'manifest.json',bytes:authorManifest}]),previousWrapperSha256:Object.fromEntries(Object.keys(RELEASE_WRAPPERS).map(p=>[p,a.inputs['web/'+p]]))});
for(const[p,h]of Object.entries(inputs))if(!Object.hasOwn(RELEASE_WRAPPERS,p.slice(4)))assert.equal(sha(readFileSync(join(root,p))),h,'immutable input changed');
process.stdout.write(JSON.stringify({result:installed.result,revision:a.revision,sourceDigest:resources.sourceDigest,authorResourceSha256:d.resource.sha256,originalAcceptanceSha256:certificate.parentAcceptanceSha256,preservedOldRevision:DATE_BASE_REVISION,inputs,toolHashes:Object.fromEntries(['tools/install_editor_date_adoption.mjs','tools/atomic_builtin_release.mjs','tools/verify_atomic_builtin_release.mjs'].map(p=>[p,sha(readFileSync(join(root,p)))])),limits:'Local coherent defaults switch only. Old directories/history/drafts/saves untouched;not deploy/commit, new human approval, auth or full goal completion.'})+'\n');
