// Real local durable job transactions; engineering marker snapshots/opaque outputs, not full compiler/runtime proof.
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { randomBytes, randomUUID, createHash } from 'node:crypto';
import { pathToFileURL } from 'node:url';
import { request as httpsRequest } from 'node:https';
import { createEditorHTTPS } from './editor_local_https.mjs';
const { Miniflare } = await import(pathToFileURL(process.env.MINIFLARE_MODULE).href);
const d = '.dragon-analysis/editor-phase/backend-jobs-session-r1/', own = mkdtempSync(join(tmpdir(), 'dragon-jobs-')), origin = 'https://127.0.0.1:8787';
const initial = randomBytes(24).toString('hex'), password = randomBytes(24).toString('hex'), nextPassword = randomBytes(24).toString('hex'), secret = randomBytes(32).toString('hex');
const sha = b => createHash('sha256').update(b).digest('hex'), key = () => randomUUID();
function json(text) { try { return JSON.parse(text); } catch(cause) { throw new Error('invalid owned jobs fixture JSON', {cause}); } }
const files = ['server/jobs.js','tools/verify_editor_backend_job_ids.mjs',d+'fixture-worker.js','server/metadata.js','server/worker.js','server/blobs.js','tools/editor_local_https.mjs'];
const sourceHashes = Object.fromEntries(files.map(p=>[p,sha(readFileSync(p))]));let mf,front,bucket;
function build(compiler='engineering-1',profile='engineering-profile-1',stages=['validate','compile']) { return new Miniflare({name:'jobs-fixture',modules:true,scriptPath:resolve(d+'fixture-worker.js'),compatibilityDate:'2026-01-01',compatibilityFlags:['nodejs_compat'],modulesRules:[{type:'ESModule',include:['**/*.js','**/*.mjs']},{type:'Text',include:['**/*.html','**/*.txt','**/*.css']}],host:'127.0.0.1',port:0,https:false,durableObjects:{EDITOR_METADATA:{className:'JobsFixture',useSQLite:true}},durableObjectsPersist:join(own,'metadata'),r2Buckets:['EDITOR_BLOBS'],r2Persist:join(own,'blobs'),bindings:{EDITOR_ORIGIN:origin,EDITOR_DEFAULT_PASSWORD:initial,EDITOR_REQUEST_KEY:secret,EDITOR_ACCOUNT_LIMIT:'50',EDITOR_SOURCE_LIMIT:'100',FIXTURE_COMPILER:compiler,FIXTURE_PROFILE:profile,FIXTURE_STAGES:JSON.stringify(stages)}}); }
const calls=[];async function call(path,value,session) { const payload=JSON.stringify(value),headers={'Content-Type':'application/json',Origin:origin,'Idempotency-Key':key(),'Content-Length':Buffer.byteLength(payload)};if(session){headers.Cookie=session.cookie;headers['X-CSRF-Token']=session.csrf;}const r=await new Promise((done,reject)=>{const req=httpsRequest(origin+path,{method:'POST',headers,rejectUnauthorized:false,agent:false},res=>{const chunks=[];res.on('data',b=>chunks.push(b));res.on('error',reject);res.on('end',()=>done({status:res.statusCode,data:json(Buffer.concat(chunks).toString()),cookie:res.headers['set-cookie']?.[0]?.split(';')[0]}));});req.on('error',reject);req.end(payload);});calls.push({path,status:r.status});return r; }
const fixture=(v,s)=>call('/api/fixture/jobs',v,s);async function ok(v,s){const r=await fixture(v,s);assert.equal(r.status,200,r.data.error);return r.data;}
async function login(account) { const r=await call('/api/auth/login',{account,password:initial});assert.equal(r.status,200);const changed=await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:r.cookie,csrf:r.data.csrf});assert.equal(changed.status,200);return{cookie:changed.cookie,csrf:changed.data.csrf,user:changed.data.user}; }
async function reopen(compiler,profile,stages) { await front?.close();front=undefined;await mf?.dispose();mf=build(compiler,profile,stages);await mf.ready;front=await createEditorHTTPS(mf);bucket=await mf.getR2Bucket('EDITOR_BLOBS'); }
async function enqueue(game,s,k=key()){return ok({action:'enqueue',input:{key:k,gameId:game.gameId,draftRevision:game.draftRevision,scope:'all'}},s);}
async function claim(job,s,closed=false){return ok({action:'claim',operationId:job.operationId,expectedRevision:job.rowRevision,closed},s);}
const bytes=new Uint8Array([11,22,33]);async function output(job,assetId='data'){const item={assetId,sha256:sha(bytes),byteLength:bytes.length};await bucket.put('jobs/'+job.operationId+'/'+item.sha256,bytes);return item;}
async function busy(id,s){const end=Date.now()+5000;while(Date.now()<end){if((await ok({action:'busy',operationId:id},s)).busy)return;await new Promise(done=>setTimeout(done,20));}throw new Error('owned checkpoint did not enter controlled I/O');}
const checks=[];
try{
 await reopen();const admin=await login('tianyi');for(const account of['author_a','author_b'])assert.equal((await call('/api/admin/accounts',{account},admin)).status,200);const a=await login('author_a'),b=await login('author_b');
 const game=await ok({action:'create',metadata:{name:'任務甲',introduction:''}},a),other=await ok({action:'create',metadata:{name:'任務乙',introduction:''}},a);const initialGame=await ok({action:'game',gameId:game.gameId},a);
 const invalidIds=[null,true,false,0,1,{},[],['bad'],'','../escape','not-a-uuid','A'+randomUUID().slice(1),randomUUID()+String.fromCharCode(0)];
 const initialCount=(await ok({action:'count'},a)).count;let rejectedIds=0;
 for(const id of [...invalidIds,randomUUID()])for(const action of ['query','claim','retry','enqueue']){
  let value={action,operationId:id,expectedRevision:'1'};
  if(action==='enqueue')value={action,input:{key:key(),gameId:id,draftRevision:'1',scope:'all'}};
  else if(action==='retry')value={action,input:{key:key(),operationId:id,expectedRevision:'1'}};
  const denied=await fixture(value,a),malformed=invalidIds.includes(id);
  let expectedCode=action==='enqueue'?'GAME_NOT_FOUND':'JOB_NOT_FOUND';
  if(malformed)expectedCode=action==='enqueue'?'JOB_GAME_ID':'JOB_ID';
  assert.equal(denied.status,malformed?422:404);assert.equal(denied.data.error,expectedCode);rejectedIds++;
 }
 assert.equal(rejectedIds,56);assert.equal((await ok({action:'count'},a)).count,initialCount);assert.equal((await ok({action:'game',gameId:game.gameId},a)).modifiedAt,initialGame.modifiedAt);
 checks.push('actual malformed IDs52reject422 plus valid unknown IDs4still404, no SQL job row or game modifiedAt change; prior static500 hypothesis not reproduced');
 const k=key(),input={key:k,gameId:game.gameId,draftRevision:'1',scope:'all'},two=await Promise.all([fixture({action:'enqueue',input},a),fixture({action:'enqueue',input},a)]);for(const r of two)assert.equal(r.status,200);let job=two[0].data;assert.equal(job.operationId,two[1].data.operationId);assert.equal((await ok({action:'count'},a)).count,1);
 for(const session of[a,b,admin])for(const action of['query','claim','retry','enqueue']){
  let value={action,operationId:[job.operationId],expectedRevision:job.rowRevision};
  if(action==='enqueue')value={action,input:{key:key(),gameId:[game.gameId],draftRevision:'1',scope:'all'}};
  else if(action==='retry')value={action,input:{key:key(),operationId:[job.operationId],expectedRevision:job.rowRevision}};
  assert.equal((await fixture(value,session)).status,422);rejectedIds++;
 }
 assert.equal((await fixture({action:'query',operationId:{id:job.operationId}},a)).status,422);rejectedIds++;
 assert.equal(rejectedIds,69);assert.equal((await ok({action:'count'},a)).count,1);assert.equal((await ok({action:'query',operationId:job.operationId},a)).rowRevision,job.rowRevision);
 assert.equal((await ok({action:'game',gameId:game.gameId},a)).modifiedAt,initialGame.modifiedAt);
 checks.push('actual known-ID array aliases reject before SQL: author/foreign author/admin query/claim/retry/enqueue; no extra row or claim/version/game mutation, real string identity and ownership unchanged');
 assert.equal((await fixture({action:'enqueue',input:{...input,gameId:other.gameId}},a)).status,409);for(const s of[b,admin])assert.equal((await fixture({action:'query',operationId:job.operationId},s)).status,404);assert.equal((await fixture({action:'enqueue',input:{...input,key:key(),gameId:'wolong-builtin'}},admin)).status,403);assert.equal((await fixture({action:'enqueue',input:{...input,key:key(),scope:'chapter'}},a)).status,422);
 checks.push('actual SQLite enqueue atomic permanent-key concurrency/identity and immutable saved snapshot binding; cross-author/admin private read and builtin/scope controls');
 const race=await Promise.all([fixture({action:'claim',operationId:job.operationId,expectedRevision:job.rowRevision},a),fixture({action:'claim',operationId:job.operationId,expectedRevision:job.rowRevision},a)]);assert.deepEqual(race.map(r=>r.status).sort(),[200,409]);let leased=race.find(r=>r.status===200).data;job=leased.job;
 assert.equal((await fixture({action:'heartbeat',ticket:{valid:true},expectedRevision:job.rowRevision},a)).status,403);assert.equal((await fixture({action:'checkpoint',ticket:leased.ticket,input:{expectedRevision:job.rowRevision,stage:'compile',outputs:[]}},a)).status,409);
 const missing={assetId:'data',sha256:'0'.repeat(64),byteLength:1};assert.equal((await fixture({action:'checkpoint',ticket:leased.ticket,input:{expectedRevision:job.rowRevision,stage:'validate',outputs:[missing]}},a)).status,404);assert.equal((await ok({action:'query',operationId:job.operationId},a)).rowRevision,job.rowRevision);
 await bucket.put('jobs/'+job.operationId+'/'+missing.sha256,new Uint8Array([99]));assert.equal((await fixture({action:'checkpoint',ticket:leased.ticket,input:{expectedRevision:job.rowRevision,stage:'validate',outputs:[missing]}},a)).status,422);
 const out=await output(job,'slow'),changed=await ok({action:'mutation',ticket:leased.ticket,input:{expectedRevision:job.rowRevision,stage:'validate',outputs:[out]}},a);assert.equal(changed.stage,1);assert.equal(changed.checkpoint[0].outputs[0].byteLength,3);job=changed;
 checks.push('lease CAS single winner, no validDTO capability, wrong stage/missing R2 bytes reject without progress; caller mutation during actual awaited output proof cannot alter checkpoint');
 const saved=await ok({action:'save',gameId:game.gameId,expectedRevision:'1',metadata:{name:'任務甲新',introduction:''}},a);assert.equal(saved.draftRevision,'2');assert.equal((await ok({action:'query',operationId:job.operationId},a)).draftRevision,'1');
 const before=await ok({action:'game',gameId:game.gameId},a);await new Promise(done=>setTimeout(done,10));await ok({action:'query',operationId:job.operationId},a);assert.equal((await ok({action:'game',gameId:game.gameId},a)).modifiedAt,before.modifiedAt);assert.notEqual(initialGame.draftRevision,saved.draftRevision);
 checks.push('new draft save never retargets old job; job queries/checkpoints do not rewrite game modifiedAt or publish');
 await reopen();assert.equal((await fixture({action:'heartbeat',ticket:leased.ticket,expectedRevision:job.rowRevision},a)).status,403);await new Promise(done=>setTimeout(done,3100));job=await ok({action:'query',operationId:job.operationId},a);leased=await claim(job,a);assert.equal(leased.job.stage,1);assert.equal(leased.job.attempt,2);const final=await ok({action:'checkpoint',ticket:leased.ticket,input:{expectedRevision:leased.job.rowRevision,stage:'compile',outputs:[await output(leased.job)]}},a);assert.equal(final.state,'ready');assert.equal(final.checkpoint.length,2);assert.equal((await enqueue(game,a,k)).operationId,job.operationId);
 checks.push('real Worker restart preserves SQL stage/operation/R2 outputs, loses transient lease, recovers only after stored deadline with new generation; ready is stage record not runtime/release certificate');
 const expiring=await enqueue(other,a),oldLease=await claim(expiring,a);await new Promise(done=>setTimeout(done,3100));const reclaimed=await claim(oldLease.job,a);assert.equal(reclaimed.job.attempt,2);assert.equal((await fixture({action:'heartbeat',ticket:oldLease.ticket,expectedRevision:reclaimed.job.rowRevision},a)).status,409);checks.push('actual lease deadline recovery without restart increments persistent generation and fences previous live capability');
 let retryJob=await enqueue(other,a),lease=await claim(retryJob,a);const priorTicket=lease.ticket;const failed=await ok({action:'fail',ticket:lease.ticket,input:{expectedRevision:lease.job.rowRevision,code:'ENGINEERING_IO',retryable:true}},a);const retryKey=key(),request={key:retryKey,operationId:retryJob.operationId,expectedRevision:failed.rowRevision};const retried=await ok({action:'retry',input:request},a);assert.equal(retried.state,'queued');assert.equal((await ok({action:'retry',input:request},a)).operationId,retryJob.operationId);assert.equal((await fixture({action:'retry',input:{...request,key:key()}},a)).status,409);
 lease=await claim(retried,a);assert.equal((await fixture({action:'heartbeat',ticket:priorTicket,expectedRevision:lease.job.rowRevision},a)).status,409);const terminal=await ok({action:'fail',ticket:lease.ticket,input:{expectedRevision:lease.job.rowRevision,code:'UNSUPPORTED',retryable:false}},a);assert.equal((await fixture({action:'retry',input:{key:key(),operationId:terminal.operationId,expectedRevision:terminal.rowRevision}},a)).status,409);
 checks.push('durable failure/retry CAS and same-key replay keep operation identity/checkpoints, nonretryable or stale retry rejected');
 const closedJob=await enqueue(other,a),closed=await claim(closedJob,a,true);assert.equal((await fixture({action:'checkpoint',closed:true,ticket:closed.ticket,input:{expectedRevision:closed.job.rowRevision,stage:'validate',outputs:[]}},a)).status,503);
 const rollbackBefore=await ok({action:'count'},a);await ok({action:'fault',enabled:true},a);assert.equal((await fixture({action:'enqueue',input:{key:'fixture_fault_0000',gameId:other.gameId,draftRevision:'1',scope:'all'}},a)).status,500);await ok({action:'fault',enabled:false},a);assert.equal((await ok({action:'count'},a)).count,rollbackBefore.count);
 checks.push('uninstalled output verifier503; actual SQLite insert-operation fault rolls back job row together, not partial visible task');
 const concurrent=await enqueue(other,a),active=await claim(concurrent,a),slow=await output(active.job,'slow');const pending=fixture({action:'checkpoint',ticket:active.ticket,input:{expectedRevision:active.job.rowRevision,stage:'validate',outputs:[slow]}},a);await busy(active.job.operationId,a);const heartbeat=await ok({action:'heartbeat',ticket:active.ticket,expectedRevision:active.job.rowRevision},a);assert.equal((await pending).status,409);assert.equal((await ok({action:'query',operationId:active.job.operationId},a)).stage,0);
 const delayed=fixture({action:'checkpoint',ticket:active.ticket,input:{expectedRevision:heartbeat.rowRevision,stage:'validate',outputs:[slow]}},a);await busy(active.job.operationId,a);const switched=await call('/api/auth/password',{oldPassword:password,newPassword:nextPassword},a);assert.equal(switched.status,200);const renewed={cookie:switched.cookie,csrf:switched.data.csrf,user:switched.data.user};assert.equal((await delayed).status,401);assert.equal((await fixture({action:'query',operationId:active.job.operationId},renewed)).status,409);
 checks.push('actual controlled awaited R2 proof rechecks lease row CAS and SQLite auth epoch: concurrent heartbeat prevents stale commit; password change cancels prefix and new token never revives old job');
 assert.equal((await fixture({action:'enqueue',input:{key:key(),gameId:other.gameId,draftRevision:'1',scope:'all'}},b)).status,404);
 const adminGame=await ok({action:'create',metadata:{name:'管理任務',introduction:''}},admin),adminKey=key(),oldPipeline=await enqueue(adminGame,admin,adminKey);await reopen('engineering-2');assert.equal((await fixture({action:'claim',operationId:oldPipeline.operationId,expectedRevision:oldPipeline.rowRevision},admin)).status,409);assert.equal((await fixture({action:'enqueue',input:{key:adminKey,gameId:adminGame.gameId,draftRevision:'1',scope:'all'}},admin)).status,409);const newPipeline=await enqueue(adminGame,admin);assert.equal(newPipeline.stage,0);assert.equal(newPipeline.compilerRevision,'engineering-2');assert.notEqual(newPipeline.operationId,oldPipeline.operationId);
 await reopen('engineering-2','engineering-profile-2');assert.equal((await fixture({action:'claim',operationId:newPipeline.operationId,expectedRevision:newPipeline.rowRevision},admin)).status,409);
 await reopen('engineering-2','engineering-profile-1',['compile','validate']);assert.equal((await fixture({action:'claim',operationId:newPipeline.operationId,expectedRevision:newPipeline.rowRevision},admin)).status,409);
 assert.equal((await call('/api/games/'+adminGame.gameId+'/validations',{draftRevision:'1'},admin)).status,404);checks.push('compiler/profile/pipeline mismatch never combines old stages; explicit new operation starts at0; production validation/compile/publish API remains closed');
 for(const[p,h]of Object.entries(sourceHashes))assert.equal(sha(readFileSync(p)),h);process.stdout.write(JSON.stringify({result:'PASS-REAL-SQLITE-JOB-IDENTITY-NEGATIVE-REGRESSION',rejectedIds,checks,calls,sourceHashes,limits:'Real local SQL/R2/account/NodeTLS fixture with engineering marker snapshots/opaque bytes only. No real GameSource validation/compiler/PNG/runtime/Trial/release publication, source registry/delete cleanup or production SLA. No production routes installed or game modifiedAt mutation by job operations; no user data/cloud deployment.'},null,2)+'\n');
}finally{await front?.close();await mf?.dispose();}
