// Actual native byte observations after fence; not media semantics, writer drain or delete permission.
import assert from 'node:assert/strict';
import { readFileSync,writeFileSync,mkdtempSync } from 'node:fs';
import { join,resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { createHash,randomBytes,randomUUID } from 'node:crypto';
import { request as httpsRequest } from 'node:https';
import { startEditorBackend } from './start_editor_backend.mjs';
const round=process.argv[2];assert.match(round??'',/^[1-9][0-9]{0,2}$/);
const dir='.dragon-analysis/editor-phase/backend-deletion-job-freeze-session-r1/',origin='https://127.0.0.1:8787',own=mkdtempSync(join(tmpdir(),'dragon-deletion-inventory-')),sha=b=>createHash('sha256').update(b).digest('hex');
function parse(b){try{return JSON.parse(b);}catch(cause){throw new Error('owned inventory JSON',{cause});}}
const before=parse(readFileSync(dir+'before.json')),inputs={...before.inputs};for(const p of ['server/deletioninventory.js']){delete inputs[p];delete before.imports[p];}
assert.equal(Object.keys(inputs).length,461);for(const[p,h]of Object.entries({...inputs,...before.imports}))assert.equal(sha(readFileSync(p)),h,p);
const sourceHashes=Object.fromEntries(['server/worker.js','server/stageapi.js','server/deletioninventory.js','server/commandtargets.js','tools/verify_editor_backend_deletion_job_freeze.mjs','server/privatewrites.js','server/deletionintegrity.js','server/deletionjobfreeze.js','server/jobs.js',dir+'fixture-worker.js'].map(p=>[p,sha(readFileSync(p))]));
const config=parse(readFileSync('server/wrangler.jsonc')),initial=randomBytes(24).toString('hex'),password=randomBytes(24).toString('hex');config.main=resolve(dir+'fixture-worker.js');writeFileSync(join(own,'wrangler.jsonc'),JSON.stringify(config),{flag:'wx'});writeFileSync(join(own,'.dev.vars'),'EDITOR_DEFAULT_PASSWORD='+JSON.stringify(initial)+'\nEDITOR_REQUEST_KEY='+JSON.stringify(randomBytes(32).toString('hex'))+'\n',{flag:'wx',mode:0o600});let server;const calls=[],checks=[],observations=[];
async function call(path,value,session,extra={}){const headers={Origin:origin,'Content-Type':'application/json','Idempotency-Key':randomUUID(),...extra};if(session){headers.Cookie=session.cookie;headers['X-CSRF-Token']=session.csrf;}const r=await new Promise((done,reject)=>{const req=httpsRequest(origin+path,{method:value===undefined?'GET':'POST',headers,rejectUnauthorized:false,agent:false},res=>{const b=[];res.on('data',v=>b.push(v));res.on('error',reject);res.on('end',()=>{try{done({status:res.statusCode,data:parse(Buffer.concat(b)),cookie:res.headers['set-cookie']?.[0]?.split(';')[0]});}catch(error){reject(error);}});});req.on('error',reject);req.end(value===undefined?undefined:JSON.stringify(value));});calls.push({path,status:r.status});return r;}
async function ok(path,value,session,extra){const r=await call(path,value,session,extra);assert.equal(r.status,200,r.data.error);return r.data;}
const inv=(v,s)=>call('/api/test/inventory',v,s),probe=(v,s)=>ok('/api/test/inventory',v,s),f=(v,s)=>ok('/api/test/fence',v,s);
async function observe(gameId,s){const r=await inv({action:'observe',gameId},s);assert.equal(r.status,200,r.data.error);const value=r.data.result;assert.equal(value.deleteAllowed,false);assert.equal(value.httpCommandCoverage,'BOUND_ROWS_ONLY_LEGACY_UNKNOWN');assert.equal(value.privateWriteCoverage,'ROOT_PUT_ADAPTER_ONLY_LEGACY_UNKNOWN');assert.equal(value.mode,'OBSERVED_METADATA_ONLY_NOT_DELETE_PLAN');assert.match(value.inventoryDigest,/^[a-f0-9]{64}$/);assert.deepEqual(Object.keys(value).sort(),['associatedRows','deleteAllowed','foreignRootReferences','gameId','intentRecords','inventoryDigest','missingReferences','mode','pendingRecords','privateListed','referencedHashes','rowRevision','sqlDigest','untrackedPrivateObjects','httpCommandCoverage','privateWritesPending','privateWritesUncertain','privateWriteCoverage'].sort());observations.push(value);return value;}
async function reject(v,s,status,code){const r=await inv(v,s);assert.equal(r.status,status);assert.equal(r.data.error,code);}
async function login(account){const r=await call('/api/auth/login',{account,password:initial});assert.equal(r.status,200);const changed=await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:r.cookie,csrf:r.data.csrf});assert.equal(changed.status,200);return{cookie:changed.cookie,csrf:changed.data.csrf};}
async function fenced(game,s){return f({action:'begin',input:{gameId:game.gameId,expectedRowRevision:game.rowRevision,confirmationName:game.metadata.name}},s);}
let admin;
try{
 server=await startEditorBackend(join(own,'wrangler.jsonc'),{stageSource:true,stageLibrary:true});admin=await login('tianyi');await ok('/api/admin/accounts',{account:'inventory_author'},admin);const author=await login('inventory_author');const opaque=(await f({action:'create',metadata:{name:'引用觀察',introduction:''}},author)).result,foreign=(await f({action:'create',metadata:{name:'隔離參照',introduction:''},marker:12},author)).result;
 await reject({action:'observe',gameId:'wolong-builtin'},admin,403,'BUILTIN_PROTECTED');await reject({action:'observe',gameId:opaque.gameId},admin,409,'DELETE_FENCE_REQUIRED');await reject({action:'observe',gameId:randomUUID()},author,404,'GAME_NOT_FOUND');await fenced(opaque,author);const initialStats=(await probe({action:'stats',gameId:opaque.gameId},admin)).result,root=initialStats.snapshots[0].root_key,hash=root.split('/').at(-1);await reject({action:'observe',gameId:[opaque.gameId]},admin,422,'GAME_ID');checks.push('actual owner/admin, builtin/UUID/unknown/mandatory durablefence and strict minimalsummary; no content or privatekeys returned');
 const first=await observe(opaque.gameId,author);assert.equal(first.privateListed,1);assert.equal(first.referencedHashes,1);assert.equal(first.missingReferences,0);assert.equal(first.untrackedPrivateObjects,0);const sharedBefore=first.inventoryDigest;await probe({action:'shared',hash},admin);assert.equal((await observe(opaque.gameId,admin)).inventoryDigest,sharedBefore);checks.push('real257B source plus actual installed/ sameSHA physicalothernamespace is notprivatecandidate/refcount; observer no sharedread/delete');
 await probe({action:'put',gameId:opaque.gameId,length:3},admin);const withOrphan=await observe(opaque.gameId,author);assert.equal(withOrphan.privateListed,2);assert.equal(withOrphan.untrackedPrivateObjects,1);await probe({action:'length',enabled:true,gameId:opaque.gameId,hash,length:258},admin);await reject({action:'observe',gameId:opaque.gameId},author,503,'DELETE_INVENTORY_LENGTH');await probe({action:'length',enabled:false,gameId:opaque.gameId},admin);await probe({action:'remove',key:root},admin);const missing=await observe(opaque.gameId,author);assert.equal(missing.missingReferences,1);assert.equal(missing.deleteAllowed,false); // Deliberate owned forensic damage; not production cleanup.
 await server.close();server=await startEditorBackend(join(own,'wrangler.jsonc'));const afterRestart=await observe(opaque.gameId,author);assert.equal(afterRestart.inventoryDigest,missing.inventoryDigest);assert.equal(afterRestart.missingReferences,1);checks.push('nativeorphan listed butnever authorised; conflictinglength rejects, fixture-onlymissingroot visible; trueworkerdrestart same observations without memoryplan');
 const foreignRoot=(await probe({action:'stats',gameId:foreign.gameId},admin)).result.snapshots[0].root_key;await probe({action:'foreign',enabled:true,target:opaque.gameId,foreign:foreign.gameId,hash},admin);assert.equal((await observe(opaque.gameId,admin)).foreignRootReferences,1);await probe({action:'foreign',enabled:false,foreign:foreign.gameId,restore:foreignRoot},admin);await probe({action:'schema',enabled:true},admin);await reject({action:'observe',gameId:opaque.gameId},admin,503,'DELETE_INVENTORY_SCHEMA');await probe({action:'schema',enabled:false},admin);const bad=(await probe({action:'put',gameId:opaque.gameId,badKey:true},admin)).result;await reject({action:'observe',gameId:opaque.gameId},admin,503,'DELETE_INVENTORY_OBJECT');await probe({action:'remove',key:bad.key},admin);checks.push('actualforeigngame root-key reference counted withoutotheridentity/content; newSQLschema failsclosed; malformedprivatekey metadata rejects, no deletioncapability');
 // Full pinned source and authentic current data/images Jobs, not an opaque stand-in.
 await ok('/api/admin/source/install',{},admin);await ok('/api/admin/library/install',{},admin);const source=(await ok('/api/admin/source',undefined,admin)).definition,copyKey=randomUUID();assert.equal((await call('/api/admin/copies',{registryId:source.registryId,name:'核清觀察',introduction:''},admin,{'Idempotency-Key':copyKey})).status,202);const copyCommand=randomUUID(),copy=await ok('/api/admin/copies/'+copyKey+'/run',{},admin,{'If-Match':'"1"','Idempotency-Key':copyCommand}),gameId=copy.gameId;const stageCommands=[];const saved=await ok('/api/games/'+gameId+'/draft/save',{metadata:{name:'保存觀察',introduction:''},resourceEdits:[]},admin,{'If-Match':'"1"'});assert.ok(saved);
 for(const purpose of ['data','images']){const q=await call('/api/games/'+gameId+'/stage-jobs/'+purpose,{draftRevision:'2',scope:'all'},admin);assert.equal(q.status,202);const commandKey=randomUUID();await ok('/api/games/'+gameId+'/stage-jobs/'+purpose+'/'+q.data.job.operationId+'/run',{},admin,{'If-Match':'"1"','Idempotency-Key':commandKey});stageCommands.push({key:commandKey,id:q.data.job.operationId,purpose});}
 const queued=await call('/api/games/'+gameId+'/stage-jobs/fallback-spring',{draftRevision:'2',scope:'all'},admin);assert.equal(queued.status,202); // queued is not in-flight or ready.
 const commandProbe=(v)=>ok('/api/test/commands',v,admin);
 const initialCommands=(await commandProbe({action:'stats'})).result;assert.equal(initialCommands.targets.length,3);assert.equal(initialCommands.copy.length,1);assert.equal(initialCommands.stage.length,2);for(const r of initialCommands.targets){assert.equal(r.game_id,gameId);assert.equal(r.kind==='copy'?r.target_id===copyKey:stageCommands.some(j=>j.id===r.target_id&&j.key===r.op_key),true);}
 const copyRelation=initialCommands.targets.find(r=>r.kind==='copy');await commandProbe({action:'remove',kind:'copy',actor:copyRelation.actor,key:copyCommand});assert.equal((await commandProbe({action:'stats'})).result.copy.length,1);await ok('/api/admin/copies/'+copyKey+'/run',{},admin,{'If-Match':'"1"','Idempotency-Key':copyCommand});assert.deepEqual((await commandProbe({action:'stats'})).result,initialCommands);checks.push('actual persisted copy+two stage commands have exact game/request/job association; simulated legacy missingrelation notguessed, explicit samekey authorizedreplay adds only structural relation');
 const faultKey=randomUUID();await commandProbe({action:'fault',enabled:true});assert.equal((await call('/api/admin/copies/'+copyKey+'/run',{},admin,{'If-Match':'"1"','Idempotency-Key':faultKey})).status,500);assert.deepEqual((await commandProbe({action:'stats'})).result,initialCommands);await commandProbe({action:'fault',enabled:false});await ok('/api/admin/copies/'+copyKey+'/run',{},admin,{'If-Match':'"1"','Idempotency-Key':faultKey});const four=(await commandProbe({action:'stats'})).result;assert.equal(four.targets.length,4);assert.equal(four.copy.length,2);checks.push('actual SQL association inserttrigger500 rolls new command bindingback atomically; explicit originalkey retries afterward, no successfulcommand receipt inference');
 for(const relation of [copyRelation,initialCommands.targets.find(r=>r.kind==='stage')]){await commandProbe({action:'corrupt',kind:relation.kind,actor:relation.actor,key:relation.op_key,target:'fixture-corrupt'});const j=stageCommands.find(j=>j.key===relation.op_key);const path=relation.kind==='copy'?'/api/admin/copies/'+copyKey+'/run':'/api/games/'+gameId+'/stage-jobs/'+j.purpose+'/'+j.id+'/run';const bad=await call(path,{},admin,{'If-Match':'"1"','Idempotency-Key':relation.op_key});assert.equal(bad.status,503);assert.equal(bad.data.error,'COMMAND_TARGET_CORRUPT');await commandProbe({action:'corrupt',kind:relation.kind,actor:relation.actor,key:relation.op_key,target:relation.target_id});}assert.deepEqual((await commandProbe({action:'stats'})).result,four);
 const proofProbe=v=>ok('/api/test/proofs',v,admin),beforeProofFault=(await proofProbe({action:'stats'})).result;assert.equal(beforeProofFault.proofs.length,beforeProofFault.targets.length);await proofProbe({action:'fault',enabled:true});const proofFaultKey=randomUUID();const failedProof=await call('/api/admin/copies/'+copyKey+'/run',{},admin,{'If-Match':'"1"','Idempotency-Key':proofFaultKey});assert.equal(failedProof.status,500);assert.deepEqual((await proofProbe({action:'stats'})).result,beforeProofFault);await proofProbe({action:'fault',enabled:false});await ok('/api/admin/copies/'+copyKey+'/run',{},admin,{'If-Match':'"1"','Idempotency-Key':proofFaultKey});const afterProofFault=(await proofProbe({action:'stats'})).result;assert.equal(afterProofFault.proofs.length,beforeProofFault.proofs.length+1);assert.equal(afterProofFault.targets.length,beforeProofFault.targets.length+1);checks.push('actual SQLite proofINSERT trigger500 rolls command-target-proof together; originalkey explicitretry succeeds, no command execution receipt inference');
 const legacySeal=afterProofFault.proofs.find(r=>r.op_key===proofFaultKey);await proofProbe({action:'remove-proof',kind:legacySeal.kind,actor:legacySeal.actor,key:legacySeal.op_key});const withoutSeal=(await proofProbe({action:'stats'})).result;assert.equal(withoutSeal.proofs.length,afterProofFault.proofs.length-1);await ok('/api/admin/copies/'+copyKey+'/run',{},admin,{'If-Match':'"1"','Idempotency-Key':proofFaultKey});assert.deepEqual((await proofProbe({action:'stats'})).result,afterProofFault);await proofProbe({action:'mac',kind:legacySeal.kind,actor:legacySeal.actor,key:legacySeal.op_key,value:'0'.repeat(64)});const badReplay=await call('/api/admin/copies/'+copyKey+'/run',{},admin,{'If-Match':'"1"','Idempotency-Key':proofFaultKey});assert.equal(badReplay.status,503);assert.equal(badReplay.data.error,'COMMAND_TARGET_PROOF_CORRUPT');await proofProbe({action:'mac',kind:legacySeal.kind,actor:legacySeal.actor,key:legacySeal.op_key,value:legacySeal.binding_mac});assert.deepEqual((await proofProbe({action:'stats'})).result,afterProofFault);checks.push('authorized accurate samekey replay seals missinglegacy proof only; alreadysealed badMAC replay exact503 with no overwrite, ownedrestore exact originalseal notproductionrepair');
 const pendingKey=randomUUID();assert.equal((await call('/api/admin/copies',{registryId:source.registryId,name:'取消關聯',introduction:''},admin,{'Idempotency-Key':pendingKey})).status,202);const cancelKey=randomUUID(),cancelled=await ok('/api/admin/copies/'+pendingKey+'/cancel',{},admin,{'If-Match':'"1"','Idempotency-Key':cancelKey});assert.equal(cancelled.state,'canceled');assert.deepEqual(await ok('/api/admin/copies/'+pendingKey+'/cancel',{},admin,{'If-Match':'"1"','Idempotency-Key':cancelKey}),cancelled);const other=await call('/api/admin/copies/'+copyKey+'/run',{},admin,{'If-Match':'"1"','Idempotency-Key':cancelKey});assert.equal(other.status,409);assert.equal(other.data.error,'IDEMPOTENCY_CONFLICT');checks.push('corrupt existing copy/stage associations exact503; cancel terminalreplay remains compatible, samekeydifferenttarget409; no rewriting stored mapping');
 const mapped=(await commandProbe({action:'stats'})).result;await server.close();server=await startEditorBackend(join(own,'wrangler.jsonc'));assert.deepEqual((await commandProbe({action:'stats'})).result,mapped);checks.push('actual workerdstarter restart preserves exact mapping and old command bindings, not process capabilities');
 const actualGame=(await ok('/api/games',undefined,admin)).games.find(g=>g.gameId===gameId);await fenced(actualGame,admin);const boundBefore=(await commandProbe({action:'stats'})).result;const blockedKey=randomUUID();const blocked=await call('/api/admin/copies/'+copyKey+'/run',{},admin,{'If-Match':'"1"','Idempotency-Key':blockedKey});assert.equal(blocked.status,409);assert.equal(blocked.data.error,'GAME_DELETING');assert.deepEqual((await commandProbe({action:'stats'})).result,boundBefore);checks.push('actual fencedcopy denied before new command/key or association; boundrows observer remains metadata-only, legacy completeness notgranted');await reject({action:'observe',gameId},author,404,'GAME_NOT_FOUND');const beforeStats=(await probe({action:'stats',gameId},admin)).result,full=await observe(gameId,admin),afterStats=(await probe({action:'stats',gameId},admin)).result;assert.deepEqual({...afterStats,listCalls:beforeStats.listCalls},beforeStats);assert.equal(full.missingReferences,0);assert.equal(full.untrackedPrivateObjects,0);assert.ok(full.privateListed>60);assert.equal(full.privateListed,full.referencedHashes);assert.ok(full.associatedRows>full.privateListed);assert.ok(afterStats.listCalls-beforeStats.listCalls>2);assert.equal(beforeStats.snapshots.length,2);checks.push('actual20chapter fullcopy/baseline, saved2refs, real data29 and images7 outputs plus queuedfallback; forcednative2itempagination two completepasses; exactbefore-afterSQL/R2sharedfacts unchanged, bodyhash/heap/SLA notclaimed');
 await commandProbe({action:'corrupt',kind:copyRelation.kind,actor:copyRelation.actor,key:copyRelation.op_key,target:'fixture-corrupt'});await reject({action:'observe',gameId},admin,503,'DELETE_INVENTORY_COMMAND_TARGET');await commandProbe({action:'corrupt',kind:copyRelation.kind,actor:copyRelation.actor,key:copyRelation.op_key,target:copyRelation.target_id});await commandProbe({action:'remove',kind:copyRelation.kind,actor:copyRelation.actor,key:copyRelation.op_key});const legacy=await observe(gameId,admin);assert.equal(legacy.associatedRows,full.associatedRows-2);assert.equal(legacy.privateListed,full.privateListed);assert.equal(legacy.httpCommandCoverage,'BOUND_ROWS_ONLY_LEGACY_UNKNOWN');assert.equal(legacy.deleteAllowed,false);await commandProbe({action:'restore',relation:copyRelation});assert.equal((await observe(gameId,admin)).inventoryDigest,full.inventoryDigest);checks.push('actual postfence inventory rejects corrupt target before listing; missing legacy mapping omits no claimed knownrows and explicitly retains UNKNOWN coverage/deleteAllowedfalse; fixture-only exactrestore recovers originaldigest');
 for(const [kind,code]of [['cursor','DELETE_INVENTORY_CURSOR'],['duplicate','DELETE_INVENTORY_OBJECT'],['outside','DELETE_INVENTORY_OBJECT'],['type','DELETE_INVENTORY_LIST'],['null','DELETE_INVENTORY_OBJECT']]){await probe({action:'list-fault',kind},admin);await reject({action:'observe',gameId},admin,503,code);await probe({action:'list-fault',kind:null},admin);}assert.equal((await observe(gameId,admin)).inventoryDigest,full.inventoryDigest);checks.push('five separatelyinjected actualnative-list envelopefaults: repeatedcursor/duplicate/outsideprefix/truncatedtype/nullentry exact503, nopartialsuccess; actualforeignauthor404 afterfence beforeinventory');
 // Controlled list awaits preserve actual response; never stitch two inconsistent scans.
 await probe({action:'pause'},admin);const sqlPending=inv({action:'observe',gameId},admin);for(let i=0;i<200;i++){if((await f({action:'control'},admin)).result.waiting)break;await new Promise(done=>setTimeout(done,10));}assert.equal((await f({action:'control'},admin)).result.waiting,true);await probe({action:'sql-change',gameId},admin);await f({action:'release'},admin);const sqlResult=await sqlPending;assert.equal(sqlResult.status,409);assert.equal(sqlResult.data.error,'DELETE_INVENTORY_CHANGED');
 await probe({action:'pause'},admin);const objectPending=inv({action:'observe',gameId:opaque.gameId},admin);for(let i=0;i<200;i++){if((await f({action:'control'},admin)).result.waiting)break;await new Promise(done=>setTimeout(done,10));}assert.equal((await f({action:'control'},admin)).result.waiting,true);await probe({action:'put',gameId:opaque.gameId,length:4},admin);await f({action:'release'},admin);const objectResult=await objectPending;assert.equal(objectResult.status,409);assert.equal(objectResult.data.error,'DELETE_INVENTORY_OBJECTS_CHANGED');checks.push('controlledactualfirstR2listresponse then SQLmutation or appendedorphan; lateSQLchanged / two-list metadatachanged exact409, no partial inventorysuccess');
 const staleKey=randomUUID();assert.equal((await call('/api/admin/copies',{registryId:source.registryId,name:'舊會話取消',introduction:''},admin,{'Idempotency-Key':staleKey})).status,202);
 await probe({action:'pause'},admin);const epochPending=inv({action:'observe',gameId},admin);for(let i=0;i<200;i++){if((await f({action:'control'},admin)).result.waiting)break;await new Promise(done=>setTimeout(done,10));}assert.equal((await f({action:'control'},admin)).result.waiting,true);const next=randomBytes(24).toString('hex'),changed=await call('/api/auth/password',{oldPassword:password,newPassword:next},admin);assert.equal(changed.status,200);admin={cookie:changed.cookie,csrf:changed.data.csrf};const staleRun=await call('/api/admin/copies/'+staleKey+'/run',{},admin,{'If-Match':'"1"'});assert.equal(staleRun.status,409);assert.equal(staleRun.data.error,'COPY_OPERATION_REVOKED');const staleCanceled=await ok('/api/admin/copies/'+staleKey+'/cancel',{},admin,{'If-Match':'"1"'});assert.equal(staleCanceled.state,'canceled');checks.push('actual password replacement keeps stale pendingrun409 but newlyauthenticated sameowner may explicitly cancel with newkey; original cancellation permission preserved');await f({action:'release'},admin);const epochResult=await epochPending;assert.equal(epochResult.status,401);assert.equal(epochResult.data.error,'SESSION_INVALID');const resumed=await observe(gameId,admin);assert.equal(resumed.deleteAllowed,false);checks.push('actualpasswordhandler while native listawait revokes oldsession; newepoch fresh observation stillfenced, notresume-capability orcompleteddelete');

 // Additional engineering bytes use the actual production Root BlobStore on existing sameSQL games; not GameSource or playable edits.
 const w=(v)=>ok('/api/test/writes',v,admin),stats=(gameId)=>w({action:'stats',gameId}).then(r=>r.result);
 const make=async name=>(await f({action:'create',metadata:{name,introduction:''}},admin)).result;
 const wait=async gameId=>{for(let i=0;i<200;i++){if((await stats(gameId)).waiting)return;await new Promise(done=>setTimeout(done,10));}assert.fail('owned native write gate not reached');};
 for(const [kind,name,marker] of [['before','寫前栅欄',181],['after','寫後栅欄',182]]){
  const g=await make(name);await w({action:'pause',kind});const pending=call('/api/test/writes',{action:'put',gameId:g.gameId,marker},admin);await wait(g.gameId);
  const paused=await stats(g.gameId);assert.equal(paused.rows.length,1);assert.equal(paused.rows[0].state,'pending');await fenced(g,admin);
  const seen=await observe(g.gameId,admin);assert.equal(seen.privateWritesPending,1);assert.equal(seen.privateWritesUncertain,0);assert.equal(seen.deleteAllowed,false);
  const blocked=await call('/api/test/writes',{action:'put',gameId:g.gameId,marker:183},admin);assert.equal(blocked.status,409);assert.equal(blocked.data.error,'GAME_DELETING');assert.equal((await stats(g.gameId)).calls,paused.calls);
  await w({action:'release'});const late=await pending;assert.equal(late.status,409);assert.equal(late.data.error,'GAME_DELETING');assert.equal((await stats(g.gameId)).rows[0].state,'settled');assert.equal((await observe(g.gameId,admin)).privateWritesPending,0);
 }
 checks.push('actual nativePUT before/after controlled awaits: durable pending observed afterfence, newRootwrite rejected before nativecall, late promise settles but outer authority denies409; settled notcontentcommit/delete/drain permission');
 const errorGame=await make('未知寫結果');await w({action:'fail-after'});assert.equal((await call('/api/test/writes',{action:'put',gameId:errorGame.gameId,marker:184},admin)).status,500);const errorRows=(await stats(errorGame.gameId)).rows;assert.equal(errorRows.length,1);assert.equal(errorRows[0].state,'uncertain');await fenced(errorGame,admin);const uncertain=await observe(errorGame.gameId,admin);assert.equal(uncertain.privateWritesUncertain,1);assert.equal(uncertain.untrackedPrivateObjects,1);
 await server.close();server=await startEditorBackend(join(own,'wrangler.jsonc'));assert.deepEqual((await stats(errorGame.gameId)).rows,errorRows);assert.equal((await observe(errorGame.gameId,admin)).privateWritesUncertain,1);
 checks.push('actual nativecommit then injected unknownoutcome remains uncertain; physicalorphan listed, realworkerdrestart retains exact unresolved record, no automatic TTL repair or inferredpermission');
 const faultGame=await make('日誌回滾');const faultBefore=await stats(faultGame.gameId);await w({action:'fault',kind:'insert',enabled:true});assert.equal((await call('/api/test/writes',{action:'put',gameId:faultGame.gameId,marker:185},admin)).status,500);await w({action:'fault',kind:'insert',enabled:false});assert.deepEqual(await stats(faultGame.gameId),faultBefore);
 await w({action:'fault',kind:'ack',enabled:true});assert.equal((await call('/api/test/writes',{action:'put',gameId:faultGame.gameId,marker:186},admin)).status,500);await w({action:'fault',kind:'ack',enabled:false});const unacked=(await stats(faultGame.gameId)).rows;assert.equal(unacked.length,1);assert.equal(unacked[0].state,'pending');await fenced(faultGame,admin);assert.equal((await observe(faultGame.gameId,admin)).privateWritesPending,1);
 await server.close();server=await startEditorBackend(join(own,'wrangler.jsonc'));assert.deepEqual((await stats(faultGame.gameId)).rows,unacked);assert.equal((await observe(faultGame.gameId,admin)).privateWritesPending,1);
 checks.push('actual journalinsert trigger500 rolls back before nativecall; nativewrite then SQLack trigger500 keeps pending despite physicalcompletion, actualrestart never clears it; no resolver/delete opened');
 const foreignBefore=await stats(foreign.gameId);const foreignWrite=await call('/api/test/writes',{action:'put',gameId:foreign.gameId,marker:187},admin);assert.equal(foreignWrite.status,404);assert.equal(foreignWrite.data.error,'GAME_NOT_FOUND');assert.deepEqual(await stats(foreign.gameId),foreignBefore);
 const corruptGame=await make('記錄綁定');await w({action:'pause',kind:'after'});const corruptPending=call('/api/test/writes',{action:'put',gameId:corruptGame.gameId,marker:188},admin);await wait(corruptGame.gameId);const captured=(await stats(corruptGame.gameId)).rows[0];await w({action:'corrupt',id:captured.operation_id,sha256:'0'.repeat(64)});await w({action:'release'});const mismatch=await corruptPending;assert.equal(mismatch.status,503);assert.equal(mismatch.data.error,'PRIVATE_WRITE_JOURNAL_CHANGED');assert.equal((await stats(corruptGame.gameId)).rows[0].state,'pending');await w({action:'corrupt',id:captured.operation_id,sha256:captured.sha256});await fenced(corruptGame,admin);assert.equal((await observe(corruptGame.gameId,admin)).privateWritesPending,1);
 checks.push('adminforeign opaqueRootblob write denied404 before journal/nativecall; controlled SQLtuple corruption afteractualnativecommit exact503 withpending retained, fixture restoration not acknowledgement orresolver');

 // Actual private bytes proof after fence; never cleanup authority. Old nineteen flows unchanged.
 const integrityCalls=(v,s=admin)=>call('/api/test/integrity',v,s),io=(v)=>ok('/api/test/integrity',v,admin),byteObservations=[];
 async function verified(id,s=admin){const r=await integrityCalls({action:'verify',gameId:id},s);assert.equal(r.status,200,r.data.error);const v=r.data.result;assert.equal(v.mode,'VERIFIED_CURRENT_PRIVATE_BYTES_ONLY_NOT_DELETE_PLAN');assert.equal(v.deleteAllowed,false);assert.equal(v.privateWriteCoverage,'ROOT_PUT_ADAPTER_ONLY_LEGACY_UNKNOWN');assert.equal(v.httpCommandCoverage,'BOUND_ROWS_ONLY_LEGACY_UNKNOWN');assert.match(v.byteObservationDigest,/^[a-f0-9]{64}$/);assert.deepEqual(Object.keys(v).sort(),['gameId','rowRevision','sqlDigest','inventoryDigest','byteObservationDigest','verifiedObjects','verifiedBytes','untrackedPrivateObjects','foreignRootReferences','privateWritesPending','privateWritesUncertain','privateWriteCoverage','httpCommandCoverage','deleteAllowed','mode'].sort());byteObservations.push(v);return v;}
 async function denyBytes(id,status,code,s=admin){const r=await integrityCalls({action:'verify',gameId:id},s);assert.equal(r.status,status);assert.equal(r.data.error,code);}
 await denyBytes('wolong-builtin',403,'BUILTIN_PROTECTED');await denyBytes([gameId],422,'GAME_ID');await denyBytes(randomUUID(),404,'GAME_NOT_FOUND');await denyBytes(gameId,404,'GAME_NOT_FOUND',author);await denyBytes(opaque.gameId,409,'DELETE_INTEGRITY_MISSING_REFERENCE');
 const fullState=(await probe({action:'stats',gameId},admin)).result,readBefore=(await io({action:'stats'})).result,hashed=await verified(gameId),readAfter=(await io({action:'stats'})).result,fullAfter=(await probe({action:'stats',gameId},admin)).result;
 assert.equal(hashed.verifiedObjects,fullState.privateObjects.length);assert.equal(hashed.verifiedBytes,fullState.privateObjects.reduce((n,o)=>n+o.size,0));assert.equal(readAfter.gets-readBefore.gets,hashed.verifiedObjects);assert.ok(readAfter.reads-readBefore.reads>=hashed.verifiedObjects);assert.deepEqual({...fullAfter,listCalls:fullState.listCalls},fullState);assert.equal(hashed.privateWritesPending,0);assert.equal(hashed.privateWritesUncertain,0);
 await server.close();server=await startEditorBackend(join(own,'wrangler.jsonc'));assert.deepEqual(await verified(gameId),hashed);checks.push('actual fenced20chapter/baseline/saved2 and genuine data29/images7: every private object read via native stream, fullSHA matches address/length; minimalcounts only, SQL/sharedfacts unchanged, trueworkerdrestart repeats same bytes observations; no media/ref/drain certificate');
 await denyBytes(foreign.gameId,409,'DELETE_FENCE_REQUIRED');await fenced(foreign,author);const managed=await verified(foreign.gameId);assert.equal(managed.verifiedObjects,1);assert.equal(managed.verifiedBytes,257);assert.deepEqual(await verified(foreign.gameId,author),managed);const retained=await verified(errorGame.gameId);assert.equal(retained.privateWritesUncertain,1);assert.equal(retained.untrackedPrivateObjects,1);assert.equal(retained.verifiedBytes,261);checks.push('actual management bytehash inside service gives neither privatekeys nor bodies/other identities; realowner same minimalresult; physically committed uncertain/orphan bytes can hash but remain untracked/uncertain and never deleteAllowed');
 const target=(await probe({action:'stats',gameId:foreign.gameId},admin)).result.snapshots[0].root_key;
 const stamp=await observe(foreign.gameId,admin);await io({action:'damage',key:target});const metadataOnly=await observe(foreign.gameId,admin);assert.equal(metadataOnly.privateListed,stamp.privateListed);assert.equal(metadataOnly.missingReferences,0);await denyBytes(foreign.gameId,503,'DELETE_INTEGRITY_SHA');await io({action:'damage',key:target});assert.deepEqual(await verified(foreign.gameId),managed);checks.push('actual same-length native overwrite at original hash-key: metadata observation still lists complete references but actual body SHA rejects; explicit second fixture XOR restores originalbody only, no production repair/write bypass');
 for(const [kind,status,code]of [['missing',409,'DELETE_INTEGRITY_OBJECT_MISSING'],['size',409,'DELETE_INTEGRITY_OBJECT_CHANGED'],['etag',409,'DELETE_INTEGRITY_OBJECT_CHANGED'],['stream',503,'DELETE_INTEGRITY_STREAM'],['short',503,'DELETE_INTEGRITY_LENGTH'],['long',413,'DELETE_INTEGRITY_BUDGET'],['budget',413,'DELETE_INTEGRITY_BUDGET'],['cursor',503,'DELETE_INTEGRITY_CURSOR'],['count',413,'DELETE_INTEGRITY_BUDGET'],['done-type',503,'DELETE_INTEGRITY_STREAM'],['empty',503,'DELETE_INTEGRITY_STREAM']]){await io({action:'fault',kind});await denyBytes(foreign.gameId,status,code);await io({action:'fault',kind:null});}assert.deepEqual(await verified(foreign.gameId),managed);await io({action:'fault',kind:'total'});const budgetBefore=(await io({action:'stats'})).result.gets;await denyBytes(gameId,413,'DELETE_INTEGRITY_BUDGET');assert.equal((await io({action:'stats'})).result.gets,budgetBefore);await io({action:'fault',kind:null});checks.push('twelve independent actualnative response controls: missing/get size-etag/body nonbytes/truncated/oversize/done-type/zerochunk, preGET objectcount+perobject+totalbudget and repeatedcursor exact rejection; totalbudget no nativeGET and no partial successful hash or delete permission');
 const waitRead=async()=>{for(let i=0;i<200;i++){if((await io({action:'stats'})).result.waiting)return;await new Promise(done=>setTimeout(done,10));}assert.fail('native read gate not reached');};
 const oldTime=(await probe({action:'stats',gameId:foreign.gameId},admin)).result.game.modified_at;
 await io({action:'pause',kind:'get'});const changedSQL=integrityCalls({action:'verify',gameId:foreign.gameId});await waitRead();await probe({action:'sql-change',gameId:foreign.gameId},admin);await io({action:'release'});const staleRead=await changedSQL;assert.equal(staleRead.status,409);assert.equal(staleRead.data.error,'DELETE_INTEGRITY_CHANGED');await io({action:'restore-time',gameId:foreign.gameId,time:oldTime});assert.deepEqual(await verified(foreign.gameId),managed);checks.push('actual nativeGET response paused then gameSQL modifiedAt changes: late byte verification exact409 beforestream success; fixture-only exact time restoration not production rollback');
 await io({action:'pause',kind:'body'});const appended=integrityCalls({action:'verify',gameId:foreign.gameId});await waitRead();const added=(await probe({action:'put',gameId:foreign.gameId,length:7},admin)).result;await io({action:'release'});const objectChanged=await appended;assert.equal(objectChanged.status,409);assert.equal(objectChanged.data.error,'DELETE_INTEGRITY_OBJECTS_CHANGED');await probe({action:'remove',key:added.key},admin);assert.deepEqual(await verified(foreign.gameId),managed);checks.push('actual streamread held afternativechunk then newprivate orphan appears: final native metadata comparison exact409, no partial certificate; removal only owned forensic fixture');
 await io({action:'pause',kind:'body'});const lateEpoch=integrityCalls({action:'verify',gameId:foreign.gameId});await waitRead();const lastPassword=randomBytes(24).toString('hex'),newSession=await call('/api/auth/password',{oldPassword:next,newPassword:lastPassword},admin);assert.equal(newSession.status,200);admin={cookie:newSession.cookie,csrf:newSession.data.csrf};await io({action:'release'});const oldResponse=await lateEpoch;assert.equal(oldResponse.status,401);assert.equal(oldResponse.data.error,'SESSION_INVALID');assert.deepEqual(await verified(foreign.gameId),managed);checks.push('actual passwordhandler while nativebody readawait revokes old token; finally cancels/releases reader without creating result, freshnew epoch may only reobserve hashes, not revive cleanup/oldoperation');
 const commandObservations=[];
 const commands=(v,s=admin)=>call('/api/test/proofs',v,s);
 async function commandVerified(id,s=admin){const r=await commands({action:'observe',gameId:id},s);assert.equal(r.status,200,r.data.error);const v=r.data.result;assert.equal(v.mode,'VERIFIED_BOUND_COMMAND_ASSOCIATIONS_NOT_DELETE_PLAN');assert.equal(v.coverage,'BOUND_COMMAND_PROOFS_ONLY_LEGACY_UNKNOWN');assert.equal(v.deleteAllowed,false);assert.match(v.associationDigest,/^[a-f0-9]{64}$/);assert.deepEqual(Object.keys(v).sort(),['gameId','rowRevision','associationDigest','sealedTargets','unsealedTargets','deleteAllowed','coverage','mode'].sort());commandObservations.push(v);return v;}
 async function commandDenied(v,status,code,s=admin){const r=await commands(v,s);assert.equal(r.status,status);assert.equal(r.data.error,code);}
 await commandDenied({action:'observe',gameId:'wolong-builtin'},403,'BUILTIN_PROTECTED');await commandDenied({action:'observe',gameId:[gameId]},422,'GAME_ID');await commandDenied({action:'observe',gameId:randomUUID()},404,'GAME_NOT_FOUND');await commandDenied({action:'observe',gameId},404,'GAME_NOT_FOUND',author);const proofState=(await proofProbe({action:'stats'})).result,verifiedCommands=await commandVerified(gameId);assert.ok(verifiedCommands.sealedTargets>=5);assert.equal(verifiedCommands.unsealedTargets,0);assert.deepEqual((await proofProbe({action:'stats'})).result,proofState);assert.equal((await commandVerified(foreign.gameId)).sealedTargets,0);assert.equal((await commandVerified(foreign.gameId,author)).sealedTargets,0);checks.push('actual fenced owner/admin commandMAC observations return counts/hash only; foreignauthor404 andbuiltin/UUID gates, management no content or commandkeys, zero targets notglobalhistory/drain/delete proof');
 const stageSeal=proofState.proofs.find(r=>r.game_id===gameId&&r.kind==='stage'),otherStage=stageCommands.find(r=>r.id!==stageSeal.target_id);assert.ok(otherStage);await commandProbe({action:'corrupt',kind:stageSeal.kind,actor:stageSeal.actor,key:stageSeal.op_key,target:otherStage.id});const structurallyExisting=await observe(gameId,admin);assert.equal(structurallyExisting.deleteAllowed,false);await commandDenied({action:'observe',gameId},503,'COMMAND_TARGET_PROOF_CORRUPT');await commandProbe({action:'corrupt',kind:stageSeal.kind,actor:stageSeal.actor,key:stageSeal.op_key,target:stageSeal.target_id});assert.deepEqual(await commandVerified(gameId),verifiedCommands);checks.push('actualsameactor anotherlegitimatejob target stillpassesoldstructuralinventory UNKNOWN, but originalsealed command-target MAC rejects reassociation503; old metadata is not proofverification');
 const storedCommand=proofState.commands.stage.find(r=>r.actor===stageSeal.actor&&r.op_key===stageSeal.op_key);for(const part of ['digest','epoch','mac']){if(part==='mac')await proofProbe({action:'mac',kind:'stage',actor:stageSeal.actor,key:stageSeal.op_key,value:'0'.repeat(64)});else await proofProbe({action:'command',kind:'stage',actor:stageSeal.actor,key:stageSeal.op_key,digest:part==='digest'?'0'.repeat(64):storedCommand.request_digest,epoch:part==='epoch'?storedCommand.auth_epoch+1:storedCommand.auth_epoch});await commandDenied({action:'observe',gameId},503,'COMMAND_TARGET_PROOF_CORRUPT');if(part==='mac')await proofProbe({action:'mac',kind:'stage',actor:stageSeal.actor,key:stageSeal.op_key,value:stageSeal.binding_mac});else await proofProbe({action:'command',kind:'stage',actor:stageSeal.actor,key:stageSeal.op_key,digest:storedCommand.request_digest,epoch:storedCommand.auth_epoch});}await commandDenied({action:'other-key',gameId},503,'COMMAND_TARGET_PROOF_CORRUPT');assert.deepEqual(await commandVerified(gameId),verifiedCommands);checks.push('actual stored command digest/authEpoch/MAC independently corrupted, and distinct server requestkey: each exact503, no ignore/reseal or partialsuccess; originalfacts restoredonlyownedforensics');
 await proofProbe({action:'remove-proof',kind:stageSeal.kind,actor:stageSeal.actor,key:stageSeal.op_key});const unsealed=await commandVerified(gameId);assert.equal(unsealed.sealedTargets,verifiedCommands.sealedTargets-1);assert.equal(unsealed.unsealedTargets,1);assert.equal(unsealed.deleteAllowed,false);assert.equal((await proofProbe({action:'stats'})).result.proofs.length,proofState.proofs.length-1);await proofProbe({action:'restore-proof',row:stageSeal});assert.deepEqual(await commandVerified(gameId),verifiedCommands);await commandProbe({action:'remove',kind:stageSeal.kind,actor:stageSeal.actor,key:stageSeal.op_key});await commandDenied({action:'observe',gameId},503,'COMMAND_TARGET_PROOF_CORRUPT');await commandProbe({action:'restore',relation:proofState.targets.find(r=>r.kind===stageSeal.kind&&r.actor===stageSeal.actor&&r.op_key===stageSeal.op_key)});assert.deepEqual(await commandVerified(gameId),verifiedCommands);checks.push('missinglegacyseal counts explicitlyunsealed without auto mutation/deletiongrant; orphanproof missing structural relation exact503, notsilentlyomitted; restoration requiresfixture-only exactoriginalrows');
 await server.close();server=await startEditorBackend(join(own,'wrangler.jsonc'));assert.deepEqual(await commandVerified(gameId),verifiedCommands);assert.deepEqual((await proofProbe({action:'stats'})).result,proofState);checks.push('actualworkerdrestart retains exact proof/command/target rows and observationdigest under persistentservicekey; no brand/SQLrow count alone confers runtime, drain or physicalcleanup');
 // Actual current CompileJobs termination after permanent fence; not provider cancellation/drain.
 const freezeObservations=[],freezer=(v,s=admin)=>call('/api/test/job-freeze',v,s),fo=(v)=>ok('/api/test/job-freeze',v,admin);
 const freezeInput=(g)=>({gameId:g.gameId,expectedRowRevision:g.rowRevision});
 async function frozenJobs(input,s=admin){const r=await freezer({action:'freeze',input},s);assert.equal(r.status,200,r.data.error);const v=r.data.result;assert.equal(v.mode,'CURRENT_COMPILE_JOBS_FROZEN_NOT_DRAINED');assert.equal(v.nativeDrainVerified,false);assert.equal(v.deleteAllowed,false);assert.match(v.jobStateDigest,/^[a-f0-9]{64}$/);assert.deepEqual(Object.keys(v).sort(),['gameId','rowRevision','jobStateDigest','jobsFrozen','jobsPreserved','createdAt','nativeDrainVerified','deleteAllowed','mode'].sort());freezeObservations.push(v);return v;}
 async function freezeDenied(input,status,code,s=admin){const r=await freezer({action:'freeze',input},s);assert.equal(r.status,status);assert.equal(r.data.error,code);}
 const fullFreezeBefore=(await fo({action:'stats',gameId})).result,fullInput=freezeInput({gameId,rowRevision:fullFreezeBefore.game.row_revision});
 await freezeDenied({gameId:'wolong-builtin',expectedRowRevision:'1'},403,'BUILTIN_PROTECTED');await freezeDenied({...fullInput,gameId:[gameId]},422,'DELETE_JOB_FREEZE_INPUT');await freezeDenied(fullInput,404,'GAME_NOT_FOUND',author);await freezeDenied({...fullInput,expectedRowRevision:'1'},409,'DELETE_JOB_FREEZE_CHANGED');await freezeDenied({...fullInput,unexpected:true},422,'REQUEST_FIELDS');
 const races=await Promise.all([freezer({action:'freeze',input:fullInput}),freezer({action:'freeze',input:fullInput})]);for(const r of races)assert.equal(r.status,200,r.data.error);assert.deepEqual(races[0].data,races[1].data);const fullFrozen=await frozenJobs(fullInput);assert.equal(fullFrozen.jobsFrozen,1);assert.equal(fullFrozen.jobsPreserved,2);const fullFreezeAfter=(await fo({action:'stats',gameId})).result;assert.deepEqual(fullFreezeAfter.game,fullFreezeBefore.game);assert.deepEqual(fullFreezeAfter.snapshots,fullFreezeBefore.snapshots);assert.equal(fullFreezeAfter.freezes.length,1);for(const j of fullFreezeBefore.jobs){const updated=fullFreezeAfter.jobs.find(x=>x.job_id===j.job_id);if(j.state==='ready')assert.deepEqual(updated,j);else {assert.equal(updated.state,'failed');assert.equal(updated.failure_code,'DELETION_FROZEN');assert.equal(updated.retryable,0);assert.equal(updated.generation,j.generation+1);assert.equal(updated.row_revision,String(BigInt(j.row_revision)+1n));assert.equal(updated.checkpoint_json,j.checkpoint_json);assert.equal(updated.root_key,j.root_key);}}assert.deepEqual(await commandVerified(gameId),verifiedCommands);checks.push('actual fullcopy ready data/images preserved byte-for-byte, queued fallback nonretryterminal with generation/row advance and lease removed; sameinput realrace one sealedrecord, game/contentmodifiedAt/snapshots unchanged; current commandproof remains valid, foreign/strictfield/CAS failbeforemutation');
 const failureGame=await make('任務凍結故障'),running=(await f({action:'job',gameId:failureGame.gameId},admin)).result,retryJob=(await f({action:'job',gameId:failureGame.gameId},admin)).result,preservedJob=(await f({action:'job',gameId:failureGame.gameId},admin)).result;await fo({action:'job-fail',id:retryJob.operationId,retryable:true});await fo({action:'job-fail',id:preservedJob.operationId,retryable:false});await freezeDenied(freezeInput(failureGame),409,'DELETE_FENCE_REQUIRED');const fenceFailure=(await fenced(failureGame,admin)).result,failureInput={gameId:failureGame.gameId,expectedRowRevision:fenceFailure.rowRevision},failureBefore=(await fo({action:'stats',gameId:failureGame.gameId})).result;
 await fo({action:'job-state',id:running.operationId,state:'unknown-future-state',retryable:0});await freezeDenied(failureInput,503,'DELETE_JOB_FREEZE_JOB');await fo({action:'job-state',id:running.operationId,state:'running',retryable:0});await fo({action:'schema',enabled:true});await freezeDenied(failureInput,503,'DELETE_JOB_FREEZE_SCHEMA');await fo({action:'schema',enabled:false});assert.deepEqual((await fo({action:'stats',gameId:failureGame.gameId})).result,failureBefore);
 await fo({action:'fault',enabled:true});assert.equal((await freezer({action:'freeze',input:failureInput})).status,500);await fo({action:'fault',enabled:false});assert.deepEqual((await fo({action:'stats',gameId:failureGame.gameId})).result,failureBefore);const failureFrozen=await frozenJobs(failureInput);assert.equal(failureFrozen.jobsFrozen,2);assert.equal(failureFrozen.jobsPreserved,1);const failedAfter=(await fo({action:'stats',gameId:failureGame.gameId})).result;assert.deepEqual(failedAfter.jobs.find(j=>j.job_id===preservedJob.operationId),failureBefore.jobs.find(j=>j.job_id===preservedJob.operationId));assert.ok(failedAfter.jobs.every(j=>j.state==='failed'&&j.retryable===0&&j.lease_hash===null&&j.lease_until===0));checks.push('actual real claimedJobs/running+retryablefailed terminalized while pre-existing nonretryfailure unchanged; unknownstate/newcolumn rejected; actual sealINSERT trigger500 rolls back all preceding jobupdates/record, explicit retry success with no name/snapshot/reference removal');
 for(const [action,code]of [['other-key','DELETE_JOB_FREEZE_CORRUPT'],['missing-key','DELETE_JOB_FREEZE_KEY_UNAVAILABLE']]){const badKey=await freezer({action,input:failureInput});assert.equal(badKey.status,503);assert.equal(badKey.data.error,code);assert.deepEqual((await fo({action:'stats',gameId:failureGame.gameId})).result,failedAfter);}const frozenSeal=failedAfter.freezes[0];await fo({action:'seal',gameId:failureGame.gameId,value:'0'.repeat(64)});await freezeDenied(failureInput,503,'DELETE_JOB_FREEZE_CORRUPT');await fo({action:'seal',gameId:failureGame.gameId,value:frozenSeal.freeze_mac});const originalRow=failedAfter.jobs.find(j=>j.job_id===running.operationId);await fo({action:'row',id:running.operationId,value:String(BigInt(originalRow.row_revision)+1n)});await freezeDenied(failureInput,409,'DELETE_JOB_FREEZE_CHANGED');assert.deepEqual((await fo({action:'stats',gameId:failureGame.gameId})).result.freezes,failedAfter.freezes);await fo({action:'row',id:running.operationId,value:originalRow.row_revision});assert.deepEqual(await frozenJobs(failureInput),failureFrozen);await server.close();server=await startEditorBackend(join(own,'wrangler.jsonc'));assert.deepEqual(await frozenJobs(failureInput),failureFrozen);assert.deepEqual((await fo({action:'stats',gameId:failureGame.gameId})).result,failedAfter);checks.push('bad stored freezeMAC503 and postfreeze realjob rowchange409 do not overwrite originalsealedrecord; owned exactrestore is notproductionrepair; trueworkerdrestart exact frozenjobs and same minimalresult, no TTL/unfreeze/brand authority');
 const lateGame=await make('遲到任務結果'),lateJob=(await f({action:'job',gameId:lateGame.gameId},admin)).result,checkpoint=call('/api/test/fence',{action:'checkpoint',gameId:lateGame.gameId,id:lateJob.operationId},admin);for(let i=0;i<200;i++){if((await f({action:'control'},admin)).result.waiting)break;await new Promise(done=>setTimeout(done,10));}assert.equal((await f({action:'control'},admin)).result.waiting,true);const lateFence=(await fenced(lateGame,admin)).result,lateInput={gameId:lateGame.gameId,expectedRowRevision:lateFence.rowRevision},lateFrozen=await frozenJobs(lateInput);assert.equal(lateFrozen.jobsFrozen,1);const lateRows=(await fo({action:'stats',gameId:lateGame.gameId})).result;await f({action:'release'},admin);const lateResult=await checkpoint;assert.equal(lateResult.status,409);assert.equal(lateResult.data.error,'GAME_DELETING');assert.deepEqual((await fo({action:'stats',gameId:lateGame.gameId})).result,lateRows);assert.equal(lateRows.jobs[0].checkpoint_json,'[]');assert.equal(lateRows.jobs[0].generation,2);checks.push('actual opaque checkpoint verifier held after native body read, then actualfence and SQLfreeze: leasehash removed/genadvanced; late checkpoint exactexisting GAME_DELETING guard denies beforewrite, remains same terminalrow/emptycheckpoint, not separate leaseguard attribution or media/gameplay proof');
 const nativeGame=await make('原生寫入未排空');await f({action:'job',gameId:nativeGame.gameId},admin);await w({action:'pause',kind:'after'});const nativePending=call('/api/test/writes',{action:'put',gameId:nativeGame.gameId,marker:220},admin);await wait(nativeGame.gameId);const nativeFence=(await fenced(nativeGame,admin)).result,nativeInput={gameId:nativeGame.gameId,expectedRowRevision:nativeFence.rowRevision},nativeFrozen=await frozenJobs(nativeInput);assert.equal(nativeFrozen.jobsFrozen,1);const nativeObservation=await observe(nativeGame.gameId,admin);assert.equal(nativeObservation.pendingRecords,0);assert.equal(nativeObservation.privateWritesPending,1);assert.equal(nativeObservation.deleteAllowed,false);assert.equal((await stats(nativeGame.gameId)).rows[0].state,'pending');await w({action:'release'});const lateNative=await nativePending;assert.equal(lateNative.status,409);assert.equal(lateNative.data.error,'GAME_DELETING');assert.deepEqual(await frozenJobs(nativeInput),nativeFrozen);assert.equal((await stats(nativeGame.gameId)).rows[0].state,'settled');checks.push('actual Root nativePUT alreadycommitted but returnpromise held: SQL Job frozen/count0 while persistent nativepending1; no provider abort or journalack in freeze, original callback settles only afterexplicit fixture release and outerfence409; counters0 notglobaldrain/delete proof');
 const foreignState=(await fo({action:'stats',gameId:foreign.gameId})).result,foreignInput={gameId:foreign.gameId,expectedRowRevision:foreignState.game.row_revision},managedFreeze=await (async()=>{await probe({action:'pause'},admin);const pendingInventory=inv({action:'observe',gameId:foreign.gameId},admin);for(let i=0;i<200;i++){if((await f({action:'control'},admin)).result.waiting)break;await new Promise(done=>setTimeout(done,10));}assert.equal((await f({action:'control'},admin)).result.waiting,true);const result=await frozenJobs(foreignInput);await f({action:'release'},admin);const invalidated=await pendingInventory;assert.equal(invalidated.status,409);assert.equal(invalidated.data.error,'DELETE_INVENTORY_CHANGED');checks.push('actual paused nativeinventory list on zerojob game, only newfreeze record changes: late oldcapture409 proves scoped frozenrecord participates in SQLdigest; no Job/content mutation or in-flightdrain assertion');return result;})();assert.equal(managedFreeze.jobsFrozen,0);assert.equal(managedFreeze.jobsPreserved,0);assert.deepEqual(await frozenJobs(foreignInput,author),managedFreeze);const oldAdmin=admin,finalPassword=randomBytes(24).toString('hex'),changedAgain=await call('/api/auth/password',{oldPassword:lastPassword,newPassword:finalPassword},admin);assert.equal(changedAgain.status,200);admin={cookie:changedAgain.cookie,csrf:changedAgain.data.csrf};await freezeDenied(failureInput,401,'SESSION_INVALID',oldAdmin);assert.deepEqual(await frozenJobs(failureInput),failureFrozen);const noPublic=await call('/api/games/'+failureGame.gameId+'/delete',{},admin);assert.equal(noPublic.status,404);checks.push('actualadmin crossauthor management only smallest freezefacts, owner same zerojob result; actualpasswordhandler oldcookie401/newprincipal repeats persistent freeze without reviving anylease; publicdelete remains404, no bodies/keys/contents/cleanup claim');

 for(const[p,h]of Object.entries({...inputs,...before.imports,...sourceHashes}))assert.equal(sha(readFileSync(p)),h,p);process.stdout.write(JSON.stringify({result:'PASS-ACTUAL-DELETION-JOB-FREEZE-NOT-DRAIN',checks,calls,observations,byteObservations,commandObservations,freezeObservations,sourceHashes,protected:461,limits:'Current private native bytes SHA/length observations, not media/schema validity, fullrefs/drain/crossservice atomicity or delete permission. Owned fixture body damage/removal only fault injection. No product deletion/resolver/cache/backup/player410/Trial/release/overallcompletion.'},null,2)+'\n');
}catch(error){writeFileSync(dir+'failure-r'+round+'.json',JSON.stringify({checks,calls,sourceHashes,error:{message:error.message,code:error.code??null}},null,2)+'\n',{flag:'wx'});throw error;}finally{await server?.close();}
