// Real Root, own persisted SQLite/R2, fresh Chromium; response loss only at browser network boundary.
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { randomBytes, randomUUID, createHash } from 'node:crypto';
import { request as httpsRequest } from 'node:https';
import { pathToFileURL } from 'node:url';
import { startEditorBackend } from './start_editor_backend.mjs';
const own = mkdtempSync(join(tmpdir(), 'dragon-draft-ui-')), origin = 'https://127.0.0.1:8787', initial = randomBytes(24).toString('hex'), password = randomBytes(24).toString('hex'), secret = randomBytes(32).toString('hex'), sha = b => createHash('sha256').update(b).digest('hex');
function json(bytes) { try { return JSON.parse(bytes); } catch (cause) { throw new Error('invalid owned UI evidence JSON', { cause }); } }
const config = json(readFileSync('server/wrangler.jsonc')); config.main = resolve('server/worker.js'); writeFileSync(join(own, 'wrangler.jsonc'), JSON.stringify(config)); writeFileSync(join(own, '.dev.vars'), 'EDITOR_DEFAULT_PASSWORD=' + JSON.stringify(initial) + '\nEDITOR_REQUEST_KEY=' + JSON.stringify(secret) + '\n', { flag: 'wx', mode: 0o600 });
const paths = ['server/worker.js', 'server/public/client.txt', 'server/public/index.html', 'server/public/draft.txt', 'tools/verify_editor_backend_draft_ui.mjs'], sourceHashes = Object.fromEntries(paths.map(p => [p, sha(readFileSync(p))])), calls = [], checks = []; let server, browser;
async function call(path, body, session, extra = {}) { const headers = { Origin: origin, ...extra }; if (session) { headers.Cookie = session.cookie; headers['X-CSRF-Token'] = session.csrf; } if (body !== undefined) { headers['Content-Type'] = 'application/json'; headers['Idempotency-Key'] ??= randomUUID(); } const response = await new Promise((done, reject) => { const req = httpsRequest(origin + path, { method: body === undefined ? 'GET' : 'POST', headers, rejectUnauthorized: false }, res => { const parts = []; res.on('data', b => parts.push(b)); res.on('error', reject); res.on('end', () => done({ status: res.statusCode, cookie: res.headers['set-cookie']?.[0]?.split(';')[0], data: json(Buffer.concat(parts).toString()) })); }); req.on('error', reject); req.end(body === undefined ? undefined : JSON.stringify(body)); }); calls.push({ path, status: response.status }); return response; }
const wait = page => page.waitForFunction(() => !document.querySelector('#draft-games-refresh').disabled, undefined, { timeout: 240000 });
async function load(page, revision) { await page.locator('#draft-revision').fill(revision); await page.locator('#draft-load').click(); await page.waitForFunction(rev => document.querySelector('#draft-context').textContent.includes('已保存修訂 ' + rev) && !document.querySelector('#draft-name').disabled, revision, { timeout: 240000 }); }
try {
  process.stderr.write('draft-ui: setup\n'); server = await startEditorBackend(join(own, 'wrangler.jsonc'), { stageSource: true }); const login = await call('/api/auth/login', { account: 'tianyi', password: initial }); assert.equal(login.status, 200); const changed = await call('/api/auth/password', { oldPassword: initial, newPassword: password }, { cookie: login.cookie, csrf: login.data.csrf }); assert.equal(changed.status, 200); const admin = { cookie: changed.cookie, csrf: changed.data.csrf };
  const source = await call('/api/admin/source', undefined, admin); assert.equal((await call('/api/admin/source/install', {}, admin)).status, 200); const copyKey = randomUUID(), copy = await call('/api/admin/copies', { registryId: source.data.definition.registryId, name: '<img>', introduction: '私有原稿' }, admin, { 'Idempotency-Key': copyKey }); assert.equal(copy.status, 202); assert.equal((await call('/api/admin/copies/' + copyKey + '/run', {}, admin, { 'If-Match': '"1"' })).status, 200); const gameId = copy.data.gameId;
  const { chromium } = await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href); browser = await chromium.launch({ headless: true }); const context = await browser.newContext({ ignoreHTTPSErrors: true, viewport: { width: 1280, height: 1000 } }), errors = [], outside = [], expected = [], requests = [];
  await context.addInitScript(() => Object.defineProperty(globalThis, 'indexedDB', { get() { globalThis.__idbAccess = (globalThis.__idbAccess ?? 0) + 1; throw new Error('IDB forbidden'); } })); await context.route('**/*', route => { if (new URL(route.request().url()).origin !== origin) { outside.push('outside'); return route.abort(); } return route.continue(); });
  const page = await context.newPage(); page.on('pageerror', error => errors.push(error.message)); page.on('console', message => { if (message.type() !== 'error') return; const path = new URL(message.location().url || origin).pathname, text = message.text(); if (path === '/api/session' && text.includes('401') || path === '/favicon.ico' && text.includes('404') || path === '/api/games/' + gameId + '/draft/save' && (text.includes('net::ERR_FAILED') || text.includes('412')) || path.startsWith('/api/games/' + gameId + '/draft/operations/') && text.includes('404')) expected.push({ path, text }); else errors.push(text); }); page.on('request', request => { const path = new URL(request.url()).pathname; if (path.endsWith('/draft/save')) requests.push({ method: request.method(), path, key: request.headers()['idempotency-key'], revision: request.headers()['if-match'] }); });
  await page.goto(origin); await page.locator('#login [name=account]').fill('tianyi'); await page.locator('#login [name=password]').fill(password); await page.locator('#login button').click(); await page.locator('#draft-editor').waitFor({ state: 'visible' }); await wait(page); await page.locator('#draft-games-refresh').click(); await page.waitForFunction(() => document.querySelector('#draft-game').options.length === 1 && !document.querySelector('#draft-games-refresh').disabled); assert.equal(await page.locator('#draft-game').inputValue(), gameId); assert.equal(await page.locator('#draft-game option').textContent(), '<img>／清單修訂 1'); assert.equal(await page.locator('#draft-game img').count(), 0);
  process.stderr.write('draft-ui: explicit read\n'); await load(page, '1'); assert.equal(await page.locator('#draft-name').inputValue(), '<img>'); assert.equal(await page.locator('#draft-resources details').count(), 20); assert.equal(await page.locator('#draft-resources input').count(), 0); checks.push('actual authenticated own-summary/explicit immutable draft1, textContent author labels and20chapter/fourresource readonly, no playable controls');
  await page.locator('#draft-name').fill('未保存'); page.once('dialog', dialog => dialog.dismiss()); await page.locator('#draft-load').click(); await wait(page); assert.equal(await page.locator('#draft-name').inputValue(), '未保存'); assert.ok((await page.locator('#draft-context').textContent()).includes('有未保存修改')); const unloadDialog = new Promise((done, reject) => page.once('dialog', async dialog => { try { assert.equal(dialog.type(), 'beforeunload'); await dialog.dismiss(); done(); } catch (error) { reject(error); } })); await page.evaluate(() => location.reload()); await unloadDialog; assert.equal(await page.locator('#draft-name').inputValue(), '未保存'); const savesBefore = requests.length; await page.locator('#draft-name').fill('九個字ABCDEFGHI'); await page.locator('#draft-save-button').click(); await wait(page); assert.equal(requests.length, savesBefore); assert.equal(await page.locator('#draft-name').inputValue(), '九個字ABCDEFGHI'); checks.push('dirty reload cancel retains input/context; codepoint validation rejects before request, no implicit save');
  let dropped = 0; const saveURL = origin + '/api/games/' + gameId + '/draft/save'; await page.route(saveURL, async route => { const response = await route.fetch({ timeout: 240000 }); assert.equal(response.status(), 200); dropped++; await route.abort(); });
  await page.locator('#draft-name').fill('資料二'); await page.locator('#draft-introduction').fill('e\u0301 😀 <x>'); process.stderr.write('draft-ui: lost committed response\n'); await page.locator('#draft-save-button').click(); await page.waitForFunction(() => document.querySelector('#draft-status').textContent.includes('保存未確認') && !document.querySelector('#draft-operation-query').disabled, undefined, { timeout: 240000 }); assert.equal(dropped, 1); assert.equal(await page.locator('#draft-introduction').inputValue(), 'e\u0301 😀 <x>'); assert.equal(await page.locator('#draft-save-button').isDisabled(), true); await page.unroute(saveURL);
  await page.locator('#draft-operation-query').click(); await page.waitForFunction(() => document.querySelector('#draft-status').textContent.includes('已確認保存修訂 2') && !document.querySelector('#draft-name').disabled); assert.equal(await page.locator('#draft-introduction').inputValue(), 'é 😀 <x>'); assert.equal(requests.length, savesBefore + 1); checks.push('actual Root commits draft2 but browser response deliberately dropped: original fields/key kept, no newkey/autoretry; explicit query confirms same operation and NFC result');
  const external = await call('/api/games/' + gameId + '/draft/save', { metadata: { name: '他頁修改', introduction: '另一明確請求' }, resourceEdits: [] }, admin, { 'If-Match': '"2"' }); assert.equal(external.status, 200); await page.locator('#draft-name').fill('本頁保留'); process.stderr.write('draft-ui: conditional conflict\n'); await page.locator('#draft-save-button').click(); await page.waitForFunction(() => document.querySelector('#draft-status').textContent.includes('保存未確認') && !document.querySelector('#draft-operation-query').disabled, undefined, { timeout: 240000 }); assert.equal(await page.locator('#draft-name').inputValue(), '本頁保留'); await page.locator('#draft-operation-query').click(); await page.waitForFunction(() => document.querySelector('#draft-status').textContent.includes('服務已記錄失敗') && !document.querySelector('#draft-operation-retry').disabled); const staleKey = requests.at(-1).key;
  await page.locator('#draft-operation-retry').click(); await page.waitForFunction(() => document.querySelector('#draft-status').textContent.includes('保存未確認') && !document.querySelector('#draft-operation-query').disabled, undefined, { timeout: 240000 }); assert.equal(requests.at(-1).key, staleKey); assert.equal(requests.at(-1).revision, '"2"'); assert.equal(await page.locator('#draft-name').inputValue(), '本頁保留'); await page.locator('#draft-operation-query').click(); await page.waitForFunction(() => document.querySelector('#draft-status').textContent.includes('服務已記錄失敗')); page.once('dialog', dialog => dialog.accept()); await load(page, '3'); assert.equal(await page.locator('#draft-name').inputValue(), '他頁修改'); checks.push('actual concurrent writer moves saved3; stale2 HTTP412 retains field, explicit query/identical key retry notlatest; confirmed discard+explicit read3 only');
  await page.route(saveURL, async route => { const response = await route.fetch({ timeout: 240000 }); assert.equal(response.status(), 200); dropped++; await route.abort(); }); await page.locator('#draft-name').fill('重新載入'); process.stderr.write('draft-ui: unresolved reload\n'); await page.locator('#draft-save-button').click(); await page.waitForFunction(() => document.querySelector('#draft-status').textContent.includes('保存未確認') && !document.querySelector('#draft-operation-query').disabled, undefined, { timeout: 240000 });
  const association = await page.evaluate(() => Object.entries(sessionStorage).filter(([key]) => key.startsWith('editor-draft-operation:')).map(([,value]) => Object.keys(JSON.parse(value)).sort())); assert.deepEqual(association, [['gameId','key','revision']]); await page.unroute(saveURL); page.once('dialog', dialog => dialog.accept()); await page.reload(); await page.locator('#draft-editor').waitFor({ state: 'visible' }); await wait(page); assert.equal(await page.locator('#draft-operation-retry').isDisabled(), true); await page.locator('#draft-operation-query').click(); await page.waitForFunction(() => document.querySelector('#draft-status').textContent.includes('已確認保存修訂 4')); assert.equal(await page.locator('#draft-save-button').isDisabled(), true); assert.equal(requests.length, savesBefore + 4); checks.push('unresolved page reload retains only actor-associated game/revision/key, no author input/credential; actual permanent operation confirms4 without reconstructed payload or autosave, editing requires exact read');
  process.stderr.write('draft-ui: no-op and author isolation\n'); await page.locator('#draft-games-refresh').click(); await page.waitForFunction(() => document.querySelector('#draft-game').options.length === 1 && !document.querySelector('#draft-games-refresh').disabled); await load(page, '4'); await page.locator('#draft-save-button').click(); await page.waitForFunction(() => document.querySelector('#draft-status').textContent.includes('已確認保存修訂 4') && !document.querySelector('#draft-name').disabled, undefined, { timeout: 240000 }); assert.equal(requests.length, savesBefore + 5); assert.equal(await page.locator('#draft-name').inputValue(), '重新載入'); checks.push('recovered receipt alone does not enable edits; actual explicit read4 then clean metadata no-op keeps saved4');
  assert.equal((await call('/api/admin/accounts', { account: 'ui_author' }, admin)).status, 200); const authorLogin = await call('/api/auth/login', { account: 'ui_author', password: initial }); assert.equal(authorLogin.status, 200); const authorChanged = await call('/api/auth/password', { oldPassword: initial, newPassword: password }, { cookie: authorLogin.cookie, csrf: authorLogin.data.csrf }); assert.equal(authorChanged.status, 200);
  const foreignContext = await browser.newContext({ ignoreHTTPSErrors: true }); await foreignContext.addInitScript(() => Object.defineProperty(globalThis, 'indexedDB', { get() { globalThis.__idbAccess = (globalThis.__idbAccess ?? 0) + 1; throw new Error('IDB forbidden'); } })); await foreignContext.route('**/*', route => { if (new URL(route.request().url()).origin !== origin) { outside.push('outside'); return route.abort(); } return route.continue(); }); const foreignPage = await foreignContext.newPage(); foreignPage.on('pageerror', error => errors.push(error.message)); foreignPage.on('console', message => { if (message.type() !== 'error') return; const path = new URL(message.location().url || origin).pathname, text = message.text(); if (path === '/api/session' && text.includes('401') || path === '/favicon.ico' && text.includes('404')) expected.push({ path, text }); else errors.push(text); }); await foreignPage.goto(origin); await foreignPage.locator('#login [name=account]').fill('ui_author'); await foreignPage.locator('#login [name=password]').fill(password); await foreignPage.locator('#login button').click(); await foreignPage.locator('#draft-editor').waitFor({ state: 'visible' }); await wait(foreignPage); assert.equal(await foreignPage.locator('#admin').isVisible(), false); await foreignPage.locator('#draft-games-refresh').click(); await foreignPage.waitForFunction(() => !document.querySelector('#draft-games-refresh').disabled); assert.equal(await foreignPage.locator('#draft-game option').count(), 0); assert.equal(await foreignPage.locator('#draft-name').isDisabled(), true); assert.equal(await foreignPage.locator('#draft-resources details').count(), 0); assert.equal(await foreignPage.evaluate(() => globalThis.__idbAccess ?? 0), 0); await foreignContext.close(); checks.push('separate actual author login sees no administrator copy/game/inputs; no client owner or storage association grants access');
  process.stderr.write('draft-ui: missing original body recovery\n'); let unsent = 0; await page.route(saveURL, async route => { unsent++; await route.abort(); }); await page.locator('#draft-name').fill('未送達'); await page.locator('#draft-save-button').click(); await page.waitForFunction(() => document.querySelector('#draft-status').textContent.includes('保存未確認') && !document.querySelector('#draft-operation-query').disabled); assert.equal(unsent, 1); await page.unroute(saveURL); page.once('dialog', dialog => dialog.accept()); await page.reload(); await page.locator('#draft-editor').waitFor({ state: 'visible' }); await wait(page); await page.locator('#draft-operation-query').click(); await page.waitForFunction(() => document.querySelector('#draft-status').textContent.includes('目前查無原操作')); assert.equal(await page.locator('#draft-load').isDisabled(), true); assert.equal(await page.locator('#draft-operation-retry').isDisabled(), true);
  const recoveryPassword = randomBytes(24).toString('hex'); await page.locator('#password [name=oldPassword]').fill(password); await page.locator('#password [name=newPassword]').fill(recoveryPassword); await page.locator('#password [name=confirmPassword]').fill(recoveryPassword); page.once('dialog', dialog => dialog.accept()); await page.locator('#password button').click(); await page.waitForFunction(() => document.querySelector('#draft-status').textContent.includes('服務已確認改密') && !document.querySelector('#draft-load').disabled); await page.locator('#draft-operation-query').click(); await page.waitForFunction(() => document.querySelector('#draft-status').textContent.includes('舊會話已由實際改密撤銷') && !document.querySelector('#draft-load').disabled); await page.locator('#draft-games-refresh').click(); await page.waitForFunction(() => document.querySelector('#draft-game').options.length === 1 && !document.querySelector('#draft-games-refresh').disabled); page.once('dialog', dialog => dialog.accept()); await load(page, '4'); assert.equal(await page.locator('#draft-name').inputValue(), '重新載入'); assert.equal(requests.length, savesBefore + 6); checks.push('browser aborts BEFORE sending Root POST; reload loses body, real404 forbids reconstruction/newkey; actual user-confirmed password change revokes old epoch, still404 is not saved/failed, explicit discard+read4 recovers without new save');
  assert.equal(await page.evaluate(() => globalThis.__idbAccess ?? 0), 0); assert.deepEqual(errors, []); assert.deepEqual(outside, []); const shot = process.argv[2]; assert.ok(typeof shot === 'string' && /^\.dragon-analysis\/editor-phase\/backend-draft-ui-session-r1\/ui-r[1-9][0-9]*\.png$/.test(shot)); const pixels = await page.screenshot({ fullPage: true }); writeFileSync(shot, pixels, { flag: 'wx' }); for (const [p,h] of Object.entries(sourceHashes)) assert.equal(sha(readFileSync(p)), h);
  process.stdout.write(JSON.stringify({ result: 'PASS-REAL-PRIVATE-METADATA-UI', checks, calls, sourceHashes, browserSaveRequests: requests.length, droppedResponses: dropped, errors, outside, expected, screenshot: shot, screenshotSha: sha(pixels), limits: 'Actual local Root/SQL/R2 and fresh browser metadata-only UI; resource values readonly, no arbitrary source/map/role UI, playable range/runtime/compiler/Q69/Trial/release/cloudSLA or goalcompletion. Response loss at browser network only, no fake successful backend.' }, null, 2) + '\n');
} finally { await browser?.close(); await server?.close(); }
