// Fake HTTP/lifecycle/bitmap model. NOT native authority, browser or runtime evidence.
import assert from 'node:assert/strict';import {webcrypto,createHash} from 'node:crypto';import {readFileSync,writeFileSync} from 'node:fs';import {createPrivateResourceContext} from '../web/src/content/privateresources.js';import {encodePNG} from '../server/pngio.js';
const d='.dragon-analysis/editor-phase/backend-private-resource-decode-session-r1/',round=process.argv[2]??'1';assert.match(round,/^[1-9][0-9]{0,2}$/);const checks=[],ref={gameId:'11111111-1111-4111-8111-111111111111',draftRevision:'1',sourceDigest:'a'.repeat(64),dependencyDigest:'b'.repeat(64)},operationId='22222222-2222-4222-8222-222222222222',sha=b=>createHash('sha256').update(b).digest('hex'),jsonBytes=v=>new TextEncoder().encode(JSON.stringify(v));
function loc(raw){return {kind:'private-stage',gameId:ref.gameId,draftRevision:'1',sourceDigest:ref.sourceDigest,purpose:'data',operationId,assetId:'roads_0',sha256:sha(raw),byteLength:raw.length};}
function setup(raw,ports={}){let calls=0,alive=true,closes=0,decodeCalls=0;const x=loc(raw),fetcher=async()=>{calls++;return new Response(raw.slice(),{headers:{'X-Game-ID':ref.gameId,'X-Draft-Revision':'1','X-Source-SHA256':ref.sourceDigest,'X-Dependency-SHA256':ref.dependencyDigest,'X-Content-SHA256':x.sha256,'Content-Type':'application/octet-stream','Cache-Control':'no-store','X-Content-Admission':'stage-only'}});},decodeBitmap=async()=>{decodeCalls++;return {width:2,height:1,close(){closes++;}};};const ctx=createPrivateResourceContext(ref,{fetcher,subtle:webcrypto.subtle,decodeBitmap,assertCurrent(){assert.ok(alive,'local life changed');},...ports});return {ctx,x,calls:()=>calls,closes:()=>closes,decodeCalls:()=>decodeCalls,revoke(){alive=false;}};}
async function rejects(fn,code){try{await fn();assert.fail('expected '+code);}catch(e){assert.equal(e.message,code);}checks.push(code);}
const expected={version:2,items:[1,'繁體',null,{unknown:true}],literal:'<img onerror=evil>'},raw=jsonBytes(expected),s=setup(raw);const value=await s.ctx.readJSON(s.x);assert.deepEqual(value,expected);assert.ok(Object.isFrozen(value)&&Object.isFrozen(value.items)&&Object.isFrozen(value.items[3]));await s.ctx.readJSON(s.x);assert.equal(s.calls(),2);assert.equal(s.decodeCalls(),0);checks.push('detached frozen JSON through byte verified fresh GET each explicit call; no decoder/eval/settled cache');
for(const invalid of [new Uint8Array([0xff]),new TextEncoder().encode('{bad}'),new TextEncoder().encode('\ufeff{}')]){const t=setup(invalid);await rejects(()=>t.ctx.readJSON(t.x),'PRIVATE_RESOURCE_JSON');}
const inf=setup(new TextEncoder().encode('1e999'));await rejects(()=>inf.ctx.readJSON(inf.x),'PRIVATE_RESOURCE_JSON_NUMBER');let deep=null;for(let i=0;i<34;i++)deep=[deep];const nested=setup(jsonBytes(deep));await rejects(()=>nested.ctx.readJSON(nested.x),'PRIVATE_RESOURCE_JSON_BUDGET');const many=setup(jsonBytes(Array(200000).fill(null)));await rejects(()=>many.ctx.readJSON(many.x),'PRIVATE_RESOURCE_JSON_BUDGET');await rejects(()=>s.ctx.readJSON({...s.x,byteLength:4194305}),'PRIVATE_RESOURCE_JSON_BUDGET');let getterCalls=0;const getter={...s.x};Object.defineProperty(getter,'assetId',{enumerable:true,get(){getterCalls++;return 'roads_0';}});await rejects(()=>s.ctx.readJSON(getter),'PRIVATE_RESOURCE_LOCATOR');assert.equal(getterCalls,0);
await rejects(()=>s.ctx.readJSON({...s.x,gameId:'33333333-3333-4333-8333-333333333333'}),'PRIVATE_BYTES_CONTEXT');await rejects(()=>s.ctx.readJSON({...s.x,extra:true}),'PRIVATE_BYTES_FIELDS');const encoded=Uint8Array.from(encodePNG(new Uint8Array([1,2,3,255,4,5,6,255]),2,1)),p=setup(encoded);const bitmap=await p.ctx.readPNG(p.x);assert.equal(bitmap.width,2);assert.equal(bitmap.height,1);assert.ok(Object.isFrozen(bitmap));assert.equal(p.decodeCalls(),1);bitmap.dispose();bitmap.dispose();assert.equal(p.closes(),1);checks.push('PNG envelope+trusted bitmap port, detached owned handle explicit idempotent dispose');
const handles=[];for(let i=0;i<8;i++)handles.push(await p.ctx.readPNG(p.x));await rejects(()=>p.ctx.readPNG(p.x),'PRIVATE_RESOURCE_IMAGE_BUDGET');assert.equal(p.calls(),9);p.ctx.close();p.ctx.close();assert.equal(p.closes(),9);await rejects(()=>p.ctx.readPNG(p.x),'PRIVATE_RESOURCE_CLOSED');checks.push('eight owned images budget; close each owned once without SQL/provider cancellation or settled cache');
const badSig=setup(raw);await rejects(()=>badSig.ctx.readPNG(badSig.x),'PRIVATE_RESOURCE_PNG_SIGNATURE');const badCrc=encoded.slice();badCrc[29]^=1;const c=setup(badCrc);await rejects(()=>c.ctx.readPNG(c.x),'PRIVATE_RESOURCE_PNG_CRC');assert.equal(c.decodeCalls(),0);
function crc(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let j=0;j<8;j++)c=c&1?(c>>>1)^0xedb88320:c>>>1;}return (c^0xffffffff)>>>0;}
function ihdrChange(offset,byte){const b=encoded.slice();b[offset]=byte;new DataView(b.buffer,b.byteOffset,b.byteLength).setUint32(29,crc(b.subarray(12,29)));return b;}
for(const [b,code]of [[ihdrChange(28,1),'PNG_FORMAT'],[ihdrChange(24,16),'PNG_FORMAT'],[ihdrChange(16,1),'PNG_PIXELS']]){const t=setup(b);await rejects(()=>t.ctx.readPNG(t.x),'PRIVATE_RESOURCE_'+code);assert.equal(t.decodeCalls(),0);}
const trailing=setup(Uint8Array.from([...encoded,0]));await rejects(()=>trailing.ctx.readPNG(trailing.x),'PRIVATE_RESOURCE_PNG_IEND');const missingEnd=setup(encoded.slice(0,-12));await rejects(()=>missingEnd.ctx.readPNG(missingEnd.x),'PRIVATE_RESOURCE_PNG_IEND');
function chunk(kind,body=new Uint8Array()){const out=new Uint8Array(body.length+12),view=new DataView(out.buffer);view.setUint32(0,body.length);out.set(new TextEncoder().encode(kind),4);out.set(body,8);view.setUint32(body.length+8,crc(out.subarray(4,body.length+8)));return out;}
for(const kind of ['acTL','iCCP','gAMA','cICP']){const b=Uint8Array.from([...encoded.slice(0,33),...chunk(kind),...encoded.slice(33)]),t=setup(b);await rejects(()=>t.ctx.readPNG(t.x),'PRIVATE_RESOURCE_PNG_METADATA');assert.equal(t.decodeCalls(),0);}
const broken=setup(encoded,{decodeBitmap:async()=>{throw new Error('native decode failed');}});await rejects(()=>broken.ctx.readPNG(broken.x),'native decode failed');const badShape=setup(encoded,{decodeBitmap:async()=>({width:1,height:1,close(){}})});await rejects(()=>badShape.ctx.readPNG(badShape.x),'PRIVATE_RESOURCE_PNG_DECODE');
let resume,closed=0;const late=setup(encoded,{decodeBitmap:()=>new Promise(resolve=>{resume=resolve;})});const loading=late.ctx.readPNG(late.x);while(!resume)await new Promise(resolve=>setImmediate(resolve));late.ctx.close();resume({width:2,height:1,close(){closed++;}});await rejects(()=>loading,'PRIVATE_RESOURCE_CLOSED');assert.equal(closed,1);checks.push('close during bitmap await: late owned image closed, no escaped handle/provider drain claim');
let resume2,closed2=0;const revoked=setup(encoded,{decodeBitmap:()=>new Promise(resolve=>{resume2=resolve;})});const pending=revoked.ctx.readPNG(revoked.x);while(!resume2)await new Promise(resolve=>setImmediate(resolve));revoked.revoke();resume2({width:2,height:1,close(){closed2++;throw new Error('cleanup');}});await rejects(()=>pending,'local life changed');assert.equal(closed2,1);checks.push('late lifecycle failure preserved even if owned bitmap cleanup throws');
const library={kind:'private-library',gameId:ref.gameId,draftRevision:'1',sourceDigest:ref.sourceDigest,assetId:'library-001',sha256:sha(raw),byteLength:raw.length,registryId:'approved-available-library-76cdf28-1',catalogRoot:'c'.repeat(64),logicalURL:'battle_rules.json',mime:'application/json'};await rejects(()=>s.ctx.readPNG(library),'PRIVATE_RESOURCE_FORMAT');await rejects(()=>s.ctx.readJSON({...library,mime:'image/png',logicalURL:'kao/0.png'}),'PRIVATE_RESOURCE_FORMAT');assert.equal(s.calls(),2);
const ordinary=setup(new TextEncoder().encode('{"__proto__":{"safe":true},"constructor":"literal"}'));const literal=await ordinary.ctx.readJSON(ordinary.x);assert.ok(Object.hasOwn(literal,'__proto__'));assert.equal({}.safe,undefined);checks.push('JSON keys preserved as inert own frozen data, never Object.assign/eval/install/schema certificate');assert.deepEqual(['runtimeAllowed','trialAllowed','releaseAllowed','deleteAllowed'].map(k=>s.ctx[k]),[false,false,false,false]);s.ctx.close();writeFileSync(d+'model-r'+round+'.json',JSON.stringify({checks,fakeHTTP:true,fakeBitmap:true,nativeRootAuthority:false,actualBrowser:false,providerDrain:false,sourceHashes:Object.fromEntries(['web/src/content/privateresources.js','web/src/content/privatebytes.js','tools/verify_editor_private_resources.mjs'].map(p=>[p,sha(readFileSync(p))]))},null,2)+'\n',{flag:'wx'});process.stdout.write(JSON.stringify({checks:checks.length})+'\n');
