// Owned real Root-derived Worker/SQL/R2, full fixed-copy source and unchanged common compiler.
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { randomBytes, randomUUID, createHash } from 'node:crypto';
import { request as httpsRequest } from 'node:https';
import { DatabaseSync } from 'node:sqlite';
import { startEditorBackend } from './start_editor_backend.mjs';
import { compileGameSource } from '../web/src/content/authoring/trialcompile.js';
import { encodeSourceChunks } from '../web/src/content/authoring/sourcejson.js';
const dir = '.dragon-analysis/editor-phase/backend-data-compile-session-r1/', own = mkdtempSync(join(tmpdir(), 'dragon-data-compile-')), origin = 'https://127.0.0.1:8787', sha = b => createHash('sha256').update(b).digest('hex'), jsonBytes = v => Buffer.concat(encodeSourceChunks(v));
function parse(b) { try { return JSON.parse(b); } catch (cause) { throw new Error('invalid owned compile response', { cause }); } }
const initial = randomBytes(24).toString('hex'), password = randomBytes(24).toString('hex'), secret = randomBytes(32).toString('hex'), config = parse(readFileSync('server/wrangler.jsonc')), configPath = join(own, 'wrangler.jsonc'); config.main = resolve(dir + 'fixture-worker.js'); writeFileSync(configPath, JSON.stringify(config)); writeFileSync(join(own, '.dev.vars'), 'EDITOR_DEFAULT_PASSWORD=' + JSON.stringify(initial) + '\nEDITOR_REQUEST_KEY=' + JSON.stringify(secret) + '\n', { flag: 'wx', mode: 0o600 });
const inputs = ['server/datacompiler.js','server/drafts.js','server/jobs.js','server/worker.js','tools/verify_editor_backend_data_compile.mjs',dir+'fixture-worker.js'], sourceHashes = Object.fromEntries(inputs.map(p => [p, sha(readFileSync(p))])), checks = [], calls = []; let server;
async function call(path, value, session, extra = {}, raw = false) { const headers = { Origin: origin, ...extra }; if (session) { headers.Cookie = session.cookie; headers['X-CSRF-Token'] = session.csrf; } if (value !== undefined) { headers['Content-Type'] = 'application/json'; headers['Idempotency-Key'] ??= randomUUID(); } const r = await new Promise((done,reject) => { const req = httpsRequest(origin+path, { method: value === undefined ? 'GET' : 'POST', headers, rejectUnauthorized: false }, res => { const parts = []; res.on('data', b => parts.push(b)); res.on('error', reject); res.on('end', () => { try { const bytes = Buffer.concat(parts); done({ status: res.statusCode, data: raw ? bytes : parse(bytes), cookie: res.headers['set-cookie']?.[0]?.split(';')[0] }); } catch (error) { reject(error); } }); }); req.on('error', reject); req.end(value === undefined ? undefined : JSON.stringify(value)); }); calls.push({ path: path.split('?')[0], status: r.status }); return r; }
async function login(name) { const a = await call('/api/auth/login', { account: name, password: initial }); assert.equal(a.status,200); const c = await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:a.cookie,csrf:a.data.csrf}); assert.equal(c.status,200); return {cookie:c.cookie,csrf:c.data.csrf}; }
function databases(p) { return readdirSync(p,{withFileTypes:true}).flatMap(e=>{ if(e.isDirectory())return databases(join(p,e.name)); if(e.name.endsWith('.sqlite'))return [join(p,e.name)]; return []; }); }
function db() { for(const p of databases(join(own,'.local/metadata'))) { const d=new DatabaseSync(p); if(d.prepare("SELECT name FROM sqlite_master WHERE name='compile_jobs'").get())return d; d.close(); } throw new Error('owned compile SQL missing'); }
try {
  process.stderr.write('data-compile: fixed full source\n'); server = await startEditorBackend(configPath,{stageSource:true}); const admin = await login('tianyi'); assert.equal((await call('/api/admin/accounts',{account:'compile_author'},admin)).status,200); const foreign=await login('compile_author'); assert.equal((await call('/api/admin/source/install',{},admin)).status,200); const source=(await call('/api/admin/source',undefined,admin)).data,copyKey=randomUUID(); assert.equal((await call('/api/admin/copies',{registryId:source.definition.registryId,name:'資料編譯',introduction:''},admin,{'Idempotency-Key':copyKey})).status,202); const copied=await call('/api/admin/copies/'+copyKey+'/run',{},admin,{'If-Match':'"1"'}); assert.equal(copied.status,200,copied.data.error); const gameId=copied.data.gameId,enqueue='/api/fixture/data/enqueue',key=randomUUID(),value={gameId,draftRevision:'1',scope:'all'};
  assert.equal((await call(enqueue,value)).status,401); assert.equal((await call(enqueue,value,foreign)).status,404); assert.equal((await call(enqueue,{...value,gameId:'wolong-builtin'},admin)).status,403); assert.equal((await call(enqueue,{...value,scope:'chapter'},admin)).status,422); assert.equal((await call(enqueue,{...value,valid:true},admin)).status,422); const job=(await call(enqueue,value,admin,{'Idempotency-Key':key})).data; assert.equal(job.state,'queued'); assert.equal((await call(enqueue,value,admin,{'Idempotency-Key':key})).data.operationId,job.operationId); assert.equal((await call(enqueue,{...value,draftRevision:'2'},admin,{'Idempotency-Key':key})).status,404); assert.equal((await call('/api/games/'+gameId+'/draft/save',{metadata:{name:'後續草稿',introduction:''},resourceEdits:[]},admin,{'If-Match':'"1"'})).status,200); assert.equal((await call(enqueue,{...value,draftRevision:'2'},admin,{'Idempotency-Key':key})).status,409); assert.equal((await call('/api/admin/accounts',{account:'not_created'},admin,{'Idempotency-Key':key})).status,409); checks.push('real saved fullcopy/own principal, immutable revision, permanent job/key and crossnamespace/foreign/builtin/scope/self-valid gates');
  const before=(await call('/api/games',undefined,admin)).data.games[0].modifiedAt; let database=db(); database.exec("CREATE TRIGGER stop_data_stage AFTER UPDATE ON compile_jobs WHEN NEW.stage_cursor=1 AND OLD.stage_cursor=0 BEGIN UPDATE compile_jobs SET lease_until=0 WHERE job_id=NEW.job_id; END"); database.close();
  process.stderr.write('data-compile: actual common stage/controlled SQL expiry\n'); const stopped=await call('/api/fixture/data/run?id='+job.operationId,{},admin,{'If-Match':'"1"'}); assert.equal(stopped.status,409,stopped.data.error); assert.equal(stopped.data.error,'JOB_LEASE_EXPIRED'); const partial=(await call('/api/fixture/data/query?id='+job.operationId,undefined,admin)).data; assert.equal(partial.state,'running'); assert.equal(partial.stage,1); assert.equal(partial.checkpoint.length,1); database=db(); database.exec('DROP TRIGGER stop_data_stage'); const row=database.prepare('SELECT source_digest,dependency_digest,root_key FROM compile_jobs WHERE job_id=?').get(job.operationId); assert.ok(row.root_key.startsWith('private/'+gameId+'/')); database.close(); checks.push('actual shared compiler/fullprofile output checkpoint1, realSQL expiry before datawrite; no ready or runtime permission');
  await server.close(); server=null; process.stderr.write('data-compile: actual restart/rebuild/resume\n'); server=await startEditorBackend(configPath); const ready=await call('/api/fixture/data/run?id='+job.operationId,{},admin,{'If-Match':'"'+partial.rowRevision+'"'}); assert.equal(ready.status,200,ready.data.error); assert.equal(ready.data.state,'ready'); assert.equal(ready.data.stage,2); assert.equal(ready.data.attempt,2); assert.equal(ready.data.compilerRevision,'editor-local-0.6-server-data-1'); assert.equal(ready.data.checkpoint[0].digest,partial.checkpoint[0].digest); assert.equal((await call('/api/games',undefined,admin)).data.games[0].modifiedAt,before); checks.push('real restart loses transient plans/lease, SQL expired generation reclaimed; exact source reread/recompiled + existingactualR2 checkpoint verified before remaining data; modifiedAt unchanged');
  process.stderr.write('data-compile: actual outputs/full source parity\n'); const snapshot=await call('/api/fixture/data/source-data?game='+gameId+'&revision=1',undefined,admin); assert.equal(snapshot.status,200,snapshot.data.error); const common=compileGameSource(snapshot.data,sha); assert.equal(common.sourceDigest,row.source_digest); const expected={terrain_0:common.terrainBytes,geography_0:Uint8Array.from(common.geography),minimap_geography_0:Uint8Array.from(common.minimapGeography),road_mask_0:common.roadMask,road_cost_0:common.roadCost,road_offset_0:common.roadOffsetBytes,roads_0:jsonBytes(common.roadGraph)};
  snapshot.data.chapterOrder.forEach((chapterId,index)=>{expected['chapter_'+index+'_0']=jsonBytes({chapterId,definition:snapshot.data.chapters[chapterId]});});
  const outputs=ready.data.checkpoint.flatMap(r=>r.outputs); assert.equal(outputs.length,29); for(const output of outputs) { const actual=await call('/api/fixture/data/artifact?id='+job.operationId+'&asset='+output.assetId,undefined,admin,{},true); assert.equal(actual.status,200); assert.equal(actual.data.length,output.byteLength); assert.equal(sha(actual.data),output.sha256); if(expected[output.assetId])assert.equal(sha(expected[output.assetId]),output.sha256,output.assetId); else { const record=parse(actual.data); assert.equal(record.admission,'data-only'); assert.equal(record.sourceDigest,row.source_digest); assert.equal(record.dependencyDigest,row.dependency_digest); assert.equal(record.operationId,job.operationId); assert.equal(record.missing.length,4); assert.equal(Object.hasOwn(record,'valid'),false); } } checks.push('29actual privateR2 artifacts complete lengths/SHA: native/geo/helpers and all20chapterJSON equal unchanged common Node compiler on actual exact source; report/binding data-only withoutvalid/runtime/PNG');
  process.stderr.write('data-compile: ready revalidation/SQL corruption controls\n'); const reverified=await call('/api/fixture/data/run?id='+job.operationId,{},admin,{'If-Match':'"'+ready.data.rowRevision+'"'}); assert.equal(reverified.status,200,reverified.data.error); assert.deepEqual(reverified.data,ready.data); assert.equal((await call('/api/fixture/data/run?id='+job.operationId,{},admin,{'If-Match':'"1"'})).status,409);
  database=db(); const pristine=database.prepare('SELECT pipeline_digest,checkpoint_json FROM compile_jobs WHERE job_id=?').get(job.operationId),badCheckpoint=parse(pristine.checkpoint_json); badCheckpoint[0].digest='0'.repeat(64); database.prepare('UPDATE compile_jobs SET checkpoint_json=? WHERE job_id=?').run(JSON.stringify(badCheckpoint),job.operationId); database.close(); const corruptRecord=await call('/api/fixture/data/run?id='+job.operationId,{},admin,{'If-Match':'"'+ready.data.rowRevision+'"'}); assert.equal(corruptRecord.status,503,corruptRecord.data.error); assert.equal(corruptRecord.data.error,'DATA_CHECKPOINT_CORRUPT'); database=db(); database.prepare('UPDATE compile_jobs SET checkpoint_json=?,pipeline_digest=? WHERE job_id=?').run(pristine.checkpoint_json,'0'.repeat(64),job.operationId); database.close(); const changedPipeline=await call('/api/fixture/data/run?id='+job.operationId,{},admin,{'If-Match':'"'+ready.data.rowRevision+'"'}); assert.equal(changedPipeline.status,409,'actual ready pipeline SQL binding must be rechecked'); assert.equal(changedPipeline.data.error,'JOB_PIPELINE_CHANGED'); database=db(); database.prepare('UPDATE compile_jobs SET pipeline_digest=? WHERE job_id=?').run(pristine.pipeline_digest,job.operationId); database.close(); checks.push('ready recomputes and rereads outputs without row writes; stale CAS/checkpoint corruption/actual persisted pipeline tampering fail closed');
  process.stderr.write('data-compile: real same-size R2 corruption\n'); const artifactControl={operationId:job.operationId,assetId:'terrain_0',action:'damage'}; assert.equal((await call('/api/fixture/data/artifact-control',artifactControl,admin)).status,200); const damaged=await call('/api/fixture/data/run?id='+job.operationId,{},admin,{'If-Match':'"'+ready.data.rowRevision+'"'}); assert.equal(damaged.status,503,damaged.data.error); assert.equal(damaged.data.error,'BLOB_CORRUPT'); assert.deepEqual((await call('/api/fixture/data/query?id='+job.operationId,undefined,admin)).data,ready.data); assert.equal((await call('/api/fixture/data/artifact-control',{...artifactControl,action:'restore'},admin)).status,200); const terrain=await call('/api/fixture/data/artifact?id='+job.operationId+'&asset=terrain_0',undefined,admin,{},true); assert.equal(sha(terrain.data),sha(expected.terrain_0)); checks.push('actual own R2 byte flip with unchanged size fails ready revalidation503/fullSHA; no blind overwrite or SQL ready mutation, explicit fixture-only restoration preserves bytes');
  assert.equal((await call('/api/fixture/data/query?id='+job.operationId,undefined,foreign)).status,404); assert.equal((await call('/api/fixture/data/artifact?id='+job.operationId+'&asset=terrain_0',undefined,foreign)).status,404); assert.equal((await call('/api/games/'+gameId+'/compile',{},admin)).status,404); checks.push('private Job/output actor gates and public production compiler remains404');
  process.stderr.write('data-compile: controlled actual password epoch during output\n'); const epochKey=randomUUID(),epochJob=(await call(enqueue,{...value,draftRevision:'2'},admin,{'Idempotency-Key':epochKey})).data; assert.equal(epochJob.state,'queued'); assert.equal((await call('/api/fixture/data/arm',{},admin)).status,200); const pending=call('/api/fixture/data/run?id='+epochJob.operationId,{},admin,{'If-Match':'"1"'}).then(response=>({response}),error=>({error})); const deadline=Date.now()+240000; for(;;) { const gate=await call('/api/fixture/data/gate',undefined,admin); assert.equal(gate.status,200); if(gate.data.blocked)break; assert.ok(Date.now()<deadline,'actual output boundary must become blocked'); await new Promise(done=>setTimeout(done,250)); } const changed=await call('/api/auth/password',{oldPassword:password,newPassword:password+'X'},admin); assert.equal(changed.status,200,changed.data.error); const fresh={cookie:changed.cookie,csrf:changed.data.csrf}; assert.equal((await call('/api/fixture/data/release',{},fresh)).status,200); const finished=await pending; if(finished.error)throw finished.error; assert.equal(finished.response.status,401,finished.response.data.error); assert.equal((await call('/api/fixture/data/query?id='+epochJob.operationId,undefined,admin)).status,401); const revoked=await call('/api/fixture/data/query?id='+epochJob.operationId,undefined,fresh); assert.equal(revoked.status,409); assert.equal(revoked.data.error,'JOB_AUTH_REVOKED'); assert.equal((await call(enqueue,{...value,draftRevision:'2'},fresh,{'Idempotency-Key':epochKey})).status,409); database=db(); const abandoned=database.prepare('SELECT state,stage_cursor,checkpoint_json FROM compile_jobs WHERE job_id=?').get(epochJob.operationId); assert.equal(abandoned.state,'running'); assert.equal(abandoned.stage_cursor,0); assert.equal(abandoned.checkpoint_json,'[]'); assert.equal(database.prepare("SELECT COUNT(*) AS n FROM data_compile_objects WHERE operation_id=? AND state='verified'").get(epochJob.operationId).n,0); database.close(); assert.equal((await call('/api/games',undefined,fresh)).data.games[0].modifiedAt,before); checks.push('actual output intent/held real BlobStore boundary then actual password change revokes epoch: oldawait401/checkpoint0/noverifiedwrite; fresh session query/key cannot revive oldJob409, no game modifiedAt write');
  for(const[p,h]of Object.entries(sourceHashes))assert.equal(sha(readFileSync(p)),h,p); process.stdout.write(JSON.stringify({result:'PASS-REAL-FIXED-COPY-DATA-COMPILE-SCOPED',checks,calls,sourceHashes,outputs:outputs.length,limits:'Internal realWorker data-only execution; no public compiler/PNG/runtime/resourceconsumer closure/Q69/Trial/Release/physicalGC/cloudSLA/full goal completion.'},null,2)+'\n');
} finally { await server?.close(); }
