// Actual owned SQL/R2 and fixed saved source, one season per operation; no runtime grant.
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { randomBytes, randomUUID, createHash } from 'node:crypto';
import { request as httpsRequest } from 'node:https';
import { DatabaseSync } from 'node:sqlite';
import { startEditorBackend } from './start_editor_backend.mjs';
const dir='.dragon-analysis/editor-phase/backend-fallback-jobs-session-r1/',round=process.argv[2];assert.match(round??'',/^[1-9][0-9]{0,3}$/);
const sha=b=>createHash('sha256').update(b).digest('hex');function parse(b){try{return JSON.parse(b);}catch(cause){throw new Error('invalid owned fallback JSON',{cause});}}
const before=parse(readFileSync(dir+'before.json')),protectedHashes={...before.inputs};delete protectedHashes['server/copyimages.js'];assert.equal(Object.keys(protectedHashes).length,440);for(const[p,h]of Object.entries(protectedHashes))assert.equal(sha(readFileSync(p)),h,p);
const sourcePaths=['server/copyimages.js','server/fallbackjobs.js','tools/verify_editor_backend_fallback_jobs.mjs',dir+'fixture-worker.js','server/worker.js','server/jobs.js','server/rowpng.js','web/src/content/authoring/tilepixels.js'],sourceHashes=Object.fromEntries(sourcePaths.map(p=>[p,sha(readFileSync(p))]));
const own=mkdtempSync(join(tmpdir(),'dragon-fallback-jobs-')),origin='https://127.0.0.1:8787',initial=randomBytes(24).toString('hex'),password=randomBytes(24).toString('hex'),newPassword=randomBytes(24).toString('hex'),secret=randomBytes(32).toString('hex'),config=parse(readFileSync('server/wrangler.jsonc')),configPath=join(own,'wrangler.jsonc');config.main=resolve(dir+'fixture-worker.js');writeFileSync(configPath,JSON.stringify(config),{flag:'wx'});writeFileSync(join(own,'.dev.vars'),'EDITOR_DEFAULT_PASSWORD='+JSON.stringify(initial)+'\nEDITOR_REQUEST_KEY='+JSON.stringify(secret)+'\n',{flag:'wx',mode:0o600});
const calls=[],checks=[],artifacts=[],bindings=[];let server;
async function call(path,value,session,extra={},raw=false){const headers={Origin:origin,...extra};if(session){headers.Cookie=session.cookie;headers['X-CSRF-Token']=session.csrf;}if(value!==undefined){headers['Content-Type']='application/json';headers['Idempotency-Key']??=randomUUID();}const response=await new Promise((done,reject)=>{const req=httpsRequest(origin+path,{method:value===undefined?'GET':'POST',headers,agent:false,rejectUnauthorized:false},res=>{const parts=[];res.on('data',b=>parts.push(b));res.on('error',reject);res.on('end',()=>{try{const content=Buffer.concat(parts);done({status:res.statusCode,data:raw?content:parse(content),cookie:res.headers['set-cookie']?.[0]?.split(';')[0]});}catch(error){reject(error);}});});req.on('error',reject);req.end(value===undefined?undefined:JSON.stringify(value));});calls.push({path:path.split('?')[0],status:response.status});return response;}
async function login(account){const a=await call('/api/auth/login',{account,password:initial});assert.equal(a.status,200);const c=await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:a.cookie,csrf:a.data.csrf});assert.equal(c.status,200);return{cookie:c.cookie,csrf:c.data.csrf};}
function databases(path){const result=[];for(const e of readdirSync(path,{withFileTypes:true})){if(e.isDirectory())result.push(...databases(join(path,e.name)));else if(e.name.endsWith('.sqlite'))result.push(join(path,e.name));}return result;}
function db(){for(const p of databases(join(own,'.local/metadata'))){const database=new DatabaseSync(p);if(database.prepare("SELECT name FROM sqlite_master WHERE name='fallback_compile_objects'").get())return database;database.close();}throw new Error('owned fallback SQL missing');}
const prefix='/api/test/fallback/',match=r=>({'If-Match':'"'+r+'"'}),path=(action,id,season='spring')=>prefix+action+'?season='+season+(id?'&id='+id:''),ok=async(...args)=>{const r=await call(...args);assert.equal(r.status,200,r.data?.error);return r.data;};
try{
  server=await startEditorBackend(configPath,{stageSource:true});let admin=await login('tianyi');assert.equal((await call('/api/admin/accounts',{account:'fallback_author'},admin)).status,200);const author=await login('fallback_author');await ok('/api/admin/source/install',{},admin);const source=await ok('/api/admin/source',undefined,admin),copyKey=randomUUID();assert.equal((await call('/api/admin/copies',{registryId:source.definition.registryId,name:'整圖持久副本',introduction:''},admin,{'Idempotency-Key':copyKey})).status,202);const copied=await ok('/api/admin/copies/'+copyKey+'/run',{},admin,match('1')),gameId=copied.gameId,value={gameId,draftRevision:'1',scope:'all'},key=randomUUID();
  assert.equal((await call(path('enqueue'),value)).status,401);assert.equal((await call(path('enqueue'),value,author)).status,403);assert.equal((await call(path('enqueue'),{...value,gameId:'wolong-builtin'},admin)).status,403);assert.equal((await call(path('enqueue'),{...value,scope:'spring'},admin)).status,422);assert.equal((await call(path('enqueue'),{...value,season:'spring'},admin)).status,422);assert.equal((await call(path('enqueue',null,'unknown'),value,admin)).status,422);assert.equal((await call(path('enqueue'),value,admin,{Origin:'http://127.0.0.1:8787'})).status,403);
  const queued=await ok(path('enqueue'),value,admin,{'Idempotency-Key':key});assert.equal((await ok(path('enqueue'),value,admin,{'Idempotency-Key':key})).operationId,queued.operationId);assert.equal((await call(path('enqueue',null,'summer'),value,admin,{'Idempotency-Key':key})).status,409);assert.equal((await call('/api/admin/accounts',{account:'not_created'},admin,{'Idempotency-Key':key})).status,409);await ok('/api/games/'+gameId+'/draft/save',{metadata:{name:'整圖新修訂',introduction:''},resourceEdits:[]},admin,match('1'));assert.equal((await call(path('enqueue'),{...value,draftRevision:'2'},admin,{'Idempotency-Key':key})).status,409);const modified=(await ok('/api/games',undefined,admin)).games[0].modifiedAt;checks.push('actual administrator own exactsaved1 while current2, strict role/builtin/Origin/scope/season and permanent crossseason/crossnamespace key guards');
  await ok(prefix+'arm',{gameId,action:'expire'},admin);const expired=await call(path('run',queued.operationId),{},admin,match('1'));assert.equal(expired.status,409,expired.data.error);assert.equal(expired.data.error,'JOB_LEASE_EXPIRED');assert.deepEqual(await ok(prefix+'control',undefined,admin),{calls:130,done:true,passwordStatus:null});let database=db();const failed=database.prepare('SELECT state,stage_cursor,checkpoint_json FROM compile_jobs WHERE job_id=?').get(queued.operationId);assert.deepEqual({...failed},{state:'running',stage_cursor:0,checkpoint_json:'[]'});assert.equal(database.prepare('SELECT COUNT(*) AS n FROM fallback_compile_objects WHERE operation_id=?').get(queued.operationId).n,0);database.exec('CREATE TRIGGER stop_fallback_stage AFTER UPDATE ON compile_jobs WHEN NEW.stage_cursor=1 AND OLD.stage_cursor=0 BEGIN UPDATE compile_jobs SET lease_until=0 WHERE job_id=NEW.job_id; END');database.close();const partial=await ok(path('query',queued.operationId),undefined,admin);const stopped=await call(path('run',queued.operationId),{},admin,match(partial.rowRevision));assert.equal(stopped.status,409,stopped.data.error);assert.equal(stopped.data.error,'JOB_LEASE_EXPIRED');const stage1=await ok(path('query',queued.operationId),undefined,admin);assert.equal(stage1.stage,1);assert.equal(stage1.checkpoint.length,1);database=db();database.exec('DROP TRIGGER stop_fallback_stage');database.close();checks.push('native lease expiry at row128 stops generator before any intent/checkpoint; explicit reclaimed generation later completes boundreport then real SQL lease expiry fences PNG storage');
  await server.close();server=null;server=await startEditorBackend(configPath);const spring=await ok(path('run',queued.operationId),{},admin,match(stage1.rowRevision));assert.equal(spring.state,'ready');assert.equal(spring.attempt,3);assert.equal(spring.stage,2);assert.equal(spring.checkpoint[0].digest,stage1.checkpoint[0].digest);const jobs=[['spring',spring]];
  for(const season of['summer','autumn','winter']){const q=await ok(path('enqueue',null,season),value,admin);assert.equal((await call(path('query',q.operationId,'spring'),undefined,admin)).status,409);const r=await ok(path('run',q.operationId,season),{},admin,match('1'));assert.equal(r.state,'ready');jobs.push([season,r]);}checks.push('actual restart drops plans, new generation revalidates exactsource1 and reportR2; four separately configured single-season operations, no four fullrawmaps together or oldcompiler migration');
  const oldReceiptPath='.dragon-analysis/editor-phase/backend-fallback-rows-session-r1/static-receipt-r1.json';assert.equal(sha(readFileSync(oldReceiptPath)),'9913d9bc1c833b1c7ec85290108b7f635e64c7ce394daf6e052ca5e17c2e402c');const old=parse(readFileSync(oldReceiptPath)),oracle=parse(readFileSync('.dragon-analysis/editor-phase/backend-fallback-rows-session-r1/oracle-r1.stdout'));
  for(const[season,job]of jobs){const outputs=job.checkpoint.flatMap(c=>c.outputs);assert.equal(outputs.length,2);let binding;for(const o of outputs){const response=await call(path('artifact',job.operationId,season)+'&asset='+o.assetId,undefined,admin,{},true);assert.equal(response.status,200);assert.equal(response.data.length,o.byteLength);assert.equal(sha(response.data),o.sha256);const p=dir+'r'+round+'-'+o.assetId+(o.assetId==='fallback_report'?'-'+season:'')+'.bin';writeFileSync(p,response.data,{flag:'wx'});artifacts.push({path:p,...o});if(o.assetId==='fallback_report')binding=parse(response.data);else {const priorPath='.dragon-analysis/editor-phase/backend-fallback-rows-session-r1/r1-'+season+'-worker.png',prior=oracle.results.find(r=>r.path===priorPath);assert.equal(sha(readFileSync(priorPath)),old.historical[priorPath]);assert.equal(o.sha256,prior.byteSha);}}
    assert.equal(binding.draftRevision,'1');assert.equal(binding.season,season);assert.equal(binding.admission,'single-season-stage-outputs-only');assert.equal(Object.hasOwn(binding,'valid'),false);const d=binding.sourceReport.outputs[0],prior=oracle.results.find(r=>r.path.endsWith('-'+season+'-worker.png'));assert.equal(d.pixelSha256,prior.pixelSha);assert.equal(d.width,6144);assert.equal(d.height,4096);assert.equal(binding.sourceReport.rowPNGRevision,'png-rgba8-rows-1');bindings.push(binding);
  }
  assert.equal((await ok('/api/games',undefined,admin)).games[0].modifiedAt,modified);checks.push('eight actual privateR2 report/PNG assets, fullbyte length/SHA, four completePNG bytes exactly equal earlier independentPillow sealed outputs and fullpixel descriptors; no neworacle or runtimeclaim');
  assert.equal((await call(path('run',spring.operationId),{},admin,match('1'))).status,409);assert.deepEqual(await ok(path('run',spring.operationId),{},admin,match(spring.rowRevision)),spring);database=db();const saved=database.prepare('SELECT checkpoint_json,pipeline_digest FROM compile_jobs WHERE job_id=?').get(spring.operationId),bad=parse(saved.checkpoint_json);bad[0].digest='0'.repeat(64);database.prepare('UPDATE compile_jobs SET checkpoint_json=? WHERE job_id=?').run(JSON.stringify(bad),spring.operationId);database.close();const damage=await call(path('run',spring.operationId),{},admin,match(spring.rowRevision));assert.equal(damage.status,503,damage.data.error);assert.equal(damage.data.error,'FALLBACK_JOB_CHECKPOINT_CORRUPT');database=db();database.prepare('UPDATE compile_jobs SET checkpoint_json=?,pipeline_digest=? WHERE job_id=?').run(saved.checkpoint_json,'0'.repeat(64),spring.operationId);database.close();assert.equal((await call(path('run',spring.operationId),{},admin,match(spring.rowRevision))).data.error,'JOB_PIPELINE_CHANGED');database=db();database.prepare('UPDATE compile_jobs SET pipeline_digest=? WHERE job_id=?').run(saved.pipeline_digest,spring.operationId);database.close();checks.push('ready recompiled exactsource and allcheckpoints without rowwrites; staleCAS, actual persistedpipeline and checkpoint corruption reject');
  const control={operationId:spring.operationId,assetId:'fallback_spring',action:'damage'};await ok(prefix+'artifact-control',control,admin);const corrupt=await call(path('run',spring.operationId),{},admin,match(spring.rowRevision));assert.equal(corrupt.status,503,corrupt.data.error);assert.equal(corrupt.data.error,'BLOB_CORRUPT');assert.deepEqual(await ok(path('query',spring.operationId),undefined,admin),spring);await ok(prefix+'artifact-control',{...control,action:'restore'},admin);checks.push('actual nativeR2 same-length fullPNG damage rejects readyproof and leavesSQLready unchanged, no automaticoverwrite or cleanup');
  const epochKey=randomUUID(),epoch=await ok(path('enqueue'),{...value,draftRevision:'2'},admin,{'Idempotency-Key':epochKey});await ok(prefix+'arm',{gameId,action:'password',oldPassword:password,newPassword},admin);const interrupted=await call(path('run',epoch.operationId),{},admin,match('1'));assert.equal(interrupted.status,401,interrupted.data.error);const signed=await call('/api/auth/login',{account:'tianyi',password:newPassword});assert.equal(signed.status,200);admin={cookie:signed.cookie,csrf:signed.data.csrf};assert.deepEqual(await ok(prefix+'control',undefined,admin),{calls:130,done:true,passwordStatus:200});assert.equal((await call(path('query',epoch.operationId),undefined,admin)).data.error,'JOB_AUTH_REVOKED');assert.equal((await call(path('enqueue'),{...value,draftRevision:'2'},admin,{'Idempotency-Key':epochKey})).status,409);database=db();assert.equal(database.prepare('SELECT COUNT(*) AS n FROM fallback_compile_objects WHERE operation_id=?').get(epoch.operationId).n,0);assert.equal(database.prepare('SELECT checkpoint_json FROM compile_jobs WHERE job_id=?').get(epoch.operationId).checkpoint_json,'[]');database.close();assert.equal((await ok('/api/games',undefined,admin)).games[0].modifiedAt,modified);assert.equal((await call('/api/games/'+gameId+'/compile',{},admin)).status,404);checks.push('actual unchanged passwordhandler invoked at native row128 await revokes oldepoch401 before any outputintent; freshlogin cannot revive key/job; metadata unchanged and publicruntimecompile still404');
  for(const[p,h]of Object.entries({...protectedHashes,...sourceHashes}))assert.equal(sha(readFileSync(p)),h,p);process.stdout.write(JSON.stringify({result:'PASS-ACTUAL-SINGLE-SEASON-FALLBACK-JOBS',checks,calls,sourceHashes,artifacts,bindings,protectedInputs:440,limits:'Internal fixed configured seasons, realSQL/R2/lease/epoch only; four separate jobs, completePNGbytes reuse earlier independentPillow proof. No RootUI/API/runtime/Q69/Trial/release/GC/cloudSLA/fullgoal.'},null,2)+'\n');
}catch(error){writeFileSync(dir+'failure-state-r'+round+'.json',JSON.stringify({message:String(error.message).slice(0,600),code:error.code??null,checks,calls,sourceHashes},null,2)+'\n',{flag:'wx'});throw error;}finally{await server?.close();}
