// E-03 author UI/service gate. Only current readonly Web pack + owned output,
// temp file store/loopback/Chromium context. No DOS/profile/formal save access.
import assert from "node:assert/strict";
import { readFileSync, writeFileSync, mkdtempSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createRequire } from "node:module";
import { BUILTIN_RESOURCES } from "../web/src/content/builtinresources.generated.js";
import { startEditorServer } from "./editor_server.mjs";
import { compileGameSource } from "../web/src/content/authoring/trialcompile.js";
import { composeMapLayers } from "../web/src/content/authoring/maplayers.js";
import { componentCells } from "../web/src/editor/componenttools.js";
import { prepareTrialScenario } from "../web/src/content/authoring/trialruntime.js";
import { prepareScenario, readSavedAssembly, snapshotScenarioAssembly } from "../web/src/game/scenarioassembly.js";
const round = process.argv[2]; assert.match(round ?? "", /^[A-Za-z0-9-]{1,64}$/);
const output = join(".dragon-analysis/editor-phase", round); mkdirSync(output);
const sha = (b) => createHash("sha256").update(b).digest("hex");
function json(b) { try { return JSON.parse(b.toString()); } catch (cause) { throw new TypeError("invalid author verification JSON", { cause }); } }
const prefix = BUILTIN_RESOURCES.sourceURL.replace("game-source.json", ""), manifest = json(readFileSync("web/" + prefix + "manifest.json"));
const paths = ["web/src/content/builtinresources.generated.js", "web/" + prefix + "manifest.json", ...manifest.assets.map((a) => "web/" + a.url)];
const sourceHashes = Object.fromEntries(paths.map((p) => [p, sha(readFileSync(p))]));
const store = mkdtempSync(join(tmpdir(), "editor-component-")), server = await startEditorServer(0, store);
const origin = `http://127.0.0.1:${server.address().port}`, originalFetch = globalThis.fetch;
const errors = [], forbidden = [], dialogs = [], checks = []; let browser, stage = "copy";
async function call(path, body, code = 200) {
  process.stdout.write(`REQUEST ${path} / ${stage}\n`);
  const init = { headers: { connection: "close" } };
  if (body !== undefined) { init.method = "POST"; init.headers["content-type"] = "application/json"; init.body = JSON.stringify(body); }
  const response = await originalFetch(origin + path, init), data = await response.json(); assert.equal(response.status, code, JSON.stringify(data).slice(0, 300)); return data;
}
try {
  await call("/api/copy", { gameId: "component-test", ownerId: "owned-test", kind: "full" });
  const initial = await call("/api/draft?game=component-test"), initialCompiled = compileGameSource(initial, sha);
  assert.equal(initial.map.decorations.find((d) => d.x === 10 && d.y === 10).waterClass, undefined);
  assert.equal(initial.map.decorations.find((d) => d.x === 11 && d.y === 10).waterClass, undefined);
  const require = createRequire(import.meta.url), { chromium } = require(process.env.PLAYWRIGHT_MODULE || "C:/Users/fczll/AppData/Roaming/npm/node_modules/@playwright/cli/node_modules/playwright");
  browser = await chromium.launch({ headless: true }); const context = await browser.newContext({ viewport: { width: 1280, height: 900 } });
  await context.route("**/*", (route) => { const u = new URL(route.request().url());
    if (u.origin !== origin || /save\.dat|\/mmap_map\.bin$|^\/map_atlas_|\.dragon-analysis/i.test(u.pathname)) { forbidden.push(u.href); return route.abort(); } return route.continue(); });
  const page = await context.newPage(); page.setDefaultTimeout(90000);
  page.on("pageerror", (e) => errors.push(String(e)));
  page.on("console", (m) => { if (m.type() === "error" && !m.location().url?.endsWith("/favicon.ico")) errors.push(m.text()); });
  page.on("dialog", (d) => { dialogs.push(d.message()); return d.accept(); });
  await page.addInitScript(() => { window.__componentIDB = 0; indexedDB.open = () => { window.__componentIDB++; throw new Error("formal IDB forbidden in author fixture"); }; });
  await page.goto(origin + "/studio?game=component-test"); await page.waitForFunction(() => window.__studio != null);
  async function point(x, y) { await page.locator("#cv").scrollIntoViewIfNeeded(); const box = await page.locator("#cv").boundingBox();
    const cam = await page.evaluate(() => window.__studio.cam); const px = box.x + 1 + x * 16 + 8 - cam.x, py = box.y + 1 + y * 16 + 8 - cam.y;
    assert.ok(px > box.x && px < box.x + box.width && py > box.y && py < box.y + box.height);
    await page.mouse.click(px, py); }
  stage = "actual full-map all-instance rectangle parity against original footprint scan";
  const expectedGridIds = new Set(initial.map.decorations.filter(d => componentCells(initial, d).some(([x, y]) => x >= 2 && x <= 21 && y >= 2 && y <= 13)).map(d => d.id));
  const beforePick = await page.evaluate(() => ({ map: JSON.stringify(window.__studio.draft.map), dirty: window.__studio.dirty }));
  await page.click('[data-tool="select-area"]'); await page.locator("#cv").scrollIntoViewIfNeeded();
  const gridBox = await page.locator("#cv").boundingBox();
  await page.mouse.move(gridBox.x + 1 + 2 * 16 + 8, gridBox.y + 1 + 2 * 16 + 8); await page.mouse.down();
  await page.mouse.move(gridBox.x + 1 + 21 * 16 + 8, gridBox.y + 1 + 13 * 16 + 8);
  await page.evaluate(() => {
    const canvas = document.querySelector("#cv"), ctx = canvas.getContext("2d"), layers = document.querySelector("#layers");
    const clear = ctx.clearRect, replace = layers.replaceChildren; let inside = false;
    const stats = { clears: 0, layerRefreshes: 0 }; window.__rectangleDrawStats = stats;
    ctx.clearRect = function (...args) { if (inside) stats.clears++; return clear.apply(this, args); };
    layers.replaceChildren = function (...args) { if (inside) stats.layerRefreshes++; return replace.apply(this, args); };
    window.addEventListener("pointerup", () => { inside = true; }, { capture: true, once: true });
    window.addEventListener("pointerup", () => { inside = false; delete ctx.clearRect; delete layers.replaceChildren; }, { once: true });
  });
  await page.mouse.up();
  assert.deepEqual(await page.evaluate(() => window.__rectangleDrawStats), { clears: 1, layerRefreshes: 1 });
  assert.deepEqual(new Set(await page.evaluate(() => [...window.__studio.selectedIds])), expectedGridIds);
  assert.deepEqual(await page.evaluate(() => ({ map: JSON.stringify(window.__studio.draft.map), dirty: window.__studio.dirty })), beforePick);
  checks.push("current92586 decoration240cell rectangle matches original all-instance scan; one final canvas/layer refresh; map/dirty unchanged");
  stage = "actual rectangle select and captured multi-cell definition";
  await page.click('[data-tool="select-area"]'); await page.locator("#cv").scrollIntoViewIfNeeded();
  let box = await page.locator("#cv").boundingBox(); await page.mouse.move(box.x + 1 + 10 * 16 + 2, box.y + 1 + 10 * 16 + 2); await page.mouse.down();
  await page.mouse.move(box.x + 1 + 11 * 16 + 14, box.y + 1 + 10 * 16 + 14); await page.mouse.up();
  assert.equal(await page.evaluate(() => window.__studio.selectedIds.size), 2);
  await page.click("#materials summary");
  stage = "bounded visible material gallery / page and filter controls do not edit";
  const paletteBefore = await page.evaluate(() => ({ source: JSON.stringify(window.__studio.draft), dirty: window.__studio.dirty,
    selected: [...window.__studio.selectedIds], mini: document.querySelector("#mini").toDataURL() }));
  const pageOne = await page.locator("#material-gallery button").evaluateAll(buttons => buttons.map(b => b.dataset.materialId));
  assert.equal(pageOne.length, 24); assert.equal(await page.isDisabled("#material-prev"), true);
  await page.click("#material-next"); const pageTwo = await page.locator("#material-gallery button").evaluateAll(buttons => buttons.map(b => b.dataset.materialId));
  assert.equal(pageTwo.length, 24); assert.equal(pageTwo.some(id => pageOne.includes(id)), false);
  await page.focus("#material-prev"); await page.keyboard.press("Enter");
  assert.deepEqual(await page.locator("#material-gallery button").evaluateAll(buttons => buttons.map(b => b.dataset.materialId)), pageOne);
  await page.selectOption("#material-select", "tile-16");
  const tileButton = page.locator('#material-gallery button[data-material-id="tile-16"]');
  assert.equal(await tileButton.getAttribute("aria-pressed"), "true"); await tileButton.focus(); await page.keyboard.press("Enter");
  assert.equal(await page.locator("#material-select").inputValue(), "tile-16");
  assert.equal(await page.evaluate(() => document.activeElement.dataset.materialId), "tile-16");
  assert.equal(await page.evaluate(() => {
    const small = document.querySelector('#material-gallery [aria-pressed="true"] canvas').getContext("2d");
    const preview = document.querySelector("#material-preview").getContext("2d");
    return JSON.stringify([...small.getImageData(0,0,32,32).data]) === JSON.stringify([...preview.getImageData(0,0,32,32).data]);
  }), true);
  await page.fill("#material-search", "NO-MATCH-OWNED-PALETTE");
  assert.equal(await page.locator("#material-gallery button").count(), 0); assert.equal(await page.locator("#material-select option").count(), 0);
  assert.match(await page.locator("#material-page-info").textContent(), /沒有符合/);
  assert.equal(await page.locator("#material-preview").evaluate(c => c.draggable), false);
  assert.equal(await page.locator("#material-preview").evaluate(c => [...c.getContext("2d").getImageData(0,0,c.width,c.height).data].every(n => n === 0)), true);
  assert.equal(await page.locator("#material-info").textContent(), "沒有選取素材"); assert.equal(await page.isDisabled("#rename-material"), true);
  assert.equal(await page.isDisabled("#remove-material"), true); assert.equal(await page.isDisabled("#material-prev"), true); assert.equal(await page.isDisabled("#material-next"), true);
  await page.fill("#material-search", ""); await page.selectOption("#material-shape", "single");
  assert.equal(await page.locator("#material-select").evaluate(select => [...select.options].every(o => window.__studio.draft.componentDefinitions[o.value].footprint.length === 1)), true);
  await page.selectOption("#material-origin", "author"); assert.equal(await page.locator("#material-gallery button").count(), 0);
  await page.selectOption("#material-origin", "all"); await page.selectOption("#material-shape", "all");
  assert.deepEqual(await page.evaluate(() => ({ source: JSON.stringify(window.__studio.draft), dirty: window.__studio.dirty,
    selected: [...window.__studio.selectedIds], mini: document.querySelector("#mini").toDataURL() })), paletteBefore);
  await page.fill("#material-name", "雙格素材測試"); await page.click("#capture-material");
  const definition = await page.locator("#material-select").inputValue(); assert.match(definition, /^material-/);
  const def = await page.evaluate((id) => window.__studio.draft.componentDefinitions[id], definition); assert.equal(def.footprint.length, 2);
  assert.deepEqual(def.variants.original.tiles.map((p) => p[2]), [initialCompiled.terrainBytes[3850], initialCompiled.terrainBytes[3851]]);
  const capturedMap = await page.evaluate(() => window.__studio.draft.map); assert.deepEqual(capturedMap, initial.map);
  await page.selectOption("#material-origin", "author"); await page.selectOption("#material-shape", "multi");
  assert.equal(await page.locator("#material-gallery button").count(), 1); assert.equal(await page.locator("#material-select").inputValue(), definition);
  assert.equal(await page.locator('#material-gallery button[aria-pressed="true"]').getAttribute("data-material-id"), definition);
  await page.fill("#material-name", "<img src=x>"); await page.click("#rename-material");
  assert.match(await page.locator("#material-gallery").textContent(), /<img src=x>/); assert.equal(await page.locator("#material-gallery img").count(), 0);
  await page.fill("#material-name", "雙格素材測試"); await page.click("#rename-material");
  await page.selectOption("#material-origin", "all"); await page.selectOption("#material-shape", "all");
  assert.equal(await page.evaluate(() => {
    const grid = document.querySelector("#material-gallery").getBoundingClientRect();
    const selected = document.querySelector('#material-gallery button[aria-pressed="true"]').getBoundingClientRect();
    return selected.top >= grid.top && selected.bottom <= grid.bottom + 1;
  }), true);
  await page.screenshot({ path: join(output, "material-gallery.png") });
  checks.push("gallery24/page next+keyboard previous/dropdown+keyboard thumbnail sync/actual recipe pixels; no-match clears canvas, drag and author actions; source filters and single/multi only; author textContent not HTML; filters/selection do not edit source, dirty, selected map or mini");
  stage = "real material drag/drop and whole-footprint nonanchor selection";
  await page.selectOption("#material-water", "river");
  await page.locator("#material-preview").dragTo(page.locator("#cv"), { targetPosition: { x: 1 + 20 * 16 + 8, y: 1 + 20 * 16 + 8 } });
  const first = await page.evaluate(() => window.__studio.draft.map.decorations.at(-1)); assert.equal(first.definitionRef, definition); assert.equal(first.x, 20); assert.equal(first.y, 20);
  // Rectangle selects ALL overlapping instances, unlike inspect's top-only hit.
  const overlapBefore = await page.evaluate(() => ({ source: JSON.stringify(window.__studio.draft), mini: document.querySelector("#mini").toDataURL(), dirty: window.__studio.dirty, sel: window.__studio.sel, groupId: window.__studio.groupId }));
  const overlapIds = initial.map.decorations.filter(d => componentCells(initial, d).some(([x, y]) => x >= 20 && x <= 21 && y === 20)).map(d => d.id).concat(first.id);
  assert.equal(overlapIds.length, 3);
  await page.click('[data-tool="select-area"]'); await page.locator("#cv").scrollIntoViewIfNeeded();
  const overlapBox = await page.locator("#cv").boundingBox();
  await page.mouse.move(overlapBox.x + 1 + 20 * 16 + 2, overlapBox.y + 1 + 20 * 16 + 2); await page.mouse.down();
  await page.mouse.move(overlapBox.x + 1 + 21 * 16 + 14, overlapBox.y + 1 + 20 * 16 + 14); await page.mouse.up();
  assert.deepEqual(await page.evaluate(() => [...window.__studio.selectedIds]), overlapIds);
  await page.keyboard.down("Shift"); try {
    await page.mouse.move(overlapBox.x + 1 + 21 * 16 + 14, overlapBox.y + 1 + 20 * 16 + 14); await page.mouse.down();
    await page.mouse.move(overlapBox.x + 1 + 20 * 16 + 2, overlapBox.y + 1 + 20 * 16 + 2); await page.mouse.up();
  } finally { await page.keyboard.up("Shift"); }
  assert.deepEqual(await page.evaluate(() => [...window.__studio.selectedIds]), overlapIds);
  assert.deepEqual(await page.evaluate(() => ({ source: JSON.stringify(window.__studio.draft), mini: document.querySelector("#mini").toDataURL(), dirty: window.__studio.dirty, sel: window.__studio.sel, groupId: window.__studio.groupId })), overlapBefore);
  checks.push("rectangle includes both underlying atoms and author multi-cell in source order; reverse Shift rectangle retains union, source/mini/dirty/sel/group unchanged; inspect remains top only");
  await page.click('[data-tool="inspect"]'); await point(21, 20);
  assert.deepEqual(await page.evaluate(() => [...window.__studio.selectedIds]), [first.id]);
  await page.click('[data-tool="material"]'); await point(24, 20);
  const second = await page.evaluate(() => window.__studio.draft.map.decorations.at(-1)); assert.notEqual(first.id, second.id);
  await page.click('[data-tool="inspect"]'); await point(20, 20); await page.uncheck("#show-minimap");
  await page.keyboard.down("Shift"); try { await point(24, 20); } finally { await page.keyboard.up("Shift"); }
  assert.equal(await page.evaluate(() => window.__studio.selectedIds.size), 2);
  stage = "create/split/merge physical water groups via actual UI";
  const nativeBefore = await page.evaluate(() => { const m = window.__studio.draft.map; return { base:m.base, decorations:m.decorations, roads:m.roads, placements:m.placements }; });
  await page.click("#group-edit summary"); await page.fill("#group-name", "合成河段"); await page.uncheck("#new-group-visible"); await page.click("#create-group");
  let group = await page.evaluate(() => window.__studio.draft.map.waterGroups.find((g) => g.id === window.__studio.groupId));
  assert.deepEqual(new Set(group.memberIds), new Set([first.id, second.id])); assert.equal(group.showOnMinimap, false); const joinedId = group.id;
  await point(20, 20); await page.fill("#group-name", "拆出河段"); await page.click("#split-group");
  group = await page.evaluate(() => window.__studio.draft.map.waterGroups.find((g) => g.id === window.__studio.groupId)); assert.equal(group.showOnMinimap, false); assert.deepEqual(group.memberIds, [first.id]);
  await page.selectOption("#group-merge-list", [joinedId]); await page.fill("#group-name", "合併河段"); await page.check("#new-group-visible"); await page.click("#merge-groups");
  group = await page.evaluate(() => window.__studio.draft.map.waterGroups.find((g) => g.id === window.__studio.groupId));
  assert.equal(group.showOnMinimap, true); assert.deepEqual(new Set(group.memberIds), new Set([first.id, second.id])); const finalGroup = group.id;
  assert.deepEqual(await page.evaluate(() => { const m = window.__studio.draft.map; return { base:m.base, decorations:m.decorations, roads:m.roads, placements:m.placements }; }), nativeBefore);
  checks.push("actual rectangle/2-cell capture/atlas drag/whole nonanchor selection; physical group create/split inherited false/merge explicit true; native inputs unchanged by groups");
  stage = "author material management / physical instance split / batch translate";
  await page.click("#save"); await page.waitForFunction(() => !window.__studio.busy && document.getElementById("status").textContent.startsWith("已保存修訂"));
  const librarySaved = await call("/api/draft?game=component-test");
  const libraryBuild = await call("/api/compile", { gameId:"component-test", expectedRevision:librarySaved.localModel.draftRevision });
  const oldPackURI = `/api/trial-pack?game=component-test&revision=${librarySaved.localModel.draftRevision}&chapter=${encodeURIComponent(librarySaved.chapterOrder[0])}`;
  const oldPack = await call(oldPackURI), deleteUsed = structuredClone(librarySaved.componentDefinitions); delete deleteUsed[definition];
  await call("/api/save", { gameId:"component-test", expectedRevision:librarySaved.localModel.draftRevision, map:librarySaved.map, componentDefinitions:deleteUsed }, 400);
  assert.equal((await call("/api/draft?game=component-test")).localModel.draftRevision, librarySaved.localModel.draftRevision);
  await page.selectOption("#material-select", definition); await page.fill("#material-name", "雙格素材更名"); await page.click("#rename-material");
  assert.equal(await page.evaluate((id) => window.__studio.draft.componentDefinitions[id].name, definition), "雙格素材更名");
  assert.equal(await page.isDisabled("#remove-material"), true);
  await page.click("#save"); await page.waitForFunction(() => !window.__studio.busy && document.getElementById("status").textContent.startsWith("已保存修訂"));
  const renamedSaved = await call("/api/draft?game=component-test"); assert.equal(renamedSaved.componentDefinitions[definition].name, "雙格素材更名");
  const renamedBuild = await call("/api/compile", { gameId:"component-test", expectedRevision:renamedSaved.localModel.draftRevision });
  assert.notEqual(renamedBuild.identity.sourceDigest, libraryBuild.identity.sourceDigest);
  assert.deepEqual([...renamedBuild.assets,...renamedBuild.minimapAssets].map((a) => a.sha256), [...libraryBuild.assets,...libraryBuild.minimapAssets].map((a) => a.sha256));
  await page.selectOption("#group-list", finalGroup); await page.uncheck("#show-minimap");
  const beforeSplitMap = await page.evaluate(() => window.__studio.draft.map), miniBeforeSplit = await page.locator("#mini").evaluate((c) => c.toDataURL());
  await page.click('[data-tool="inspect"]'); await point(20, 20);
  await page.click("#instance-edit summary"); await page.click("#split-instances");
  const children = await page.evaluate(() => [...window.__studio.selectedIds]); assert.equal(children.length, 2);
  const afterSplitMap = await page.evaluate(() => window.__studio.draft.map);
  assert.ok(!afterSplitMap.decorations.some((d) => d.id === first.id));
  const composedBefore = composeMapLayers({ ...initial, map:beforeSplitMap, componentDefinitions:{ ...initial.componentDefinitions, [definition]:def } });
  const composedAfter = composeMapLayers({ ...initial, map:afterSplitMap, componentDefinitions:{ ...initial.componentDefinitions, [definition]:def } });
  for (const key of ["terrain", "geography", "minimapGeography"]) assert.deepEqual(composedBefore[key], composedAfter[key]);
  assert.equal(await page.locator("#mini").evaluate((c) => c.toDataURL()), miniBeforeSplit);
  const splitGroup = afterSplitMap.waterGroups.find((g) => g.id === finalGroup);
  assert.equal(splitGroup.showOnMinimap, false); assert.deepEqual(new Set(splitGroup.memberIds), new Set([...children, second.id]));
  await page.fill("#translate-x", "400"); await page.fill("#translate-y", "0"); await page.click("#translate-selection");
  assert.match(await page.locator("#status").textContent(), /超界/); assert.deepEqual(await page.evaluate(() => window.__studio.draft.map), afterSplitMap);
  await page.fill("#translate-x", "2"); await page.fill("#translate-y", "2"); await page.click("#translate-selection");
  assert.deepEqual(await page.evaluate((ids) => window.__studio.draft.map.decorations.filter((d) => ids.includes(d.id)).map((d) => [d.x,d.y]), children), [[22,22],[23,22]]);
  await page.fill("#translate-x", "-2"); await page.fill("#translate-y", "-2"); await page.click("#translate-selection");
  assert.deepEqual(await page.evaluate(() => window.__studio.draft.map), afterSplitMap);
  await page.click('[data-tool="del"]'); await point(24, 20);
  assert.equal(await page.isDisabled("#remove-material"), false);
  const beforeLibraryRemove = await page.evaluate(() => window.__studio.draft.map);
  await page.click("#remove-material"); assert.equal(await page.evaluate((id) => Object.hasOwn(window.__studio.draft.componentDefinitions,id),definition), false);
  assert.deepEqual(await page.evaluate(() => window.__studio.draft.map), beforeLibraryRemove);
  checks.push("author rename; used-definition server/UI refuse; whole 2-cell split preserves plane/full+mini geography and false group; batch bounds all-or-none and real translate/return; unused definition removal leaves map and old immutable build intact");
  stage = "actual decoration order controls / stable multiselect / layer guards";
  async function placeOrder(id, x, y, water = "") {
    await page.selectOption("#material-select", id); await page.selectOption("#material-water", water);
    await page.click('[data-tool="material"]'); await point(x, y);
    return page.evaluate(() => window.__studio.draft.map.decorations.at(-1).id);
  }
  const riverId = await placeOrder("tile-16", 30, 30, "river"), lakeId = await placeOrder("tile-32", 30, 30, "lake");
  const coverId = await placeOrder("tile-20", 30, 30);
  await page.click('[data-tool="inspect"]'); await point(30, 30);
  assert.deepEqual(await page.evaluate(() => [...window.__studio.selectedIds]), [coverId]);
  const atBoundary = await page.evaluate(() => ({ map:window.__studio.draft.map,dirty:window.__studio.dirty }));
  await page.click("#move-up"); assert.match(await page.locator("#status").textContent(), /邊界/);
  assert.deepEqual(await page.evaluate(() => ({ map:window.__studio.draft.map,dirty:window.__studio.dirty })), atBoundary);
  const miniOrderBefore = await page.locator("#mini").evaluate((c) => c.toDataURL());
  await page.click("#move-down");
  assert.deepEqual(await page.evaluate(() => [...window.__studio.selectedIds]), [coverId]);
  assert.equal(await page.evaluate(() => window.__studio.draft.map.decorations[window.__studio.sel].id), coverId);
  assert.equal(await page.locator("#mini").evaluate((c) => c.toDataURL()), miniOrderBefore);
  await point(30, 30); assert.deepEqual(await page.evaluate(() => [...window.__studio.selectedIds]), [lakeId]);
  await page.click("#move-down"); await page.click("#move-down");
  const reorderedMap = await page.evaluate(() => window.__studio.draft.map);
  assert.deepEqual(reorderedMap.decorations.filter((d) => [riverId,lakeId,coverId].includes(d.id)).map((d) => d.id), [lakeId,riverId,coverId]);
  for (const key of ["base","roads","placements","waterGroups"]) assert.deepEqual(reorderedMap[key], atBoundary.map[key]);
  const reorderBefore = composeMapLayers({ ...initial,map:atBoundary.map,componentDefinitions:renamedSaved.componentDefinitions });
  const reorderAfter = composeMapLayers({ ...initial,map:reorderedMap,componentDefinitions:renamedSaved.componentDefinitions });
  assert.deepEqual(reorderBefore.terrain,reorderAfter.terrain); assert.equal(reorderAfter.terrain[30*384+30],20);
  assert.equal(reorderBefore.geography[30*384+30],3); assert.equal(reorderAfter.geography[30*384+30],2);
  assert.equal(reorderAfter.minimapGeography[30*384+30],2);
  const pairA = await placeOrder("tile-16",32,30), pairB = await placeOrder("tile-16",33,30);
  await page.click('[data-tool="inspect"]'); await point(32,30);
  await page.keyboard.down("Shift"); try { await point(33,30); } finally { await page.keyboard.up("Shift"); }
  assert.deepEqual(await page.evaluate(() => [...window.__studio.selectedIds]), [pairA,pairB]);
  const beforePairOrder = await page.evaluate(() => window.__studio.draft.map);
  await page.click("#move-down");
  const afterPairOrder = await page.evaluate(() => window.__studio.draft.map), pairIds = [pairA,pairB];
  assert.deepEqual(afterPairOrder.decorations.filter((d) => pairIds.includes(d.id)).map((d) => d.id), pairIds);
  for (const id of pairIds) assert.equal(afterPairOrder.decorations.findIndex((d) => d.id === id),beforePairOrder.decorations.findIndex((d) => d.id === id)-1);
  await page.click("#move-up"); assert.deepEqual(await page.evaluate(() => window.__studio.draft.map),beforePairOrder);
  await page.locator("#layers button").filter({ hasText:"基本地圖" }).click();
  assert.equal(await page.isDisabled("#move-down"),true);
  assert.equal(await page.evaluate(() => window.moveSelected(-1)),false);
  assert.deepEqual(await page.evaluate(() => window.__studio.draft.map),beforePairOrder);
  await page.locator("#layers button").filter({ hasText:"裝飾" }).click(); await page.click("#lock");
  assert.equal(await page.isDisabled("#move-up"),true); assert.equal(await page.evaluate(() => window.moveSelected(-1)),false);
  assert.deepEqual(await page.evaluate(() => window.__studio.draft.map),beforePairOrder); await page.click("#lock");
  await page.keyboard.down("Shift"); try { await point(33,30); } finally { await page.keyboard.up("Shift"); }
  assert.deepEqual(await page.evaluate(() => [...window.__studio.selectedIds]),[pairA]);
  await page.click("#move-down");
  assert.equal(await page.evaluate(() => window.__studio.draft.map.decorations[window.__studio.sel].id),pairA);
  const finalOrderMap = await page.evaluate(() => window.__studio.draft.map);
  assert.equal(finalOrderMap.decorations.findIndex((d) => d.id === pairB),beforePairOrder.decorations.findIndex((d) => d.id === pairB));
  await page.click("#save"); await page.waitForFunction(() => !window.__studio.busy && document.getElementById("status").textContent.startsWith("已保存修訂"));
  await page.reload(); await page.waitForFunction(() => window.__studio != null);
  assert.deepEqual(await page.evaluate(() => window.__studio.draft.map),finalOrderMap);
  assert.equal(await page.isDisabled("#move-up"),true); assert.deepEqual(await call(oldPackURI),oldPack);
  checks.push("visible up/down; boundary no-op; stable selected IDs/multi-block order; other-layer+locked direct-call refuse; deselected stale index not moved; nonwater retains water and topwater changes geography only; saved order/old build retained");
  stage = "unknown underlay refusal and explicit base replacement";
  await page.click('[data-tool="del"]'); await point(10, 10);
  await page.click("#save"); await page.waitForFunction(() => !window.__studio.busy && document.getElementById("status").textContent.startsWith("已保存修訂"));
  const missing = await call("/api/draft?game=component-test"); assert.equal(missing.map.base.terrainRef[3850], null);
  assert.throws(() => compileGameSource(missing, sha), /UNKNOWN_UNDERLAY/); await call("/api/compile", { gameId:"component-test" }, 400);
  await page.locator("#layers button").filter({ hasText:"基本地圖" }).click(); await page.click("#lock"); await page.click('[data-tool="inspect"]'); await point(10, 10);
  await page.click("#base-edit summary"); await page.fill("#base-tile", "16"); await page.selectOption("#base-geography", "0"); await page.click("#fill-base");
  assert.equal(await page.evaluate(() => window.__studio.draft.map.base.terrainRef[3850]), 16); assert.ok(dialogs.some((t) => t.includes("明確補繪1格底層")));
  await page.click("#save"); await page.waitForFunction(() => !window.__studio.busy && document.getElementById("status").textContent.startsWith("已保存修訂"));
  await page.reload(); await page.waitForFunction(() => window.__studio != null);
  assert.equal(await page.evaluate((id) => Object.hasOwn(window.__studio.draft.componentDefinitions,id), definition), false);
  await page.selectOption("#group-list", finalGroup); assert.equal(await page.isChecked("#show-minimap"), false);
  assert.deepEqual(await call(oldPackURI), oldPack);
  await page.click("#compile"); await page.waitForFunction(() => !window.__studio.busy && document.querySelectorAll("#compiled-minis img").length === 2);
  await page.waitForFunction(() => [...document.querySelectorAll("#compiled-minis img")].every((i) => i.complete && i.naturalWidth > 0));
  await page.screenshot({ path: join(output,"component-workspace.png") });
  const saved = await call("/api/draft?game=component-test"), edited = compileGameSource(saved, sha);
  assert.equal(edited.terrainBytes[3850], 16); assert.deepEqual(edited.roadGraph, initialCompiled.roadGraph); assert.deepEqual(edited.roadCost, initialCompiled.roadCost); assert.deepEqual(edited.roadOffsetBytes, initialCompiled.roadOffsetBytes);
  await call("/api/save", { gameId:"component-test", expectedRevision:"1", map:saved.map, componentDefinitions:saved.componentDefinitions }, 400);
  const badDefs = structuredClone(saved.componentDefinitions); badDefs["tile-0"].ruleRecipeRef = "guessed-recipe";
  await call("/api/save", { gameId:"component-test", expectedRevision:saved.localModel.draftRevision, map:saved.map, componentDefinitions:badDefs }, 400);
  const invalidNew = { ...saved.componentDefinitions, bad: { ...def, id:"bad", ruleRecipeRef:"guessed-recipe" } };
  await call("/api/save", { gameId:"component-test", expectedRevision:saved.localModel.draftRevision, componentDefinitions:invalidNew }, 400);
  assert.equal((await call("/api/draft?game=component-test")).localModel.draftRevision, saved.localModel.draftRevision);
  checks.push("unknown preserved and strict compile refuses; explicit confirmed 1-cell fill/other cells retained; split children+author removal+false group survive save/reopen; both PNGs and original old build immutable; stale/raw overwrite/unused bad recipe rejects");
  stage = "20 edited-source native fresh and production JSON restore";
  for (const chapter of saved.chapterOrder) {
    process.stdout.write(`PREPARE ${chapter}\n`);
    const pack = await call(`/api/trial-pack?game=component-test&revision=${saved.localModel.draftRevision}&chapter=${encodeURIComponent(chapter)}`);
    const allowed = new Set(pack.manifest.assets.map((a) => a.url)); globalThis.fetch = (url) => { assert.ok(allowed.has(String(url))); return originalFetch(origin + url, { headers: { connection:"close" } }); };
    try { const ready = await prepareTrialScenario(pack); assert.equal(ready.scenario.cities.length, 192);
      const jsonSaved = json(Buffer.from(JSON.stringify({ state:ready.scenario, webMeta:snapshotScenarioAssembly({ scenario:ready.scenario, scenarioIdx:0, content:ready.content, world:ready.world }) })));
      const restored = await prepareScenario({ raw:jsonSaved.state, idx:0, mode:"restore", content:ready.content, world:ready.world, ...readSavedAssembly(jsonSaved) });
      assert.deepEqual(snapshotScenarioAssembly({ scenario:restored.scenario, scenarioIdx:0, content:ready.content, world:ready.world }), jsonSaved.webMeta);
    } finally { globalThis.fetch = originalFetch; }
  }
  assert.equal(await page.evaluate(() => window.__componentIDB), 0); assert.deepEqual(errors, []); assert.deepEqual(forbidden, []);
  await page.setViewportSize({ width:1024, height:768 }); await page.waitForFunction(() => document.querySelector("aside").getBoundingClientRect().right <= innerWidth);
  for (const [p, hash] of Object.entries(sourceHashes)) assert.equal(sha(readFileSync(p)), hash, p);
  const tools = ["tools/verify_editor_component_browser.mjs", "tools/editor_server.mjs", "tools/editor_builtin_source.mjs", "tools/minimap_png.mjs", "web/src/editor/componenttools.js", "web/src/editor/studio.js", "web/editor-studio.html", "web/src/content/authoring/maplayers.js", "web/src/content/authoring/mapcompile.js", "web/src/content/authoring/trialcompile.js"];
  writeFileSync(join(output,"receipt.json"), JSON.stringify({ result:"PASS-SCOPED", currentRevision:BUILTIN_RESOURCES.world.revision, sourceHashes,
    toolHashes:Object.fromEntries(tools.map((p) => [p,sha(readFileSync(p))])), chapters:20, checks, errors, forbidden, dialogs, artifactPaths:["component-workspace.png"],
    coverageLimits:"Local fixed-domain author workflow only. No accounts/durable backend/fullApptrial/publish/arbitrary topology or native formula certification; screenshot not new style approval." },null,2) + "\n");
  process.stdout.write("PASS scoped component workspace / material management+instance split+batch+groups+base /20 fresh+JSON / current39 unchanged\n");
} catch (error) { writeFileSync(join(output,"failure.json"),JSON.stringify({ stage,error:String(error),stack:error.stack,errors,forbidden,checks },null,2)+"\n"); throw error;
} finally { globalThis.fetch = originalFetch; await browser?.close(); await new Promise((r) => server.close(r)); }
