// Actual default Root only, owned persistent stores and engineering sessions.
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { randomBytes, randomUUID, createHash } from 'node:crypto';
import { request as httpsRequest } from 'node:https';
import { DatabaseSync } from 'node:sqlite';
import { startEditorBackend } from './start_editor_backend.mjs';
const own = mkdtempSync(join(tmpdir(), 'dragon-stage-api-')), origin = 'https://127.0.0.1:8787', initial = randomBytes(24).toString('hex'), password = randomBytes(24).toString('hex'), secret = randomBytes(32).toString('hex'), sha = b => createHash('sha256').update(b).digest('hex');
function parse(b) { try { return JSON.parse(b); } catch (cause) { throw new Error('invalid owned stage JSON', { cause }); } }
const configuration = parse(readFileSync('server/wrangler.jsonc')), configPath = join(own, 'wrangler.jsonc'); configuration.main = resolve('server/worker.js'); writeFileSync(configPath, JSON.stringify(configuration)); writeFileSync(join(own, '.dev.vars'), 'EDITOR_DEFAULT_PASSWORD=' + JSON.stringify(initial) + '\nEDITOR_REQUEST_KEY=' + JSON.stringify(secret) + '\n', { flag: 'wx', mode: 0o600 });
const sources = ['server/worker.js','server/stageapi.js','tools/verify_editor_backend_stage_api.mjs'], sourceHashes = Object.fromEntries(sources.map(p => [p,sha(readFileSync(p))])), checks = [], calls = []; let server;
async function call(path, body, session, extra = {}, raw = false) { const headers = { Origin: origin, ...extra }; if (session) { headers.Cookie = session.cookie; if (!Object.hasOwn(extra, 'X-CSRF-Token')) headers['X-CSRF-Token'] = session.csrf; } if (body !== undefined) { headers['Content-Type'] = 'application/json'; headers['Idempotency-Key'] ??= randomUUID(); } const response = await new Promise((done,reject) => { const request = httpsRequest(origin + path, { method: body === undefined ? 'GET' : 'POST', headers, rejectUnauthorized: false }, result => { const parts=[]; result.on('data', b => parts.push(b)); result.on('error',reject); result.on('end',()=>{try{const bytes=Buffer.concat(parts);done({status:result.statusCode,data:raw?bytes:parse(bytes),headers:result.headers,cookie:result.headers['set-cookie']?.[0]?.split(';')[0]});}catch(error){reject(error);}}); }); request.on('error',reject); request.end(body===undefined?undefined:JSON.stringify(body)); }); calls.push({path,status:response.status}); return response; }
async function login(account) { const a=await call('/api/auth/login',{account,password:initial}); assert.equal(a.status,200);const b=await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:a.cookie,csrf:a.data.csrf});assert.equal(b.status,200);return{cookie:b.cookie,csrf:b.data.csrf}; }
function files(path) { return readdirSync(path,{withFileTypes:true}).flatMap(entry=>{ if(entry.isDirectory())return files(join(path,entry.name)); if(entry.name.endsWith('.sqlite'))return [join(path,entry.name)]; return []; }); }
function database() { for(const path of files(join(own,'.local/metadata'))){const db=new DatabaseSync(path);if(db.prepare("SELECT name FROM sqlite_master WHERE name='compile_jobs'").get())return db;db.close();}throw new Error('owned stage SQL absent'); }
try {
  process.stderr.write('stage-api: actual Root copy\n'); server=await startEditorBackend(configPath,{stageSource:true});const admin=await login('tianyi');assert.equal((await call('/api/admin/accounts',{account:'stage_author'},admin)).status,200);const author=await login('stage_author');assert.equal((await call('/api/admin/source/install',{},admin)).status,200);const source=(await call('/api/admin/source',undefined,admin)).data,key=randomUUID();assert.equal((await call('/api/admin/copies',{registryId:source.definition.registryId,name:'階段入口',introduction:''},admin,{'Idempotency-Key':key})).status,202);const copied=await call('/api/admin/copies/'+key+'/run',{},admin,{'If-Match':'"1"'});assert.equal(copied.status,200,copied.data.error);const gameId=copied.data.gameId,base='/api/games/'+gameId+'/stage-jobs/',value={draftRevision:'1',scope:'all'},enqueueKey=randomUUID();
  assert.equal((await call(base+'data',value)).status,401);assert.equal((await call(base+'data',value,author)).status,404);assert.equal((await call(base+'images',value,author)).status,403);assert.equal((await call(base+'data',value,admin,{'Origin':'https://127.0.0.1:8788'})).status,403);assert.equal((await call(base+'data',value,admin,{'X-CSRF-Token':'wrong'})).status,403);assert.equal((await call(base+'data',{...value,valid:true},admin)).status,422);assert.equal((await call('/api/games/wolong-builtin/stage-jobs/data',value,admin)).status,403);const queued=await call(base+'data',value,admin,{'Idempotency-Key':enqueueKey});assert.equal(queued.status,202,queued.data.error);assert.equal(queued.data.admission,'stage-only');const data=queued.data.job,dataPath=base+'data/'+data.operationId;assert.equal((await call(base+'data',value,admin,{'Idempotency-Key':enqueueKey})).data.job.operationId,data.operationId);assert.equal((await call('/api/admin/accounts',{account:'not_created'},admin,{'Idempotency-Key':enqueueKey})).status,409);assert.equal((await call(dataPath+'/run',{},admin)).status,428);assert.equal((await call(dataPath+'/run',{},admin,{'If-Match':'"99"'})).status,412);assert.equal((await call(dataPath+'/artifacts/terrain_0',undefined,admin)).status,409);checks.push('actual Root owner/auth/Origin-port/CSRF/builtin/self-valid gates, permanent enqueue namespace, conditional428/412 and no queued artifact grant');
  const before=(await call('/api/games',undefined,admin)).data.games[0].modifiedAt,dataRunKey=randomUUID();process.stderr.write('stage-api: actual data execution\n');const dataReady=await call(dataPath+'/run',{},admin,{'If-Match':'"1"','Idempotency-Key':dataRunKey});assert.equal(dataReady.status,200,dataReady.data.error);assert.equal(dataReady.data.job.state,'ready');assert.equal(dataReady.data.job.checkpoint.flatMap(stage=>stage.outputs).length,29);assert.equal((await call('/api/admin/accounts',{account:'also_not_created'},admin,{'Idempotency-Key':dataRunKey})).status,409);assert.equal((await call(dataPath+'/run',{},admin,{'If-Match':'"2"','Idempotency-Key':dataRunKey})).status,409);assert.equal((await call(base+'images/'+data.operationId,undefined,admin)).status,409);assert.equal((await call(dataPath+'?valid=true',undefined,admin)).status,422);checks.push('actual default Root common data29 outputs, runkey request binding notreceipt, purpose/pipeline and query-field guards');
  let dataDb=database();const dataRow=dataDb.prepare('SELECT pipeline_digest FROM compile_jobs WHERE job_id=?').get(data.operationId);dataDb.prepare('UPDATE compile_jobs SET pipeline_digest=? WHERE job_id=?').run('0'.repeat(64),data.operationId);dataDb.close();const reenqueue=await call(base+'data',value,admin,{'Idempotency-Key':enqueueKey});assert.equal(reenqueue.status,409,'duplicate enqueue must validate persisted pipeline: '+reenqueue.status);dataDb=database();dataDb.prepare('UPDATE compile_jobs SET pipeline_digest=? WHERE job_id=?').run(dataRow.pipeline_digest,data.operationId);dataDb.close();checks.push('same permanent enqueue key still checks actual persisted SQL pipeline, no stale summary authorization');
  const rawData=await call(dataPath+'/artifacts/terrain_0',undefined,admin,{},true);assert.equal(rawData.status,200);const terrain=dataReady.data.job.checkpoint.flatMap(stage=>stage.outputs).find(output=>output.assetId==='terrain_0');assert.equal(rawData.data.length,terrain.byteLength);assert.equal(sha(rawData.data),terrain.sha256);assert.equal(rawData.headers['x-content-sha256'],terrain.sha256);assert.equal(rawData.headers['cache-control'],'no-store');assert.equal(rawData.headers['x-content-type-options'],'nosniff');assert.equal((await call(dataPath,undefined,author)).status,404);assert.equal((await call(dataPath+'/artifacts/terrain_0',undefined,author)).status,404);checks.push('authenticated artifact exact descriptor/full-source rebuild/all-checkpoint and actualR2 proof, bytes/SHA/no-store/nosniff, foreign denied');
  process.stderr.write('stage-api: actual image execution\n');const imageQueued=await call(base+'images',value,admin);assert.equal(imageQueued.status,202);const image=imageQueued.data.job,imagePath=base+'images/'+image.operationId,imageRunKey=randomUUID();const imageReady=await call(imagePath+'/run',{},admin,{'If-Match':'"1"','Idempotency-Key':imageRunKey});assert.equal(imageReady.status,200,imageReady.data.error);assert.equal(imageReady.data.job.checkpoint.flatMap(stage=>stage.outputs).length,7);const rawImage=await call(imagePath+'/artifacts/minimap_base',undefined,admin,{},true),mini=imageReady.data.job.checkpoint.flatMap(stage=>stage.outputs).find(output=>output.assetId==='minimap_base');assert.equal(rawImage.status,200);assert.equal(sha(rawImage.data),mini.sha256);assert.equal(rawImage.data.length,mini.byteLength);assert.equal((await call(imagePath,undefined,author)).status,403);checks.push('actual Root real catalog/profile/image planner/imageJob sevenoutputs and privatePNG proof; no image privilege impersonation');
  let db=database();const persisted=db.prepare('SELECT * FROM compile_jobs WHERE job_id=?').get(image.operationId),bad=JSON.parse(persisted.checkpoint_json);bad[0].digest='0'.repeat(64);db.prepare('UPDATE compile_jobs SET checkpoint_json=? WHERE job_id=?').run(JSON.stringify(bad),image.operationId);db.close();const rejected=await call(imagePath+'/artifacts/minimap_base',undefined,admin);assert.equal(rejected.status,503,rejected.data.error);assert.equal(rejected.data.error,'IMAGE_JOB_CHECKPOINT_CORRUPT');db=database();db.prepare('UPDATE compile_jobs SET checkpoint_json=? WHERE job_id=?').run(persisted.checkpoint_json,image.operationId);db.prepare('UPDATE compile_jobs SET pipeline_digest=? WHERE job_id=?').run('0'.repeat(64),image.operationId);db.close();assert.equal((await call(imagePath,undefined,admin)).status,409);db=database();db.prepare('UPDATE compile_jobs SET pipeline_digest=? WHERE job_id=?').run(persisted.pipeline_digest,image.operationId);db.close();checks.push('actual SQL ready-checkpoint corruption cannot serve otherwise healthy artifact; wrong persistedpipeline query409; explicit owned restore only');
  await server.close();server=null;server=await startEditorBackend(configPath);const replay=await call(imagePath+'/run',{},admin,{'If-Match':'"1"','Idempotency-Key':imageRunKey});assert.equal(replay.status,200,replay.data.error);assert.deepEqual(replay.data,imageReady.data);assert.equal((await call('/api/games',undefined,admin)).data.games[0].modifiedAt,before);assert.equal((await call('/api/games/'+gameId+'/compile',{},admin)).status,404);assert.equal((await call('/api/games/'+gameId+'/trial',{},admin)).status,404);checks.push('actual restart recovers SQL command binding/job and revalidates exact source/outputs before terminal facts; modifiedAt unchanged, fullcompile/Trial404');
  for(const[p,h]of Object.entries(sourceHashes))assert.equal(sha(readFileSync(p)),h,p);process.stdout.write(JSON.stringify({result:'PASS-REAL-ROOT-STAGE-API-SCOPED',checks,calls,sourceHashes,artifacts:{data:29,images:7},limits:'Authenticated stage artifacts only; repeated full source verification has no cloudSLA. No full dependency/runtimeQ69/Valid/Trial/Release/public compile or goal completion.'},null,2)+'\n');
} finally { await server?.close(); }
