import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import {createHash} from 'node:crypto';import {HUD} from '../web/src/ui/hud.js';import {createPortraitCanvas} from '../web/src/ui/portraitcanvas.js';
const d='.dragon-analysis/editor-phase/hud-faction-card-ports-session-r1/',round=process.argv[2];assert.match(round??'',/^[1-9][0-9]{0,2}$/);const checks=[],hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex'),sourcePaths=['web/src/ui/hud.js','web/src/ui/portraitcanvas.js','web/src/core/assets.js','web/src/game/talk.js','web/index.html','tools/verify_hud_faction_card_ports.mjs'];const sourceHashes=Object.fromEntries(sourcePaths.map(p=>[p,hash(p)]));
class Element{constructor(tag='div'){this.tagName=tag;this.style={};this.dataset={};this.children=[];this.parentNode=null;this.width=0;this.height=0;this.context={imageSmoothingEnabled:true,drawImage:(...args)=>{this.drawn=args;}};}setAttribute(k,v){this[k]=v;}addEventListener(){}append(...children){for(const c of children){this.children.push(c);if(c instanceof Element)c.parentNode=this;}}replaceChildren(...children){for(const c of this.children)if(c instanceof Element)c.parentNode=null;this.children=[];this.append(...children);if(this.afterReplace)this.afterReplace();}remove(){if(this.parentNode){this.parentNode.children=this.parentNode.children.filter(c=>c!==this);this.parentNode=null;}}getContext(){return this.context;}}
const oldDoc=globalThis.document,oldImage=globalThis.Image;let currentDoc;globalThis.document={createElement:tag=>new Element(tag),querySelector:s=>currentDoc?.[s]??null};globalThis.Image=class{constructor(){throw new Error('public portrait transport forbidden');}};
function fixture(overrides={}){currentDoc=Object.fromEntries(['#tip','#card','#tabs','#seasons','#legend'].map(k=>[k,new Element()]));const faction={idx:0,capital:3,monarch:'君主',n_cities:2,n_generals:4,gold:8,food:9,troops:10},monarch={portrait:0},scenario={name:'唯讀夾具',factions:[faction],player_faction:0,monarchOf:()=>monarch,city:i=>({name:'城'+i})};let revoked=false,reads=0,quotes=0,disposed=0;const handles=[],ports={assertCurrent:()=>{if(revoked)throw new Error('LOCAL_REVOKED');},loadPortrait:async i=>{reads++;const handle={image:{width:128,height:128,index:i},width:128,height:128,dispose(){disposed++;}};handles.push(handle);return handle;},loadQuote:async()=>{quotes++;return '讀取後提示';},...overrides};const app={scenario,data:{scenarios:[]},setSeason(){},view:{draw(){}}},hud=new HUD(app,ports);return{hud,app,ports,scenario,monarch,faction,card:hud.card,handles,get reads(){return reads;},get quotes(){return quotes;},get disposed(){return disposed;},revoke(){revoked=true;}};}
function defer(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};}async function test(name,fn){await fn();checks.push(name);}
try{
await test('Actual HUD constructor and existing faction-card DOM with decoded private canvas, same128 border/text, no publicImage',async()=>{const x=fixture();await x.hud.showFactionCard(x.faction);assert.equal(x.reads,1);assert.equal(x.quotes,1);assert.equal(x.card.style.display,'flex');assert.equal(x.card.children[0].tagName,'canvas');assert.equal(x.card.children[0].width,128);assert.equal(x.card.children[0].style.border,'1px solid #6b5335');assert.equal(x.card.children[0].drawn[0],x.handles[0].image);x.hud.disposeFactionCardImageResources();assert.equal(x.disposed,1);});
await test('Explicit samefaction new invocation freshportrait/quote and releases prior only; null clearsowncard',async()=>{const x=fixture();await x.hud.showFactionCard(x.faction);await x.hud.showFactionCard(x.faction);assert.equal(x.reads,2);assert.equal(x.quotes,2);assert.equal(x.disposed,1);await x.hud.showFactionCard(null);assert.equal(x.disposed,2);assert.equal(x.card.style.display,'none');assert.equal(x.card.children.filter(v=>v instanceof Element&&v.tagName==='canvas').length,0);});
await test('Installed functions captured; replacing port properties cannot redirect old instance',async()=>{const x=fixture();x.ports.loadPortrait=()=>{throw new Error('replacement');};x.ports.loadQuote=()=>{throw new Error('replacement');};x.ports.assertCurrent=()=>{throw new Error('replacement');};await x.hud.showFactionCard(x.faction);assert.equal(x.reads,1);x.hud.disposeFactionCardImageResources();});
await test('Foreign/unknownportrait255/-1/150/string/NaN refuse before any image or quote I/O',async()=>{for(const value of [255,-1,150,'0',NaN]){const x=fixture();x.monarch.portrait=value;await assert.rejects(x.hud.showFactionCard(x.faction),/HUD_PORTRAIT_ROLE/);assert.equal(x.reads,0);assert.equal(x.quotes,0);}});
await test('Missing/null ports default constructor still has no privateownedentry; malformed functions refused',async()=>{const x=fixture();const normal=new HUD(x.app);assert.equal(normal._factionCardPorts,null);normal.disposeFactionCardImageResources();assert.equal(normal._factionCardClosed,false);assert.throws(()=>new HUD(x.app,{}),/HUD_FACTION_CARD_PORTS/);});
await test('Local revoked entry before first I/O; existing fields not rewritten',async()=>{const x=fixture(),before=JSON.stringify(x.faction);x.revoke();await assert.rejects(x.hud.showFactionCard(x.faction),/LOCAL_REVOKED/);assert.equal(x.reads,0);assert.equal(JSON.stringify(x.faction),before);assert.equal(x.card.style.display,'none');});
await test('Late image after null consumes and disposes once, neverquote or DOMinstall',async()=>{const pending=defer();let disposed=0;const x=fixture({loadPortrait:()=>pending.promise});const task=x.hud.showFactionCard(x.faction);await x.hud.showFactionCard(null);pending.resolve({image:{width:128,height:128},width:128,height:128,dispose(){disposed++;}});await assert.rejects(task,/HUD_FACTION_CARD_STALE/);assert.equal(disposed,1);assert.equal(x.quotes,0);assert.equal(x.card.style.display,'none');});
await test('Late quote after explicit permanent localclose releases held handle once',async()=>{const pending=defer();const x=fixture({loadQuote:()=>pending.promise});const task=x.hud.showFactionCard(x.faction);await Promise.resolve();x.hud.disposeFactionCardImageResources();pending.resolve('晚提示');await assert.rejects(task,/HUD_FACTION_CARD_CLOSED/);assert.equal(x.disposed,1);assert.equal(x.card.style.display,'none');assert.equal(x.hud._factionCardEntry,null);});
await test('Scenario/card/monarch/portrait/factioncapital/index changes while quote pending all refuse independently',async()=>{for(const mutate of [x=>x.app.scenario={...x.scenario},x=>x.hud.card=new Element(),x=>x.scenario.monarchOf=()=>({portrait:0}),x=>x.monarch.portrait=1,x=>x.faction.capital=4,x=>x.faction.idx=2]){const pending=defer();const x=fixture({loadQuote:()=>pending.promise});const task=x.hud.showFactionCard(x.faction);await Promise.resolve();mutate(x);pending.resolve('晚提示');await assert.rejects(task,/HUD_FACTION_CARD_STALE/);assert.equal(x.disposed,1);assert.ok(!x.card.children.some(v=>v?.tagName==='canvas'));}});
await test('New request does not get erased by old quote resolving late',async()=>{const pending=defer();let n=0;const x=fixture({loadQuote:()=>++n===1?pending.promise:Promise.resolve('新提示')});const old=x.hud.showFactionCard(x.faction);await Promise.resolve();await x.hud.showFactionCard(x.faction);const installed=x.card.children[0];pending.resolve('舊提示');await assert.rejects(old,/HUD_FACTION_CARD_STALE/);assert.equal(x.card.children[0],installed);assert.equal(x.card.style.display,'flex');assert.equal(x.disposed,1);x.hud.disposeFactionCardImageResources();assert.equal(x.disposed,2);});
await test('Image409/quote401 refuse no public fallback and explicit later call only can retry',async()=>{let bad=true;const x=fixture({loadPortrait:async()=>{if(bad)throw new Error('PRIVATE_BYTES_HTTP_409');return{image:{width:128,height:128},width:128,height:128,dispose(){}};}});await assert.rejects(x.hud.showFactionCard(x.faction),/PRIVATE_BYTES_HTTP_409/);assert.equal(x.card.style.display,'none');bad=false;await x.hud.showFactionCard(x.faction);x.hud.disposeFactionCardImageResources();const y=fixture({loadQuote:async()=>{throw new Error('PRIVATE_BYTES_HTTP_401');}});await assert.rejects(y.hud.showFactionCard(y.faction),/PRIVATE_BYTES_HTTP_401/);assert.equal(y.disposed,1);assert.equal(y.card.style.display,'none');});
await test('Bad image shape/nativeCanvas null reject and dispose receivedhandle, notpublicURL',async()=>{let disposed=0;const x=fixture({loadPortrait:async()=>({image:{width:64,height:64},width:64,height:64,dispose(){disposed++;}})});await assert.rejects(x.hud.showFactionCard(x.faction),/HUD_PORTRAIT_IMAGE/);assert.equal(disposed,1);assert.throws(()=>createPortraitCanvas({image:{width:128,height:128},width:128,height:128,dispose(){}},{createElement:()=>({style:{},setAttribute(){},getContext:()=>null})}),/HUD_PORTRAIT_CANVAS/);});
await test('Cleanup throw cannot mask primary quote failure or cause repeat dispose',async()=>{let n=0;const x=fixture({loadPortrait:async()=>({image:{width:128,height:128},width:128,height:128,dispose(){n++;throw new Error('cleanup');}}),loadQuote:async()=>{throw new Error('primary');}});await assert.rejects(x.hud.showFactionCard(x.faction),/primary/);x.hud.disposeFactionCardImageResources();assert.equal(n,1);});
await test('Readyquote formatting reentrant null is caught BEFORE DOMcommit',async()=>{const x=fixture({loadQuote:async()=>({toString(){void x.hud.showFactionCard(null);return '不安裝';}})});await assert.rejects(x.hud.showFactionCard(x.faction),/HUD_FACTION_CARD_STALE/);assert.equal(x.disposed,1);assert.equal(x.card.style.display,'none');assert.equal(x.card.children.filter(v=>v?.tagName==='canvas').length,0);});
await test('Post-DOMreplace reentrantclose does not redisplay stalecard or double release',async()=>{const x=fixture();x.card.afterReplace=()=>x.hud.disposeFactionCardImageResources();await assert.rejects(x.hud.showFactionCard(x.faction),/HUD_FACTION_CARD_CLOSED/);assert.equal(x.disposed,1);assert.equal(x.card.style.display,'none');});
await test('Dispose previous handle reentrantclose rejects new request before newloader',async()=>{let x,disposed=0;const ports={loadPortrait:async()=>({image:{width:128,height:128},width:128,height:128,dispose(){disposed++;x.hud.disposeFactionCardImageResources();}})};x=fixture(ports);await x.hud.showFactionCard(x.faction);await assert.rejects(x.hud.showFactionCard(x.faction),/HUD_FACTION_CARD_STALE|HUD_FACTION_CARD_CLOSED/);assert.equal(disposed,1);assert.equal(x.hud._factionCardClosed,true);});
await test('Unknown nextportrait hides earlier text/card and releases previous bitmap before role refusal',async()=>{const x=fixture();await x.hud.showFactionCard(x.faction);x.monarch.portrait=255;await assert.rejects(x.hud.showFactionCard(x.faction),/HUD_PORTRAIT_ROLE/);assert.equal(x.card.style.display,'none');assert.equal(x.disposed,1);assert.equal(x.reads,1);});
await test('Monarch reader reentrant scenario change on second guard is detected before imageI/O',async()=>{const x=fixture();let n=0;x.scenario.monarchOf=()=>{if(++n===3)x.app.scenario={...x.scenario};return x.monarch;};await assert.rejects(x.hud.showFactionCard(x.faction),/HUD_FACTION_CARD_STALE/);assert.equal(x.reads,0);assert.equal(x.quotes,0);});
for(const[p,h]of Object.entries(sourceHashes))assert.equal(hash(p),h,p);writeFileSync(d+'model-r'+round+'.json',JSON.stringify({checks,sourceHashes,fakeDOM:true,fakeTrustedIO:true,actualHUDConstructor:true,actualBrowser:false,nativeAuthority:false,ruleExecution:false,runtimeManifestImplemented:false,allHUDConsumersIntegrated:false},null,2)+'\n',{flag:'wx'});process.stdout.write(JSON.stringify({checks:checks.length,fakeDOM:true,actualHUD:true})+'\n');
}finally{globalThis.document=oldDoc;globalThis.Image=oldImage;}
