// Real local workerd+SQLite+HTTPS. Fixture refs are NOT actual content/blob/compile admission.
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { randomBytes, randomUUID, createHash } from 'node:crypto';
import { pathToFileURL } from 'node:url';
import { request as httpsRequest } from 'node:https';
import { DatabaseSync } from 'node:sqlite';
const modulePath=process.env.MINIFLARE_MODULE;assert.ok(modulePath);const {Miniflare}=await import(pathToFileURL(modulePath).href);
const folder='.dragon-analysis/editor-phase/backend-metadata-session-r1/',own=mkdtempSync(join(tmpdir(),'dragon-metadata-')),origin='https://127.0.0.1:8787',initial=randomBytes(24).toString('hex'),secret=randomBytes(32).toString('hex'),password=randomBytes(24).toString('hex');
const paths=['server/metadata.js','server/worker.js','server/security.js','tools/verify_editor_backend_metadata.mjs',folder+'fixture-worker.js'],hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex'),before=Object.fromEntries(paths.map(p=>[p,hash(p)]));
let mf;const build=()=>new Miniflare({name:'metadata-fixture',modules:true,scriptPath:resolve(folder+'fixture-worker.js'),compatibilityDate:'2026-01-01',compatibilityFlags:['nodejs_compat'],modulesRules:[{type:'ESModule',include:['**/*.js','**/*.mjs']},{type:'Text',include:['**/*.html','**/*.txt','**/*.css']}],host:'127.0.0.1',port:8787,https:true,durableObjects:{EDITOR_METADATA:{className:'MetadataFixture',useSQLite:true}},durableObjectsPersist:join(own,'metadata'),bindings:{EDITOR_ORIGIN:origin,EDITOR_DEFAULT_PASSWORD:initial,EDITOR_REQUEST_KEY:secret,EDITOR_ACCOUNT_LIMIT:'50',EDITOR_SOURCE_LIMIT:'100'}});
const calls=[];async function call(path,value,session,key=randomUUID()) {assert.equal((await mf.ready).origin,origin);const headers={};if(value!==undefined){headers['Content-Type']='application/json';headers.Origin=origin;headers['Idempotency-Key']=key;if(session)headers['X-CSRF-Token']=session.csrf;}if(session)headers.Cookie=session.cookie;const raw=await new Promise((done,reject)=>{const req=httpsRequest(origin+path,{method:value===undefined?'GET':'POST',headers,rejectUnauthorized:false},res=>{const chunks=[];res.on('data',chunk=>chunks.push(chunk));res.on('error',reject);res.on('end',()=>done({status:res.statusCode,cookie:res.headers['set-cookie']?.[0]?.split(';')[0],text:Buffer.concat(chunks).toString('utf8')}));});req.on('error',reject);req.end(value===undefined?undefined:JSON.stringify(value));});let data;try{data=JSON.parse(raw.text);}catch(cause){throw new Error('invalid owned metadata response',{cause});}calls.push({path,status:raw.status});return{status:raw.status,data,cookie:raw.cookie};}
const fixture=(value,s,key)=>call('/api/fixture/metadata',value,s,key);
async function login(account) {const first=await call('/api/auth/login',{account,password:initial});assert.equal(first.status,200);let s={cookie:first.cookie,csrf:first.data.csrf,user:first.data.user};const changed=await call('/api/auth/password',{oldPassword:initial,newPassword:password},s);assert.equal(changed.status,200);return{cookie:changed.cookie,csrf:changed.data.csrf,user:changed.data.user};}
const checks=[];try {
 mf=build();const admin=await login('tianyi');for(const account of ['author_a','author_b'])assert.equal((await call('/api/admin/accounts',{account},admin)).status,200);let a=await login('author_a'),b=await login('author_b');
 const createKey=randomUUID(),input={action:'create',metadata:{name:'  Cafe\u0301  ',introduction:' 原样 '}};
 const created=await fixture(input,a,createKey);assert.equal(created.status,200,created.data.error);const game=created.data.result;assert.equal(game.metadata.name,'Café');assert.equal(game.metadata.introduction,'原样');assert.equal(game.ownerId,a.user.id);assert.equal(game.draftRevision,'1');assert.equal(game.rowRevision,'1');assert.equal(game.createdAt,game.modifiedAt);assert.equal(game.nextOrdinal,'0');assert.equal(game.currentReleaseId,null);assert.equal(game.listed,false);
 assert.deepEqual((await fixture(input,a,createKey)).data.result,game);assert.equal((await fixture({...input,metadata:{name:'Changed',introduction:''}},a,createKey)).status,409);
 assert.equal((await fixture({action:'create',metadata:{name:'Café',introduction:''}},a)).status,409);assert.equal((await fixture({action:'create',metadata:{name:'Café',introduction:''}},b)).status,200);
 const lower=await fixture({action:'create',metadata:{name:'café',introduction:''}},a);assert.equal(lower.status,200);const supplementary=await fixture({action:'create',metadata:{name:'😀'.repeat(8),introduction:'文'.repeat(20)}},a);assert.equal(supplementary.status,200);
 for(const metadata of [{name:'😀'.repeat(9),introduction:''},{name:'  ',introduction:''},{name:'x',introduction:'文'.repeat(21)},{name:'\nx',introduction:''},{name:'x',introduction:'\ud800'},{name:'x\0',introduction:''},{name:'x',introduction:'\u0085'}])assert.equal((await fixture({action:'create',metadata},a)).status,422);
 checks.push('real principal owns UUID; trim/NFC/case-sensitive codepoint8/20 uniqueness, cross-author names, no formal version/listing');
 const ownList=await call('/api/games',undefined,a),otherList=await call('/api/games',undefined,b),adminOwn=await call('/api/games',undefined,admin);assert.equal(ownList.data.games.length,3);assert.equal(otherList.data.games.length,1);assert.equal(adminOwn.data.games.length,0);assert.equal((await call('/api/admin/games',undefined,a)).status,403);const global=await call('/api/admin/games',undefined,admin);assert.equal(global.data.games.length,4);for(const row of global.data.games){assert.equal(row.name,null);assert.ok(!Object.hasOwn(row,'draftRevision'));assert.ok(!Object.hasOwn(row,'metadata'));assert.ok(!JSON.stringify(row).includes('rootKey'));}
 const reference=await fixture({action:'reference',gameId:game.gameId,revision:'1'},a);assert.equal(reference.status,200);for(const s of [b,admin]) {const denied=await fixture({action:'reference',gameId:game.gameId,revision:'1'},s);assert.equal(denied.status,404);const deniedSave=await fixture({action:'save',gameId:game.gameId,expectedRevision:'1',metadata:{name:'Hacked',introduction:''}},s);assert.equal(deniedSave.status,404);assert.equal(deniedSave.data.error,'GAME_NOT_FOUND');}
 assert.equal((await fixture({action:'reference',gameId:'wolong-builtin',revision:'1'},admin)).status,403);checks.push('own lists and references, admin management no private draft; cross-author/admin writes denied before snapshot I/O; builtin protected');
 const update={action:'save',gameId:game.gameId,expectedRevision:'1',metadata:{name:'新版',introduction:'二'}};const saveKey=randomUUID(),saved=await fixture(update,a,saveKey);assert.equal(saved.status,200);assert.equal(saved.data.result.draftRevision,'2');assert.deepEqual((await fixture(update,a,saveKey)).data.result,saved.data.result);assert.equal((await fixture({...update,metadata:{name:'別名',introduction:''}},a)).status,409);assert.deepEqual((await fixture({action:'reference',gameId:game.gameId,revision:'1'},a)).data.result,reference.data.result);
 const noop=await fixture({...update,expectedRevision:'2'},a);assert.equal(noop.status,200);assert.deepEqual(noop.data.result,saved.data.result);
 assert.equal((await fixture({action:'create',metadata:{name:'Café',introduction:''}},a)).status,200); // prior draft-only name released; historical names do not reserve forever
 const oldState=saved.data.result;assert.equal((await fixture({action:'save',gameId:game.gameId,expectedRevision:'2',metadata:{name:'回滾',introduction:''},rollback:true},a)).status,503);assert.deepEqual((await call('/api/games',undefined,a)).data.games.find(g=>g.gameId===game.gameId),oldState);assert.equal((await fixture({action:'reference',gameId:game.gameId,revision:'3'},a)).status,404);assert.equal((await fixture({action:'create',metadata:{name:'創建回滾',introduction:''},rollback:true},a)).status,503);assert.equal((await fixture({action:'create',metadata:{name:'創建回滾',introduction:''}},a)).status,200);
 checks.push('CAS, immutable old snapshot refs, exact replay, no-op no revision/time change, actual SQL rollback removes snapshots/claims/receipts');
 const races=await Promise.all(['勝者一','勝者二'].map(name=>fixture({action:'save',gameId:game.gameId,expectedRevision:'2',metadata:{name,introduction:''}},a)));assert.deepEqual(races.map(r=>r.status).sort(),[200,409]);const winner=races.find(r=>r.status===200).data.result;assert.equal(winner.draftRevision,'3');
 const sameKey=randomUUID(),same={action:'save',gameId:game.gameId,expectedRevision:'3',metadata:{name:'單次',introduction:''}};const equalRaces=await Promise.all([fixture(same,a,sameKey),fixture(same,a,sameKey)]);assert.deepEqual(equalRaces.map(r=>r.status),[200,200]);assert.deepEqual(equalRaces[0].data.result,equalRaces[1].data.result);assert.equal(equalRaces[0].data.result.draftRevision,'4');checks.push('two request saves one CAS winner; same-key concurrent calls exactly one revision');
 assert.equal((await fixture({action:'formal',gameId:game.gameId},admin)).status,200);const renamed=await fixture({action:'save',gameId:game.gameId,expectedRevision:'4',metadata:{name:'新草稿',introduction:''}},a);assert.equal(renamed.status,200);assert.equal((await fixture({action:'create',metadata:{name:'單次',introduction:''}},a)).status,409);assert.equal((await fixture({action:'create',metadata:{name:'新草稿',introduction:''}},a)).status,409);assert.equal((await fixture({action:'create',metadata:{name:'單次',introduction:''}},b)).status,200);checks.push('fixture-only current formal name remains occupied beside renamed draft; not publish/compile proof');
 const scope=await fixture({action:'scope',metadata:{name:'作用域',introduction:''}},a);assert.equal(scope.status,200,scope.data.error);assert.equal(scope.data.result.rejected.length,7);checks.push('unforgeable server allocation/prepared capability; async/thenable/multi-write rollback and escaped callback revoked; absent production verifier503');
 assert.equal((await fixture({action:'counter',gameId:lower.data.result.gameId},a)).status,200);const big=await fixture({action:'save',gameId:lower.data.result.gameId,expectedRevision:'9007199254740999',metadata:{name:'大序號',introduction:''}},a);assert.equal(big.status,200);assert.equal(big.data.result.draftRevision,'9007199254741000');assert.equal(big.data.result.rowRevision,'9007199254741000');
 assert.equal((await fixture({action:'prepareDeferred',gameId:game.gameId,expectedRevision:'5',metadata:{name:'提交拒絕',introduction:''}},a)).status,200);
 const pending=fixture({action:'save',gameId:game.gameId,expectedRevision:'5',metadata:{name:'遲到寫入',introduction:''},source:{hold:true}},a);let waiting=false;for(let i=0;i<50;i++){const r=await fixture({action:'waiting'},admin);if(r.data.result.waiting){waiting=true;break;}await new Promise(done=>setTimeout(done,10));}assert.equal(waiting,true);
 const disabled=await call('/api/admin/accounts/'+a.user.id+'/disable',{expectedVersion:a.user.version,disabled:true},admin);assert.equal(disabled.status,200);assert.equal((await fixture({action:'commitDeferred'},admin)).status,401);assert.equal((await fixture({action:'release'},admin)).status,200);assert.equal((await pending).status,401);assert.equal((await call('/api/games',undefined,a)).status,401);assert.equal((await call('/api/games',undefined,b)).status,200);const enabled=await call('/api/admin/accounts/'+a.user.id+'/disable',{expectedVersion:disabled.data.account.version,disabled:false},admin);assert.equal(enabled.status,200);const relogin=await call('/api/auth/login',{account:'author_a',password});assert.equal(relogin.status,200);a={cookie:relogin.cookie,csrf:relogin.data.csrf,user:relogin.data.user};assert.equal((await fixture(input,a,createKey)).status,409);assert.equal((await fixture({action:'reference',gameId:game.gameId,revision:'6'},a)).status,404);checks.push('actual disable rejects already-prepared commit and in-flight prepare; old token/receipt never revive, other author unaffected; exact decimal counters beyond MAX_SAFE_INTEGER');
 const priorList=(await call('/api/games',undefined,a)).data.games;await mf.dispose();mf=undefined;mf=build();assert.deepEqual((await call('/api/games',undefined,a)).data.games,priorList);assert.equal((await fixture({action:'create',metadata:{name:'單次',introduction:''}},a)).status,409);assert.equal((await fixture({action:'reference',gameId:game.gameId,revision:'1'},a)).data.result.sourceDigest,reference.data.result.sourceDigest);await mf.dispose();mf=undefined;
 function find(path){return readdirSync(path,{withFileTypes:true}).flatMap(row=>{if(row.isDirectory())return find(join(path,row.name));if(row.name.endsWith('.sqlite'))return[join(path,row.name)];return[];});}
 let db;for(const file of find(join(own,'metadata'))){const candidate=new DatabaseSync(file,{readOnly:true});if(candidate.prepare("SELECT name FROM sqlite_master WHERE name='content_games'").get()){assert.equal(db,undefined);db=candidate;}else candidate.close();}assert.ok(db);try{assert.equal(db.prepare('SELECT COUNT(*) n FROM content_snapshots WHERE game_id=?').get(game.gameId).n,5);assert.equal(db.prepare('SELECT COUNT(*) n FROM content_names WHERE game_id=?').get(game.gameId).n,2);const rows=db.prepare('SELECT * FROM content_operations').all();assert.ok(rows.length>5);assert.ok(rows.every(row=>!Object.hasOwn(row,'expires_at')));assert.equal(rows.filter(row=>row.op_key===sameKey).length,1);assert.ok(!JSON.stringify(rows).includes(initial));const audit=db.prepare('SELECT * FROM content_audits').all();assert.ok(audit.length>5);assert.ok(audit.every(row=>!Object.hasOwn(row,'metadata')));}finally{db.close();}checks.push('workerd restart persists own lists/history/formal-name protection and permanent operation receipts; actual owned SQLite inspection');
 for(const[p,h]of Object.entries(before))assert.equal(hash(p),h);const receipt={result:'PASS-REAL-SQLITE-METADATA-FOUNDATION',checks,calls,sourceHashes:before,ownedPersistence:true,limits:'Engineering snapshot refs and formal-name fixture, NOT actual content/blob/compile/release, no public creation/save endpoint or complete backend/editor certificate. Snapshot verifier production still closed.'};writeFileSync(join(own,'receipt.json'),JSON.stringify(receipt,null,2));process.stdout.write(JSON.stringify(receipt,null,2)+'\n');
} finally {await mf?.dispose();}
