// Bounded Node + actual workerd PNG I/O. Installed Pillow is test-only independent pixel oracle.
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { createHash } from 'node:crypto';
import { deflateSync, crc32 } from 'node:zlib';
import { spawnSync } from 'node:child_process';
import { decodePNG, encodePNG, PNGError, PNG_IO_REVISION } from '../server/pngio.js';
import { renderMinimapPixels } from '../web/src/content/authoring/minimap.js';
const dir = '.dragon-analysis/editor-phase/backend-png-io-session-r1/', round = process.argv[2], sha = b => createHash('sha256').update(b).digest('hex');
assert.match(round ?? '', /^[1-9][0-9]{0,3}$/);
function parse(bytes) { try { return JSON.parse(bytes.toString()); } catch (cause) { throw new Error('invalid owned PNG test JSON', { cause }); } }
const receiptPath = '.dragon-analysis/editor-phase/backend-available-library-session-r1/static-receipt-r1.json', receiptBytes = readFileSync(receiptPath); assert.equal(sha(receiptBytes), '2bb651d6f808e2355a3ef4d8648297a6959d205764d6aff10af2691c0cc0f4c8'); const receipt = parse(receiptBytes), protectedHashes = { ...receipt.sourceHashes, ...receipt.protectedHashes }; assert.equal(Object.keys(protectedHashes).length, 433); for (const path of ['server/pngio.js', 'server/copyimages.js', 'tools/verify_editor_backend_png_io.mjs', 'tools/verify_editor_backend_image_jobs.mjs']) delete protectedHashes[path]; assert.equal(Object.keys(protectedHashes).length, 429); for (const [path, hash] of Object.entries(protectedHashes)) assert.equal(sha(readFileSync(path)), hash, path);
const inputs = ['server/pngio.js', 'tools/verify_editor_backend_png_io.mjs', 'tools/verify_editor_png_oracle.py', dir + 'fixture-worker.js', 'server/wrangler.jsonc', 'server/pinned/world-manifest.txt', 'web/src/content/authoring/minimap.js']; const sourceHashes = Object.fromEntries(inputs.map(path => [path, sha(readFileSync(path))]));
function chunk(type, bytes) { const body = Buffer.concat([Buffer.from(type), bytes]), length = Buffer.alloc(4), checksum = Buffer.alloc(4); length.writeUInt32BE(bytes.length); checksum.writeUInt32BE(crc32(body)); return Buffer.concat([length, body, checksum]); }
const signature = Buffer.from('89504e470d0a1a0a', 'hex');
function header(width, height, type, bit = 8, interlace = 0) { const b = Buffer.alloc(13); b.writeUInt32BE(width); b.writeUInt32BE(height, 4); b[8] = bit; b[9] = type; b[12] = interlace; return b; }
function png(h, raw, prefix = [], tail = [], compressed = deflateSync(raw)) { return Buffer.concat([signature, chunk('IHDR', h), ...prefix, chunk('IDAT', compressed), ...tail, chunk('IEND', Buffer.alloc(0))]); }
// Independent fixture filter encoder: tie order from a sorted predictor distance list.
function filtered(rows, bpp, selector) { const bytes = []; for (let y = 0; y < rows.length; y++) { const row = rows[y], prior = rows[y - 1]; const filter = selector(y); bytes.push(filter); for (let x = 0; x < row.length; x++) { const a = row[x - bpp] ?? 0, b = prior?.[x] ?? 0, c = prior?.[x - bpp] ?? 0; let p = 0; if (filter === 1) p = a; else if (filter === 2) p = b; else if (filter === 3) p = Math.floor((a + b) / 2); else if (filter === 4) p = [a, b, c].map((n,i) => ({ n, i, distance: Math.abs(a + b - c - n) })).sort((l,r) => l.distance - r.distance || l.i - r.i)[0].n; bytes.push((row[x] - p) & 255); } } return Buffer.from(bytes); }
const cases = [], negatives = [], generated = [], checks = [], calls = []; let mf;
for (const type of [0,2,3,4,6]) for (const width of [1,7]) {
  const height = 5, channels = { 0:1, 2:3, 3:1, 4:2, 6:4 }[type], rows = Array.from({ length:height }, (_,y) => Uint8Array.from({ length:width*channels }, (_,x) => (x*19+y*47)%256)), prefix = [];
  if (type === 3) { prefix.push(chunk('PLTE', Buffer.from(Array.from({ length:768 }, (_,i) => (i*11)%256)))); prefix.push(chunk('tRNS', Buffer.from(Array.from({ length:256 }, (_,i) => i)))); }
  if (type === 0) prefix.push(chunk('tRNS', Buffer.from([0,0]))); if (type === 2) prefix.push(chunk('tRNS', Buffer.from([0,0,0,19,0,38])));
  const bytes = png(header(width,height,type), filtered(rows,channels,y => y), prefix), path = dir+'fixture-'+(Number(round)*1000+cases.length)+'.png'; writeFileSync(path, bytes, { flag:'wx' }); cases.push({ path, bytes });
}
for (const season of ['spring','summer','autumn','winter']) { const path = 'web/map_atlas_'+season+'.png'; cases.push({ path, bytes:readFileSync(path) }); }
for (const asset of parse(readFileSync('server/pinned/world-manifest.txt')).assets.filter(asset => ['minimap_base.png','minimap_large.png'].includes(asset.path))) { const path = 'web/'+asset.url, bytes = readFileSync(path); assert.equal(sha(bytes),asset.sha256); assert.equal(bytes.length,asset.byteLength); cases.push({path,bytes}); }
const badCRC = Buffer.from(cases[0].bytes); badCRC[29] ^= 1; negatives.push(['bad-crc',badCRC,'PNG_CRC']);
negatives.push(['signature',Buffer.alloc(33),'PNG_SIGNATURE'], ['truncated',cases[0].bytes.subarray(0,cases[0].bytes.length-1),'PNG_TRUNCATED'], ['post-iend',Buffer.concat([cases[0].bytes,Buffer.from([0])]),'PNG_IEND']);
for (const [id,h] of [['interlaced',header(1,1,6,8,1)],['depth16',header(1,1,6,16)],['gray4',header(1,1,0,4)]]) negatives.push([id,png(h,Buffer.alloc(5)),'PNG_UNSUPPORTED_FORMAT']);
negatives.push(['pixel-budget',png(header(6144,4096,3),Buffer.alloc(2)),'PNG_PIXEL_BUDGET'], ['short-row',png(header(1,1,6),Buffer.alloc(4)),'PNG_SCANLINE_LENGTH'], ['filter5',png(header(1,1,6),Buffer.from([5,1,2,3,4])),'PNG_FILTER'], ['bomb',png(header(1,1,6),Buffer.alloc(100000)),'PNG_DEFLATE'], ['compressed-tail',png(header(1,1,6),Buffer.alloc(5),[],[],Buffer.concat([deflateSync(Buffer.alloc(5)),Buffer.from([1])])),'PNG_DEFLATE_TRAILING']);
negatives.push(['no-palette',png(header(1,1,3),Buffer.alloc(2)),'PNG_CHUNK_ORDER'], ['palette-index',png(header(1,1,3),Buffer.from([0,1]),[chunk('PLTE',Buffer.from([1,2,3]))]),'PNG_PALETTE_INDEX'], ['palette-size',png(header(1,1,3),Buffer.alloc(2),[chunk('PLTE',Buffer.from([1,2]))]),'PNG_PALETTE'], ['trns-rgba',png(header(1,1,6),Buffer.alloc(5),[chunk('tRNS',Buffer.from([1]))]),'PNG_TRANSPARENCY'], ['critical',png(header(1,1,6),Buffer.alloc(5),[chunk('ABCD',Buffer.alloc(0))]),'PNG_UNKNOWN_CRITICAL'], ['animated',png(header(1,1,6),Buffer.alloc(5),[chunk('acTL',Buffer.alloc(8))]),'PNG_UNSUPPORTED_METADATA'], ['color-profile',png(header(1,1,6),Buffer.alloc(5),[chunk('iCCP',Buffer.from([0]))]),'PNG_UNSUPPORTED_METADATA']);
const splitStream=deflateSync(Buffer.alloc(5)); negatives.push(['idat-gap',Buffer.concat([signature,chunk('IHDR',header(1,1,6)),chunk('IDAT',splitStream.subarray(0,3)),chunk('tEXt',Buffer.from('a\0b')),chunk('IDAT',splitStream.subarray(3)),chunk('IEND',Buffer.alloc(0))]),'PNG_CHUNK_ORDER']);
const validHeader=header(1,1,6), validRaw=Buffer.alloc(5), stream=deflateSync(validRaw), badAdler=Buffer.from(stream); badAdler[badAdler.length-1]^=1;
negatives.push(['duplicate-header',png(validHeader,validRaw,[chunk('IHDR',validHeader)]),'PNG_IHDR'],['reserved-chunk-bit',png(validHeader,validRaw,[chunk('abca',Buffer.alloc(0))]),'PNG_CHUNK_TYPE'],['missing-iend',png(validHeader,validRaw).subarray(0,-12),'PNG_IEND'],['incomplete-zlib',png(validHeader,validRaw,[],[],stream.subarray(0,-2)),'PNG_DEFLATE'],['empty-idat',png(validHeader,validRaw,[],[],Buffer.alloc(0)),'PNG_DEFLATE'],['adler',png(validHeader,validRaw,[],[],badAdler),'PNG_DEFLATE'],['duplicate-palette',png(header(1,1,3),Buffer.alloc(2),[chunk('PLTE',Buffer.from([1,2,3])),chunk('PLTE',Buffer.from([1,2,3]))]),'PNG_PALETTE'],['rgb-trns-range',png(header(1,1,2),Buffer.alloc(4),[chunk('tRNS',Buffer.from([1,0,0,0,0,0]))]),'PNG_TRANSPARENCY'],['zero-dimension',png(header(0,1,6),validRaw),'PNG_PIXEL_BUDGET'],['nonempty-iend',Buffer.concat([signature,chunk('IHDR',validHeader),chunk('IDAT',stream),chunk('IEND',Buffer.from([0]))]),'PNG_IEND']);
function storeGenerated(bytes,expected) { const path=dir+'fixture-'+(Number(round)*1000+100+generated.length)+'.png'; writeFileSync(path,bytes,{flag:'wx'}); generated.push({path,expected}); }
try {
  const { Miniflare } = await import(pathToFileURL(process.env.MINIFLARE_MODULE).href), config = parse(readFileSync('server/wrangler.jsonc')); mf = new Miniflare({ modules:true,modulesRules:[{type:'ESModule',include:['**/*.js','**/*.mjs']}],scriptPath:resolve(dir+'fixture-worker.js'),compatibilityDate:config.compatibility_date,compatibilityFlags:config.compatibility_flags,host:'127.0.0.1',port:0 }); const origin = await mf.ready;
  async function request(path,bytes,raw=false) { const response = await fetch(new URL(path,origin),{method:'POST',body:bytes}); calls.push({path,status:response.status}); const body = Buffer.from(await response.arrayBuffer()); return {status:response.status,body:raw?body:parse(body)}; }
  const env = {}; for (const key of ['SystemRoot','WINDIR','COMSPEC','PATH','Path','PATHEXT','TEMP','TMP','USERPROFILE','LOCALAPPDATA','APPDATA','HOMEDRIVE','HOMEPATH']) if(process.env[key]!==undefined)env[key]=process.env[key]; env.PYTHONUTF8='1'; env.PYTHONDONTWRITEBYTECODE='1';
  const oracle = spawnSync('python',['-B','tools/verify_editor_png_oracle.py'],{input:JSON.stringify(cases.map(c=>c.path)),env,encoding:'utf8',timeout:60000}); writeFileSync(dir+'oracle-r'+round+'.stderr',oracle.stderr,{flag:'wx'}); assert.equal(oracle.status,0,oracle.stderr); writeFileSync(dir+'oracle-r'+round+'.json',oracle.stdout,{flag:'wx'}); const reference = parse(Buffer.from(oracle.stdout)); assert.equal(reference.results.length,cases.length);
  for(let i=0;i<cases.length;i++) { const test=cases[i], expected=reference.results[i], decoded=decodePNG(test.bytes); assert.equal(decoded.width,expected.width); assert.equal(decoded.height,expected.height); assert.equal(sha(decoded.pixels),expected.pixelSha,test.path); const actual=await request('/decode',test.bytes); assert.equal(actual.status,200); assert.deepEqual(actual.body,{width:expected.width,height:expected.height,pixelSha:expected.pixelSha}); const nodeOutput=encodePNG(decoded.pixels,decoded.width,decoded.height), workerOutput=await request('/encode?width='+decoded.width+'&height='+decoded.height+'&channels=4',decoded.pixels,true); assert.equal(workerOutput.status,200); assert.equal(sha(decodePNG(nodeOutput).pixels),expected.pixelSha); assert.equal(sha(decodePNG(workerOutput.body).pixels),expected.pixelSha); storeGenerated(nodeOutput,expected); storeGenerated(workerOutput.body,expected); }
  checks.push('16 Pillow independent RGBA pixel oracles: all5supported color types, all5rowfilters, transparency/edge widths, four actual indexed8 atlases and two pinned mini PNGs; actual Node/workerd decode+encode roundtrips');
  for(const [name,bytes,code]of negatives) { assert.throws(()=>decodePNG(bytes),error=>error instanceof PNGError&&error.code===code,name); const actual=await request('/decode',bytes); assert.equal(actual.status,422,name); assert.equal(actual.body.error,code,name); } checks.push(negatives.length+' exact Node/workerd negative format/CRC/order/filter/length/palette/animation/profile/budget/bomb/trailing-stream controls reject without partial image');
  let getterCalls=0; const typed = new Uint8Array(cases[0].bytes); Object.defineProperty(typed,'buffer',{get(){getterCalls++;throw new Error('must not invoke caller accessor');}}); assert.equal(sha(decodePNG(typed).pixels),reference.results[0].pixelSha); assert.equal(getterCalls,0); for(const bad of [null,[],new Proxy(typed,{}),new DataView(new ArrayBuffer(8)),new Uint8Array(new SharedArrayBuffer(8))])assert.throws(()=>decodePNG(bad),error=>error.code==='PNG_INPUT_TYPE'); assert.throws(()=>decodePNG(new Uint8Array(16*1024*1024+1)),error=>error.code==='PNG_BYTE_BUDGET'); assert.throws(()=>encodePNG(new Uint8Array(3),1,1),error=>error.code==='PNG_PIXEL_LENGTH'); assert.throws(()=>encodePNG(new Uint8Array(3),1,1,1),error=>error.code==='PNG_INPUT_CHANNELS'); checks.push('owned copied Uint8 input, intrinsic getters no accessor side-effect; proxy/nonbyte/shared/budget and wrong encoder lengths/channels rejected');
  const geography=Uint8Array.from({length:24*16},(_,i)=>i%4),roads=Uint8Array.from({length:24*16},(_,i)=>Number(i%11===0)); const originalRandom=Math.random; let mini; try { Math.random=()=>{throw new Error('ambient RNG forbidden');}; mini=renderMinimapPixels(geography,roads,24,16,208,139,17); const encoded=encodePNG(mini.pixels,208,139,3), decoded=decodePNG(encoded); for(let i=0;i<208*139;i++){assert.deepEqual(Array.from(decoded.pixels.subarray(i*4,i*4+3)),Array.from(mini.pixels.subarray(i*3,i*3+3)));assert.equal(decoded.pixels[i*4+3],255);} } finally {Math.random=originalRandom;}
  const actualMini=await request('/encode?width=208&height=139&channels=3',mini.pixels,true); assert.equal(actualMini.status,200); assert.equal(sha(decodePNG(actualMini.body).pixels),sha(decodePNG(encodePNG(mini.pixels,208,139,3)).pixels)); checks.push('unchanged shared mini renderer RGB output encoded without DOM/ambient RNG; actual Worker RGB PNG has same opaque RGBA pixels, not second mini algorithm');
  const miniExpected={width:208,height:139,pixelSha:sha(decodePNG(actualMini.body).pixels)}; storeGenerated(actualMini.body,miniExpected);
  const encodedOracle=spawnSync('python',['-B','tools/verify_editor_png_oracle.py'],{input:JSON.stringify(generated.map(c=>c.path)),env,encoding:'utf8',timeout:60000}); writeFileSync(dir+'encoded-oracle-r'+round+'.stderr',encodedOracle.stderr,{flag:'wx'}); assert.equal(encodedOracle.status,0,encodedOracle.stderr); writeFileSync(dir+'encoded-oracle-r'+round+'.json',encodedOracle.stdout,{flag:'wx'}); const encodedReference=parse(Buffer.from(encodedOracle.stdout)); assert.equal(encodedReference.results.length,generated.length); encodedReference.results.forEach((record,i)=>assert.deepEqual({width:record.width,height:record.height,pixelSha:record.pixelSha},{width:generated[i].expected.width,height:generated[i].expected.height,pixelSha:generated[i].expected.pixelSha})); checks.push('33 actual new Node/Worker encoded PNGs independently decoded by installed Pillow, not solely self-roundtrip');
  for(const[path,hash]of Object.entries({...protectedHashes,...sourceHashes}))assert.equal(sha(readFileSync(path)),hash,path);
  process.stdout.write(JSON.stringify({result:'PASS-BOUNDED-NODE-WORKER-PNG-IO',revision:PNG_IO_REVISION,checks,calls,sourceHashes,protectedInputs:429,oracle:reference,encodedOracle:encodedReference,negativeCount:negatives.length,limits:'Standalone bounded PNG raw-sample adapter only, not authenticated compiler/stores/identity or runtime grant. 4Mi pixel cap explicitly rejects full6144x4096fallbacks; interlace/16bit/color-management/animation unsupported. NoRoot/Job/playerchanges, noQ69/Trial/Release/cloudSLA/goalcompletion.'},null,2)+'\n');
}finally{await mf?.dispose();}
