// Fake HTTP/lifecycle/bitmap model: envelope-only synthetic big header, NOT real big raster/authority.
import assert from 'node:assert/strict';import {webcrypto,createHash} from 'node:crypto';import {readFileSync,writeFileSync} from 'node:fs';import {encodePNG} from '../server/pngio.js';import {createPrivateFallbackContext} from '../web/src/content/privatefallback.js';import {inspectSmallPrivatePNG} from '../web/src/content/privatepng.js';
const d='.dragon-analysis/editor-phase/backend-private-fallback-decode-session-r1/',round=process.argv[2];assert.match(round??'',/^[1-9][0-9]{0,2}$/);const checks=[],ref={gameId:'11111111-1111-4111-8111-111111111111',draftRevision:'1',sourceDigest:'a'.repeat(64),dependencyDigest:'b'.repeat(64)},operationId='22222222-2222-4222-8222-222222222222',sha=b=>createHash('sha256').update(b).digest('hex');
function crc(b){let c=0xffffffff;for(const v of b){c^=v;for(let i=0;i<8;i++)c=c&1?(c>>>1)^0xedb88320:c>>>1;}return (c^0xffffffff)>>>0;}
const tiny=Uint8Array.from(encodePNG(new Uint8Array([1,2,3,255]),1,1));function big(change=()=>{}){const x=tiny.slice(),view=new DataView(x.buffer);view.setUint32(16,6144);view.setUint32(20,4096);change(x,view);view.setUint32(29,crc(x.subarray(12,29)));return x;}const valid=big();
function setup(raw=valid,ports={}){let alive=true,calls=0,decodes=0,closes=0;const x={kind:'private-stage',gameId:ref.gameId,draftRevision:'1',sourceDigest:ref.sourceDigest,purpose:'fallback-spring',operationId,assetId:'fallback_spring',sha256:sha(raw),byteLength:raw.length},ctx=createPrivateFallbackContext(ref,{subtle:webcrypto.subtle,assertCurrent(){assert.ok(alive,'local revoked');},fetcher:async()=>{calls++;return new Response(raw.slice(),{headers:{'X-Game-ID':ref.gameId,'X-Draft-Revision':'1','X-Source-SHA256':ref.sourceDigest,'X-Dependency-SHA256':ref.dependencyDigest,'X-Content-SHA256':x.sha256,'Content-Type':'application/octet-stream','Cache-Control':'no-store','X-Content-Admission':'stage-only'}});},decodeBitmap:async(blob,options)=>{decodes++;assert.equal(blob.type,'image/png');assert.deepEqual(options,{premultiplyAlpha:'none',colorSpaceConversion:'none',imageOrientation:'none'});return {width:6144,height:4096,close(){closes++;}};},...ports});return {ctx,x,calls:()=>calls,decodes:()=>decodes,closes:()=>closes,revoke(){alive=false;}};}
async function reject(fn,code){try{await fn();assert.fail('expected '+code);}catch(e){assert.equal(e.message,code);}checks.push(code);}
const s=setup(),h=await s.ctx.readPNG(s.x);assert.ok(Object.isFrozen(h));assert.equal(h.width,6144);assert.equal(h.height,4096);await reject(()=>s.ctx.readPNG(s.x),'PRIVATE_FALLBACK_OWNED_BUDGET');assert.equal(s.calls(),1);h.dispose();h.dispose();assert.equal(s.closes(),1);const again=await s.ctx.readPNG(s.x);assert.equal(s.calls(),2);s.ctx.close();s.ctx.close();assert.equal(s.closes(),2);again.dispose();await reject(()=>s.ctx.readPNG(s.x),'PRIVATE_FALLBACK_CLOSED');checks.push('oneownedbitmap/idempotentdispose/close/fresh explicit GET afterdispose; local only no revocation/drain claim');
for(const v of [{kind:'private-library'},{purpose:'data'},{purpose:'fallback-winter'},{assetId:'fallback_report'}]){const p=setup();await reject(()=>p.ctx.readPNG({...p.x,...v}),'PRIVATE_FALLBACK_ROLE');assert.equal(p.calls(),0);}
const g=setup();let getterCalls=0;const acc={...g.x};Object.defineProperty(acc,'assetId',{enumerable:true,get(){getterCalls++;return 'fallback_spring';}});await reject(()=>g.ctx.readPNG(acc),'PRIVATE_FALLBACK_LOCATOR');assert.equal(getterCalls,0);await reject(()=>g.ctx.readPNG({...g.x,extra:true}),'PRIVATE_BYTES_FIELDS');await reject(()=>g.ctx.readPNG({...g.x,sourceDigest:'c'.repeat(64)}),'PRIVATE_BYTES_CONTEXT');assert.equal(g.calls(),0);
for(const raw of [tiny,big((x,v)=>v.setUint32(16,6145)),big((x,v)=>v.setUint32(20,4097)),big(x=>x[25]=2),big(x=>x[24]=16)]){const p=setup(raw);await reject(()=>p.ctx.readPNG(p.x),'PRIVATE_RESOURCE_PNG_FALLBACK_SHAPE');assert.equal(p.decodes(),0);}const interlace=setup(big(x=>x[28]=1));await reject(()=>interlace.ctx.readPNG(interlace.x),'PRIVATE_RESOURCE_PNG_FORMAT');const badCRC=valid.slice();badCRC[29]^=1;const corrupt=setup(badCRC);await reject(()=>corrupt.ctx.readPNG(corrupt.x),'PRIVATE_RESOURCE_PNG_CRC');assert.equal(corrupt.decodes(),0);const end=setup(valid.slice(0,-12));await reject(()=>end.ctx.readPNG(end.x),'PRIVATE_RESOURCE_PNG_IEND');
assert.throws(()=>inspectSmallPrivatePNG(valid),{message:'PRIVATE_RESOURCE_PNG_PIXELS'});checks.push('original generic4Mipixel policy still rejects EXACTlarge header; no general PNG/library size increase');
let resume,closed=0;const late=setup(valid,{decodeBitmap:()=>new Promise(r=>{resume=r;})}),task=late.ctx.readPNG(late.x);while(!resume)await new Promise(r=>setImmediate(r));await reject(()=>late.ctx.readPNG(late.x),'PRIVATE_FALLBACK_OWNED_BUDGET');late.ctx.close();resume({width:6144,height:4096,close(){closed++;}});await reject(()=>task,'PRIVATE_FALLBACK_CLOSED');assert.equal(closed,1);
let resume2,closed2=0;const revoked=setup(valid,{decodeBitmap:()=>new Promise(r=>{resume2=r;})}),pending=revoked.ctx.readPNG(revoked.x);while(!resume2)await new Promise(r=>setImmediate(r));revoked.revoke();resume2({width:6144,height:4096,close(){closed2++;throw new Error('cleanup');}});await reject(()=>pending,'local revoked');assert.equal(closed2,1);
const badShape=setup(valid,{decodeBitmap:async()=>({width:6143,height:4096,close(){closed2++;}})});await reject(()=>badShape.ctx.readPNG(badShape.x),'PRIVATE_FALLBACK_DECODE');for(const status of [401,403,409,410,503]){let n=0;const p=setup(valid,{fetcher:async()=>{n++;return new Response('',{status});}});await reject(()=>p.ctx.readPNG(p.x),'PRIVATE_BYTES_HTTP_'+status);assert.equal(n,1);assert.equal(p.decodes(),0);}const clean=setup(valid,{decodeBitmap:async()=>{throw new Error('codec failed');}});await reject(()=>clean.ctx.readPNG(clean.x),'codec failed');await reject(()=>clean.ctx.readPNG(clean.x),'codec failed');assert.equal(clean.calls(),2);checks.push('failed decode frees ownedpending reservation but doesnot retry without explicit newcall');assert.deepEqual(['runtimeAllowed','trialAllowed','releaseAllowed','deleteAllowed'].map(k=>g.ctx[k]),[false,false,false,false]);writeFileSync(d+'model-r'+round+'.json',JSON.stringify({checks,fakeHTTP:true,fakeBitmap:true,syntheticBigIHDRNotDecodedPixels:true,nativeAuthority:false,actualBrowser:false,providerDrain:false,sourceHashes:Object.fromEntries(['web/src/content/privatefallback.js','web/src/content/privatepng.js','web/src/content/privatebytes.js','tools/verify_editor_private_fallback.mjs'].map(p=>[p,sha(readFileSync(p))]))},null,2)+'\n',{flag:'wx'});process.stdout.write(JSON.stringify({checks:checks.length})+'\n');
