// Actual default Root and separately labelled native-await controls; owned local SQL/R2 only.
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { randomBytes, randomUUID, createHash } from 'node:crypto';
import { request as httpsRequest } from 'node:https';
import { DatabaseSync } from 'node:sqlite';
import { pathToFileURL } from 'node:url';
import { startEditorBackend } from './start_editor_backend.mjs';
const dir = '.dragon-analysis/editor-phase/backend-library-assets-session-r1/', round = process.argv[2] ?? '1', own = mkdtempSync(join(tmpdir(), 'dragon-private-library-'));
assert.match(round, /^[1-9][0-9]{0,2}$/);
const controlsOnly = process.argv[3] === 'controls-only';
const sha = bytes => createHash('sha256').update(bytes).digest('hex');
function json(bytes) { try { return JSON.parse(bytes.toString()); } catch (cause) { throw new Error('owned library assets JSON invalid', { cause }); } }
const doc = json(readFileSync('server/wrangler.jsonc')), configPath = join(own, 'worker.json'); doc.main = resolve('server/worker.js'); doc.name = 'private-assets-' + randomUUID();
const initial = randomBytes(24).toString('hex'), password = randomBytes(24).toString('hex');
writeFileSync(configPath, JSON.stringify(doc), { flag: 'wx' }); writeFileSync(join(own, '.dev.vars'), 'EDITOR_DEFAULT_PASSWORD=' + JSON.stringify(initial) + '\nEDITOR_REQUEST_KEY=' + JSON.stringify(randomBytes(32).toString('hex')) + '\n', { flag: 'wx', mode: 0o600 });
const sources = ['server/worker.js','server/libraryassets.js','server/sourcecatalog.js','server/drafts.js','server/available-library.txt','server/sourcecatalogpolicy.js','tools/start_editor_backend.mjs','tools/verify_editor_backend_library_assets.mjs',dir+'fixture-worker.js'];
const sourceHashes = Object.fromEntries(sources.map(p => [p, sha(readFileSync(p))])), checks = [], calls = [], artifacts = []; let server;
async function call(path, value, session, extra = {}, raw = false) {
  const headers = { Origin: 'https://127.0.0.1:8787', Connection: 'close', ...extra };
  if (session) { headers.Cookie = session.cookie; headers['X-CSRF-Token'] ??= session.csrf; }
  if (value !== undefined) { headers['Content-Type'] = 'application/json'; headers['Idempotency-Key'] ??= randomUUID(); }
  const result = await new Promise((done,reject) => { const request = httpsRequest(new URL(path, server.url), { method: value === undefined ? 'GET' : 'POST', headers, rejectUnauthorized: false, agent: false }, reply => { const parts=[]; reply.on('data', bytes=>parts.push(bytes)); reply.on('error',reject); reply.on('end',()=>{try{const bytes=Buffer.concat(parts);done({status:reply.statusCode,bytes,data:raw?undefined:json(bytes),headers:reply.headers,cookie:reply.headers['set-cookie']?.[0]?.split(';')[0]});}catch(error){reject(error);}}); }); request.on('error',reject); request.end(value===undefined?undefined:JSON.stringify(value)); }); calls.push({path,status:result.status}); if(controlsOnly) process.stderr.write(path+' '+result.status+'\n'); return result;
}
async function login(account) { const first=await call('/api/auth/login',{account,password:initial});assert.equal(first.status,200);const next=await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:first.cookie,csrf:first.data.csrf});assert.equal(next.status,200);return{cookie:next.cookie,csrf:next.data.csrf}; }
function files(path) { return readdirSync(path,{withFileTypes:true}).flatMap(e=>{ if(e.isDirectory()) return files(join(path,e.name)); if(e.name.endsWith('.sqlite')) return [join(path,e.name)]; return []; }); }
function database() { for(const path of files(join(own,'.local/metadata'))){const db=new DatabaseSync(path);if(db.prepare("SELECT name FROM sqlite_master WHERE name='content_snapshots'").get())return db;db.close();}throw new Error('owned metadata SQL absent'); }
async function bucketMutation(action) {
  await server.close();server=undefined;
  const {Miniflare}=await import(pathToFileURL(process.env.MINIFLARE_MODULE).href), mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response(null,{status:404})}}',compatibilityDate:doc.compatibility_date,compatibilityFlags:doc.compatibility_flags,r2Buckets:['EDITOR_BLOBS'],r2Persist:join(own,'.local/blobs'),host:'127.0.0.1',port:0});
  try { await mf.ready;await action(await mf.getR2Bucket('EDITOR_BLOBS')); } finally { await mf.dispose(); }
  server=await startEditorBackend(configPath);
}
try {
  server=await startEditorBackend(configPath,{stageSource:true,stageLibrary:true});const admin=await login('tianyi');assert.equal((await call('/api/admin/accounts',{account:'asset_author'},admin)).status,200);const author=await login('asset_author');
  assert.equal((await call('/api/admin/source/install',{},admin)).status,200);const source=(await call('/api/admin/source',undefined,admin)).data,key=randomUUID();assert.equal((await call('/api/admin/copies',{registryId:source.definition.registryId,name:'資源讀取',introduction:''},admin,{'Idempotency-Key':key})).status,202);const copied=await call('/api/admin/copies/'+key+'/run',{},admin,{'If-Match':'"1"'});assert.equal(copied.status,200,copied.data.error);const gameId=copied.data.gameId,base='/api/games/'+gameId+'/draft/library-assets',url=base+'?revision=1';
  let fresh=admin, nextPassword=password, db=database(); const origin=db.prepare('SELECT * FROM copy_origins WHERE game_id=?').get(gameId);db.close();
  if (!controlsOnly) {
  assert.equal((await call(url,undefined,admin)).status,404,'staged library must not be registered implicitly');assert.equal((await call('/api/admin/library/install',{},admin)).status,200);
  assert.equal((await call(url,undefined)).status,401);assert.equal((await call(url,undefined,author)).status,403);assert.equal((await call(url,undefined,admin,{Origin:'http://127.0.0.1:8787'})).status,403);assert.equal((await call('/api/games/wolong-builtin/draft/library-assets?revision=1',undefined,admin)).status,403);assert.equal((await call('/api/games/'+randomUUID()+'/draft/library-assets?revision=1',undefined,admin)).status,404);
  for(const query of['','?revision=0','?revision=01','?revision=1&revision=1','?revision=1&path=kao/255.png','?latest=1'])assert.equal((await call(base+query,undefined,admin)).status,422,query);
  assert.equal((await call(base+'?revision=99',undefined,admin)).status,404);assert.equal((await call(base+'/library-999?revision=1',undefined,admin)).status,404);assert.equal((await call(base+'/kao/255.png?revision=1',undefined,admin)).status,404);
  checks.push('actual default Root staged-not-registered/auth/admin-owner/Origin/builtin/unknown-game/exact-positive-revision/fixed-assetId/path guards, no implicitlatest or255');
  process.stderr.write('library-assets: exact saved1 full source and all400 roles\n');const listed=await call(url,undefined,admin);assert.equal(listed.status,200,listed.data.error);assert.equal(listed.data.assets.length,398);assert.equal(listed.data.unresolvedReferences.length,20);assert.equal(listed.data.admission,'private-available-bytes-only');assert.equal(listed.data.mode,'STAGED_AVAILABLE_LIBRARY_NOT_Q69_CLOSURE');assert.equal(listed.data.draftRevision,'1');assert.ok(!listed.data.assets.some(a=>a.logicalURL==='kao/255.png'));
  const manifest=json(readFileSync('server/available-library.txt'));for(const asset of listed.data.assets){const expected=manifest.resources[asset.logicalURL];assert.equal(asset.sha256,expected.sha256);assert.equal(asset.byteLength,expected.byteLength);assert.equal(asset.mime,expected.mime);}
  const saved=await call('/api/games/'+gameId+'/draft/save',{metadata:{name:'資源第二修訂',introduction:'新修訂'},resourceEdits:[]},admin,{'If-Match':'"1"'});assert.equal(saved.status,200,saved.data.error);assert.equal(saved.data.draftRevision,'2');const before=(await call('/api/games',undefined,admin)).data.games.find(g=>g.gameId===gameId);
  checks.push('actual all400 R2 full-role verification bound saved1 and explicit immutable catalogue/source, save2 neither rewrites nor relabels old read');
  const selected=['kao/0.png','battle_rules.json','grf/music/loops/BGM_02.flac','grf/sfx/ynsound-record3.wav','font/Oswald-Light.woff2','battle_display.bin'];
  for(let n=0;n<selected.length;n++) { const asset=listed.data.assets.find(a=>a.logicalURL===selected[n]);assert.ok(asset,selected[n]);const reply=await call(base+'/'+asset.assetId+'?revision=1',undefined,admin,{},true);assert.equal(reply.status,200,reply.bytes.toString().slice(0,100));assert.equal(reply.bytes.length,asset.byteLength);assert.equal(sha(reply.bytes),asset.sha256);assert.equal(reply.headers['x-content-sha256'],asset.sha256);assert.equal(reply.headers['x-draft-revision'],'1');assert.equal(reply.headers['x-source-sha256'],listed.data.sourceDigest);assert.equal(reply.headers['x-library-root'],listed.data.catalogRoot);assert.equal(reply.headers['x-content-admission'],'private-available-bytes-only');assert.equal(reply.headers['content-type'],'application/octet-stream');assert.equal(reply.headers['cache-control'],'no-store');assert.equal(reply.headers['x-content-type-options'],'nosniff');assert.equal(reply.headers['content-disposition'],'attachment; filename="'+asset.assetId+'.bin"');const path=dir+'asset-r'+round+'-'+n+'.bin';writeFileSync(path,reply.bytes,{flag:'wx'});artifacts.push({path,logicalURL:asset.logicalURL,sha256:asset.sha256,byteLength:asset.byteLength});}
  const current=await call(base+'?revision=2',undefined,admin);assert.equal(current.status,200,current.data.error);assert.equal(current.data.draftRevision,'2');assert.notEqual(current.data.sourceDigest,listed.data.sourceDigest);assert.equal(current.data.catalogRoot,listed.data.catalogRoot);
  assert.deepEqual((await call('/api/games',undefined,admin)).data.games.find(g=>g.gameId===gameId),before);
  checks.push('six actual PNG/JSON/FLAC/WAV/WOFF2/bin attachments fullbytesSHA, source1 despite current2, distinct source2 sameimmutablelibrary, no metadata/modifiedAt mutation');
  db=database();db.prepare('UPDATE content_games SET owner_id=(SELECT id FROM users WHERE account=?) WHERE game_id=?').run('asset_author',gameId);db.close();assert.equal((await call(url,undefined,admin)).status,404);db=database();db.prepare('UPDATE content_games SET owner_id=(SELECT id FROM users WHERE account=?) WHERE game_id=?').run('tianyi',gameId);db.prepare('UPDATE copy_origins SET definition_digest=? WHERE game_id=?').run('0'.repeat(64),gameId);db.close();assert.equal((await call(url,undefined,admin)).status,409);db=database();db.prepare('UPDATE copy_origins SET definition_digest=? WHERE game_id=?').run(origin.definition_digest,gameId);const libraryRow=db.prepare('SELECT * FROM installed_sources WHERE registry_id=?').get(listed.data.registryId);db.prepare('UPDATE installed_sources SET definition_digest=? WHERE registry_id=?').run('0'.repeat(64),listed.data.registryId);db.close();assert.equal((await call(url,undefined,admin)).status,409);db=database();db.prepare('UPDATE installed_sources SET definition_digest=? WHERE registry_id=?').run(libraryRow.definition_digest,listed.data.registryId);db.close();
  checks.push('actual owned SQL owner/source-origin/library-policy damage rejects before byte response, controlled exactrestore only');
  const png=listed.data.assets.find(a=>a.logicalURL==='kao/0.png'), objectKey='installed/'+listed.data.registryId+'/'+png.sha256;let original;
  await bucketMutation(async bucket=>{const object=await bucket.get(objectKey);assert.ok(object);original=new Uint8Array(await object.arrayBuffer());assert.equal(sha(original),png.sha256);const bad=original.slice();bad[0]^=1;await bucket.put(objectKey,bad);});const damaged=await call(url,undefined,admin);assert.equal(damaged.status,503);assert.equal(damaged.data.error,'SOURCE_OBJECT_CORRUPT');await bucketMutation(async bucket=>{await bucket.put(objectKey,original);});assert.equal((await call(url,undefined,admin)).status,200);
  nextPassword=randomBytes(24).toString('hex');const changed=await call('/api/auth/password',{oldPassword:password,newPassword:nextPassword},admin);assert.equal(changed.status,200);assert.equal((await call(url,undefined,admin)).status,401);fresh={cookie:changed.cookie,csrf:changed.data.csrf};assert.equal((await call(url,undefined,fresh)).status,200);assert.equal((await call('/api/games/'+gameId+'/trial',{},fresh)).status,404);
  checks.push('actual R2 same-size corruption of one role blocks whole manifest, real stop/restart restores proof; actualpassword oldcookie401/fresh read, noTrial grant');
  } else { assert.equal((await call('/api/admin/library/install',{},admin)).status,200); }
  await server.close();server=undefined;const controlled=join(own,'controlled.json');writeFileSync(controlled,JSON.stringify({...doc,main:resolve(dir+'fixture-worker.js')}),{flag:'wx'});server=await startEditorBackend(controlled);
  for(const [point,action]of[['catalog','origin'],['result','snapshot']]) { db=database();const snapshot=db.prepare('SELECT * FROM content_snapshots WHERE game_id=? AND revision=?').get(gameId,'1');db.close();assert.equal((await call('/api/test/library/control',{point,action,gameId},fresh)).status,200);const denied=await call(url,undefined,fresh);assert.equal(denied.status,409,denied.data.error);assert.equal(denied.data.error,action==='origin'?'DRAFT_SOURCE_CHANGED':'LIBRARY_SNAPSHOT_CHANGED');db=database();db.prepare('UPDATE copy_origins SET definition_digest=? WHERE game_id=?').run(origin.definition_digest,gameId);db.prepare('UPDATE content_snapshots SET source_digest=? WHERE game_id=? AND revision=?').run(snapshot.source_digest,gameId,'1');db.close(); }
  checks.push('separate native fixture calls unchanged full catalogue/service; SQL origin changed afternativecatalog await rejected, snapshot changed afteractual service return rejected by Root finalassert');
  const finalPassword=randomBytes(24).toString('hex');assert.equal((await call('/api/test/library/control',{point:'result',action:'password',gameId,oldPassword:nextPassword,newPassword:finalPassword},fresh)).status,200);const revoked=await call(url,undefined,fresh);assert.equal(revoked.status,401);assert.equal(revoked.data.error,'SESSION_INVALID');
  assert.equal((await call('/api/session',undefined,fresh)).status,401);const last=await call('/api/auth/login',{account:'tianyi',password:finalPassword});assert.equal(last.status,200);const finalSession={cookie:last.cookie,csrf:last.data.csrf};assert.deepEqual((await call('/api/test/library/last-password',undefined,finalSession)).data,{performed:true,status:200});assert.equal((await call(url,undefined,finalSession)).status,200);
  checks.push('actual result await callback invokes unchanged passwordhandler KDF/SQL/session revocation200; Root finalassert401 notbytes, oldcookie401 and freshactual-login may read; notconcurrentHTTP or directepoch mutation');
  for(const[p,h]of Object.entries(sourceHashes))assert.equal(sha(readFileSync(p)),h,p);process.stdout.write(JSON.stringify({result:'PASS-PRIVATE-EXACT-SAVED-LIBRARY-BYTES-NOT-RUNTIME',executionMode:controlsOnly?'native-controls-only':'default-plus-native',checks,calls,sourceHashes,artifacts,roles:400,assets:398,unresolved:20,limits:'DefaultRoot main flow plus explicitlyseparate native await fixture. Opaque bytes not audio/font semantics, whole-library dependency/runtime admission, Trial, Release or cloudSLA.'},null,2)+'\n');
} catch(error) { writeFileSync(dir+'failure-state-r'+round+'.json',JSON.stringify({message:String(error.message).slice(0,2000),code:error.code??null,calls,checks,sourceHashes},null,2)+'\n',{flag:'wx'});throw error; } finally { await server?.close(); }
