// Actual Root-derived SQL/R2/image planner; all original products protected, no runtime admission.
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { randomBytes, randomUUID, createHash } from 'node:crypto';
import { request as httpsRequest } from 'node:https';
import { DatabaseSync } from 'node:sqlite';
import { startEditorBackend } from './start_editor_backend.mjs';
import { decodePNG } from '../server/pngio.js';
const dir='.dragon-analysis/editor-phase/backend-image-jobs-session-r1/',own=mkdtempSync(join(tmpdir(),'dragon-image-job-')),origin='https://127.0.0.1:8787',sha=value=>createHash('sha256').update(value).digest('hex');
function parse(value){try{return JSON.parse(value);}catch(cause){throw new Error('invalid owned image job JSON',{cause});}}
const initial=randomBytes(24).toString('hex'),password=randomBytes(24).toString('hex'),secret=randomBytes(32).toString('hex'),config=parse(readFileSync('server/wrangler.jsonc')),configPath=join(own,'wrangler.jsonc');config.main=resolve(dir+'fixture-worker.js');writeFileSync(configPath,JSON.stringify(config));writeFileSync(join(own,'.dev.vars'),'EDITOR_DEFAULT_PASSWORD='+JSON.stringify(initial)+'\nEDITOR_REQUEST_KEY='+JSON.stringify(secret)+'\n',{flag:'wx',mode:0o600});
const sources=['server/imagejobs.js','tools/verify_editor_backend_image_jobs.mjs',dir+'fixture-worker.js'],sourceHashes=Object.fromEntries(sources.map(p=>[p,sha(readFileSync(p))])),checks=[],calls=[];let server,gateSession;
async function call(path,value,session,extra={},raw=false){const headers={Origin:origin,...extra};if(session){headers.Cookie=session.cookie;headers['X-CSRF-Token']=session.csrf;}if(value!==undefined){headers['Content-Type']='application/json';headers['Idempotency-Key']??=randomUUID();}const response=await new Promise((done,reject)=>{const req=httpsRequest(origin+path,{method:value===undefined?'GET':'POST',headers,rejectUnauthorized:false},res=>{const parts=[];res.on('data',b=>parts.push(b));res.on('error',reject);res.on('end',()=>{try{const content=Buffer.concat(parts);done({status:res.statusCode,data:raw?content:parse(content),cookie:res.headers['set-cookie']?.[0]?.split(';')[0]});}catch(error){reject(error);}});});req.on('error',reject);req.end(value===undefined?undefined:JSON.stringify(value));});calls.push({path:path.split('?')[0],status:response.status});return response;}
async function login(name){const a=await call('/api/auth/login',{account:name,password:initial});assert.equal(a.status,200);const c=await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:a.cookie,csrf:a.data.csrf});assert.equal(c.status,200);return{cookie:c.cookie,csrf:c.data.csrf};}
function databases(path){return readdirSync(path,{withFileTypes:true}).flatMap(entry=>{if(entry.isDirectory())return databases(join(path,entry.name));if(entry.name.endsWith('.sqlite'))return[join(path,entry.name)];return[];});}
function db(){for(const path of databases(join(own,'.local/metadata'))){const database=new DatabaseSync(path);if(database.prepare("SELECT name FROM sqlite_master WHERE name='compile_jobs'").get())return database;database.close();}throw new Error('owned image SQL missing');}
const prefix='/api/fixture/image-jobs/',match=revision=>({'If-Match':'"'+revision+'"'});
try{
  process.stderr.write('image-jobs: actual fixed fullcopy\n');server=await startEditorBackend(configPath,{stageSource:true});const admin=await login('tianyi');assert.equal((await call('/api/admin/accounts',{account:'image_author'},admin)).status,200);const foreign=await login('image_author');assert.equal((await call('/api/admin/source/install',{},admin)).status,200);const source=(await call('/api/admin/source',undefined,admin)).data,copyKey=randomUUID();assert.equal((await call('/api/admin/copies',{registryId:source.definition.registryId,name:'持久圖稿',introduction:''},admin,{'Idempotency-Key':copyKey})).status,202);const copied=await call('/api/admin/copies/'+copyKey+'/run',{},admin,match('1'));assert.equal(copied.status,200,copied.data.error);const gameId=copied.data.gameId,value={gameId,draftRevision:'1',scope:'all'},key=randomUUID();
  assert.equal((await call(prefix+'enqueue',value)).status,401);assert.equal((await call(prefix+'enqueue',value,foreign)).status,403);assert.equal((await call(prefix+'enqueue',{...value,gameId:'wolong-builtin'},admin)).status,403);assert.equal((await call(prefix+'enqueue',{...value,scope:'chapter'},admin)).status,422);assert.equal((await call(prefix+'enqueue',{...value,valid:true},admin)).status,422);assert.equal((await call(prefix+'enqueue',{...value,gameId:[gameId]},admin)).status,422);const queued=await call(prefix+'enqueue',value,admin,{'Idempotency-Key':key});assert.equal(queued.status,200,queued.data.error);const job=queued.data;assert.equal((await call(prefix+'enqueue',value,admin,{'Idempotency-Key':key})).data.operationId,job.operationId);assert.equal((await call('/api/admin/accounts',{account:'not_created'},admin,{'Idempotency-Key':key})).status,409);assert.equal((await call('/api/games/'+gameId+'/draft/save',{metadata:{name:'新修訂圖稿',introduction:''},resourceEdits:[]},admin,match('1'))).status,200);assert.equal((await call(prefix+'enqueue',{...value,draftRevision:'2'},admin,{'Idempotency-Key':key})).status,409);const modified=(await call('/api/games',undefined,admin)).data.games[0].modifiedAt;checks.push('actual administrator-owned fixedcopy/source and permanent precise1 job while latest2 exists; authenticated role/builtin/array/scope/selfvalid and crossnamespace key guards');
  let database=db();database.exec('CREATE TRIGGER stop_image_stage AFTER UPDATE ON compile_jobs WHEN NEW.stage_cursor=1 AND OLD.stage_cursor=0 BEGIN UPDATE compile_jobs SET lease_until=0 WHERE job_id=NEW.job_id; END');database.close();process.stderr.write('image-jobs: checkpoint1 lease expiry\n');const stopped=await call(prefix+'run?id='+job.operationId,{},admin,match('1'));assert.equal(stopped.status,409,stopped.data.error);assert.equal(stopped.data.error,'JOB_LEASE_EXPIRED');const partial=(await call(prefix+'query?id='+job.operationId,undefined,admin)).data;assert.equal(partial.stage,1);assert.equal(partial.state,'running');assert.equal(partial.checkpoint.length,1);database=db();database.exec('DROP TRIGGER stop_image_stage');database.close();checks.push('actual six-image recomputation/full41source validation and real reportcheckpoint; SQL lease expires before remaining sixwrites, no ready/runtime claim');
  await server.close();server=null;server=await startEditorBackend(configPath);process.stderr.write('image-jobs: reconstruct after actual restart\n');const response=await call(prefix+'run?id='+job.operationId,{},admin,match(partial.rowRevision));assert.equal(response.status,200,response.data.error);const ready=response.data;assert.equal(ready.state,'ready');assert.equal(ready.stage,2);assert.equal(ready.attempt,2);assert.equal(ready.compilerRevision,'fixed-copy-images-2-indexed124-job-1');assert.equal(ready.checkpoint[0].digest,partial.checkpoint[0].digest);assert.equal((await call('/api/games',undefined,admin)).data.games[0].modifiedAt,modified);checks.push('actual restart drops brands/plans; SQL expired generation reclaimed, immutable1 source/profile/catalog rebuilt, oldreport R2 verified and sixPNG/checkpoint stored without game timestamp writes');
  const outputs=ready.checkpoint.flatMap(record=>record.outputs);assert.equal(outputs.length,7);let binding;const artifacts={};for(const output of outputs){const actual=await call(prefix+'artifact?id='+job.operationId+'&asset='+output.assetId,undefined,admin,{},true);assert.equal(actual.status,200);assert.equal(actual.data.length,output.byteLength);assert.equal(sha(actual.data),output.sha256);artifacts[output.assetId]=actual.data;if(output.assetId==='image_report')binding=parse(actual.data);}
  assert.equal(binding.operationId,job.operationId);assert.equal(binding.draftRevision,'1');assert.equal(binding.admission,'image-stage-outputs-only');assert.equal(Object.hasOwn(binding,'valid'),false);assert.equal(binding.sourceReport.missing.length,4);
  const oldPath='.dragon-analysis/editor-phase/backend-copy-images-session-r1/static-receipt-r1.json';assert.equal(sha(readFileSync(oldPath)),'612852830f3e04de8bce2163b646a2ed9cd1c4197c32586ef2cb31cf262af673');const old=parse(readFileSync(oldPath));for(const descriptor of binding.sourceReport.outputs){const pixel=decodePNG(artifacts[descriptor.assetId]);assert.equal(sha(pixel.pixels),descriptor.pixelSha256);assert.equal(pixel.width,descriptor.width);assert.equal(pixel.height,descriptor.height);const index=['atlas_spring','atlas_summer','atlas_autumn','atlas_winter','minimap_base','minimap_large'].indexOf(descriptor.assetId),path='.dragon-analysis/editor-phase/backend-copy-images-session-r1/images-r2/asset-'+(index+1)+'.png';assert.equal(sha(readFileSync(path)),old.historical[path]);assert.equal(sha(artifacts[descriptor.assetId]),sha(readFileSync(path)),descriptor.assetId);}checks.push('all7 actualR2 artifacts full length/SHA; sixPNG decodedRGBA/dimensions and exactbytes equal independently Pillow-verified protected prior siximages; binding exactjob/source1, notlatest/runtime or neworacle claim');
  const versionDb=db(),versionRow=versionDb.prepare('SELECT compiler_revision,pipeline_digest FROM compile_jobs WHERE job_id=?').get(job.operationId);versionDb.prepare('UPDATE compile_jobs SET compiler_revision=?,pipeline_digest=? WHERE job_id=?').run('fixed-copy-images-1-job-1',parse(readFileSync('.dragon-analysis/editor-phase/backend-image-jobs-session-r1/jobs-r1.stdout')).binding.pipelineDigest,job.operationId);versionDb.close();const oldVersion=await call(prefix+'query?id='+job.operationId,undefined,admin);assert.equal(oldVersion.status,409);assert.equal(oldVersion.data.error,'JOB_PIPELINE_CHANGED');assert.equal((await call(prefix+'run?id='+job.operationId,{},admin,match(ready.rowRevision))).status,409);const restoreVersion=db();restoreVersion.prepare('UPDATE compile_jobs SET compiler_revision=?,pipeline_digest=? WHERE job_id=?').run(versionRow.compiler_revision,versionRow.pipeline_digest,job.operationId);restoreVersion.close();assert.deepEqual((await call(prefix+'query?id='+job.operationId,undefined,admin)).data,ready);checks.push('owned persisted oldcompiler/oldpipeline tuple query/run409 with current PNG revision; no automatic oldJob relabel, explicit owned restore of exact newer tuple');
  process.stderr.write('image-jobs: ready/source checkpoint guards\n');assert.deepEqual((await call(prefix+'run?id='+job.operationId,{},admin,match(ready.rowRevision))).data,ready);assert.equal((await call(prefix+'run?id='+job.operationId,{},admin,match('1'))).status,409);database=db();const pristine=database.prepare('SELECT pipeline_digest,checkpoint_json FROM compile_jobs WHERE job_id=?').get(job.operationId),damaged=parse(pristine.checkpoint_json);damaged[0].digest='0'.repeat(64);database.prepare('UPDATE compile_jobs SET checkpoint_json=? WHERE job_id=?').run(JSON.stringify(damaged),job.operationId);database.close();const bad=await call(prefix+'run?id='+job.operationId,{},admin,match(ready.rowRevision));assert.equal(bad.status,503,bad.data.error);assert.equal(bad.data.error,'IMAGE_JOB_CHECKPOINT_CORRUPT');database=db();database.prepare('UPDATE compile_jobs SET checkpoint_json=?,pipeline_digest=? WHERE job_id=?').run(pristine.checkpoint_json,'0'.repeat(64),job.operationId);database.close();const pipeline=await call(prefix+'run?id='+job.operationId,{},admin,match(ready.rowRevision));assert.equal(pipeline.status,409);assert.equal(pipeline.data.error,'JOB_PIPELINE_CHANGED');database=db();database.prepare('UPDATE compile_jobs SET pipeline_digest=? WHERE job_id=?').run(pristine.pipeline_digest,job.operationId);database.close();checks.push('ready actual source reconstruction/readback without row writes; staleCAS, corruptcheckpoint and actualSQLpipeline binding rejected before acceptance');
  const control={operationId:job.operationId,assetId:'atlas_spring',action:'damage'};assert.equal((await call(prefix+'artifact-control',control,admin)).status,200);const corrupt=await call(prefix+'run?id='+job.operationId,{},admin,match(ready.rowRevision));assert.equal(corrupt.status,503,corrupt.data.error);assert.equal(corrupt.data.error,'BLOB_CORRUPT');assert.deepEqual((await call(prefix+'query?id='+job.operationId,undefined,admin)).data,ready);assert.equal((await call(prefix+'artifact-control',{...control,action:'restore'},admin)).status,200);assert.equal(sha((await call(prefix+'artifact?id='+job.operationId+'&asset=atlas_spring',undefined,admin,{},true)).data),sha(artifacts.atlas_spring));checks.push('nativeR2 same-size PNG damage fails fullbytes proof, leaves ready row unchanged/no blindrepair; explicit ownedfixture original restoration');
  assert.equal((await call(prefix+'query?id='+job.operationId,undefined,foreign)).status,403);assert.equal((await call(prefix+'artifact?id='+job.operationId+'&asset=atlas_spring',undefined,foreign)).status,403);assert.equal((await call('/api/games/'+gameId+'/compile',{},admin)).status,404);checks.push('actual author cannot read admin imageJob/artifact, production Rootcompiler remains404');
  process.stderr.write('image-jobs: real output-await epoch revocation\n');const epochKey=randomUUID(),epoch=(await call(prefix+'enqueue',{...value,draftRevision:'2'},admin,{'Idempotency-Key':epochKey})).data;assert.equal((await call(prefix+'arm',{},admin)).status,200);gateSession=admin;const pending=call(prefix+'run?id='+epoch.operationId,{},admin,match('1')).then(response=>({response}),error=>({error}));const deadline=Date.now()+240000;for(;;){const state=await call(prefix+'gate',undefined,admin);assert.equal(state.status,200);if(state.data.blocked)break;assert.ok(Date.now()<deadline,'actual output await must block');await new Promise(done=>setTimeout(done,250));}const changed=await call('/api/auth/password',{oldPassword:password,newPassword:password+'X'},admin);assert.equal(changed.status,200);const fresh={cookie:changed.cookie,csrf:changed.data.csrf};gateSession=fresh;assert.equal((await call(prefix+'release',{},fresh)).status,200);gateSession=null;const finished=await pending;if(finished.error)throw finished.error;assert.equal(finished.response.status,401,finished.response.data.error);assert.equal((await call(prefix+'query?id='+epoch.operationId,undefined,fresh)).data.error,'JOB_AUTH_REVOKED');assert.equal((await call(prefix+'enqueue',{...value,draftRevision:'2'},fresh,{'Idempotency-Key':epochKey})).status,409);database=db();const abandoned=database.prepare('SELECT state,stage_cursor,checkpoint_json FROM compile_jobs WHERE job_id=?').get(epoch.operationId);assert.equal(abandoned.state,'running');assert.equal(abandoned.stage_cursor,0);assert.equal(abandoned.checkpoint_json,'[]');assert.equal(database.prepare("SELECT COUNT(*) AS n FROM image_compile_objects WHERE operation_id=? AND state='verified'").get(epoch.operationId).n,0);database.close();assert.equal((await call('/api/games',undefined,fresh)).data.games[0].modifiedAt,modified);checks.push('real outputintent/BlobStore hold then password epoch revokes oldawait401; no verifiedoutput/checkpoint, freshsession cannot revive oldjob/key, no game timestamp changes');
  for(const[p,h]of Object.entries(sourceHashes))assert.equal(sha(readFileSync(p)),h,p);process.stdout.write(JSON.stringify({result:'PASS-REAL-PERSISTENT-FIXED-COPY-IMAGE-JOBS',checks,calls,sourceHashes,outputs:outputs.length,binding,limits:'Internal administrator own exact fixedsource two-stage image outputs only. No publiccompiler/data-image unified execution/runtime/fullfallback/Q69/Trial/Release/physicalGC/cloudSLA/goalcompletion; prior independentlyverified identicalPNG bytes reused honestly.'},null,2)+'\n');
}finally{if(server&&gateSession){try{await call(prefix+'release',{},gateSession);}catch{/* Only own pending fixture boundary is drained; original failure remains. */}}await server?.close();}
