// Same real authority/DO SQL/native R2. Small opaque snapshots/jobs are NOT gameplay or deletion completion.
import assert from 'node:assert/strict';
import { readFileSync,writeFileSync,mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve,join } from 'node:path';
import { randomBytes,randomUUID,createHash } from 'node:crypto';
import { request as httpsRequest } from 'node:https';
import { startEditorBackend } from './start_editor_backend.mjs';
const dir='.dragon-analysis/editor-phase/backend-deletion-fence-session-r1/',round=process.argv[2];assert.match(round??'',/^[1-9][0-9]{0,2}$/);const sha=b=>createHash('sha256').update(b).digest('hex');function json(b){try{return JSON.parse(b);}catch(cause){throw new Error('owned fence JSON',{cause});}}
const before=json(readFileSync(dir+'before.json')),protectedHashes={...before.inputs},changed=['metadata','drafts','copyimages','worker'];for(const n of changed)delete protectedHashes['server/'+n+'.js'];assert.equal(Object.keys(protectedHashes).length,447);for(const[p,h]of Object.entries(protectedHashes))assert.equal(sha(readFileSync(p)),h,p);
const paths=[...changed.map(n=>'server/'+n+'.js'),'server/deletionfence.js','tools/verify_editor_backend_deletion_fence.mjs',dir+'fixture-worker.js'],sourceHashes=Object.fromEntries(paths.map(p=>[p,sha(readFileSync(p))]));
const own=mkdtempSync(join(tmpdir(),'dragon-fence-')),origin='https://127.0.0.1:8787',initial=randomBytes(24).toString('hex'),password=randomBytes(24).toString('hex'),config=json(readFileSync('server/wrangler.jsonc'));config.main=resolve(dir+'fixture-worker.js');const configPath=join(own,'wrangler.jsonc');writeFileSync(configPath,JSON.stringify(config),{flag:'wx'});writeFileSync(join(own,'.dev.vars'),'EDITOR_DEFAULT_PASSWORD='+JSON.stringify(initial)+'\nEDITOR_REQUEST_KEY='+JSON.stringify(randomBytes(32).toString('hex'))+'\n',{flag:'wx',mode:0o600});
let server;const calls=[],checks=[];
async function call(path,value,session,extra={}){const headers={Origin:origin,...extra};if(session){headers.Cookie=session.cookie;headers['X-CSRF-Token']=session.csrf;}if(value!==undefined){headers['Content-Type']='application/json';headers['Idempotency-Key']??=randomUUID();}const r=await new Promise((done,reject)=>{const req=httpsRequest(origin+path,{method:value===undefined?'GET':'POST',headers,agent:false,rejectUnauthorized:false},res=>{const parts=[];res.on('data',b=>parts.push(b));res.on('error',reject);res.on('end',()=>{try{done({status:res.statusCode,data:json(Buffer.concat(parts)),cookie:res.headers['set-cookie']?.[0]?.split(';')[0]});}catch(error){reject(error);}});});req.on('error',reject);req.end(value===undefined?undefined:JSON.stringify(value));});calls.push({path,status:r.status});return r;}
const fixture=(v,s,key)=>call('/api/test/fence',v,s,key?{'Idempotency-Key':key}:{}),ok=async(v,s,key)=>{const r=await fixture(v,s,key);assert.equal(r.status,200,r.data.error);return r.data.result;};
async function login(name){const a=await call('/api/auth/login',{account:name,password:initial});assert.equal(a.status,200);const b=await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:a.cookie,csrf:a.data.csrf});assert.equal(b.status,200);return{cookie:b.cookie,csrf:b.data.csrf,user:b.data.user};}
async function waiting(admin){for(let n=0;n<200;n++){if((await ok({action:'control'},admin)).waiting)return;await new Promise(done=>setTimeout(done,10));}throw new Error('owned awaited port did not pause');}
function input(game){return{gameId:game.gameId,expectedRowRevision:'1',confirmationName:game.metadata.name};}
try{
 server=await startEditorBackend(configPath);const admin=await login('tianyi');for(const name of ['fence_a','fence_b'])assert.equal((await call('/api/admin/accounts',{account:name},admin)).status,200);const a=await login('fence_a'),b=await login('fence_b');
 const creationKey=randomUUID(),create={action:'create',metadata:{name:'栅欄來源',introduction:'opaque only'}},game=await ok(create,a,creationKey);const rows=await ok({action:'rows',gameId:game.gameId},admin),descriptor={sha256:rows.snapshots[0].source_digest,byteLength:257};assert.equal(rows.fence,null);assert.equal(rows.snapshots.length,1);assert.equal((await ok({action:'direct-blob',gameId:game.gameId,descriptor},a)).byteLength,257);checks.push('real author-owned engineering opaque257byte nativeR2 and SQLsnapshot; realauth distinctauthors/admin, no normaltemplate or gameplay semantics');
 assert.equal((await fixture({action:'begin',input:input(game)})).status,401);assert.equal((await fixture({action:'begin',input:input(game)},b)).status,404);assert.equal((await fixture({action:'begin',input:{...input(game),gameId:'wolong-builtin'}},admin)).status,403);for(const bad of [{...input(game),expectedRowRevision:'2'},{...input(game),confirmationName:'別名'},{...input(game),expectedRowRevision:[1]},{...input(game),extra:true}])assert.ok([409,422].includes((await fixture({action:'begin',input:bad},a)).status));assert.equal((await fixture({action:'begin',input:input(game)},a,creationKey)).status,409);
 await ok({action:'listed',gameId:game.gameId,listed:true},admin);assert.equal((await fixture({action:'begin',input:input(game)},admin)).data.error,'GAME_LISTED');await ok({action:'listed',gameId:game.gameId,listed:false},admin);assert.equal((await ok({action:'rows',gameId:game.gameId},admin)).fence,null);checks.push('actual principal/builtin/foreign/notlisted/rowCAS/exactname/strictfields and existing metadata key fence; failed checks add nofence');
 await ok({action:'fault',enabled:true},admin);const failureKey=randomUUID(),failed=await fixture({action:'begin',input:input(game)},a,failureKey);assert.equal(failed.status,500);await ok({action:'fault',enabled:false},admin);assert.deepEqual(await ok({action:'rows',gameId:game.gameId},admin),rows);checks.push('actual SQLite receipt insert trigger failure rolls rowCAS/fence/audit/key back together, bytes/snapshot remain');
 await ok({action:'prepare',gameId:game.gameId},a);const fenceKey=randomUUID(),pair=await Promise.all([fixture({action:'begin',input:input(game)},a,fenceKey),fixture({action:'begin',input:input(game)},a,fenceKey)]);assert.deepEqual(pair.map(x=>x.status),[200,200]);assert.deepEqual(pair[0].data,pair[1].data);const fence=pair[0].data.result;assert.equal(fence.state,'fenced');assert.equal(fence.rowRevision,'2');assert.equal((await fixture({action:'begin',input:input(game)},a)).data.error,'GAME_DELETING');assert.equal((await fixture({action:'begin',input:{...input(game),confirmationName:'更改'}},a,fenceKey)).status,409);assert.deepEqual(await ok({action:'query',key:fenceKey},a),fence);assert.equal((await fixture({action:'query',key:fenceKey},b)).status,404);assert.equal((await fixture({action:'commit'},a)).data.error,'GAME_DELETING');assert.equal((await fixture({action:'replay-create',request:create},a,creationKey)).data.error,'GAME_DELETING'); // Original persisted create receipt is rechecked, no new allocation/I/O.
 assert.equal((await fixture({action:'direct-blob',gameId:game.gameId,descriptor},a)).data.error,'GAME_DELETING');assert.equal((await fixture({action:'direct-blob',gameId:game.gameId,descriptor},admin)).status,404);for(const foreign of [b,admin])assert.equal((await fixture({action:'prepare',gameId:game.gameId},foreign)).status,404);assert.equal((await fixture({action:'allocation',gameId:game.gameId},a)).data.error,'GAME_DELETING');const fencedRows=await ok({action:'rows',gameId:game.gameId},admin);assert.equal(fencedRows.game.modified_at,rows.game.modified_at);assert.equal(fencedRows.game.row_revision,'2');assert.deepEqual(fencedRows.snapshots,rows.snapshots);assert.equal(fencedRows.operations.length,1);assert.ok(!JSON.stringify(fencedRows.operations).includes(game.metadata.name));checks.push('samekey actual concurrent requests one permanent minimalfencedreceipt; differentkey rejects; preparedcommit/read/oldallocation denied, rowrevision-only/contenttime+snapshots remain; not deletion completion');
 // Independent port pauses: actual R2 GET/PUT or actual checkpoint byte-verifier has run, then fence commits.
 for(const action of ['blob','put','prepare-hold','checkpoint']){
  const g=await ok({action:'create',metadata:{name:'待'+action.slice(0,5),introduction:''},marker:action.length},a);let job;if(action==='checkpoint')job=await ok({action:'job',gameId:g.gameId},a);const pending=fixture({action,gameId:g.gameId,id:job?.operationId},a);await waiting(admin);const result=await ok({action:'begin',input:input(g)},a);assert.equal(result.state,'fenced');await ok({action:'release'},admin);const late=await pending;assert.equal(late.status,409,action+':'+late.data.error);assert.equal(late.data.error,'GAME_DELETING');const actual=await ok({action:'rows',gameId:g.gameId},admin);assert.equal(actual.snapshots.length,1);assert.equal(actual.game.draft_revision,'1');if(job){assert.equal(actual.jobs[0].state,'running');assert.equal(actual.jobs[0].checkpoint_json,'[]');assert.equal((await fixture({action:'job-query',id:job.operationId},a)).data.error,'GAME_DELETING');}
 }checks.push('four separate controlled actualGET/nativePUT/snapshot-verifier/opaquecheckpoint awaits then fence: late return/prepare/commit denied; no new snapshot/checkpoint. Native PUT may have left private orphan; no physicalrollback or cleanup claim');
 const cross=await ok({action:'create',metadata:{name:'管理刪除',introduction:''}},b),crossKey=randomUUID();assert.equal((await fixture({action:'direct-blob',gameId:cross.gameId,descriptor},admin)).status,404);const managed=await ok({action:'begin',input:input(cross)},admin,crossKey);assert.equal(managed.state,'fenced');assert.equal((await fixture({action:'direct-blob',gameId:cross.gameId,descriptor},b)).data.error,'GAME_DELETING');assert.equal((await fixture({action:'direct-blob',gameId:cross.gameId,descriptor},admin)).status,404);assert.equal((await call('/api/admin/accounts',{account:'never_created'},admin,{'Idempotency-Key':crossKey})).status,409);assert.equal((await call('/api/games/'+game.gameId,{},a)).status,404);checks.push('actual admin crossauthor management fence without privateblob read grant; globalRoot auth/key cannotreuse deletekey; no publicdelete endpoint opens');
 await server.close();server=undefined;server=await startEditorBackend(configPath);assert.deepEqual(await ok({action:'query',key:fenceKey},a),fence);assert.equal((await fixture({action:'direct-blob',gameId:game.gameId,descriptor},a)).data.error,'GAME_DELETING');const persisted=await ok({action:'rows',gameId:game.gameId},admin);assert.equal(persisted.fence.fence_revision,'2');assert.equal(persisted.operations.length,1);checks.push('actual restart retains same SQLfence/minimalreceipt and does not revive byte access; processcaps lost; names/snapshot/bytes intentionally retained pending cleanup');
 const changed=await call('/api/auth/password',{oldPassword:password,newPassword:randomBytes(24).toString('hex')},a);assert.equal(changed.status,200);const renewed={cookie:changed.cookie,csrf:changed.data.csrf,user:changed.data.user};assert.equal((await fixture({action:'query',key:fenceKey},a)).status,401);assert.equal((await fixture({action:'query',key:fenceKey},renewed)).data.error,'OPERATION_REVOKED');assert.equal((await fixture({action:'begin',input:input(game)},renewed,fenceKey)).data.error,'OPERATION_REVOKED');assert.equal((await fixture({action:'direct-blob',gameId:game.gameId,descriptor},renewed)).data.error,'GAME_DELETING');checks.push('actual password epoch revocation denies oldcookie/replay under newepoch but permanent fence remains; no undelete, objectdelete/backup/runtime/Trial/publicrelease guarantee');
 for(const[p,h]of Object.entries({...protectedHashes,...sourceHashes}))assert.equal(sha(readFileSync(p)),h,p);process.stdout.write(JSON.stringify({result:'PASS-ACTUAL-PERSISTENT-DELETION-FENCE-NOT-CLEANUP',checks,calls,sourceHashes,protectedInputs:447,limits:'Internal fence and current SQL/R2/save/Job authority boundaries only. Engineering opaque refs/jobs, no complete GameSource/create/delete/release/Trial/physicalcleanup/sharedrefs/backups/cloudSLA/maincompletion.'},null,2)+'\n');
}catch(error){writeFileSync(dir+'failure-r'+round+'.json',JSON.stringify({checks,calls,sourceHashes,error:{message:String(error.message).slice(0,500),code:error.code??null}},null,2)+'\n',{flag:'wx'});throw error;}finally{await server?.close();}
