// Actual default Root, own SQLite/R2 and fresh Chromium. Response controls are browser-only.
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { randomBytes, randomUUID, createHash } from 'node:crypto';
import { request as httpsRequest } from 'node:https';
import { pathToFileURL } from 'node:url';
import { startEditorBackend } from './start_editor_backend.mjs';
const round = process.argv[2]; assert.ok(/^[1-9][0-9]{0,2}$/.test(round));
const dir = '.dragon-analysis/editor-phase/backend-stage-ui-session-r1/', own = mkdtempSync(join(tmpdir(), 'dragon-stage-ui-')), origin = 'https://127.0.0.1:8787', sha = bytes => createHash('sha256').update(bytes).digest('hex');
function parse(bytes) { try { return JSON.parse(bytes); } catch (cause) { throw new Error('invalid owned UI JSON', { cause }); } }
const config = parse(readFileSync('server/wrangler.jsonc')), initial = randomBytes(24).toString('hex'), password = randomBytes(24).toString('hex'), requestKey = randomBytes(32).toString('hex'); config.main = resolve('server/worker.js'); writeFileSync(join(own, 'wrangler.jsonc'), JSON.stringify(config)); writeFileSync(join(own, '.dev.vars'), 'EDITOR_DEFAULT_PASSWORD=' + JSON.stringify(initial) + '\nEDITOR_REQUEST_KEY=' + JSON.stringify(requestKey) + '\n', { flag: 'wx', mode: 0o600 });
const paths = ['server/worker.js','server/public/client.txt','server/public/draft.txt','server/public/index.html','server/public/stage.txt','tools/verify_editor_backend_stage_ui.mjs'], sourceHashes = Object.fromEntries(paths.map(p => [p, sha(readFileSync(p))])), calls = [], checks = [], downloads = []; let server, browser;
async function call(path, value, session, extra = {}) {
  const headers = { Origin: origin, ...extra }; if (session) { headers.Cookie = session.cookie; headers['X-CSRF-Token'] = session.csrf; } if (value !== undefined) { headers['Content-Type'] = 'application/json'; headers['Idempotency-Key'] ??= randomUUID(); }
  const response = await new Promise((done,reject) => { const req = httpsRequest(origin+path, { method: value === undefined ? 'GET' : 'POST', headers, rejectUnauthorized: false }, res => { const parts = []; res.on('data',bytes=>parts.push(bytes)); res.on('error',reject); res.on('end',()=>{ try { done({ status:res.statusCode, data:parse(Buffer.concat(parts)), cookie:res.headers['set-cookie']?.[0]?.split(';')[0] }); } catch(error) { reject(error); } }); }); req.on('error',reject); req.end(value === undefined ? undefined : JSON.stringify(value)); }); calls.push({path,status:response.status}); return response;
}
async function wait(page) { await page.waitForFunction(() => !document.querySelector('#draft-games-refresh').disabled, undefined, { timeout:300000 }); }
async function draft(page) { await page.locator('#draft-games-refresh').click(); await page.waitForFunction(()=>document.querySelector('#draft-game').options.length===1 && !document.querySelector('#draft-games-refresh').disabled); await page.locator('#draft-revision').fill('1'); await page.locator('#draft-load').click(); await page.waitForFunction(()=>document.querySelector('#draft-context').textContent.includes('已保存修訂 1') && !document.querySelector('#draft-name').disabled,undefined,{timeout:300000}); }
async function download(page, selector, label) { const event=page.waitForEvent('download',{timeout:300000}); await selector.click(); const file=await event, stream=await file.createReadStream(); assert.ok(stream); const parts=[]; for await(const bytes of stream)parts.push(bytes); const bytes=Buffer.concat(parts),path=dir+'download-r'+round+'-'+label+'.bin'; assert.equal(existsSync(path),false); writeFileSync(path,bytes,{flag:'wx'}); downloads.push({path,sha256:sha(bytes),byteLength:bytes.length}); await wait(page); return bytes; }
try {
  process.stderr.write('stage-ui: setup actual Root\n'); server=await startEditorBackend(join(own,'wrangler.jsonc'),{stageSource:true}); const login=await call('/api/auth/login',{account:'tianyi',password:initial}); assert.equal(login.status,200); const changed=await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:login.cookie,csrf:login.data.csrf}); assert.equal(changed.status,200); const admin={cookie:changed.cookie,csrf:changed.data.csrf}; assert.equal((await call('/api/admin/accounts',{account:'stage_viewer'},admin)).status,200); const foreignLogin=await call('/api/auth/login',{account:'stage_viewer',password:initial}); assert.equal(foreignLogin.status,200); const foreignChanged=await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:foreignLogin.cookie,csrf:foreignLogin.data.csrf}); assert.equal(foreignChanged.status,200); assert.equal((await call('/api/admin/source/install',{},admin)).status,200); const source=(await call('/api/admin/source',undefined,admin)).data,copyKey=randomUUID(); assert.equal((await call('/api/admin/copies',{registryId:source.definition.registryId,name:'<img>',introduction:''},admin,{'Idempotency-Key':copyKey})).status,202); const copied=await call('/api/admin/copies/'+copyKey+'/run',{},admin,{'If-Match':'"1"'}); assert.equal(copied.status,200); const gameId=copied.data.gameId, before=(await call('/api/games',undefined,admin)).data.games[0];
  const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href); browser=await chromium.launch({headless:true}); const context=await browser.newContext({ignoreHTTPSErrors:true,acceptDownloads:true,viewport:{width:1280,height:1100}}),errors=[],outside=[],expected=[],posts=[];
  await context.addInitScript(()=>Object.defineProperty(globalThis,'indexedDB',{get(){globalThis.__idbAccess=(globalThis.__idbAccess??0)+1;throw new Error('IDB forbidden');}})); await context.route('**/*',route=>{if(new URL(route.request().url()).origin!==origin){outside.push('outside');return route.abort();}return route.continue();});
  const page=await context.newPage(); let downloadCount=0, revokedQueryPath=null; page.on('download',()=>downloadCount++); page.on('pageerror',error=>errors.push(error.message)); page.on('console',message=>{if(message.type()!=='error')return;const path=new URL(message.location().url||origin).pathname,text=message.text();if(path==='/api/session'&&text.includes('401')||path==='/favicon.ico'&&text.includes('404')||path.includes('/stage-jobs/')&&text.includes('net::ERR_FAILED')||path===revokedQueryPath&&text.includes('409'))expected.push({path,text});else errors.push(text);}); page.on('request',request=>{const path=new URL(request.url()).pathname;if(request.method()==='POST'&&path.includes('/stage-jobs/'))posts.push({path,key:request.headers()['idempotency-key'],revision:request.headers()['if-match'],body:parse(request.postData())});});
  await page.goto(origin); await page.locator('#login [name=account]').fill('tianyi'); await page.locator('#login [name=password]').fill(password); await page.locator('#login button').click(); await page.locator('#stage-editor').waitFor({state:'visible'}); await wait(page); assert.equal(await page.locator('#stage-create').isDisabled(),true); await draft(page); assert.equal(await page.locator('#draft-game img').count(),0); checks.push('actual fresh authenticated UI: stage disabled until exact private saved1 read, author labels textContent, no trial/publish controls');
  await page.locator('#draft-name').fill('未保存'); page.once('dialog',dialog=>dialog.dismiss()); await page.locator('#stage-create').click(); await wait(page); assert.equal(posts.length,0); assert.equal(await page.locator('#draft-name').inputValue(),'未保存');
  const dataURL=origin+'/api/games/'+gameId+'/stage-jobs/data'; await page.route(dataURL,async route=>{const response=await route.fetch({timeout:300000});assert.equal(response.status(),202);await route.abort();}); page.once('dialog',dialog=>dialog.accept()); await page.locator('#stage-create').click(); await page.waitForFunction(()=>!document.querySelector('#stage-query').disabled,undefined,{timeout:300000}); assert.equal(await page.locator('#stage-create').isDisabled(),true); assert.deepEqual(posts[0].body,{draftRevision:'1',scope:'all'}); await page.unroute(dataURL); page.once('dialog',dialog=>dialog.accept()); await page.reload(); await page.locator('#stage-editor').waitFor({state:'visible'}); await wait(page); assert.equal(posts.length,1); assert.equal(await page.locator('#stage-run').isDisabled(),true); page.once('dialog',dialog=>dialog.accept()); await page.locator('#stage-query').click(); await page.waitForFunction(()=>document.querySelector('#stage-task').textContent.includes('queued')&&!document.querySelector('#stage-run').disabled); assert.equal(posts.length,2); assert.equal(posts[0].key,posts[1].key); assert.equal(await page.locator('#draft-name').isDisabled(),true); await draft(page); await page.locator('#draft-name').fill('未保存');
  const association=await page.evaluate(()=>Object.entries(sessionStorage).filter(([key])=>key.startsWith('editor-stage-jobs:')).map(([,value])=>JSON.parse(value))); assert.equal(association.length,1); const dataId=association[0].data.id; assert.deepEqual(Object.keys(association[0].data).sort(),['command','draftRevision','enqueueKey','gameId','id','purpose']); checks.push('dirty cancel no POST; lost actual202 then explicit reload preserves complete original association, no automaticPOST; explicit confirmation reuses original key/body, no implicit save');
  process.stderr.write('stage-ui: actual data run/lost reply\n'); const runURL=dataURL+'/'+dataId+'/run'; await page.route(runURL,async route=>{const response=await route.fetch({timeout:300000});assert.equal(response.status(),200);await route.abort();}); page.once('dialog',dialog=>dialog.accept()); await page.locator('#stage-run').click(); await page.waitForFunction(()=>document.querySelector('#stage-status').textContent.includes('階段操作未確認')&&!document.querySelector('#stage-query').disabled,undefined,{timeout:300000}); assert.equal(await page.locator('#stage-run').isDisabled(),true); await page.unroute(runURL); const count=posts.length; const commandKeys=await page.evaluate(()=>Object.entries(sessionStorage).filter(([key])=>key.startsWith('editor-stage-jobs:')).map(([,value])=>Object.keys(JSON.parse(value).data.command).sort())); assert.deepEqual(commandKeys,[['action','key','revision']]); page.once('dialog',dialog=>dialog.accept()); await page.reload(); await page.locator('#stage-editor').waitFor({state:'visible'}); await wait(page); assert.equal(posts.length,count); assert.equal(await page.locator('#stage-run').isDisabled(),true); await page.locator('#stage-query').click(); await page.waitForFunction(()=>document.querySelector('#stage-task').textContent.includes('ready')&&!document.querySelector('#stage-query').disabled); assert.equal(posts.length,count); assert.equal(await page.locator('#stage-artifacts button').count(),29); assert.equal(await page.locator('#draft-name').isDisabled(),true); await draft(page); await page.locator('#draft-name').fill('未保存'); const dataJob=(await call('/api/games/'+gameId+'/stage-jobs/data/'+dataId,undefined,admin)).data.job,terrain=dataJob.checkpoint.flatMap(record=>record.outputs).find(item=>item.assetId==='terrain_0'); checks.push('actual data29 ready after dropped command reply+reload with exact original commandkey/CAS restored; explicitGET only, no autorun/newcommand, saved metadata untouched; stage-only');
  process.stderr.write('stage-ui: actual artifact download and client corruption guard\n'); const terrainButton=page.locator('#stage-artifacts p').filter({hasText:'terrain_0／'}).locator('button'); const actual=await download(page,terrainButton,'terrain'); assert.equal(actual.length,terrain.byteLength); assert.equal(sha(actual),terrain.sha256); const artifactURL=dataURL+'/'+dataId+'/artifacts/terrain_0'; await page.route(artifactURL,async route=>{const response=await route.fetch({timeout:300000}),bytes=Buffer.from(await response.body());assert.equal(response.status(),200);bytes[0]^=1;await route.fulfill({response,body:bytes});}); const previousDownloads=downloadCount; await terrainButton.click(); await page.waitForFunction(()=>document.querySelector('#stage-status').textContent.includes('不建立檔案')&&!document.querySelector('#stage-query').disabled,undefined,{timeout:300000}); assert.equal(downloadCount,previousDownloads); await page.unroute(artifactURL); await page.route(artifactURL,async route=>{const response=await route.fetch({timeout:300000}); assert.equal(response.status(),200); await route.fulfill({response,headers:{...response.headers(),'x-content-sha256':'0'.repeat(64)}});}); await terrainButton.click(); await page.waitForFunction(()=>document.querySelector('#stage-status').textContent.includes('不建立檔案')&&!document.querySelector('#stage-query').disabled,undefined,{timeout:300000}); assert.equal(downloadCount,previousDownloads); await page.unroute(artifactURL); checks.push('actual ready artifact streamed to owned download and fullSHA/length checked; browser-only byteflip and separately wrong fullSHA header rejected before creating another download');
  page.once('dialog',dialog=>dialog.accept()); await page.reload(); await page.locator('#stage-editor').waitFor({state:'visible'}); await wait(page); assert.equal(posts.length,count); assert.equal(await page.locator('#stage-run').isDisabled(),true); assert.equal(await page.locator('#stage-artifacts button').count(),0); await page.locator('#stage-query').click(); await page.waitForFunction(()=>document.querySelector('#stage-task').textContent.includes('ready')&&!document.querySelector('#stage-query').disabled); assert.equal(posts.length,count); assert.equal(await page.locator('#stage-artifacts button').count(),29); checks.push('reload preserves only complete fixed association, not credentials/source/output; no automatic POST/artifact, explicit query rebuilds UI facts without latest switching');
  process.stderr.write('stage-ui: actual image job\n'); await draft(page); await page.locator('#stage-purpose').selectOption('images'); await page.locator('#stage-create').click(); await page.waitForFunction(()=>document.querySelector('#stage-task').textContent.includes('queued')&&!document.querySelector('#stage-run').disabled); page.once('dialog',dialog=>dialog.accept()); await page.locator('#stage-run').click(); await page.waitForFunction(()=>document.querySelector('#stage-task').textContent.includes('ready')&&!document.querySelector('#stage-query').disabled,undefined,{timeout:300000}); assert.equal(await page.locator('#stage-artifacts button').count(),7); const imageAssociation=await page.evaluate(()=>Object.entries(sessionStorage).filter(([key])=>key.startsWith('editor-stage-jobs:')).map(([,value])=>JSON.parse(value))[0].images),imageJob=(await call('/api/games/'+gameId+'/stage-jobs/images/'+imageAssociation.id,undefined,admin)).data.job,mini=imageJob.checkpoint.flatMap(record=>record.outputs).find(item=>item.assetId==='minimap_base'); const miniBytes=await download(page,page.locator('#stage-artifacts p').filter({hasText:'minimap_base／'}).locator('button'),'minimap'); assert.equal(sha(miniBytes),mini.sha256); assert.equal(sha(miniBytes),sha(readFileSync('.dragon-analysis/editor-phase/backend-copy-images-session-r1/images-r2/asset-5.png'))); const after=(await call('/api/games',undefined,admin)).data.games[0]; assert.equal(after.draftRevision,'1'); assert.equal(after.modifiedAt,before.modifiedAt); assert.equal(after.metadata.name,'<img>'); checks.push('actual separate image7 ready and ownedmini download equals prior independent pixel-certified PNG; all stages/downloads leave saved1/metadata/modifiedAt unchanged');
  const foreignContext=await browser.newContext({ignoreHTTPSErrors:true}),foreignPage=await foreignContext.newPage(); foreignPage.on('pageerror',error=>errors.push(error.message)); await foreignContext.route('**/*',route=>{if(new URL(route.request().url()).origin!==origin){outside.push('outside');return route.abort();}return route.continue();}); await foreignContext.addInitScript(()=>Object.defineProperty(globalThis,'indexedDB',{get(){globalThis.__idbAccess=(globalThis.__idbAccess??0)+1;throw new Error('IDB forbidden');}})); await foreignPage.goto(origin); await foreignPage.locator('#login [name=account]').fill('stage_viewer'); await foreignPage.locator('#login [name=password]').fill(password); await foreignPage.locator('#login button').click(); await foreignPage.locator('#stage-editor').waitFor({state:'visible'}); await wait(foreignPage); assert.equal(await foreignPage.locator('#stage-purpose [value=images]').evaluate(option=>option.disabled),true); assert.equal(await foreignPage.locator('#stage-create').isDisabled(),true); assert.equal(await foreignPage.locator('#stage-artifacts button').count(),0); assert.equal(await foreignPage.evaluate(()=>globalThis.__idbAccess??0),0); await foreignContext.close(); checks.push('actual separate author cannot select administrator images, sees no other-owner association/inputs/outputs; server gates remain authority');
  process.stderr.write('stage-ui: actual password/epoch UI invalidation\n'); revokedQueryPath='/api/games/'+gameId+'/stage-jobs/images/'+imageAssociation.id; const nextPassword=randomBytes(24).toString('hex'); await page.locator('#password [name=oldPassword]').fill(password); await page.locator('#password [name=newPassword]').fill(nextPassword); await page.locator('#password [name=confirmPassword]').fill(nextPassword); await page.locator('#password button').click(); await page.waitForFunction(()=>document.querySelector('#stage-status').textContent.includes('實際改密已撤銷')&&!document.querySelector('#draft-games-refresh').disabled,undefined,{timeout:300000}); assert.equal(await page.locator('#stage-run').isDisabled(),true); assert.equal(await page.locator('#stage-artifacts button:not([disabled])').count(),0); const actualEpochResponse=page.waitForResponse(response=>response.url()===origin+'/api/games/'+gameId+'/stage-jobs/images/'+imageAssociation.id&&response.request().method()==='GET'); await page.locator('#stage-query').click(); assert.equal((await actualEpochResponse).status(),409); await wait(page); assert.equal(await page.locator('#stage-create').isDisabled(),false); checks.push('actual password success revokes oldepoch, disables old run/download; actual oldjob query409 cannot revive it, explicit newreservation allowed without deleting old artifacts');
  assert.equal(await page.evaluate(()=>globalThis.__idbAccess??0),0); assert.deepEqual(outside,[]); assert.deepEqual(errors,[]); const shot=dir+'ui-r'+round+'.png'; writeFileSync(shot,await page.screenshot({fullPage:true}),{flag:'wx'}); for(const[p,h]of Object.entries(sourceHashes))assert.equal(sha(readFileSync(p)),h,p); process.stdout.write(JSON.stringify({result:'PASS-REAL-ROOT-STAGE-UI-SCOPED',checks,calls,posts,sourceHashes,downloads,screenshot:shot,screenshotSha:sha(readFileSync(shot)),expected,errors,outside,limits:'Actual default Root/SQL/R2/fresh Chromium stage operations/downloads; no automatic save, runtime/Q69/Trial/Release/full goal completion, no cloudSLA.'},null,2)+'\n');
} finally { await browser?.close(); await server?.close(); }
