import assert from 'node:assert/strict';import {createHash,webcrypto} from 'node:crypto';import {readFileSync,writeFileSync} from 'node:fs';import {createPrivateAudioContext} from '../web/src/content/privateaudio.js';
const d='.dragon-analysis/editor-phase/backend-private-audio-decode-session-r1/',round=process.argv[2];assert.match(round??'',/^[1-9][0-9]{0,2}$/);const sha=b=>createHash('sha256').update(b).digest('hex'),reference={gameId:'12345678-abcd-4123-8123-123456789abc',draftRevision:'1',sourceDigest:'a'.repeat(64),dependencyDigest:'b'.repeat(64)},checks=[];
function wav(){const b=new Uint8Array(52),v=new DataView(b.buffer);for(const[p,t]of [[0,'RIFF'],[8,'WAVE'],[12,'fmt '],[36,'data']])for(let i=0;i<t.length;i++)b[p+i]=t.charCodeAt(i);v.setUint32(4,44,true);v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,8000,true);v.setUint32(28,16000,true);v.setUint16(32,2,true);v.setUint16(34,16,true);v.setUint32(40,8,true);return b;}
function flac(samples=4,rate=8000,channels=1){const b=new Uint8Array(43);b.set([102,76,97,67,128,0,0,34]);new DataView(b.buffer).setBigUint64(18,(BigInt(rate)<<44n)|(BigInt(channels-1)<<41n)|(15n<<36n)|BigInt(samples));return b;}
function setup(raw=wav(),mime='audio/wav',options={}){const requests=[],calls=[];let revoked=false;const locator={kind:'private-library',gameId:reference.gameId,draftRevision:'1',sourceDigest:reference.sourceDigest,assetId:'library-194',registryId:'approved-available-library-76cdf28-1',catalogRoot:'c'.repeat(64),logicalURL:mime==='audio/flac'?'grf/music/loops/BGM_04.flac':'grf/sfx/ynsound-record13.wav',mime,sha256:sha(raw),byteLength:raw.length};const audioContext={sampleRate:8000,state:'suspended',async decodeAudioData(bytes){calls.push(bytes);if(options.decoder)return options.decoder(bytes);return {sampleRate:8000,numberOfChannels:1,length:4,duration:4/8000,getChannelData:()=>new Float32Array(4)};}};const headers=new Headers({'x-game-id':reference.gameId,'x-draft-revision':'1','x-source-sha256':reference.sourceDigest,'x-dependency-sha256':reference.dependencyDigest,'x-content-sha256':locator.sha256,'cache-control':'no-store','content-type':'application/octet-stream','x-content-admission':'private-available-bytes-only','x-library-root':locator.catalogRoot});const context=createPrivateAudioContext(reference,{audioContext,subtle:webcrypto.subtle,assertCurrent(){if(revoked)throw new Error('revoked');},async fetcher(path,init){requests.push({path,init});return new Response(raw,{status:options.status??200,headers});}});return {context,locator,audioContext,requests,calls,revoke(){revoked=true;}};}
async function rejected(f,code){await assert.rejects(f,e=>e.message===code);checks.push(code);}
const first=setup();const a=await first.context.readAudio(first.locator);assert.equal(a.length,4);assert.ok(Object.isFrozen(a));assert.equal(a.buffer.sampleRate,8000);a.dispose();a.dispose();const second=await first.context.readAudio(first.locator);assert.equal(first.requests.length,2);assert.notEqual(second.buffer,a.buffer);assert.equal(first.requests[0].path,'/api/games/'+reference.gameId+'/draft/library-assets/library-194?revision=1');assert.equal(first.requests[0].init.credentials,'same-origin');assert.equal(first.requests[0].init.redirect,'error');assert.deepEqual(['runtimeAllowed','trialAllowed','releaseAllowed','deleteAllowed'].map(k=>first.context[k]),[false,false,false,false]);checks.push('WAV fresh GET and detached own handle/no playback/loop/admission');await rejected(()=>first.context.readAudio(first.locator),'PRIVATE_AUDIO_OWNED_BUDGET');first.context.close();assert.equal(first.audioContext.state,'suspended');await rejected(()=>first.context.readAudio(first.locator),'PRIVATE_AUDIO_CLOSED');
const f=setup(flac(),'audio/flac');const fh=await f.context.readAudio(f.locator);assert.equal(fh.numberOfChannels,1);fh.dispose();f.context.close();checks.push('FLAC STREAMINFO parsed, native decoder owns frame decoding');
for(const mutate of [x=>({...x,mime:'image/png'}),x=>({...x,logicalURL:1}),x=>({...x,kind:'private-stage'}),x=>({...x,logicalURL:'grf/music/test.mp3'}),x=>({...x,logicalURL:{endsWith(){throw new Error('unsafe');}}})]){const s=setup();await rejected(()=>s.context.readAudio(mutate(s.locator)),'PRIVATE_AUDIO_FORMAT');assert.equal(s.requests.length,0);}
let touched=0;const getter=setup(),x={...getter.locator};Object.defineProperty(x,'mime',{get(){touched++;return 'audio/wav';},enumerable:true});await rejected(()=>getter.context.readAudio(x),'PRIVATE_AUDIO_LOCATOR');assert.equal(touched,0);
const foreign=setup();await rejected(()=>foreign.context.readAudio({...foreign.locator,sourceDigest:'d'.repeat(64)}),'PRIVATE_BYTES_CONTEXT');assert.equal(foreign.requests.length,0);
for(const [change,code]of [[b=>b[0]=0,'WAV_SIGNATURE'],[b=>new DataView(b.buffer).setUint32(4,1,true),'WAV_SIGNATURE'],[b=>new DataView(b.buffer).setUint16(20,3,true),'WAV_FORMAT'],[b=>new DataView(b.buffer).setUint16(34,64,true),'WAV_FORMAT'],[b=>new DataView(b.buffer).setUint16(32,0,true),'WAV_FORMAT'],[b=>new DataView(b.buffer).setUint32(28,1,true),'WAV_FORMAT'],[b=>new DataView(b.buffer).setUint32(40,7,true),'WAV_DATA'],[b=>b.set([74,85,78,75],36),'WAV_DATA']]){const raw=wav();change(raw);const s=setup(raw);await rejected(()=>s.context.readAudio(s.locator),'PRIVATE_AUDIO_'+code);assert.equal(s.calls.length,0);}
for(const [raw,code]of [[flac(0),'FORMAT'],[flac(4,1),'FORMAT'],[flac(0xfffffffff),'PCM_BUDGET'],[new Uint8Array(10),'FLAC_SIGNATURE']]){const s=setup(raw,'audio/flac');await rejected(()=>s.context.readAudio(s.locator),'PRIVATE_AUDIO_'+code);assert.equal(s.calls.length,0);}
const badMetadata=flac();badMetadata[4]=127;const bm=setup(badMetadata,'audio/flac');await rejected(()=>bm.context.readAudio(bm.locator),'PRIVATE_AUDIO_FLAC_METADATA');
for(const patch of [{sampleRate:44100},{numberOfChannels:2},{length:9},{duration:Infinity}]){const s=setup(wav(),'audio/wav',{decoder:async()=>({sampleRate:8000,numberOfChannels:1,length:4,duration:4/8000,getChannelData:()=>new Float32Array(4),...patch})});await rejected(()=>s.context.readAudio(s.locator),'PRIVATE_AUDIO_DECODE');}
for(const status of [401,403,409,410,503]){const s=setup(wav(),'audio/wav',{status});await rejected(()=>s.context.readAudio(s.locator),'PRIVATE_BYTES_HTTP_'+status);assert.equal(s.calls.length,0);assert.equal(s.requests.length,1);}
let finish;const slow=setup(wav(),'audio/wav',{decoder:()=>new Promise(done=>finish=done)});const task=slow.context.readAudio(slow.locator);while(!finish)await new Promise(done=>setImmediate(done));await rejected(()=>slow.context.readAudio(slow.locator),'PRIVATE_AUDIO_OWNED_BUDGET');slow.revoke();finish({sampleRate:8000,numberOfChannels:1,length:4,duration:4/8000,getChannelData:()=>new Float32Array(4)});await rejected(()=>task,'revoked');
const broken=setup(wav(),'audio/wav',{decoder:async()=>{throw new Error('decode failed');}});await rejected(()=>broken.context.readAudio(broken.locator),'decode failed');await rejected(()=>broken.context.readAudio(broken.locator),'decode failed');assert.equal(broken.requests.length,2);checks.push('failed decoder releases owned slot; only later explicit retry makes GET');
const closed=setup();closed.audioContext.state='closed';await rejected(()=>closed.context.readAudio(closed.locator),'PRIVATE_AUDIO_CONTEXT');assert.equal(closed.requests.length,0);
let finishClosed;const pendingClose=setup(wav(),'audio/wav',{decoder:()=>new Promise(done=>finishClosed=done)});const closing=pendingClose.context.readAudio(pendingClose.locator);while(!finishClosed)await new Promise(done=>setImmediate(done));pendingClose.context.close();finishClosed({sampleRate:8000,numberOfChannels:1,length:4,duration:4/8000,getChannelData:()=>new Float32Array(4)});await rejected(()=>closing,'PRIVATE_AUDIO_CLOSED');assert.equal(pendingClose.audioContext.state,'suspended');
let finishRate;const pendingRate=setup(wav(),'audio/wav',{decoder:()=>new Promise(done=>finishRate=done)});const rateTask=pendingRate.context.readAudio(pendingRate.locator);while(!finishRate)await new Promise(done=>setImmediate(done));pendingRate.audioContext.sampleRate=16000;finishRate({sampleRate:8000,numberOfChannels:1,length:4,duration:4/8000,getChannelData:()=>new Float32Array(4)});await rejected(()=>rateTask,'PRIVATE_AUDIO_CONTEXT');
const sourceHashes=Object.fromEntries(['web/src/content/privateaudio.js','web/src/content/privatebytes.js','tools/verify_editor_private_audio.mjs'].map(p=>[p,sha(readFileSync(p))]));writeFileSync(d+'model-r'+round+'.json',JSON.stringify({checks,sourceHashes,fakeHTTP:true,fakeAudioContext:true,nativeAuthority:false,actualBrowser:false,providerDrain:false,runtimeManifestImplemented:false},null,2)+'\n',{flag:'wx'});process.stdout.write(JSON.stringify({checks:checks.length})+'\n');
