// Focused actual GameBar constructor with fake trusted image I/O. No Rule/browser/authority.
import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import {createHash} from 'node:crypto';
import {GameBar} from '../web/src/ui/gamebar.js';import {GAMEBAR_UI_IMAGES} from '../web/src/ui/gamebarimages.js';
const round=process.argv[2];assert.match(round??'',/^[1-9][0-9]{0,2}$/);const d='.dragon-analysis/editor-phase/gamebar-image-resource-ports-session-r1/',hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex'),paths=['tools/verify_gamebar_image_resource_ports.mjs','web/src/ui/gamebar.js','web/src/ui/gamebarimages.js','web/src/render/ownedimages.js','web/src/core/assets.js'],sourceHashes=Object.fromEntries(paths.map(p=>[p,hash(p)])),checks=[];async function test(name,fn){await fn();checks.push(name);}const turn=()=>new Promise(r=>setImmediate(r));function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};}
function fixture(extra={}){const f={reads:[],handles:[],draws:0,revoked:false};f.app={world:{definition:{assets:{minimap:{base:'exact.world/base.png',large:'exact.world/large.png'}}}},view:{draw(){f.draws++;extra.draw?.(f);}},clock:{hold:new Set(['FOREIGN']),speed:3},scenario:{mustNotRun:true}};f.guard=()=>{if(f.revoked)throw new Error('LOCAL_REVOKED');extra.guard?.(f);};f.handle=url=>{const h={image:{role:url,width:16,height:16},disposed:0,dispose(){h.disposed++;assert.equal(h.disposed,1,'double release');extra.dispose?.(f,h);}};f.handles.push(h);return h;};f.ports={assertCurrent:f.guard,loadImage:async url=>{f.reads.push(url);return extra.load?extra.load(f,url):f.handle(url);}};f.start=()=>f.bar=new GameBar(f.app,f.ports);return f;}
const expected=()=>[...GAMEBAR_UI_IMAGES.slice(0,13),'exact.world/base.png',...GAMEBAR_UI_IMAGES.slice(13),'exact.world/large.png'];
await test('same constructor exact17UI+2mini original order and holders, state/hold unchanged',async()=>{const f=fixture(),before=JSON.stringify({world:f.app.world,clock:[...f.app.clock.hold],scenario:f.app.scenario});f.start();await f.bar._assets;assert.deepEqual(f.reads,expected());assert.equal(f.draws,1);assert.equal(f.bar.imgs.mbg.role,expected()[13]);assert.equal(f.bar.imgs.mbgLarge.role,expected()[18]);assert.equal(f.bar._gf.cloud.role,GAMEBAR_UI_IMAGES[9]);assert.equal(Object.keys(f.bar.imgs).length,15);assert.equal(Object.keys(f.bar._gf).length,4);assert.equal(JSON.stringify({world:f.app.world,clock:[...f.app.clock.hold],scenario:f.app.scenario}),before);f.bar.disposeImageResources();assert.equal(f.handles.filter(h=>h.disposed===1).length,19);});
await test('ports captured at construction, later mutation not executable',async()=>{const f=fixture();f.start();f.ports.loadImage=()=>{throw new Error('CHANGED');};f.ports.assertCurrent=()=>{throw new Error('CHANGED');};await f.bar._assets;assert.equal(f.reads.length,19);f.bar.disposeImageResources();});
await test('default path remains original19 static loads/install and no owned release',async()=>{const seen=[];globalThis.Image=class{set src(v){seen.push(v);this.url=v;queueMicrotask(()=>this.onload());}};const f=fixture();const bar=new GameBar(f.app);await bar._assets;assert.equal(seen.length,19);for(const path of expected())assert.ok(seen.some(url=>url.endsWith(path)));assert.equal(f.draws,1);const old=bar.imgs;bar.disposeImageResources();assert.equal(bar.imgs,old);delete globalThis.Image;});
await test('explicit later load is fresh all19, old handles dropped before draw',async()=>{const f=fixture();f.start();await f.bar._assets;const old=f.handles.slice();const p=f.bar.loadImageResources();assert.equal(f.bar.imgs,undefined);await p;assert.equal(f.reads.length,38);assert.ok(old.every(h=>h.disposed===1));assert.equal(f.draws,2);f.bar.disposeImageResources();assert.ok(f.handles.every(h=>h.disposed===1));});
await test('four-active bounded pipeline, no partial installation, inflight load coalesces',async()=>{let active=0,max=0;const pending=[];const f=fixture({load(f,url){active++;max=Math.max(max,active);const t=deferred();pending.push(()=>{active--;t.resolve(f.handle(url));});return t.promise;}});f.start();const initial=f.bar._assets;await turn();assert.equal(f.reads.length,4);assert.equal(f.bar.imgs,undefined);assert.equal(f.bar.loadImageResources(),initial);for(let k=0;k<19;k++){assert.ok(pending.length>0);pending.shift()();await turn();}await initial;assert.equal(max,4);assert.equal(f.draws,1);f.bar.disposeImageResources();});
await test('original world replaced while loader pending rejects late result/releases all',async()=>{const tasks=[];const f=fixture({load(f,url){const t=deferred();tasks.push({t,url});return t.promise;}});f.start();await turn();f.app.world={...f.app.world};for(const x of tasks)x.t.resolve(f.handle(x.url));await assert.rejects(f.bar._assets,/GAMEBAR_IMAGE_WORLD_STALE/);await turn();assert.equal(f.draws,0);assert.equal(f.bar.imgs,undefined);assert.ok(f.handles.every(h=>h.disposed===1));});
await test('sameworld mini URL mutation after read is rejected, no fallback',async()=>{const f=fixture({load(f,url){if(f.reads.length===1)f.app.world.definition.assets.minimap.base='other/base.png';return f.handle(url);}});f.start();await assert.rejects(f.bar._assets,/GAMEBAR_IMAGE_WORLD_STALE/);await turn();assert.equal(f.draws,0);assert.ok(f.handles.every(h=>h.disposed===1));});
await test('definition identity swap under sameworld rejects before I/O',async()=>{const f=fixture();f.start();f.app.world.definition={...f.app.world.definition};await assert.rejects(f.bar._assets,/GAMEBAR_IMAGE_WORLD_STALE/);assert.equal(f.reads.length,0);});
await test('caller guard revocation before first read has zeroI/O/draw',async()=>{const f=fixture();f.start();f.revoked=true;await assert.rejects(f.bar._assets,/LOCAL_REVOKED/);assert.equal(f.reads.length,0);assert.equal(f.draws,0);});
await test('caller guard revoked by image read prevents installation and releases returned handle',async()=>{const f=fixture({load(f,url){f.revoked=true;return f.handle(url);}});f.start();await assert.rejects(f.bar._assets,/LOCAL_REVOKED/);await turn();assert.ok(f.handles.every(h=>h.disposed===1));assert.equal(f.draws,0);});
await test('dispose during pending cannot revive image holders or execute draw/message callbacks',async()=>{const tasks=[];const f=fixture({load(f,url){const t=deferred();tasks.push({t,url});return t.promise;}});f.start();await turn();f.bar.disposeImageResources();for(const x of tasks)x.t.resolve(f.handle(x.url));await assert.rejects(f.bar._assets,/GAMEBAR_IMAGES_CLOSED/);await turn();assert.equal(f.bar.imgs,undefined);assert.equal(f.draws,0);assert.ok(f.handles.every(h=>h.disposed===1));});
await test('draw callback reentrant dispose rejects commit and clears all own refs',async()=>{const f=fixture({draw(f){f.bar.disposeImageResources();}});f.start();await assert.rejects(f.bar._assets,/GAMEBAR_IMAGES_CLOSED/);assert.equal(f.bar.imgs,undefined);assert.equal(f.bar._gf,undefined);assert.ok(f.handles.every(h=>h.disposed===1));});
await test('malformed handle fails whole group, completed/late handles released',async()=>{const f=fixture({load(f,url){return f.reads.length===1?{image:null,dispose(){}}:f.handle(url);}});f.start();await assert.rejects(f.bar._assets,/GAMEBAR_IMAGE_HANDLE/);await turn();assert.equal(f.draws,0);assert.ok(f.handles.every(h=>h.disposed===1));});
await test('private HTTP error never falls back and cleanup cannot replace primary failure',async()=>{const f=fixture({load(f,url){if(f.reads.length===5)throw new Error('PRIVATE_BYTES_HTTP_409');return f.handle(url);},dispose(){throw new Error('CLEANUP_SECONDARY');}});f.start();await assert.rejects(f.bar._assets,/PRIVATE_BYTES_HTTP_409/);await turn();assert.equal(f.draws,0);assert.ok(f.handles.every(h=>h.disposed===1));await assert.rejects(f.bar.loadImageResources(),/GAMEBAR_IMAGES_CLOSED/);});
await test('cached main/mini/frame/cloud and asyncres draw stop before layout/state on localrevocation',async()=>{const f=fixture();f.start();await f.bar._assets;f.revoked=true;for(const fn of [()=>f.bar.draw(null),()=>f.bar.drawMini(null),()=>f.bar._frame(null,0,0,1,1),()=>f.bar._cloud(null,0,0,1,1)])assert.throws(fn,/LOCAL_REVOKED/);await assert.rejects(f.bar.drawRes(null),/LOCAL_REVOKED/);assert.equal(f.draws,1);f.bar.disposeImageResources();});
await test('invalid ports/missing or aliased minis refuse before trusted loads; repeated close once',async()=>{const f=fixture();assert.throws(()=>new GameBar(f.app,{}),/GAMEBAR_IMAGE_PORTS/);f.app.world.definition.assets.minimap.large=f.app.world.definition.assets.minimap.base;assert.throws(()=>f.start(),/GAMEBAR_MINIMAP_ROLES/);assert.equal(f.reads.length,0);const good=fixture();good.start();await good.bar._assets;good.bar.disposeImageResources();good.bar.disposeImageResources();assert.ok(good.handles.every(h=>h.disposed===1));});
for(const[p,h]of Object.entries(sourceHashes))assert.equal(hash(p),h,p);writeFileSync(d+'model-r'+round+'.json',JSON.stringify({checks,sourceHashes,actualGameBar:true,fakeTrustedIO:true,defaultStaticFakeImage:true,actualBrowser:false,ruleExecution:false,allPortraitConsumersIntegrated:false,runtimeManifestImplemented:false},null,2)+'\n',{flag:'wx'});process.stdout.write(JSON.stringify({checks:checks.length,actualGameBar:true,fakeTrustedIO:true})+'\n');
