// Actual private source/profile/catalog/R2 reads and bounded common image production.
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { createHash, randomBytes, randomUUID } from 'node:crypto';
import { request as httpsRequest } from 'node:https';
import { spawnSync } from 'node:child_process';
import { DatabaseSync } from 'node:sqlite';
import { startEditorBackend } from './start_editor_backend.mjs';
import { decodePNG } from '../server/pngio.js';
const dir = '.dragon-analysis/editor-phase/backend-copy-images-session-r1/', round = process.argv[2]; assert.match(round ?? '', /^[1-9][0-9]{0,2}$/); const output = dir + 'images-r' + round; mkdirSync(output);
const own = mkdtempSync(join(tmpdir(),'dragon-copy-images-')), origin = 'https://127.0.0.1:8787', sha = b => createHash('sha256').update(b).digest('hex');
function parse(b) { try { return JSON.parse(b); } catch(cause) { throw new Error('invalid owned image test JSON',{cause}); } }
const initial = randomBytes(24).toString('hex'), password = randomBytes(24).toString('hex'), nextPassword = randomBytes(24).toString('hex'), secret = randomBytes(32).toString('hex'), config = parse(readFileSync('server/wrangler.jsonc')); config.main = resolve(dir + 'fixture-worker.js'); const configPath = join(own,'wrangler.jsonc'); writeFileSync(configPath,JSON.stringify(config)); writeFileSync(join(own,'.dev.vars'),'EDITOR_DEFAULT_PASSWORD='+JSON.stringify(initial)+'\nEDITOR_REQUEST_KEY='+JSON.stringify(secret)+'\n',{flag:'wx',mode:0o600});
const inputs=['server/copyimages.js','tools/verify_editor_backend_copy_images.mjs','tools/verify_editor_copy_images_oracle.py',dir+'fixture-worker.js'], sourceHashes=Object.fromEntries(inputs.map(p=>[p,sha(readFileSync(p))])), calls=[],checks=[];let server,session,blocked=false;
async function call(path,value,who=session,extra={},raw=false) { const headers={Origin:origin,...extra};if(who){headers.Cookie=who.cookie;headers['X-CSRF-Token']=who.csrf;}if(value!==undefined){headers['Content-Type']='application/json';headers['Idempotency-Key']??=randomUUID();}const r=await new Promise((done,reject)=>{const req=httpsRequest(origin+path,{method:value===undefined?'GET':'POST',headers,rejectUnauthorized:false},res=>{const parts=[];res.on('data',b=>parts.push(b));res.on('error',reject);res.on('end',()=>{try{const bytes=Buffer.concat(parts);done({status:res.statusCode,data:raw?bytes:parse(bytes),cookie:res.headers['set-cookie']?.[0]?.split(';')[0]});}catch(error){reject(error);}});});req.on('error',reject);req.end(value===undefined?undefined:JSON.stringify(value));});calls.push({path:path.split('?')[0],status:r.status});return r; }
async function login(account) { const a=await call('/api/auth/login',{account,password:initial},null);assert.equal(a.status,200);const b=await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:a.cookie,csrf:a.data.csrf});assert.equal(b.status,200);return{cookie:b.cookie,csrf:b.data.csrf}; }
function databases(path) { return readdirSync(path,{withFileTypes:true}).flatMap(e=>{if(e.isDirectory())return databases(join(path,e.name));if(e.name.endsWith('.sqlite'))return[join(path,e.name)];return[];}); }
function database() { for(const path of databases(join(own,'.local/metadata'))){const db=new DatabaseSync(path);if(db.prepare("SELECT name FROM sqlite_master WHERE name='copy_origins'").get())return db;db.close();}throw new Error('owned origin SQL missing'); }
try {
  process.stderr.write('copy-images: actual source/copy setup\n');server=await startEditorBackend(configPath,{stageSource:true});session=await login('tianyi');assert.equal((await call('/api/admin/accounts',{account:'image_author'})).status,200);const foreign=await login('image_author');assert.equal((await call('/api/admin/source/install',{})).status,200);const definition=(await call('/api/admin/source')).data.definition,key=randomUUID();assert.equal((await call('/api/admin/copies',{registryId:definition.registryId,name:'圖像副本',introduction:''},session,{'Idempotency-Key':key})).status,202);const copied=await call('/api/admin/copies/'+key+'/run',{},session,{'If-Match':'"1"'});assert.equal(copied.status,200,copied.data.error);const gameId=copied.data.gameId,build='/api/fixture/images/build',value={gameId,draftRevision:'1'},before=(await call('/api/games')).data.games[0].modifiedAt;
  assert.equal((await call(build,value,null)).status,401);assert.equal((await call(build,value,foreign)).status,403);assert.equal((await call(build,{...value,gameId:'wolong-builtin'})).status,403);assert.equal((await call(build,{...value,valid:true})).status,422);assert.equal((await call(build,{...value,draftRevision:'999'})).status,404);assert.equal((await call(build,{...value,gameId:[gameId]})).status,422);assert.equal((await call(build,{...value,gameId:randomUUID()})).status,404);checks.push('actual own administrator source restriction, noauth/foreign/builtin/self-valid/missingrevision gates; no client role/path/cap authorization');
  process.stderr.write('copy-images: actual snapshot/profile/all41R2 roles/common pixels\n');const result=await call(build,value);assert.equal(result.status,200,result.data.error);const {id,report}=result.data;assert.equal(report.gameId,gameId);assert.equal(report.draftRevision,'1');assert.equal(report.admission,'bounded-images-only');assert.equal(report.outputs.length,6);assert.ok(report.missing.includes('runtime-admission'));assert.ok(report.missing.includes('persistent-image-job'));assert.equal(Object.hasOwn(report,'valid'),false);
  const manifest=parse(readFileSync('server/pinned/world-manifest.txt'));for(const[n,item]of report.outputs.entries()){const actual=await call('/api/fixture/images/artifact?id='+id+'&asset='+item.assetId,undefined,session,{},true);assert.equal(actual.status,200);assert.equal(actual.data.length,item.byteLength);assert.equal(sha(actual.data),item.sha256);writeFileSync(output+'/asset-'+(n+1)+'.png',actual.data,{flag:'wx'});const decoded=decodePNG(actual.data);assert.equal(sha(decoded.pixels),item.pixelSha256);const name=item.assetId.startsWith('atlas_')?'map_'+item.assetId+'.png':item.assetId+'.png',role=manifest.assets.find(a=>a.path===name);assert.ok(role);const original=readFileSync('web/'+role.url);assert.equal(sha(original),role.sha256);assert.equal(sha(decodePNG(original).pixels),item.pixelSha256);}
  const env={};for(const k of ['SystemRoot','WINDIR','COMSPEC','PATH','Path','PATHEXT','TEMP','TMP','USERPROFILE','LOCALAPPDATA','APPDATA','HOMEDRIVE','HOMEPATH'])if(process.env[k]!==undefined)env[k]=process.env[k];env.PYTHONUTF8='1';env.PYTHONDONTWRITEBYTECODE='1';const oracle=spawnSync('python',['-B','tools/verify_editor_copy_images_oracle.py',round],{env,encoding:'utf8',timeout:30000});writeFileSync(output+'/oracle.stdout',oracle.stdout,{flag:'wx'});writeFileSync(output+'/oracle.stderr',oracle.stderr,{flag:'wx'});assert.equal(oracle.status,0,oracle.stderr);const pixels=parse(oracle.stdout);assert.equal(pixels.results.length,6);for(const item of pixels.results){const descriptor=report.outputs[item.number-1];assert.equal(item.pixelSha256,descriptor.pixelSha256);assert.equal(item.width,descriptor.width);assert.equal(item.height,descriptor.height);}assert.equal((await call('/api/games')).data.games[0].modifiedAt,before);checks.push('actual full immutable source/profile+registered all41role reads; fouratlas andtwo sharedseed1 minis allpixelSHA equal pinned source, six newly produced PNGs independentlyPillow decoded; no modifiedAt write');
  const reLogin=await call('/api/auth/login',{account:'tianyi',password},null);assert.equal(reLogin.status,200);assert.equal((await call('/api/fixture/images/report?id='+id,undefined,{cookie:reLogin.cookie,csrf:reLogin.data.csrf})).status,403);assert.equal((await call('/api/fixture/images/artifact?id='+id+'&asset=not-an-output')).status,404);checks.push('same actual owner/new valid session does not acquire old temporary plan token binding; arbitrary asset selector not a path grant');
  assert.equal((await call('/api/games/'+gameId+'/draft/save',{metadata:{name:'後續圖稿',introduction:''},resourceEdits:[]},session,{'If-Match':'"1"'})).status,200);const later=(await call('/api/games')).data.games[0];assert.equal(later.draftRevision,'2');const original=await call(build,value);assert.equal(original.status,200,original.data.error);assert.equal(original.data.report.draftRevision,'1');assert.equal(original.data.report.sourceDigest,report.sourceDigest);assert.deepEqual(original.data.report.outputs,report.outputs);assert.equal((await call('/api/games')).data.games[0].modifiedAt,later.modifiedAt);checks.push('actual current saved2 does not replace requested immutable1: report sourceDigest and allsix descriptors retain1, no latest fallback or modifiedAt write');
  assert.equal((await call('/api/fixture/images/clone',{id})).status,403);assert.equal((await call('/api/fixture/images/tamper',{id})).status,200);assert.equal((await call('/api/fixture/images/report?id='+id)).status,503);checks.push('JSON/structuredClone is not temporary execution brand; captured output byte mutation rejected without source repair');
  const db=database(),old=db.prepare('SELECT definition_digest FROM copy_origins WHERE game_id=?').get(gameId);db.prepare('UPDATE copy_origins SET definition_digest=? WHERE game_id=?').run('0'.repeat(64),gameId);db.close();assert.equal((await call(build,value)).status,409);const restore=database();restore.prepare('UPDATE copy_origins SET definition_digest=? WHERE game_id=?').run(old.definition_digest,gameId);restore.close();assert.equal((await call('/api/fixture/images/source-corrupt',{})).status,200);const bad=await call(build,value);assert.equal(bad.status,503,bad.data.error);assert.equal(bad.data.error,'SOURCE_OBJECT_CORRUPT');assert.equal((await call('/api/fixture/images/source-restore',{})).status,200);checks.push('actual SQL origin mismatch and same-size registeredatlas nativeR2 corruption reject before output permission; only explicit owned fixture restores exact original bytes');
  assert.equal((await call('/api/fixture/images/arm',{})).status,200);blocked=true;process.stderr.write('copy-images: native sourceR2 await/epoch revoke\n');const pending=call(build,value),deadline=Date.now()+240000;for(;;){const state=await call('/api/fixture/images/hold');if(state.data.state==='blocked')break;assert.ok(Date.now()<deadline,'controlled native R2 not reached');await new Promise(done=>setTimeout(done,250));}
  const changed=await call('/api/auth/password',{oldPassword:password,newPassword:nextPassword});assert.equal(changed.status,200);session={cookie:changed.cookie,csrf:changed.data.csrf};assert.equal((await call('/api/fixture/images/release',{})).status,200);blocked=false;const revoked=await pending;assert.equal(revoked.status,401,revoked.data.error);assert.equal((await call('/api/fixture/images/report?id='+id)).status,403);assert.equal((await call('/api/games')).data.games[0].modifiedAt,later.modifiedAt);checks.push('native catalog R2 get held after actual read; real password epoch revoke returns401 before producing/caching image plan, fresh session cannot revive old plan');
  await server.close();server=null;server=await startEditorBackend(configPath);assert.equal((await call('/api/fixture/images/report?id='+id)).status,404);assert.equal((await call('/api/games/'+gameId+'/compile',{})).status,404);checks.push('actual SQL/R2 restart does not persist image memory brand/cache; public compiler remains404, no ready/runtime/Trial/Release');
  for(const[p,h]of Object.entries(sourceHashes))assert.equal(sha(readFileSync(p)),h,p);process.stdout.write(JSON.stringify({result:'PASS-REAL-FIXED-COPY-IMAGES-SCOPED',checks,calls,sourceHashes,report,oracle:pixels,outputDirectory:output,limits:'Six bounded images from exact private fixedcopy and actual pinned catalog. No durable image Job, largefallback/completeconsumers/Q69/runtime/publiccompile/Trial/Release/cloudSLA or fullgoalcompletion.'},null,2)+'\n');
} finally { if(blocked){try{await call('/api/fixture/images/release',{});}catch{/* Preserve primary failure; only own fixture. */}}await server?.close(); }
