// Actual Root/private SQL-R2; fresh Chromium and owned files only. No library preview execution.
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { randomBytes, randomUUID, createHash } from 'node:crypto';
import { request as httpsRequest } from 'node:https';
import { pathToFileURL } from 'node:url';
import { startEditorBackend } from './start_editor_backend.mjs';
const round=process.argv[2];assert.match(round??'',/^[1-9][0-9]{0,2}$/);
const dir='.dragon-analysis/editor-phase/backend-library-ui-session-r1/',origin='https://127.0.0.1:8787',own=mkdtempSync(join(tmpdir(),'dragon-library-ui-')),sha=b=>createHash('sha256').update(b).digest('hex');
function parse(b){try{return JSON.parse(b);}catch(cause){throw new Error('owned library UI JSON',{cause});}}
const before=parse(readFileSync(dir+'before.json')),protectedHashes={...before.inputs};for(const p of ['server/worker.js','server/public/client.txt','server/public/index.html'])delete protectedHashes[p];assert.equal(Object.keys(protectedHashes).length,444);for(const[p,h]of Object.entries(protectedHashes))assert.equal(sha(readFileSync(p)),h,p);
const sourcePaths=['server/worker.js','server/public/client.txt','server/public/index.html','server/public/library.txt','tools/verify_editor_backend_library_ui.mjs'],sourceHashes=Object.fromEntries(sourcePaths.map(p=>[p,sha(readFileSync(p))]));
const config=parse(readFileSync('server/wrangler.jsonc')),initial=randomBytes(24).toString('hex'),password=randomBytes(24).toString('hex');config.main=resolve('server/worker.js');writeFileSync(join(own,'wrangler.jsonc'),JSON.stringify(config),{flag:'wx'});writeFileSync(join(own,'.dev.vars'),'EDITOR_DEFAULT_PASSWORD='+JSON.stringify(initial)+'\nEDITOR_REQUEST_KEY='+JSON.stringify(randomBytes(32).toString('hex'))+'\n',{flag:'wx',mode:0o600});
const calls=[],checks=[],gets=[],posts=[],downloads=[],errors=[],outside=[],expected=[];let server,browser;
async function call(path,value,session,extra={}){const headers={Origin:origin,...extra};if(session){headers.Cookie=session.cookie;headers['X-CSRF-Token']=session.csrf;}if(value!==undefined){headers['Content-Type']='application/json';headers['Idempotency-Key']??=randomUUID();}const r=await new Promise((done,reject)=>{const request=httpsRequest(origin+path,{method:value===undefined?'GET':'POST',headers,rejectUnauthorized:false},res=>{const parts=[];res.on('data',b=>parts.push(b));res.on('error',reject);res.on('end',()=>{try{done({status:res.statusCode,data:parse(Buffer.concat(parts)),cookie:res.headers['set-cookie']?.[0]?.split(';')[0]});}catch(error){reject(error);}});});request.on('error',reject);request.end(value===undefined?undefined:JSON.stringify(value));});calls.push({path,status:r.status});return r;}
async function idle(page){await page.waitForFunction(()=>!document.querySelector('#draft-games-refresh').disabled,undefined,{timeout:300000});}
async function login(page,account,pw){await page.goto(origin);await page.locator('#login [name=account]').fill(account);await page.locator('#login [name=password]').fill(pw);await page.locator('#login button').click();await page.locator('#draft-editor').waitFor({state:'visible'});await idle(page);}
async function load(page,revision='1'){await page.locator('#draft-games-refresh').click();await idle(page);await page.locator('#draft-revision').fill(revision);await page.locator('#draft-load').click();await page.waitForFunction(rev=>document.querySelector('#draft-context').textContent.includes('已保存修訂 '+rev)&&!document.querySelector('#draft-name').disabled,revision,{timeout:300000});}
async function download(page,selector,label){const event=page.waitForEvent('download',{timeout:300000}).then(file=>({file}),error=>({error}));await selector.click();const result=await event;if(result.error)throw result.error;const stream=await result.file.createReadStream(),parts=[];assert.ok(stream);for await(const b of stream)parts.push(b);const bytes=Buffer.concat(parts),path=dir+'download-r'+round+'-'+label+'.bin';writeFileSync(path,bytes,{flag:'wx'});downloads.push({path,sha256:sha(bytes),byteLength:bytes.length,filename:result.file.suggestedFilename()});await idle(page);return bytes;}
async function context(){const ctx=await browser.newContext({ignoreHTTPSErrors:true,acceptDownloads:true,viewport:{width:1280,height:1000}});await ctx.addInitScript(()=>Object.defineProperty(globalThis,'indexedDB',{get(){globalThis.__idbAccess=(globalThis.__idbAccess??0)+1;throw new Error('IDB forbidden');}}));await ctx.route('**/*',route=>{try { if(new URL(route.request().url()).origin!==origin){outside.push('outside');return route.abort();} } catch { outside.push('invalid-url');return route.abort(); } return route.continue();});return ctx;}
try{
 process.stderr.write('library-ui: actual setup\n');server=await startEditorBackend(join(own,'wrangler.jsonc'),{stageSource:true,stageLibrary:true});const first=await call('/api/auth/login',{account:'tianyi',password:initial});assert.equal(first.status,200);const changed=await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:first.cookie,csrf:first.data.csrf});assert.equal(changed.status,200);const admin={cookie:changed.cookie,csrf:changed.data.csrf};assert.equal((await call('/api/admin/accounts',{account:'library_viewer'},admin)).status,200);const foreign=await call('/api/auth/login',{account:'library_viewer',password:initial});assert.equal(foreign.status,200);assert.equal((await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:foreign.cookie,csrf:foreign.data.csrf})).status,200);assert.equal((await call('/api/admin/source/install',{},admin)).status,200);const source=(await call('/api/admin/source',undefined,admin)).data,key=randomUUID();assert.equal((await call('/api/admin/copies',{registryId:source.definition.registryId,name:'私有素材庫',introduction:''},admin,{'Idempotency-Key':key})).status,202);const copied=await call('/api/admin/copies/'+key+'/run',{},admin,{'If-Match':'"1"'});assert.equal(copied.status,200);const gameId=copied.data.gameId,manifestPath='/api/games/'+gameId+'/draft/library-assets?revision=1';
 const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);browser=await chromium.launch({headless:true});const ctx=await context(),page=await ctx.newPage();let count=0;page.on('download',()=>count++);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()!=='error')return;const p=new URL(m.location().url||origin).pathname,t=m.text();if(p==='/api/session'&&t.includes('401')||p==='/favicon.ico'&&t.includes('404')||p.includes('/library-assets')&&t.includes('404'))expected.push({path:p,text:t});else errors.push(t);});page.on('request',r=>{const p=new URL(r.url());if(p.pathname.includes('/library-assets'))gets.push({path:p.pathname,query:p.search,method:r.method()});if(r.method()==='POST'&&!p.pathname.startsWith('/api/auth/'))posts.push(p.pathname);});
 await login(page,'tianyi',password);assert.equal(await page.locator('#library-load').isDisabled(),true);await load(page);await page.locator('#library-load').click();await page.waitForFunction(()=>document.querySelector('#library-status').textContent.includes('未確認')&&!document.querySelector('#library-load').disabled,undefined,{timeout:300000});assert.equal(await page.locator('#library-assets button').count(),0);checks.push('actual admin UI loaded saved1; staged-but-not-SQLregistered API rejects before any catalogue, no implicit registration or runtime grant');
 assert.equal((await call('/api/admin/library/install',{},admin)).status,200);const saved=await call('/api/games/'+gameId+'/draft/save',{metadata:{name:'素材保存二',introduction:'保留修訂一'},resourceEdits:[]},admin,{'If-Match':'"1"'});assert.equal(saved.status,200);const current=(await call('/api/games',undefined,admin)).data.games.find(g=>g.gameId===gameId);await page.locator('#draft-name').fill('未保存');const n=gets.length;page.once('dialog',d=>d.dismiss());await page.locator('#library-load').click();await idle(page);assert.equal(gets.length,n);assert.equal(await page.locator('#draft-name').inputValue(),'未保存');page.once('dialog',d=>d.accept());await page.locator('#library-load').click();await page.waitForFunction(()=>document.querySelector('#library-assets').querySelectorAll('button').length===398&&!document.querySelector('#library-load').disabled,undefined,{timeout:300000});assert.equal(await page.locator('#library-missing p').count(),20);assert.ok((await page.locator('#library-context').textContent()).includes('已保存修訂 1'));assert.ok(gets.every(r=>r.query==='?revision=1'&&r.method==='GET'));checks.push('actual current2/saved1 and dirty cancel sends noGET; explicitaccept reads398fixedavailable descriptors/20missing255, no save orlatest or POST');
 const response=(await call(manifestPath,undefined,admin)).data;const png=response.assets.find(a=>a.logicalURL==='kao/0.png'),music=response.assets.find(a=>a.logicalURL==='grf/music/loops/BGM_09.flac'),data=response.assets.find(a=>a.logicalURL==='battle_rules.json');assert.ok(png&&music&&data);assert.equal(music.byteLength,11196244);
 for(const [asset,label]of [[png,'png'],[music,'largest-flac'],[data,'json']]){await page.locator('#library-filter').fill(asset.logicalURL);const button=page.locator('#library-assets button[data-asset-id="'+asset.assetId+'"]');const bytes=await download(page,button,label);assert.equal(bytes.length,asset.byteLength);assert.equal(sha(bytes),asset.sha256);assert.equal(sha(readFileSync('web/'+asset.logicalURL)),asset.sha256);assert.equal(downloads.at(-1).filename,asset.assetId+'.bin');}checks.push('three actual fullbyte owned downloads PNG/largest11.2MBFLAC/JSON, SHAexactfixedWebbytes andfixedassetIdfilename; no media/font/JSON execution; originalstage4MiB notused for11.2MB');
 await page.locator('#library-filter').fill(png.logicalURL);const button=page.locator('#library-assets button[data-asset-id="'+png.assetId+'"]'),artifact=origin+'/api/games/'+gameId+'/draft/library-assets/'+png.assetId+'?revision=1';
 for(const kind of ['bytes','sha','revision','source','root','admission','length']){await page.route(artifact,async route=>{const r=await route.fetch({timeout:300000});assert.equal(r.status(),200);const headers={...r.headers()};let body=Buffer.from(await r.body());if(kind==='bytes')body[0]^=1;else if(kind==='length')body=Buffer.concat([body,Buffer.from([0])]);else { const names={'sha':'x-content-sha256','revision':'x-draft-revision','source':'x-source-sha256','root':'x-library-root','admission':'x-content-admission'}; let value='0'.repeat(64); if(kind==='revision')value='2'; else if(kind==='admission')value='runtime-approved'; headers[names[kind]]=value; }await route.fulfill({response:r,headers,body});});const old=count;await button.click();await page.waitForFunction(()=>document.querySelector('#library-status').textContent.includes('未確認')&&!document.querySelector('#library-load').disabled,undefined,{timeout:300000});assert.equal(count,old,kind);await page.unroute(artifact);}checks.push('seven browser response faults afteractual200: byteflip/SHA/revision/source/catalog/admission/overlength rejected without file or runtime flag');
 const oldGets=gets.length;page.once('dialog',d=>d.accept());await page.reload();await page.locator('#draft-editor').waitFor({state:'visible'});await idle(page);assert.equal(gets.length,oldGets);assert.equal(await page.locator('#library-assets button').count(),0);assert.equal(await page.locator('#library-load').isDisabled(),true);await load(page);
 await page.route(origin+manifestPath,async route=>{const r=await route.fetch({timeout:300000});assert.equal(r.status(),200);const b=await r.json();b.assets[0].assetId='../../escape';await route.fulfill({response:r,json:b});});await page.locator('#library-load').click();await page.waitForFunction(()=>document.querySelector('#library-status').textContent.includes('描述無效')&&!document.querySelector('#library-load').disabled,undefined,{timeout:300000});assert.equal(await page.locator('#library-assets button').count(),0);await page.unroute(origin+manifestPath);await page.locator('#library-load').click();await page.waitForFunction(()=>document.querySelector('#library-assets').querySelectorAll('button').length===398&&!document.querySelector('#library-load').disabled,undefined,{timeout:300000});checks.push('reload no automatic catalogue/request/credential/body restore; malformedassetIdmanifest rejected before rows; explicit saved1 reload succeeds');
 await load(page,'2');assert.equal(await page.locator('#library-assets button').count(),0);assert.equal(await page.locator('#library-missing p').count(),0);assert.equal(await page.locator('#library-filter').isDisabled(),true);await page.locator('#library-load').click();await page.waitForFunction(()=>document.querySelector('#library-assets').querySelectorAll('button').length===398&&!document.querySelector('#library-load').disabled,undefined,{timeout:300000});assert.ok((await page.locator('#library-context').textContent()).includes('已保存修訂 2'));checks.push('explicit contextchange1to2 clears oldcatalogue/downloadrefs; never followslatest but explicit2read works withoutsourcewrite');
 const fullScreenshot=dir+'catalogue-r'+round+'.png';writeFileSync(fullScreenshot,await page.screenshot({fullPage:true}),{flag:'wx'});
 const revision2URL=origin+'/api/games/'+gameId+'/draft/library-assets?revision=2';await page.route(revision2URL,async route=>{const r=await route.fetch({timeout:300000});assert.equal(r.status(),200);await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));await route.fulfill({response:r});});await page.locator('#library-load').click();await idle(page);assert.equal(await page.locator('#library-assets button').count(),0);assert.equal(await page.locator('#library-missing p').count(),0);await page.unroute(revision2URL);checks.push('separately labelled syntheticpagehide afteractual200 beforedelivery invalidatesgeneration; latecatalogue notinstalled, notactualBFCache ordeviceevent proof');
 // Actual data-stage query/download under current shared binary adapter (old 4MiB branch).
 const jobKey=randomUUID(),queued=await call('/api/games/'+gameId+'/stage-jobs/data',{draftRevision:'2',scope:'all'},admin,{'Idempotency-Key':jobKey});assert.equal(queued.status,202);const jobId=queued.data.job.operationId;const ready=await call('/api/games/'+gameId+'/stage-jobs/data/'+jobId+'/run',{},admin,{'If-Match':'"1"'});assert.equal(ready.status,200);const assoc='editor-stage-jobs:'+changed.data.user.id;await page.evaluate(({assoc,gameId,jobKey,jobId})=>sessionStorage.setItem(assoc,JSON.stringify({data:{gameId,draftRevision:'2',purpose:'data',enqueueKey:jobKey,id:jobId,command:null},images:null})),{assoc,gameId,jobKey,jobId});await page.reload();await page.locator('#stage-editor').waitFor({state:'visible'});await idle(page);await page.locator('#stage-query').click();await page.waitForFunction(()=>document.querySelector('#stage-task').textContent.includes('ready')&&!document.querySelector('#stage-query').disabled,undefined,{timeout:300000});const stageOut=ready.data.job.checkpoint.flatMap(x=>x.outputs)[0];const stageBytes=await download(page,page.locator('#stage-artifacts p').filter({hasText:stageOut.assetId+'／'}).locator('button'),'legacy-stage');assert.equal(sha(stageBytes),stageOut.sha256);assert.equal(stageBytes.length,stageOut.byteLength);checks.push('actual existingdata readyquery/restoredtwo-purposeassociation and fullSHA stage attachment uses unchanged4MiB branch withnewlibrarymodulepresent; no stage browser POST');
 await load(page,'2');await page.locator('#library-load').click();await page.waitForFunction(()=>document.querySelector('#library-assets').querySelectorAll('button').length===398&&!document.querySelector('#library-load').disabled,undefined,{timeout:300000});const next=randomBytes(24).toString('hex');await page.locator('#password [name=oldPassword]').fill(password);await page.locator('#password [name=newPassword]').fill(next);await page.locator('#password [name=confirmPassword]').fill(next);await page.locator('#password button').click();await idle(page);assert.equal(await page.locator('#library-assets button').count(),0);assert.equal(await page.locator('#library-missing p').count(),0);assert.equal(await page.locator('#library-filter').isDisabled(),true);checks.push('actual passwordhandler success replacesidentity/epoch andclearssensitivecatalogue+ownedURLs; notserverdeletion orDRM');
 const foreignCtx=await context(),foreignPage=await foreignCtx.newPage();foreignPage.on('pageerror',e=>errors.push(e.message));await login(foreignPage,'library_viewer',password);assert.equal(await foreignPage.locator('#library-editor').isHidden(),true);assert.equal(await foreignPage.locator('#library-assets button').count(),0);assert.equal(await foreignPage.evaluate(()=>globalThis.__idbAccess??0),0);await foreignCtx.close();assert.equal(await page.evaluate(()=>globalThis.__idbAccess??0),0);assert.deepEqual(posts,[]); // No Trial creation or admission request in this read-only UI probe.
 assert.deepEqual(errors,[]);assert.deepEqual(outside,[]);checks.push('actual separateauthor hasno administratorprivate-library UI; testedIDB0/outside0/no browser content POST, console/pageerrors0; librarydoesnot altergame row');
 const finalLogin=await call('/api/auth/login',{account:'tianyi',password:next});assert.equal(finalLogin.status,200);assert.deepEqual((await call('/api/games',undefined,{cookie:finalLogin.cookie,csrf:finalLogin.data.csrf})).data.games.find(g=>g.gameId===gameId),current);const screenshot=dir+'ui-r'+round+'.png';writeFileSync(screenshot,await page.screenshot({fullPage:true}),{flag:'wx'});for(const[p,h]of Object.entries({...protectedHashes,...sourceHashes}))assert.equal(sha(readFileSync(p)),h,p);process.stdout.write(JSON.stringify({result:'PASS-ACTUAL-PRIVATE-LIBRARY-UI-SCOPED',checks,calls,gets,posts,downloads,sourceHashes,screenshot,screenshotSha:sha(readFileSync(screenshot)),fullScreenshot,fullScreenshotSha:sha(readFileSync(fullScreenshot)),expected,errors,outside,protected:444,limits:'Read-only actualprivate bytes UI/currentdata-stage compatibility, no fullworkbench/upload/crop/media semantics/runtime/Q69/Trial/release/cloudSLA/maincompletion.'},null,2)+'\n');
}catch(error){writeFileSync(dir+'failure-r'+round+'.json',JSON.stringify({checks,calls,gets,posts,sourceHashes,error:{message:error.message,code:error.code??null}},null,2)+'\n',{flag:'wx'});throw error;}finally{await browser?.close();await server?.close();}
