import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdtempSync} from 'node:fs';import {resolve,join} from 'node:path';import {tmpdir} from 'node:os';import {createHash,randomBytes,randomUUID} from 'node:crypto';import {request as httpsRequest} from 'node:https';import {startEditorBackend} from './start_editor_backend.mjs';
const d='.dragon-analysis/editor-phase/backend-validated-waits-session-r1/',round=process.argv[2];assert.match(round??'',/^[1-9][0-9]{0,2}$/);const hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex');function parse(b){try{return JSON.parse(b);}catch(cause){throw new Error('owned validated wait JSON',{cause});}}const before=parse(readFileSync(d+'before.json'));for(const[p,h]of Object.entries({...before.inputs,...before.imports}))assert.equal(hash(p),h,p);const sources=Object.fromEntries(['tools/verify_editor_backend_validated_waits.mjs',d+'fixture-worker.js','server/deletionwritewait.js','server/deletionreadwait.js','server/deletionvalidatedfreeze.js','server/privatewrites.js','server/blobs.js','server/worker.js','server/security.js','.dragon-analysis/editor-phase/backend-wait-gate-preflight-r1/fixture-worker.js'].map(p=>[p,hash(p)]));const own=mkdtempSync(join(tmpdir(),'dragon-validated-waits-')),config=parse(readFileSync('server/wrangler.jsonc')),initial=randomBytes(24).toString('hex'),password=randomBytes(24).toString('hex'),origin='https://127.0.0.1:8787';config.main=resolve(d+'fixture-worker.js');writeFileSync(join(own,'wrangler.jsonc'),JSON.stringify(config),{flag:'wx'});writeFileSync(join(own,'.dev.vars'),'EDITOR_DEFAULT_PASSWORD='+JSON.stringify(initial)+'\nEDITOR_REQUEST_KEY='+JSON.stringify(randomBytes(32).toString('hex'))+'\n',{flag:'wx',mode:0o600});const calls=[],checks=[],facts=[],tasks=[];let server,admin;
async function call(path,value,session,extra={}){const headers={Origin:origin,'Content-Type':'application/json','Idempotency-Key':randomUUID(),...extra};if(session){headers.Cookie=session.cookie;headers['X-CSRF-Token']=session.csrf;}if(extra['X-CSRF-Token']!==undefined)headers['X-CSRF-Token']=extra['X-CSRF-Token'];const r=await new Promise((done,reject)=>{const req=httpsRequest(origin+path,{method:'POST',headers,rejectUnauthorized:false,agent:false},res=>{const chunks=[];res.on('data',b=>chunks.push(b));res.on('error',reject);res.on('end',()=>{try{done({status:res.statusCode,data:parse(Buffer.concat(chunks)),cookie:res.headers['set-cookie']?.[0]?.split(';')[0]});}catch(error){reject(error);}});});req.on('error',reject);req.end(JSON.stringify(value));});calls.push({path,status:r.status,action:value.action??null});return r;}
async function ok(path,v,s,x){const r=await call(path,v,s,x);assert.equal(r.status,200,r.data.error);return r.data.result??r.data;}
const control=(v,s=admin)=>ok('/api/test/validated-waits',v,s),audit=v=>ok('/api/test/wait-gate-audit',v,admin),base=v=>ok('/api/test/definitions',v,admin);
async function deny(v,status,code,s=admin,path='/api/test/wait-gate-audit',headers){const r=await call(path,v,s,headers);assert.equal(r.status,status,r.data.error);assert.equal(r.data.error,code);}
async function poll(fn,predicate,label){const start=Date.now();for(;;){const value=await fn();if(predicate(value))return value;if(Date.now()-start>12000)throw new Error('bounded owned notification observation '+label+':'+JSON.stringify(value));await new Promise(done=>setTimeout(done,20));}}
async function login(){const r=await call('/api/auth/login',{account:'tianyi',password});assert.equal(r.status,200,r.data.error);return {cookie:r.cookie,csrf:r.data.csrf};}
async function game(){const value=await base({action:'create',name:'等待'+randomUUID().slice(0,6)}),input={gameId:value.gameId,expectedRowRevision:'1'};await audit({action:'seed-snapshot',input});return {value,input};}
async function fence(g){const value=await base({action:'fence',input:{gameId:g.input.gameId,expectedRowRevision:'1',confirmationName:g.value.name}});return {gameId:g.input.gameId,expectedRowRevision:value.rowRevision};}
function fact(value,input,method,n){assert.equal(Object.keys(value).length,method==='put'?8:7);assert.equal(value.gameId,input.gameId);assert.equal(value.rowRevision,input.expectedRowRevision);assert.equal(value[method==='put'?'writesWaited':'readsWaited'],n);assert.equal(value.nativeDrainVerified,false);assert.equal(value.deleteAllowed,false);if(method==='put'){assert.equal(value.privateWritesPending,0);assert.equal(value.privateWritesUncertain,0);assert.equal(value.mode,'CURRENT_INSTANCE_REGISTERED_PUTS_RETURNED_LEGACY_UNKNOWN');}else{assert.equal(value.bodyDrainVerified,false);assert.equal(value.mode,'CURRENT_INSTANCE_REGISTERED_READ_CALLS_RETURNED_BODY_DRAIN_UNKNOWN');}facts.push(value);}
async function inflight(method,kind){const g=await game(),nativeTask=randomUUID(),waitTask=randomUUID();if(method==='get'){const stored=await control({action:'put-now',input:g.input});assert.equal(stored.byteLength,3);assert.equal(stored.created,true);}await control({action:'arm',method,input:g.input,reject:kind==='controlled-reject'});await control({action:method==='put'?'start-put':'start-read',taskId:nativeTask,input:g.input});await poll(()=>control({action:'state',input:g.input}),state=>state[method==='put'?'putEntered':'getEntered'],'actual Root registered native '+method);const input=await fence(g);const waitSession=kind==='expiry'?await login():admin;await control({action:'start-wait',method,taskId:waitTask,input,timeoutMs:kind==='timeout'?1000:5000},waitSession);await poll(()=>control({action:'state',input}),state=>method==='put'?state.putSlots===1:state.readState.slots===1,'actual captured wait subscription');const seals=await control({action:'seals',input});
 if(kind==='name')await audit({action:'remove-name',input});else if(kind==='index')await audit({action:'extra-index',input});else if(kind==='row')await control({action:'bump-row',input});else if(kind==='expiry')await control({action:'expire-wait-session',input,waitCookie:waitSession.cookie});else if(kind==='epoch'){await control({action:'epoch',input});admin=await login();}else if(kind==='ack')await control({action:'drop-ack-row',input});
 if(kind==='timeout'){const timed=await poll(()=>control({action:'task',taskId:waitTask,input}),value=>value.done,'timeout notification');assert.equal(timed.status,504);assert.equal(timed.error,method==='put'?'PRIVATE_WRITE_WAIT_TIMEOUT':'PRIVATE_READ_WAIT_TIMEOUT');const still=await control({action:'state',input});assert.equal(still[method==='put'?'putEntered':'getEntered'],true);assert.equal(method==='put'?still.putSlots:still.readState.slots,0);if(method==='put')assert.deepEqual(still.journal,[{state:'pending',n:1}]);else assert.equal(still.readState.calls,1);}
 await control({action:'release',method,input});const native=await poll(()=>control({action:'task',taskId:nativeTask,input}),value=>value.done,'original Root invocation returned');const waited=await poll(()=>control({action:'task',taskId:waitTask,input}),value=>value.done,'wait invocation returned');let nativeStatus=409;if(kind==='ack')nativeStatus=503;else if(kind==='controlled-reject')nativeStatus=500;else if(kind==='epoch')nativeStatus=401;assert.equal(native.status,nativeStatus);if(kind==='ack')assert.equal(native.error,'PRIVATE_WRITE_JOURNAL_CHANGED');else if(kind!=='controlled-reject')assert.equal(native.error,kind==='epoch'?'SESSION_INVALID':'GAME_DELETING');
 if(kind==='healthy'){assert.equal(waited.status,200,waited.error);fact(waited.value,input,method,1);}else{let expected=[503,'PRIVATE_WRITE_WAIT_UNKNOWN'];if(kind==='timeout')expected=[504,method==='put'?'PRIVATE_WRITE_WAIT_TIMEOUT':'PRIVATE_READ_WAIT_TIMEOUT'];else if(kind==='name')expected=[503,'DELETE_NAME_BINDING_ROWS'];else if(kind==='index')expected=[503,'DELETE_SCHEMA_DEFINITION'];else if(kind==='row')expected=[409,'DELETE_FENCE_CHANGED'];else if(['expiry','epoch'].includes(kind))expected=[401,'SESSION_INVALID'];assert.equal(waited.status,expected[0],waited.error);assert.equal(waited.error,expected[1]);}
 const after=await control({action:'state',input});assert.equal(after.putSlots,0);assert.deepEqual(after.readState,{calls:0,slots:0});assert.deepEqual(await control({action:'seals',input}),seals);if(kind==='name')assert.equal(after.names,0);if(kind==='controlled-reject')assert.deepEqual(after.journal,[{state:'uncertain',n:1}]);if(method==='put'&&!['ack','controlled-reject'].includes(kind))assert.deepEqual(after.journal,[{state:'settled',n:1}]);tasks.push({method,kind,native,waited,journal:after.journal});if(kind==='index')await audit({action:'remove-index',input});checks.push('Actual Root '+method+' registered before fence then actual captured subscriber: '+kind+'; final current gate/error/ACK/ownslots and original SQLseals preserved. Earlier legitimate freeze/provider commit NOT rolledback; returned read NOT EOF/providerdrain');}
try{server=await startEditorBackend(join(own,'wrangler.jsonc'),{stageSource:false,stageLibrary:false});const first=await call('/api/auth/login',{account:'tianyi',password:initial});assert.equal(first.status,200);const changed=await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:first.cookie,csrf:first.data.csrf});assert.equal(changed.status,200);admin={cookie:changed.cookie,csrf:changed.data.csrf};const g=await game(),input=await fence(g);assert.equal((await audit({action:'validated',input})).deleteAllowed,false);const fingerprint=()=>audit({action:'fingerprint',input}),healthy=await fingerprint();assert.equal(healthy.tables,35);const constructed=await control({action:'constructors',input});assert.equal(constructed.rejected,8);assert.deepEqual(await fingerprint(),healthy);checks.push('Actual Root auth/password, engineeredsaved parent and current40 initialfreeze; eight actual privatebrand/storage/budget constructor refusals beforeSQL; whole35rows/catalog/size unchanged');
 for(const method of ['put','get']){const value=await audit({action:method==='put'?'write':'read',input});fact(value,input,method,0);assert.deepEqual(await fingerprint(),healthy);}checks.push('Existingwaiters minimalexact8/7/current0false-drain-delete DTOs preserved after full current validatedSQL integration');
 for(const [bad,restore,code]of [['remove-name','restore-name','DELETE_NAME_BINDING_ROWS'],['extra-index','remove-index','DELETE_SCHEMA_DEFINITION']]){await audit({action:bad,input});const corrupt=await fingerprint();for(const action of ['write','read']){await deny({action,input},503,code);assert.deepEqual(await fingerprint(),corrupt);}await audit({action:restore,input});checks.push('Actual '+bad+' now refused by BOTH existingwaiters exact503/'+code+', no subscription, ALL35SQLrows/catalog/size unchanged; only explicit ownedrestore');}
 for(const action of ['write','read']){await deny({action,input:{...input,expectedRowRevision:'1'}},409,'DELETE_SCHEMA_CHANGED');await deny({action,input:{...input,gameId:'not-a-uuid'}},422,'DELETE_SCHEMA_INPUT');await deny({action,input:{...input,gameId:'wolong-builtin'}},403,'BUILTIN_PROTECTED');}checks.push('Stricter existing currentSchema CAS/input/builtin codes explicitly asserted; no blind legacyweak-error compatibility');
 await deny({action:'write',input},401,'LOGIN_REQUIRED',null);await deny({action:'read',input},403,'ORIGIN_REJECTED',admin,'/api/test/wait-gate-audit',{Origin:'https://example.invalid'});await deny({action:'write',input},403,'CSRF_REJECTED',admin,'/api/test/wait-gate-audit',{'X-CSRF-Token':'bad'});checks.push('Actual Cookie/Origin/independent badCSRF refusals; ownedcontrol never productpermission endpoint');
 for(const method of ['put','get'])for(const kind of ['healthy','name','index','row','expiry','epoch','timeout'])await inflight(method,kind);await inflight('put','ack');await inflight('put','controlled-reject');
 await control({action:'drop-history',input});for(const action of ['write','read'])await deny({action,input},503,'DELETE_SCHEMA_DEFINITION');const history=await control({action:'history-present',input});assert.equal(history.n,0);checks.push('Missing originalfreeze history table BOTHexistingwaiters refuses BEFORE executor constructor; absent table not recreated in this instance, NOT Root restart guarantee');
 for(const[p,h]of Object.entries({...before.inputs,...before.imports,...sources}))assert.equal(hash(p),h,p);writeFileSync(d+'report-r'+round+'.json',JSON.stringify({result:'PASS-ACTUAL-EXISTING-VALIDATED-READ-WRITE-WAITS-SCOPED',checks,calls,facts,tasks,sourceHashes:sources,protected:Object.keys(before.inputs).length,unchangedImports:Object.keys(before.imports).length,sourceStaging:false,sourceGame:false,bodyDrainVerified:false,nativeDrainVerified:false,deleteAllowed:false,allLegacy83And93ScenariosRerun:false},null,2)+'\n',{flag:'wx'});process.stdout.write('actual existing validated waits scoped native suite passed\n');}
catch(error){writeFileSync(d+'failure-r'+round+'.json',JSON.stringify({message:error?.message??String(error),code:error?.code??null,checks,calls,facts,tasks,sourceHashes:sources},null,2)+'\n',{flag:'wx'});throw error;}finally{if(server)await server.close();}
