// Own native Root/SQL coordination; no staged R2/Source, gameplay or physical cleanup.
import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdtempSync} from 'node:fs';import {resolve,join} from 'node:path';import {tmpdir} from 'node:os';import {createHash,randomBytes,randomUUID} from 'node:crypto';import {request as httpsRequest} from 'node:https';import {startEditorBackend} from './start_editor_backend.mjs';
const d='.dragon-analysis/editor-phase/backend-definition-freeze-session-r1/',round=process.argv[2],origin='https://127.0.0.1:8787';assert.match(round??'',/^[1-9][0-9]{0,2}$/);const sha=b=>createHash('sha256').update(b).digest('hex');function parse(b){try{return JSON.parse(b);}catch(cause){throw new Error('owned coordination JSON',{cause});}}
const before=parse(readFileSync(d+'before.json'));for(const[p,h]of Object.entries({...before.inputs,...before.imports}))assert.equal(sha(readFileSync(p)),h,p);const paths=['server/deletiondefinitionfreeze.js','tools/verify_editor_backend_definition_freeze.mjs',d+'fixture-worker.js'],sourceHashes=Object.fromEntries([...paths,'server/deletionsqlfreeze.js','server/deletionschemaintegrity.js','server/deletiondefinitions.js','server/worker.js','.dragon-analysis/editor-phase/backend-deletion-definitions-session-r1/fixture-worker.js'].map(p=>[p,sha(readFileSync(p))]));
const own=mkdtempSync(join(tmpdir(),'dragon-definition-freeze-')),config=parse(readFileSync('server/wrangler.jsonc')),initial=randomBytes(24).toString('hex'),password=randomBytes(24).toString('hex');config.main=resolve(d+'fixture-worker.js');writeFileSync(join(own,'wrangler.jsonc'),JSON.stringify(config),{flag:'wx'});writeFileSync(join(own,'.dev.vars'),`EDITOR_DEFAULT_PASSWORD=${JSON.stringify(initial)}\nEDITOR_REQUEST_KEY=${JSON.stringify(randomBytes(32).toString('hex'))}\n`,{flag:'wx',mode:0o600});const calls=[],checks=[],facts=[];let server;
async function call(path,value,session,extra={}){const headers={Origin:origin,'Content-Type':'application/json','Idempotency-Key':randomUUID()};if(session){headers.Cookie=session.cookie;headers['X-CSRF-Token']=session.csrf;}Object.assign(headers,extra);const r=await new Promise((done,reject)=>{const req=httpsRequest(origin+path,{method:value===undefined?'GET':'POST',headers,rejectUnauthorized:false,agent:false},res=>{const chunks=[];res.on('data',b=>chunks.push(b));res.on('error',reject);res.on('end',()=>{try{done({status:res.statusCode,data:parse(Buffer.concat(chunks)),cookie:res.headers['set-cookie']?.[0]?.split(';')[0]});}catch(error){reject(error);}});});req.on('error',reject);req.end(value===undefined?undefined:JSON.stringify(value));});calls.push({path,status:r.status});return r;}
async function ok(path,v,s,x){const r=await call(path,v,s,x);assert.equal(r.status,200,r.data.error);return r.data.result??r.data;}
const action=(v,s)=>ok('/api/test/definition-freeze',v,s),base=(v,s)=>ok('/api/test/definitions',v,s);
async function rejected(v,s,status,code,extra){const r=await call('/api/test/definition-freeze',v,s,extra);assert.equal(r.status,status,r.data.error);assert.equal(r.data.error,code);}
async function login(account){const r=await call('/api/auth/login',{account,password:initial});assert.equal(r.status,200);const p=await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:r.cookie,csrf:r.data.csrf});assert.equal(p.status,200);return{cookie:p.cookie,csrf:p.data.csrf};}
async function state(id,admin){const x=await action({action:'state',gameId:id},admin),{hook,...rows}=x;return{rows,hook};}
function fact(x,input){assert.equal(Object.keys(x).length,17);assert.equal(x.gameId,input.gameId);assert.equal(x.rowRevision,input.expectedRowRevision);for(const k of ['schemaDigest','jobStateDigest','draftStateDigest'])assert.match(x[k],/^[a-f0-9]{64}$/);assert.equal(x.jobsFrozen,1);assert.equal(x.requestsFrozen,1);assert.equal(x.jobsPreserved,0);assert.equal(x.requestsPreserved,0);assert.equal(x.copyRequestsPreserved,0);assert.equal(x.privateWritesPending,1);assert.equal(x.privateWritesUncertain,0);assert.equal(x.definitionsVerified,true);assert.equal(x.rowIntegrityVerified,false);assert.equal(x.nativeDrainVerified,false);assert.equal(x.deleteAllowed,false);assert.equal(x.mode,'CURRENT_DECLARED_SQL_FREEZES_ATOMIC_NATIVE_DRAIN_UNKNOWN');facts.push(x);return x;}
try{server=await startEditorBackend(join(own,'wrangler.jsonc'),{stageSource:false,stageLibrary:false});const admin=await login('tianyi');await ok('/api/admin/accounts',{account:'freeze_owner'},admin);await ok('/api/admin/accounts',{account:'freeze_other'},admin);const owner=await login('freeze_owner'),other=await login('freeze_other');
 async function game(name){const g=await base({action:'create',name},owner);await action({action:'seed',gameId:g.gameId},admin);return g;}
 async function fenced(g){const f=await base({action:'fence',input:{gameId:g.gameId,expectedRowRevision:'1',confirmationName:g.name}},owner);return{gameId:g.gameId,expectedRowRevision:f.rowRevision};}
 const g=await game('原子定義'),firstInput={gameId:g.gameId,expectedRowRevision:'1'};await rejected({action:'freeze',input:firstInput},owner,409,'DELETE_FENCE_REQUIRED');await rejected({action:'freeze',input:firstInput},other,404,'GAME_NOT_FOUND');await rejected({action:'freeze',input:{gameId:'wolong-builtin',expectedRowRevision:'1'}},admin,403,'BUILTIN_PROTECTED');await rejected({action:'freeze',input:{...firstInput,plan:{}}},owner,422,'REQUEST_FIELDS');await rejected({action:'freeze',input:{gameId:[g.gameId],expectedRowRevision:'1'}},owner,422,'DELETE_SCHEMA_INPUT');const input=await fenced(g);await rejected({action:'freeze',input:firstInput},owner,409,'DELETE_SCHEMA_CHANGED');const unchanged=await state(g.gameId,admin);assert.equal(unchanged.rows.jobSeals.length,0);assert.equal(unchanged.rows.draftSeals.length,0);checks.push('real Root auth/owner/admin/builtin/strict fields/UUID/CAS/fence gates; rejected coordinator leaves original queued/pending and no seals. SQL skeleton is NOT Source/enqueue/save');
 for(const kind of ['check','fk','collation','unique','index','view','trigger']){await base({action:'mutate',kind},admin);await rejected({action:'freeze',input},owner,503,'DELETE_SCHEMA_DEFINITION');assert.deepEqual((await state(g.gameId,admin)).rows,unchanged.rows);await base({action:'restore'},admin);}checks.push('seven actual same-column definition changes rejected BEFORE original freezes; queuedJob/pendingDraft/journal/game and both absent seals remain exact, fixed owned restoration not migration');
 const x=fact(await action({action:'freeze',input},owner),input),done=await state(g.gameId,admin);assert.equal(done.rows.jobs[0].state,'failed');assert.equal(done.rows.jobs[0].generation,1);assert.equal(done.rows.jobs[0].row_revision,'2');assert.equal(done.rows.jobs[0].failure_code,'DELETION_FROZEN');assert.equal(done.rows.jobs[0].retryable,0);assert.equal(done.rows.drafts[0].state,'failed');assert.equal(done.rows.drafts[0].error_status,409);assert.equal(done.rows.drafts[0].error_code,'DELETION_FROZEN');assert.equal(done.rows.jobSeals.length,1);assert.equal(done.rows.draftSeals.length,1);assert.deepEqual(done.rows.writes,unchanged.rows.writes);assert.deepEqual(done.rows.game,unchanged.rows.game);assert.deepEqual(fact(await action({action:'freeze',input},admin),input),x);assert.deepEqual((await state(g.gameId,admin)).rows,done.rows);checks.push('actual original Job and Draft updates plus two HMAC seals jointly commit under fixed70 definitions, admin repeat rechecks originals; journal pending remains1/no native repair');
 for(const [kind,code,status]of [['index','DELETE_SCHEMA_DEFINITION',503],['row','DELETE_FENCE_CHANGED',409],['epoch','SESSION_INVALID',401],['tuple','DELETE_DEFINITION_FREEZE_ACTOR_CHANGED',401]]){const a=await game('晚到'+kind.slice(0,3)),target=await fenced(a),saved=await state(a.gameId,admin);await rejected({action:'freeze',input:target,hook:kind},admin,status,code);const rolled=await state(a.gameId,admin);assert.deepEqual(rolled.rows,saved.rows);assert.equal(rolled.hook.fired,true);assert.equal(rolled.hook.calls,kind==='index'||kind==='epoch'?6:5);checks.push(`owned internal ${kind} boundary after originalJob mutation: ${kind==='tuple'?'synthetic returnedprincipal identity probe':'actual native SQL mutation'} rejected exact${status}/${code}, outertransaction rolls back Job/Draft/seals/index/epoch/row; originals and pendingjournal exact`);}
 await rejected({action:'freeze',input},undefined,401,'LOGIN_REQUIRED');await rejected({action:'freeze',input},owner,403,'CSRF_REJECTED',{'X-CSRF-Token':'bad'});await rejected({action:'freeze',input},owner,403,'ORIGIN_REJECTED',{Origin:'https://example.invalid'});checks.push('real HTTP cookie/CSRF/Origin gates, new route only ownedfixture not productRoot');
 await server.close();server=await startEditorBackend(join(own,'wrangler.jsonc'),{stageSource:false,stageLibrary:false});assert.deepEqual(fact(await action({action:'freeze',input},owner),input),x);assert.deepEqual((await state(g.gameId,admin)).rows,done.rows);checks.push('actual workerd/DO restart: fresh definition/authority/seal/row rechecks preserve original committedfreeze/journal; no prior provider result adopted');
 const changed=await call('/api/auth/password',{oldPassword:password,newPassword:randomBytes(24).toString('hex')},owner);assert.equal(changed.status,200);await rejected({action:'freeze',input},owner,401,'SESSION_INVALID');fact(await action({action:'freeze',input},{cookie:changed.cookie,csrf:changed.data.csrf}),input);const missing=await call(`/api/games/${g.gameId}/delete`,{},admin);assert.equal(missing.status,404);checks.push('actual password epoch replacement refuses old coordinator requests, new session rechecks persistedfreeze; publicdelete404/no row/ref/native/physicalcleanup authority');
 const savedBootstrap=(await state(g.gameId,admin)).rows;await action({action:'drop-bootstrap'},admin);await rejected({action:'freeze',input},admin,503,'DELETE_SCHEMA_DEFINITION');assert.equal((await action({action:'restore-bootstrap'},admin)).wasAbsent,true);assert.deepEqual((await state(g.gameId,admin)).rows,savedBootstrap);checks.push('actual missing original freeze table rejected BEFORE original IF-NOT-EXISTS constructors; no silent reconstruction of discardedseal history, fixture restores exact originaltable/rows, no migration/repair admission');
 for(const[p,h]of Object.entries({...before.inputs,...before.imports,...sourceHashes}))assert.equal(sha(readFileSync(p)),h,p);process.stdout.write(JSON.stringify({result:'PASS-ACTUAL-DEFINITION-VERIFIED-SQL-FREEZE-NOT-DELETE',checks,calls,facts,protected:480,sourceHashes,limits:'Same nativeSQL pre/post current definitions plus originalJob/Draft freeze atomic only; engineered SQL rows not real enqueue/save/Source. Tuple probe synthetic. Old services unchanged/NOT automatically protected. No R2/row-ref closure/body/provider/CPU/legacy/delete/runtime/Trial/maincompletion.'},null,2)+'\n');
}catch(error){writeFileSync(d+'failure-r'+round+'.json',JSON.stringify({message:String(error.message),checks,calls,facts},null,2)+'\n',{flag:'wx'});throw error;}finally{await server?.close();}
