// Fake-port orchestration negatives ONLY. Native Root authorization/readback tested separately.
import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import {createHash} from 'node:crypto';import {collectFixedStageAssets} from '../server/stageassetcollection.js';
function parsed(b){try{return JSON.parse(b);}catch(cause){throw new Error('owned collection fixture JSON',{cause});}}
const out=process.argv[2];assert.match(out??'',/^\.dragon-analysis\/editor-phase\/backend-stage-asset-collection-session-r1\/model-r[1-9][0-9]*\.json$/);
const source='.dragon-analysis/editor-phase/backend-stage-asset-plan-session-r1/report-r2.json',r=parsed(readFileSync(source)),library=parsed(readFileSync(r.library.path)),sha=b=>createHash('sha256').update(b).digest('hex'),token='a'.repeat(64),request={gameId:r.gameId,draftRevision:'1',operations:Object.fromEntries(Object.entries(r.jobs).map(([p,j])=>[p,j.operationId]))},checks=[];
const clone=v=>parsed(JSON.stringify(v));
function setup(){const issued=new WeakMap(),state={reads:0,assertions:0,revoked:false,hook:null,latest:'1',reference:{gameId:r.gameId,draftRevision:'1',rootKey:r.snapshot.root_key,sourceDigest:r.snapshot.source_digest,dependencyDigest:r.snapshot.dependency_digest,createdAt:r.snapshot.created_at}},manifest=clone(library);const guard=()=>{state.assertions++;if(state.revoked)throw new Error('FAKE_ACTUAL_REVOKED');};const ports={games:{snapshotReference:(h,g,v)=>{guard();assert.equal(h,token);assert.equal(g,r.gameId);assert.equal(v,'1');return clone(state.reference);}},libraryAssets:{read:async(h,p,v)=>{assert.equal(h,token);assert.equal(p.gameId,r.gameId);assert.equal(v,'1');state.reads++;state.hook?.(state.reads);return {body:manifest,assertCurrent:guard};}},stageApi:{read:async(h,path)=>{guard();assert.equal(h,token);const job=clone(r.jobs[path.purpose]);let result;if(path.assetId){const a=r.artifacts[path.purpose];assert.equal(path.assetId,a.assetId);result={artifact:{assetId:a.assetId,sha256:a.sha256,bytes:Buffer.from(readFileSync(a.path))}};}else result={body:{admission:'stage-only',purpose:path.purpose,job}};issued.set(result,{path:clone(path),body:result.body?JSON.stringify(result.body):null,sha:result.artifact?sha(result.artifact.bytes):null});state.reads++;state.hook?.(state.reads,result);return result;},assertCurrent:(h,path,res)=>{guard();assert.equal(h,token);const expected=issued.get(res);assert.ok(expected,'FAKE_ISSUED_REQUIRED');assert.deepEqual(path,expected.path);if(res.body)assert.equal(JSON.stringify(res.body),expected.body,'FAKE_BODY_CHANGED');else assert.equal(sha(res.artifact.bytes),expected.sha,'FAKE_BYTES_CHANGED');}}};return {state,ports,manifest};}
async function test(name,fn){await fn();checks.push(name);}
await test('exact saved1 detached435/44/20 plan,13 fake awaitreads,server recheck and all runtime gatesfalse',async()=>{const {state,ports}=setup(),result=await collectFixedStageAssets(token,request,ports);assert.equal(state.reads,13);assert.ok(state.assertions>30);assert.equal(result.plan.artifacts.length,44);assert.equal(result.plan.roles.shared.length,398);assert.equal(result.plan.unresolvedReferences.length,20);assert.ok(Object.isFrozen(result)&&Object.isFrozen(result.plan));for(const k of ['runtimeAllowed','trialAllowed','releaseAllowed','deleteAllowed'])assert.equal(result[k],false);assert.equal(result.admission,'stage-plan-collection-not-runtime');result.assertCurrent();state.revoked=true;assert.throws(result.assertCurrent,/FAKE_ACTUAL_REVOKED/);});
for(let after=1;after<=13;after++)await test('revoked on return of awaited segment '+after+' rejects; no remaining reads/retry',async()=>{const {state,ports}=setup();state.hook=n=>{if(n===after)state.revoked=true;};await assert.rejects(collectFixedStageAssets(token,request,ports),/FAKE_ACTUAL_REVOKED/);assert.equal(state.reads,after);});
await test('latest2 ignored: exactold saved1 stillchosen, no latest/read or enqueue/run ports',async()=>{const {state,ports}=setup();state.latest='2';const p=await collectFixedStageAssets(token,request,ports);assert.equal(p.plan.reference.draftRevision,'1');assert.equal(state.reads,13);});
await test('mutated precise savedref afterawait rejects even if fake libraryguard omitsreference',async()=>{const {state,ports}=setup();state.hook=n=>{if(n===5)state.reference.sourceDigest='f'.repeat(64);};await assert.rejects(collectFixedStageAssets(token,request,ports),/STAGE_COLLECTION_SNAPSHOT_CHANGED/);assert.equal(state.reads,5);});
await test('changed manifest afterawait rejected before nextread even if fakeguard no DTO check',async()=>{const {state,ports,manifest}=setup();state.hook=n=>{if(n===7)manifest.sourceDigest='f'.repeat(64);};await assert.rejects(collectFixedStageAssets(token,request,ports),/STAGE_COLLECTION_LIBRARY_CHANGED/);assert.equal(state.reads,7);});
await test('mutated held job on nextreport return rejected by source port',async()=>{const {state,ports}=setup();let held;state.hook=(n,res)=>{if(n===2)held=res;if(n===3)held.body.job.rowRevision='999';};await assert.rejects(collectFixedStageAssets(token,request,ports),/FAKE_BODY_CHANGED/);assert.equal(state.reads,3);});
await test('mutated held rawreport later rejected by source byteassert',async()=>{const {state,ports}=setup();let held;state.hook=(n,res)=>{if(n===3)held=res;if(n===4)held.artifact.bytes[0]^=1;};await assert.rejects(collectFixedStageAssets(token,request,ports),/FAKE_BYTES_CHANGED/);assert.equal(state.reads,4);});
for(const [name,change,code]of [['extra request',v=>v.extra=true,'FIELDS'],['wrong game',v=>v.gameId='wolong-builtin','GAME'],['zero revision',v=>v.draftRevision='0','REVISION'],['65-digit revision',v=>v.draftRevision='9'.repeat(65),'REVISION'],['missing purpose',v=>delete v.operations.images,'FIELDS'],['duplicate operation',v=>v.operations.images=v.operations.data,'OPERATION'],['operation array',v=>v.operations.data=[v.operations.data],'OPERATION'],['extra operation',v=>v.operations.extra=v.operations.data,'FIELDS']])await test(name+' rejects before any read',async()=>{const s=setup(),v=clone(request);change(v);await assert.rejects(collectFixedStageAssets(token,v,s.ports),new RegExp('STAGE_COLLECTION_'+code));assert.equal(s.state.reads,0);});
await test('request accessors not invoked',async()=>{const s=setup(),v=clone(request);let calls=0;Object.defineProperty(v,'gameId',{get(){calls++;return request.gameId;},enumerable:true});await assert.rejects(collectFixedStageAssets(token,v,s.ports));assert.equal(calls,0);assert.equal(s.state.reads,0);});
await test('bad token rejected before any read',async()=>{const s=setup();await assert.rejects(collectFixedStageAssets('x',request,s.ports),/STAGE_COLLECTION_TOKEN/);assert.equal(s.state.reads,0);});
await test('missing currentresponse assertion rejected',async()=>{const s=setup();delete s.ports.stageApi.assertCurrent;await assert.rejects(collectFixedStageAssets(token,request,s.ports),/STAGE_COLLECTION_SERVER_PORTS/);assert.equal(s.state.reads,0);});
await test('library body DTO without captured server assertion rejected',async()=>{const s=setup();s.ports.libraryAssets.read=async()=>({body:clone(library)});await assert.rejects(collectFixedStageAssets(token,request,s.ports),/STAGE_COLLECTION_LIBRARY_RESPONSE/);});
await test('detached output cannot be changed through input ports or request',async()=>{const s=setup(),v=clone(request),result=await collectFixedStageAssets(token,v,s.ports);s.manifest.unresolvedReferences[0]={fake:true};v.gameId='x';assert.equal(result.plan.reference.gameId,r.gameId);assert.deepEqual(result.plan.unresolvedReferences,library.unresolvedReferences);assert.throws(result.assertCurrent,/STAGE_COLLECTION_LIBRARY_CHANGED/);});
await test('snapshot callback revokes identity: trailing original library assertion rejects',async()=>{const s=setup(),original=s.ports.games.snapshotReference;let calls=0;s.ports.games.snapshotReference=(...args)=>{const v=original(...args);if(++calls===2)s.state.revoked=true;return v;};await assert.rejects(collectFixedStageAssets(token,request,s.ports),/FAKE_ACTUAL_REVOKED/);assert.equal(s.state.reads,1);});
const sourceHashes=Object.fromEntries([source,r.library.path,...Object.values(r.artifacts).map(a=>a.path),'server/stageassetcollection.js','tools/verify_editor_backend_stage_asset_collection.mjs'].map(p=>[p,sha(readFileSync(p))]));writeFileSync(out,JSON.stringify({checks,sourceHashes,fakePorts:true,nativeRootAuthority:false,currentBytesVerified:false,rootIntegrated:false,runtimeManifestImplemented:false,trialAllowed:false,releaseAllowed:false,deleteAllowed:false},null,2)+'\n',{flag:'wx'});process.stdout.write(JSON.stringify({checks:checks.length,fakePorts:true,nativeRootAuthority:false})+'\n');
