// Actual owned Worker/SQLite/R2 observations, never delete permission or media bytes proof.
import assert from 'node:assert/strict';
import { readFileSync,writeFileSync,mkdtempSync } from 'node:fs';
import { join,resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { createHash,randomBytes,randomUUID } from 'node:crypto';
import { request as httpsRequest } from 'node:https';
import { startEditorBackend } from './start_editor_backend.mjs';
const round=process.argv[2];assert.match(round??'',/^[1-9][0-9]{0,2}$/);
const dir='.dragon-analysis/editor-phase/backend-deletion-inventory-session-r1/',origin='https://127.0.0.1:8787',own=mkdtempSync(join(tmpdir(),'dragon-deletion-inventory-')),sha=b=>createHash('sha256').update(b).digest('hex');
function parse(b){try{return JSON.parse(b);}catch(cause){throw new Error('owned inventory JSON',{cause});}}
const before=parse(readFileSync(dir+'before.json')),inputs=before.inputs;assert.equal(Object.keys(inputs).length,453);for(const[p,h]of Object.entries({...inputs,...before.imports}))assert.equal(sha(readFileSync(p)),h,p);
const sourceHashes=Object.fromEntries(['server/deletioninventory.js','tools/verify_editor_backend_deletion_inventory.mjs',dir+'fixture-worker.js'].map(p=>[p,sha(readFileSync(p))]));
const config=parse(readFileSync('server/wrangler.jsonc')),initial=randomBytes(24).toString('hex'),password=randomBytes(24).toString('hex');config.main=resolve(dir+'fixture-worker.js');writeFileSync(join(own,'wrangler.jsonc'),JSON.stringify(config),{flag:'wx'});writeFileSync(join(own,'.dev.vars'),'EDITOR_DEFAULT_PASSWORD='+JSON.stringify(initial)+'\nEDITOR_REQUEST_KEY='+JSON.stringify(randomBytes(32).toString('hex'))+'\n',{flag:'wx',mode:0o600});let server;const calls=[],checks=[],observations=[];
async function call(path,value,session,extra={}){const headers={Origin:origin,'Content-Type':'application/json','Idempotency-Key':randomUUID(),...extra};if(session){headers.Cookie=session.cookie;headers['X-CSRF-Token']=session.csrf;}const r=await new Promise((done,reject)=>{const req=httpsRequest(origin+path,{method:value===undefined?'GET':'POST',headers,rejectUnauthorized:false,agent:false},res=>{const b=[];res.on('data',v=>b.push(v));res.on('error',reject);res.on('end',()=>{try{done({status:res.statusCode,data:parse(Buffer.concat(b)),cookie:res.headers['set-cookie']?.[0]?.split(';')[0]});}catch(error){reject(error);}});});req.on('error',reject);req.end(value===undefined?undefined:JSON.stringify(value));});calls.push({path,status:r.status});return r;}
async function ok(path,value,session,extra){const r=await call(path,value,session,extra);assert.equal(r.status,200,r.data.error);return r.data;}
const inv=(v,s)=>call('/api/test/inventory',v,s),probe=(v,s)=>ok('/api/test/inventory',v,s),f=(v,s)=>ok('/api/test/fence',v,s);
async function observe(gameId,s){const r=await inv({action:'observe',gameId},s);assert.equal(r.status,200,r.data.error);const value=r.data.result;assert.equal(value.deleteAllowed,false);assert.equal(value.mode,'OBSERVED_METADATA_ONLY_NOT_DELETE_PLAN');assert.match(value.inventoryDigest,/^[a-f0-9]{64}$/);assert.deepEqual(Object.keys(value).sort(),['associatedRows','deleteAllowed','foreignRootReferences','gameId','intentRecords','inventoryDigest','missingReferences','mode','pendingRecords','privateListed','referencedHashes','rowRevision','sqlDigest','untrackedPrivateObjects'].sort());observations.push(value);return value;}
async function reject(v,s,status,code){const r=await inv(v,s);assert.equal(r.status,status);assert.equal(r.data.error,code);}
async function login(account){const r=await call('/api/auth/login',{account,password:initial});assert.equal(r.status,200);const changed=await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:r.cookie,csrf:r.data.csrf});assert.equal(changed.status,200);return{cookie:changed.cookie,csrf:changed.data.csrf};}
async function fenced(game,s){return f({action:'begin',input:{gameId:game.gameId,expectedRowRevision:game.rowRevision,confirmationName:game.metadata.name}},s);}
let admin;
try{
 server=await startEditorBackend(join(own,'wrangler.jsonc'),{stageSource:true,stageLibrary:true});admin=await login('tianyi');await ok('/api/admin/accounts',{account:'inventory_author'},admin);const author=await login('inventory_author');const opaque=(await f({action:'create',metadata:{name:'引用觀察',introduction:''}},author)).result,foreign=(await f({action:'create',metadata:{name:'隔離參照',introduction:''},marker:12},author)).result;
 await reject({action:'observe',gameId:'wolong-builtin'},admin,403,'BUILTIN_PROTECTED');await reject({action:'observe',gameId:opaque.gameId},admin,409,'DELETE_FENCE_REQUIRED');await reject({action:'observe',gameId:randomUUID()},author,404,'GAME_NOT_FOUND');await fenced(opaque,author);const initialStats=(await probe({action:'stats',gameId:opaque.gameId},admin)).result,root=initialStats.snapshots[0].root_key,hash=root.split('/').at(-1);await reject({action:'observe',gameId:[opaque.gameId]},admin,422,'GAME_ID');checks.push('actual owner/admin, builtin/UUID/unknown/mandatory durablefence and strict minimalsummary; no content or privatekeys returned');
 const first=await observe(opaque.gameId,author);assert.equal(first.privateListed,1);assert.equal(first.referencedHashes,1);assert.equal(first.missingReferences,0);assert.equal(first.untrackedPrivateObjects,0);const sharedBefore=first.inventoryDigest;await probe({action:'shared',hash},admin);assert.equal((await observe(opaque.gameId,admin)).inventoryDigest,sharedBefore);checks.push('real257B source plus actual installed/ sameSHA physicalothernamespace is notprivatecandidate/refcount; observer no sharedread/delete');
 await probe({action:'put',gameId:opaque.gameId,length:3},admin);const withOrphan=await observe(opaque.gameId,author);assert.equal(withOrphan.privateListed,2);assert.equal(withOrphan.untrackedPrivateObjects,1);await probe({action:'length',enabled:true,gameId:opaque.gameId,hash,length:258},admin);await reject({action:'observe',gameId:opaque.gameId},author,503,'DELETE_INVENTORY_LENGTH');await probe({action:'length',enabled:false,gameId:opaque.gameId},admin);await probe({action:'remove',key:root},admin);const missing=await observe(opaque.gameId,author);assert.equal(missing.missingReferences,1);assert.equal(missing.deleteAllowed,false); // Deliberate owned forensic damage; not production cleanup.
 await server.close();server=await startEditorBackend(join(own,'wrangler.jsonc'));const afterRestart=await observe(opaque.gameId,author);assert.equal(afterRestart.inventoryDigest,missing.inventoryDigest);assert.equal(afterRestart.missingReferences,1);checks.push('nativeorphan listed butnever authorised; conflictinglength rejects, fixture-onlymissingroot visible; trueworkerdrestart same observations without memoryplan');
 const foreignRoot=(await probe({action:'stats',gameId:foreign.gameId},admin)).result.snapshots[0].root_key;await probe({action:'foreign',enabled:true,target:opaque.gameId,foreign:foreign.gameId,hash},admin);assert.equal((await observe(opaque.gameId,admin)).foreignRootReferences,1);await probe({action:'foreign',enabled:false,foreign:foreign.gameId,restore:foreignRoot},admin);await probe({action:'schema',enabled:true},admin);await reject({action:'observe',gameId:opaque.gameId},admin,503,'DELETE_INVENTORY_SCHEMA');await probe({action:'schema',enabled:false},admin);const bad=(await probe({action:'put',gameId:opaque.gameId,badKey:true},admin)).result;await reject({action:'observe',gameId:opaque.gameId},admin,503,'DELETE_INVENTORY_OBJECT');await probe({action:'remove',key:bad.key},admin);checks.push('actualforeigngame root-key reference counted withoutotheridentity/content; newSQLschema failsclosed; malformedprivatekey metadata rejects, no deletioncapability');
 // Full pinned source and authentic current data/images Jobs, not an opaque stand-in.
 await ok('/api/admin/source/install',{},admin);await ok('/api/admin/library/install',{},admin);const source=(await ok('/api/admin/source',undefined,admin)).definition,copyKey=randomUUID();assert.equal((await call('/api/admin/copies',{registryId:source.registryId,name:'核清觀察',introduction:''},admin,{'Idempotency-Key':copyKey})).status,202);const copy=await ok('/api/admin/copies/'+copyKey+'/run',{},admin,{'If-Match':'"1"'}),gameId=copy.gameId;const saved=await ok('/api/games/'+gameId+'/draft/save',{metadata:{name:'保存觀察',introduction:''},resourceEdits:[]},admin,{'If-Match':'"1"'});assert.ok(saved);
 for(const purpose of ['data','images']){const q=await call('/api/games/'+gameId+'/stage-jobs/'+purpose,{draftRevision:'2',scope:'all'},admin);assert.equal(q.status,202);await ok('/api/games/'+gameId+'/stage-jobs/'+purpose+'/'+q.data.job.operationId+'/run',{},admin,{'If-Match':'"1"'});}
 const queued=await call('/api/games/'+gameId+'/stage-jobs/fallback-spring',{draftRevision:'2',scope:'all'},admin);assert.equal(queued.status,202); // queued is not in-flight or ready.
 const actualGame=(await ok('/api/games',undefined,admin)).games.find(g=>g.gameId===gameId);await fenced(actualGame,admin);await reject({action:'observe',gameId},author,404,'GAME_NOT_FOUND');const beforeStats=(await probe({action:'stats',gameId},admin)).result,full=await observe(gameId,admin),afterStats=(await probe({action:'stats',gameId},admin)).result;assert.deepEqual({...afterStats,listCalls:beforeStats.listCalls},beforeStats);assert.equal(full.missingReferences,0);assert.equal(full.untrackedPrivateObjects,0);assert.ok(full.privateListed>60);assert.equal(full.privateListed,full.referencedHashes);assert.ok(full.associatedRows>full.privateListed);assert.ok(afterStats.listCalls-beforeStats.listCalls>2);assert.equal(beforeStats.snapshots.length,2);checks.push('actual20chapter fullcopy/baseline, saved2refs, real data29 and images7 outputs plus queuedfallback; forcednative2itempagination two completepasses; exactbefore-afterSQL/R2sharedfacts unchanged, bodyhash/heap/SLA notclaimed');
 for(const [kind,code]of [['cursor','DELETE_INVENTORY_CURSOR'],['duplicate','DELETE_INVENTORY_OBJECT'],['outside','DELETE_INVENTORY_OBJECT'],['type','DELETE_INVENTORY_LIST'],['null','DELETE_INVENTORY_OBJECT']]){await probe({action:'list-fault',kind},admin);await reject({action:'observe',gameId},admin,503,code);await probe({action:'list-fault',kind:null},admin);}assert.equal((await observe(gameId,admin)).inventoryDigest,full.inventoryDigest);checks.push('five separatelyinjected actualnative-list envelopefaults: repeatedcursor/duplicate/outsideprefix/truncatedtype/nullentry exact503, nopartialsuccess; actualforeignauthor404 afterfence beforeinventory');
 // Controlled list awaits preserve actual response; never stitch two inconsistent scans.
 await probe({action:'pause'},admin);const sqlPending=inv({action:'observe',gameId},admin);for(let i=0;i<200;i++){if((await f({action:'control'},admin)).result.waiting)break;await new Promise(done=>setTimeout(done,10));}assert.equal((await f({action:'control'},admin)).result.waiting,true);await probe({action:'sql-change',gameId},admin);await f({action:'release'},admin);const sqlResult=await sqlPending;assert.equal(sqlResult.status,409);assert.equal(sqlResult.data.error,'DELETE_INVENTORY_CHANGED');
 await probe({action:'pause'},admin);const objectPending=inv({action:'observe',gameId:opaque.gameId},admin);for(let i=0;i<200;i++){if((await f({action:'control'},admin)).result.waiting)break;await new Promise(done=>setTimeout(done,10));}assert.equal((await f({action:'control'},admin)).result.waiting,true);await probe({action:'put',gameId:opaque.gameId,length:4},admin);await f({action:'release'},admin);const objectResult=await objectPending;assert.equal(objectResult.status,409);assert.equal(objectResult.data.error,'DELETE_INVENTORY_OBJECTS_CHANGED');checks.push('controlledactualfirstR2listresponse then SQLmutation or appendedorphan; lateSQLchanged / two-list metadatachanged exact409, no partial inventorysuccess');
 await probe({action:'pause'},admin);const epochPending=inv({action:'observe',gameId},admin);for(let i=0;i<200;i++){if((await f({action:'control'},admin)).result.waiting)break;await new Promise(done=>setTimeout(done,10));}assert.equal((await f({action:'control'},admin)).result.waiting,true);const next=randomBytes(24).toString('hex'),changed=await call('/api/auth/password',{oldPassword:password,newPassword:next},admin);assert.equal(changed.status,200);admin={cookie:changed.cookie,csrf:changed.data.csrf};await f({action:'release'},admin);const epochResult=await epochPending;assert.equal(epochResult.status,401);assert.equal(epochResult.data.error,'SESSION_INVALID');const resumed=await observe(gameId,admin);assert.equal(resumed.deleteAllowed,false);checks.push('actualpasswordhandler while native listawait revokes oldsession; newepoch fresh observation stillfenced, notresume-capability orcompleteddelete');
 for(const[p,h]of Object.entries({...inputs,...before.imports,...sourceHashes}))assert.equal(sha(readFileSync(p)),h,p);process.stdout.write(JSON.stringify({result:'PASS-ACTUAL-DELETION-INVENTORY-NOT-CLEANUP',checks,calls,observations,sourceHashes,protected:453,limits:'Metadata-only read-only observations. Native owned fixture removals only fault injection. No production delete/get-body-SHA/crossservice atomicity/drain/refscrub/fullbackup/cache/player410/Trial/release or overallcompletion.'},null,2)+'\n');
}catch(error){writeFileSync(dir+'failure-r'+round+'.json',JSON.stringify({checks,calls,sourceHashes,error:{message:error.message,code:error.code??null}},null,2)+'\n',{flag:'wx'});throw error;}finally{await server?.close();}
