// Fixed actual library PNGs, independent Pillow pixels, and actual workerd adapter. No runtime grant.
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, realpathSync } from 'node:fs';
import { resolve, relative, isAbsolute } from 'node:path';
import { pathToFileURL } from 'node:url';
import { createHash } from 'node:crypto';
import { deflateSync, crc32 } from 'node:zlib';
import { spawnSync } from 'node:child_process';
import { decodePNG, PNGError, PNG_IO_REVISION } from '../server/pngio.js';
import { FIXED_TRIAL_ASSET_PATHS } from '../web/src/editor/trialassetpaths.js';
const d='.dragon-analysis/editor-phase/backend-library-png-session-r1/',sha=b=>createHash('sha256').update(b).digest('hex'),hash=p=>sha(readFileSync(p));
function json(bytes){try{return JSON.parse(bytes.toString());}catch(cause){throw new Error('invalid owned PNG JSON',{cause});}}
const before=json(readFileSync(d+'before.json')),changed=new Set(['server/pngio.js','server/copyimages.js','tools/verify_editor_backend_png_io.mjs','tools/verify_editor_backend_image_jobs.mjs']);assert.equal(Object.keys(before.inputs).length,433);
for(const[p,h]of Object.entries(before.inputs))if(!changed.has(p))assert.equal(hash(p),h,p);
const sources=[...changed,'tools/verify_editor_backend_library_png.mjs','tools/verify_editor_library_png_oracle.py',d+'fixture-worker.js','server/available-library.txt','server/wrangler.jsonc'],sourceHashes=Object.fromEntries(sources.map(p=>[p,hash(p)]));
assert.equal(hash('server/available-library.txt'),'76cdf28d1cc6099ccd9f2e7c60085ed6694be6a7509f72c41960d63648cfd2e0');const manifest=json(readFileSync('server/available-library.txt'));assert.deepEqual(Object.keys(manifest.resources).sort(),FIXED_TRIAL_ASSET_PATHS);for(const[p,h]of Object.entries(manifest.programHashes))assert.equal(hash(p),h,p);
const root=realpathSync('.');function file(p){const path=realpathSync(resolve(p)),rel=relative(root,path);assert.ok(!rel.startsWith('..')&&!isAbsolute(rel));return readFileSync(path);}
const cases=[];for(const[p,row]of Object.entries(manifest.resources)){if(!p.endsWith('.png'))continue;const path='web/'+p,bytes=file(path);assert.equal(bytes.length,row.byteLength);assert.equal(sha(bytes),row.sha256);cases.push({path,bytes});}assert.equal(cases.length,376);
for(const season of['spring','summer','autumn','winter']){const path='web/map_atlas_'+season+'.png';cases.push({path,bytes:file(path)});}const world=json(readFileSync('server/pinned/world-manifest.txt'));for(const asset of world.assets.filter(row=>['minimap_base.png','minimap_large.png'].includes(row.path))){const path='web/'+asset.url,bytes=file(path);assert.equal(bytes.length,asset.byteLength);assert.equal(sha(bytes),asset.sha256);cases.push({path,bytes});}assert.equal(cases.length,382);
const signature=Buffer.from('89504e470d0a1a0a','hex');function chunk(kind,body){const b=Buffer.concat([Buffer.from(kind),body]),size=Buffer.alloc(4),sum=Buffer.alloc(4);size.writeUInt32BE(body.length);sum.writeUInt32BE(crc32(b));return Buffer.concat([size,b,sum]);}function header(w,h,depth,type=3){const b=Buffer.alloc(13);b.writeUInt32BE(w);b.writeUInt32BE(h,4);b[8]=depth;b[9]=type;return b;}function png(h,raw,palette,alpha,compressed=deflateSync(raw)){return Buffer.concat([signature,chunk('IHDR',h),...(palette?[chunk('PLTE',palette)]:[]),...(alpha?[chunk('tRNS',alpha)]:[]),chunk('IDAT',compressed),chunk('IEND',Buffer.alloc(0))]);}
// Independent packed sample/filter fixture producer, five rows exercise every PNG row filter.
function packed(depth,width){const colors=2**depth,palette=Buffer.from(Array.from({length:colors*3},(_,i)=>(i*37+19)%256)),alpha=Buffer.from(Array.from({length:colors},(_,i)=>i===0?0:(i*53)%256)),stride=Math.ceil(width*depth/8),raw=[];let prior=Buffer.alloc(stride);for(let y=0;y<5;y++){const row=Buffer.alloc(stride,255);for(let x=0;x<width;x++){const shift=8-depth-(x*depth%8),at=Math.floor(x*depth/8),mask=(colors-1)<<shift;row[at]=(row[at]&~mask)|(((x*7+y*3)%colors)<<shift);}raw.push(y);for(let x=0;x<stride;x++){const a=row[x-1]??0,b=prior[x],c=prior[x-1]??0;let prediction=0;if(y===1)prediction=a;else if(y===2)prediction=b;else if(y===3)prediction=Math.floor((a+b)/2);else if(y===4)prediction=[a,b,c].map((value,index)=>({value,index,distance:Math.abs(a+b-c-value)})).sort((l,r)=>l.distance-r.distance||l.index-r.index)[0].value;raw.push((row[x]-prediction)&255);}prior=row;}return png(header(width,5,depth),Buffer.from(raw),palette,alpha);}
for(const depth of[1,2,4])for(const width of[1,3,8,9]){const path=d+'fixture-'+String(1000+cases.length-382)+'.png',bytes=packed(depth,width);writeFileSync(path,bytes,{flag:'wx'});cases.push({path,bytes});}
const negatives=[];for(const depth of[1,2,4]){const stride=Math.ceil(9*depth/8),palette=Buffer.from([11,22,33]);negatives.push(['palette-index-'+depth,png(header(1,1,depth),Buffer.from([0,1<<(8-depth)]),palette),'PNG_PALETTE_INDEX']);negatives.push(['packed-short-'+depth,png(header(9,1,depth),Buffer.alloc(stride),palette),'PNG_SCANLINE_LENGTH']);negatives.push(['packed-extra-'+depth,png(header(9,1,depth),Buffer.alloc(stride+2),palette),'PNG_DEFLATE']);negatives.push(['palette-depth-budget-'+depth,png(header(1,1,depth),Buffer.alloc(2),Buffer.alloc((2**depth+1)*3)),'PNG_PALETTE']);}
const h=header(1,1,4),raw=Buffer.alloc(2),palette=Buffer.from([11,22,33]),stream=deflateSync(raw);negatives.push(['gray4',png(header(1,1,4,0),Buffer.alloc(2)),'PNG_UNSUPPORTED_FORMAT'],['depth3',png(header(1,1,3),raw,palette),'PNG_UNSUPPORTED_FORMAT'],['alpha-palette',png(h,raw,palette,Buffer.from([0,255])),'PNG_TRANSPARENCY'],['packed-filter5',png(h,Buffer.from([5,0]),palette),'PNG_FILTER'],['packed-deflate-tail',png(h,raw,palette,null,Buffer.concat([stream,Buffer.from([1])])),'PNG_DEFLATE_TRAILING']);const badCRC=Buffer.from(cases[382].bytes);badCRC[29]^=1;negatives.push(['packed-crc',badCRC,'PNG_CRC']);
const env={};for(const k of['SystemRoot','SYSTEMROOT','WINDIR','COMSPEC','ComSpec','PATH','Path','PATHEXT','TEMP','TMP','USERPROFILE','LOCALAPPDATA','APPDATA','HOMEDRIVE','HOMEPATH'])if(process.env[k]!==undefined)env[k]=process.env[k];env.PYTHONUTF8='1';env.PYTHONDONTWRITEBYTECODE='1';const oracle=spawnSync('python',['-B','tools/verify_editor_library_png_oracle.py'],{env,input:JSON.stringify(cases.map(c=>c.path)),encoding:'utf8',timeout:60000,maxBuffer:4194304});writeFileSync(d+'oracle-r1.stdout',oracle.stdout??'',{flag:'wx'});writeFileSync(d+'oracle-r1.stderr',oracle.stderr??'',{flag:'wx'});assert.equal(oracle.status,0,oracle.stderr);assert.equal(oracle.signal,null);assert.equal(oracle.error,undefined);const reference=json(Buffer.from(oracle.stdout));assert.equal(reference.results.length,394);
let mf;const calls=[],checks=[],images=[];try{const{Miniflare}=await import(pathToFileURL(process.env.MINIFLARE_MODULE).href),config=json(readFileSync('server/wrangler.jsonc'));mf=new Miniflare({modules:true,modulesRules:[{type:'ESModule',include:['**/*.js','**/*.mjs']}],scriptPath:resolve(d+'fixture-worker.js'),compatibilityDate:config.compatibility_date,compatibilityFlags:config.compatibility_flags,host:'127.0.0.1',port:0});const origin=await mf.ready;
async function worker(bytes){const response=await fetch(new URL('/decode',origin),{method:'POST',body:bytes});calls.push({path:'/decode',status:response.status});return{status:response.status,data:json(Buffer.from(await response.arrayBuffer()))};}
for(let i=0;i<cases.length;i++){const c=cases[i],expected=reference.results[i];assert.equal(expected.path,c.path);assert.equal(expected.byteSha,sha(c.bytes));const result=decodePNG(c.bytes);assert.deepEqual({width:result.width,height:result.height,pixelSha:sha(result.pixels)},{width:expected.width,height:expected.height,pixelSha:expected.pixelSha},c.path);const actual=await worker(c.bytes);assert.equal(actual.status,200,c.path);assert.deepEqual(actual.data,{revision:PNG_IO_REVISION,width:expected.width,height:expected.height,pixelSha:expected.pixelSha},c.path);images.push(expected);}
checks.push('376 pinned available PNGs plus four atlases/two minis: actual Node/workerd raw RGBA full SHA/dimensions equal independent Pillow, including all168 indexed4 assets without rewriting bytes');checks.push('12 independent indexed1/2/4 packed fixtures: edge widths1/3/8/9, every filter, row byte rounding and arbitrary padding, nonzero RGB at alpha0 preserved');for(const[name,bytes,code]of negatives){assert.throws(()=>decodePNG(bytes),error=>error instanceof PNGError&&error.code===code,name);const actual=await worker(bytes);assert.equal(actual.status,422,name);assert.equal(actual.data.error,code,name);}checks.push('18 exact Node/workerd packed-format negatives: out-of-palette samples/depth-size/scanlines/alpha/filter/CRC/trailingdeflate and unsupported gray4/depth3 remain failclosed');
for(const c of cases)assert.equal(hash(c.path),sha(c.bytes),c.path);for(const[p,h]of Object.entries(before.inputs))if(!changed.has(p))assert.equal(hash(p),h,p);for(const[p,h]of Object.entries(sourceHashes))assert.equal(hash(p),h,p);process.stdout.write(JSON.stringify({result:'PASS-FIXED-LIBRARY-PNG-NODE-WORKER-PIXELS',revision:PNG_IO_REVISION,checks,calls,sourceHashes,manifestSha:hash('server/available-library.txt'),images,fixedPNGCount:376,additionalFixedCount:6,packedFixtures:12,negatives:18,unchangedInputs:429,limits:'Fixed raw samples only; no authenticated asset service, full fallback/audio/consumer closure, Q69/runtime/Trial/Release/cloudSLA or fullgoal completion.'},null,2)+'\n');}finally{await mf?.dispose();}
