// SAME MusicPlayer optional resource ports; fake decoder/authority, NOT native authorization.
import assert from 'node:assert/strict';import {MusicPlayer} from '../web/src/core/music.js';import {writeFileSync,readFileSync} from 'node:fs';import {createHash} from 'node:crypto';
const d='.dragon-analysis/editor-phase/music-resource-ports-session-r1/',round=process.argv[2];assert.match(round??'',/^[1-9][0-9]{0,2}$/);const checks=[],hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex'),manifest={tracks:[2,3].map(index=>({index,file:index+'.flac',loopStart:2,loopEnd:4}))};function setup(){const events=[],sources=[],handles=[];let valid=true,pendingManifest,pendingBuffer,failStart=false;const context={state:'running',currentTime:0,destination:{},resume:async()=>{},createGain:()=>({gain:{cancelScheduledValues(){},setValueAtTime(v,t){events.push(['gain',v,t]);}},disconnect(){},connect(){}}),createBufferSource(){const s={connect:g=>g,start(){if(failStart)throw new Error('start');s.started=true;},stop(){s.stopped=true;},disconnect(){}};sources.push(s);return s;},decodeAudioData(){throw new Error('static decode forbidden');}},ports={assertCurrent(){if(!valid)throw new Error('scope revoked');},async loadManifest(ctx){assert.equal(ctx,context);events.push('manifest');return pendingManifest??manifest;},async loadBuffer(item,ctx){assert.equal(ctx,context);events.push(['buffer',item.index]);if(pendingBuffer)return pendingBuffer;const h={buffer:{duration:4,sampleRate:49700},disposed:false,dispose(){h.disposed=true;}};handles.push(h);return h;}},p=new MusicPlayer({context:()=>context,fetcher(){throw new Error('static fallback forbidden');},resourcePorts:ports});return {p,context,ports,events,sources,handles,revoke(){valid=false;},pendingM(x){pendingManifest=x;},pendingB(x){pendingBuffer=x;},startFailure(x){failStart=x;}};}const flush=()=>new Promise(r=>setImmediate(r));function deferred(){let resolve;return {promise:new Promise(r=>resolve=r),resolve:v=>resolve(v)};}
assert.throws(()=>new MusicPlayer({context:()=>null,resourcePorts:{}}),/music resource ports/);checks.push('invalid trusted port shape rejected, not authority');
let s=setup();s.p.select(2);await flush();assert.ok(s.p.source?.started);assert.equal(s.p.source.loop,true);assert.equal(s.p.source.loopStart,2);assert.equal(s.p.source.loopEnd,4);assert.equal(s.p.cache,null);assert.deepEqual(s.events.filter(e=>typeof e==='string'),['manifest']);checks.push('same loop/player through ports, no staticfetch/decode or private settledcache');
const first=s.p.source;s.p.select(2);await flush();for(const type of [2,3,4]){s.p.setType(type);await flush();assert.equal(s.p.source,first);}assert.equal(s.handles.length,1);checks.push('same selection and CF9 attenuation preserve current phase, no unnecessary read');
s.p.setType(0);assert.equal(s.p.source,null);assert.equal(s.handles[0].disposed,true);s.p.setType(1);await flush();assert.ok(s.p.source);assert.equal(s.handles.length,2);assert.equal(s.events.filter(e=>e==='manifest').length,2);checks.push('stop disposes ownedhandle, restart re-enters BOTH ports, not oldtrack cache');
const current=s.p.source,old=s.sources[0];old.onended();assert.equal(s.p.source,current);assert.equal(s.p.resourceHandle,s.handles[1]);checks.push('old onended does not release or clear NEW ownedhandle/source');
s.p.source.onended();assert.equal(s.p.resourceHandle,null);assert.equal(s.handles[1].disposed,true);checks.push('natural end releases only associated handle');
s=setup();const a=deferred();s.pendingB(a.promise);s.p.select(2);await flush();s.pendingB(null);s.p.select(3);await flush();const newSource=s.p.source,h={buffer:{duration:4,sampleRate:49700},disposed:false,dispose(){h.disposed=true;}};a.resolve(h);await flush();assert.equal(s.p.source,newSource);assert.equal(h.disposed,true);checks.push('late old buffer after selectionchange disposed, not newscene resurrection');
s=setup();const m=deferred();s.pendingM(m.promise);s.p.select(2);await flush();s.p.setType(0);m.resolve(manifest);await flush();assert.equal(s.handles.length,0);assert.equal(s.p.source,null);checks.push('late manifest afterstop never calls decoder/track port');
s=setup();const late=deferred();s.pendingB(late.promise);s.p.select(2);await flush();s.revoke();const lateHandle={buffer:{duration:4,sampleRate:49700},disposed:false,dispose(){lateHandle.disposed=true;}};late.resolve(lateHandle);await flush();assert.equal(s.p.source,null);assert.equal(lateHandle.disposed,true);checks.push('local scope changed duringbuffer await rejects and releases, no auto retry');
s=setup();s.p.select(2);await flush();s.revoke();await s.p.ensurePlaying();assert.equal(s.p.source,null);assert.equal(s.handles[0].disposed,true);checks.push('explicit ensure with invalid local scope stops cached activevoice, NOT remote status polling');
s=setup();s.startFailure(true);s.p.select(2);await flush();assert.equal(s.p.source,null);assert.equal(s.handles[0].disposed,true);s.startFailure(false);await s.p.ensurePlaying();assert.ok(s.p.source);assert.equal(s.handles.length,2);checks.push('native source.start failure releaseshandle, next EXPLICIT attempt fresh ports');
s=setup();s.ports.loadBuffer=async()=>{throw new Error('HTTP401 fake');};s.p.select(2);await flush();assert.ok(s.p.source);checks.push('trusted port function replacement after construction does not change captured contract');
const failContext=s.context;let attempts=0;const failed=new MusicPlayer({context:()=>failContext,fetcher(){throw new Error('public fallback forbidden');},resourcePorts:{assertCurrent(){},loadManifest:async()=>manifest,loadBuffer:async()=>{attempts++;throw new Error('HTTP401 fake');}}});failed.select(2);await flush();assert.equal(attempts,1);assert.equal(failed.source,null);assert.equal(failed.loading,null);await failed.ensurePlaying();assert.equal(attempts,2);checks.push('failed401-shaped port audio-only, no fallback/autoretry; explicit current attempt may retry');
s=setup();s.pendingB({buffer:{duration:1,sampleRate:49700},disposed:false,dispose(){this.disposed=true;}});s.p.select(2);await flush();assert.equal(s.p.source,null);checks.push('original invalidloop bound rejects decoded portbuffer');
s=setup();s.context.state='suspended';s.p.select(2);await flush();assert.equal(s.events.length,0);checks.push('original running-context gate blocks ports before network');
s=setup();const cm=deferred();s.pendingM(cm.promise);s.p.select(2);await flush();s.p.context=()=>({state:'running'});cm.resolve(manifest);await flush();assert.equal(s.handles.length,0);assert.equal(s.p.source,null);checks.push('different native context at manifest await rejected before buffer');
s=setup();s.p.select(2);await flush();s.p.setEnabled(false);assert.equal(s.handles[0].disposed,true);s.p.setEnabled(true);await flush();assert.equal(s.handles.length,2);checks.push('mute release then unmute explicit startup fetches fresh manifest/buffer');
const sourceHashes=Object.fromEntries(['web/src/core/music.js','tools/verify_music_resource_ports.mjs'].map(p=>[p,hash(p)]));writeFileSync(d+'model-r'+round+'.json',JSON.stringify({checks,sourceHashes,fakeResourcePorts:true,actualCommonMusicPlayer:true,nativeAuthority:false,actualBrowser:false,runtimeManifestImplemented:false,ruleExecution:false},null,2)+'\n',{flag:'wx'});process.stdout.write(JSON.stringify({checks:checks.length})+'\n');
