// Actual Root authority with owned SQL-only native unique-key probes; no Source/provider/delete.
import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdtempSync} from 'node:fs';import {resolve,join} from 'node:path';import {tmpdir} from 'node:os';import {createHash,randomBytes,randomUUID} from 'node:crypto';import {request as httpsRequest} from 'node:https';import {startEditorBackend} from './start_editor_backend.mjs';
const d='.dragon-analysis/editor-phase/backend-declared-unique-rows-session-r1/',round=process.argv[2],origin='https://127.0.0.1:8787';assert.match(round??'',/^[1-9][0-9]{0,2}$/);const hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex');function parse(b){try{return JSON.parse(b);}catch(cause){throw new Error('owned unique-key JSON',{cause});}}
const before=parse(readFileSync(d+'before.json'));for(const[p,h]of Object.entries({...before.inputs,...before.imports}))assert.equal(hash(p),h,p);const paths=['server/deletionuniquerows.js','tools/verify_editor_backend_declared_unique_rows.mjs',d+'fixture-worker.js','server/deletionschemaintegrity.js','server/deletiondefinitions.js','server/worker.js','.dragon-analysis/editor-phase/backend-deletion-definitions-session-r1/fixture-worker.js'],sourceHashes=Object.fromEntries(paths.map(p=>[p,hash(p)]));
const own=mkdtempSync(join(tmpdir(),'dragon-unique-rows-')),config=parse(readFileSync('server/wrangler.jsonc')),initial=randomBytes(24).toString('hex'),password=randomBytes(24).toString('hex');config.main=resolve(d+'fixture-worker.js');writeFileSync(join(own,'wrangler.jsonc'),JSON.stringify(config),{flag:'wx'});writeFileSync(join(own,'.dev.vars'),`EDITOR_DEFAULT_PASSWORD=${JSON.stringify(initial)}\nEDITOR_REQUEST_KEY=${JSON.stringify(randomBytes(32).toString('hex'))}\n`,{flag:'wx',mode:0o600});const checks=[],calls=[],facts=[];let server;
async function call(path,value,session,extra={}){const headers={Origin:origin,'Content-Type':'application/json','Idempotency-Key':randomUUID()};if(session){headers.Cookie=session.cookie;headers['X-CSRF-Token']=session.csrf;}Object.assign(headers,extra);const r=await new Promise((done,reject)=>{const req=httpsRequest(origin+path,{method:value===undefined?'GET':'POST',headers,rejectUnauthorized:false,agent:false},res=>{const chunks=[];res.on('data',b=>chunks.push(b));res.on('error',reject);res.on('end',()=>{try{done({status:res.statusCode,data:parse(Buffer.concat(chunks)),cookie:res.headers['set-cookie']?.[0]?.split(';')[0]});}catch(error){reject(error);}});});req.on('error',reject);req.end(value===undefined?undefined:JSON.stringify(value));});calls.push({path,status:r.status});return r;}
async function ok(path,v,s,x){const r=await call(path,v,s,x);assert.equal(r.status,200,r.data.error);return r.data.result??r.data;}const action=(v,s)=>ok('/api/test/unique-rows',v,s),base=(v,s)=>ok('/api/test/definitions',v,s);
async function reject(v,s,status,code,extra){const r=await call('/api/test/unique-rows',v,s,extra);assert.equal(r.status,status,r.data.error);assert.equal(r.data.error,code);}
async function login(account){const r=await call('/api/auth/login',{account,password:initial});assert.equal(r.status,200);const p=await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:r.cookie,csrf:r.data.csrf});assert.equal(p.status,200);return{cookie:p.cookie,csrf:p.data.csrf};}
function fact(x,input){assert.equal(Object.keys(x).length,13);assert.equal(x.gameId,input.gameId);assert.equal(x.rowRevision,input.expectedRowRevision);assert.match(x.schemaDigest,/^[a-f0-9]{64}$/);assert.equal(x.tablesVerified,35);assert.equal(x.indexesVerified,35);assert.equal(x.foreignKeyDeclarationsVerified,3);assert.equal(x.definitionsVerified,true);assert.equal(x.uniqueKeysVerified,true);assert.equal(x.uniqueConstraintsVerified,35);assert.equal(x.rowIntegrityVerified,false);assert.equal(x.nativeDrainVerified,false);assert.equal(x.deleteAllowed,false);assert.equal(x.mode,'CURRENT_DECLARED_UNIQUE_KEYS_ONLY_LEGACY_UNKNOWN');facts.push(x);return x;}
try{
 server=await startEditorBackend(join(own,'wrangler.jsonc'),{stageSource:false,stageLibrary:false});const admin=await login('tianyi');await ok('/api/admin/accounts',{account:'unique_owner'},admin);await ok('/api/admin/accounts',{account:'unique_other'},admin);const owner=await login('unique_owner'),other=await login('unique_other'),g=await base({action:'create',name:'唯一實查'},owner),first={gameId:g.gameId,expectedRowRevision:'1'};
 await reject({action:'observe',input:first},owner,409,'DELETE_FENCE_REQUIRED');await reject({action:'observe',input:first},other,404,'GAME_NOT_FOUND');await reject({action:'observe',input:{gameId:'wolong-builtin',expectedRowRevision:'1'}},admin,403,'BUILTIN_PROTECTED');await reject({action:'observe',input:{...first,plan:{}}},owner,422,'REQUEST_FIELDS');await reject({action:'observe',input:{gameId:[g.gameId],expectedRowRevision:'1'}},owner,422,'DELETE_SCHEMA_INPUT');const f=await base({action:'fence',input:{...first,confirmationName:g.name}},owner),input={gameId:g.gameId,expectedRowRevision:f.rowRevision};await reject({action:'observe',input:first},owner,409,'DELETE_SCHEMA_CHANGED');checks.push('actual owner/admin/foreign/builtin/UUID/strictfield/CAS/fence; SQL skeleton NOT normal creation or Source');
 await action({action:'seed',gameId:g.gameId},admin);const saved=await action({action:'state'},admin),x=fact(await action({action:'observe',input},owner),input);assert.deepEqual(fact(await action({action:'observe',input},admin),input),x);assert.equal((await action({action:'state'},admin)).digest,saved.digest);checks.push('native35 declared BINARY unique keys over33 tables, NOT INDEXED marker budgets and SQL GROUP/HAVING; two full scans, exact13 owner/admin facts without global rows/values/indexdata certificate, unchanged metadata');
 const constraint=await action({action:'constraint'},admin);assert.equal(constraint.providerRejected,true);assert.match(constraint.message,/^UNIQUE constraint failed: content_names.owner_id, content_names.name/);checks.push('actual original native UNIQUE still rejects normal duplicate INSERT; temporary low-level duplicate controls below do NOT prove Root bypass or persisted native index corruption');
 assert.deepEqual(fact(await action({action:'nullable',input},admin),input),x);assert.equal((await action({action:'state'},admin)).digest,saved.digest);checks.push('native two NULL TEXT PK rows allowed under current exact declared schema; UNIQUE semantics skips NULL, NOT NULL/businessrow validity remains separate, only owned fixture removes its rows');
 for(const kind of ['composite','simple']){await reject({action:'duplicate',kind,input},admin,503,'DELETE_UNIQUE_ROWS');const s=await action({action:'state'},admin);assert.equal(s.digest,saved.digest);assert.equal(s.schema,saved.schema);checks.push('temporary actual native '+kind+' duplicate after only owned table constraint removal detected by low-level fixed NOT INDEXED GROUP predicate and complete schema/row rollback; not fullservice or retained corrupted-index evidence');}
 await reject({action:'duplicate',kind:'composite',input,full:true},admin,503,'DELETE_SCHEMA_DEFINITION');assert.equal((await action({action:'state'},admin)).schema,saved.schema);checks.push('fullservice rejects temporary removed constraint BEFORE duplicate scan; no rederived schema or relaxed declarations');
 for(const[kind,status,code]of [['index',503,'DELETE_SCHEMA_DEFINITION'],['row',409,'DELETE_FENCE_CHANGED'],['epoch',401,'SESSION_INVALID'],['tuple',401,'DELETE_UNIQUE_ACTOR_CHANGED'],['budget',503,'DELETE_UNIQUE_BUDGET']]){await reject({action:'observe',input,hook:kind},admin,status,code);const s=await action({action:'state'},admin);assert.equal(s.digest,saved.digest);assert.equal(s.schema,saved.schema);assert.equal(s.hook.fired,true);checks.push('actual scan-boundary '+kind+' '+(kind==='tuple'?'synthetic returned role':'native SQL')+' exact'+status+'/'+code+' entire rollback; latebudget after first full scan is caught by callback-free second scan, not immutable receipt');}
 await reject({action:'budget',input},admin,503,'DELETE_UNIQUE_BUDGET');assert.equal((await action({action:'state'},admin)).digest,saved.digest);checks.push('actual10001 engine-only valid-parent expired session keys exceed per-table marker budget; own transaction rolls back, no service clear/retry/expanded threshold');
 await reject({action:'observe',input},undefined,401,'LOGIN_REQUIRED');await reject({action:'observe',input},owner,403,'CSRF_REJECTED',{'X-CSRF-Token':'bad'});await reject({action:'observe',input},owner,403,'ORIGIN_REJECTED',{Origin:'https://example.invalid'});checks.push('real Cookie/CSRF/Origin at owned fixture route, no new product API');
 await server.close();server=await startEditorBackend(join(own,'wrangler.jsonc'),{stageSource:false,stageLibrary:false});assert.deepEqual(fact(await action({action:'observe',input},owner),input),x);const changed=await call('/api/auth/password',{oldPassword:password,newPassword:randomBytes(24).toString('hex')},owner);assert.equal(changed.status,200);await reject({action:'observe',input},owner,401,'SESSION_INVALID');assert.deepEqual(fact(await action({action:'observe',input},{cookie:changed.cookie,csrf:changed.data.csrf}),input),x);assert.equal((await call(`/api/games/${g.gameId}/delete`,{},admin)).status,404);checks.push('actual worker restart and realpassword epoch old401/new currentfacts; publicdelete404, rowIntegrity/nativeDrain/deletefalse');
 for(const[p,h]of Object.entries({...before.inputs,...before.imports,...sourceHashes}))assert.equal(hash(p),h,p);process.stdout.write(JSON.stringify({result:'PASS-ACTUAL-DECLARED-UNIQUE-KEYS-NOT-INDEX-CONSISTENCY',checks,calls,facts,protected:486,sourceHashes,limits:'35 fixed implicit UNIQUE keys/33 tables only. Exact BINARY native SQL predicates excluding NULL; NOT INDEXED scans bounded by rows/32MiB. Lowlevel temporary duplicates after constraint removal, NOT persisted native corruption or fullservice bypass. No index-table consistency/FK/wholebusinessrefs/provider/body/CPU/legacy/delete.'},null,2));
}catch(error){writeFileSync(d+'failure-r'+round+'.json',JSON.stringify({message:String(error.message),checks,calls,facts},null,2),{flag:'wx'});throw error;}finally{await server?.close();}
