// Actual workerd + persistent SQLite Durable Object; no fake auth/storage or user cloud/profile data.
import assert from 'node:assert/strict';import{mkdtempSync,readFileSync,readdirSync,writeFileSync}from'node:fs';import{tmpdir}from'node:os';import{join,resolve}from'node:path';import{randomBytes,randomUUID,createHash}from'node:crypto';import{pathToFileURL}from'node:url';import{DatabaseSync}from'node:sqlite';import{request as httpsRequest}from'node:https';
const modulePath=process.env.MINIFLARE_MODULE;assert.ok(modulePath,'explicit installed MINIFLARE_MODULE required');const{Miniflare}=await import(pathToFileURL(modulePath).href);
const own=mkdtempSync(join(tmpdir(),'dragon-auth-')),origin='https://127.0.0.1:8787',initial=randomBytes(24).toString('hex'),adminPassword=randomBytes(24).toString('hex'),authorPassword=randomBytes(24).toString('hex'),secret=randomBytes(32).toString('hex');
const paths=['server/worker.js','server/security.js','server/wrangler.jsonc','server/public/index.html','server/public/client.txt','server/public/style.css','tools/start_editor_backend.mjs','tools/verify_editor_backend_auth.mjs'],hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex'),before=Object.fromEntries(paths.map(p=>[p,hash(p)]));
let mf;const build=(overrides={},folder='metadata')=>new Miniflare({name:'dragon-editor',modules:true,scriptPath:resolve('server/worker.js'),compatibilityDate:'2026-01-01',compatibilityFlags:['nodejs_compat'],host:'127.0.0.1',port:8787,https:true,modulesRules:[{type:'ESModule',include:['**/*.js','**/*.mjs']},{type:'Text',include:['**/*.html','**/*.css','**/*.txt']}],durableObjects:{EDITOR_METADATA:{className:'EditorMetadata',useSQLite:true}},durableObjectsPersist:join(own,folder),bindings:{EDITOR_ORIGIN:origin,EDITOR_DEFAULT_PASSWORD:initial,EDITOR_REQUEST_KEY:secret,EDITOR_ACCOUNT_LIMIT:'50',EDITOR_SOURCE_LIMIT:'100',...overrides}});
const calls=[];async function call(path,value,session,extra={}){process.stderr.write('HTTPS '+path+' request\n');const h={};if(value!==undefined){h['Content-Type']='application/json';h.Origin=origin;h['Idempotency-Key']=randomUUID();if(session)h['X-CSRF-Token']=session.csrf;}if(session)h.Cookie=session.cookie;Object.assign(h,extra);assert.equal((await mf.ready).origin,origin);const text=value===undefined?undefined:JSON.stringify(value);const r=await new Promise((done,reject)=>{const req=httpsRequest(origin+path,{method:value===undefined?'GET':'POST',headers:h,rejectUnauthorized:false},res=>{const chunks=[];res.on('data',chunk=>chunks.push(chunk));res.on('end',()=>{const headers=new Headers();for(let i=0;i<res.rawHeaders.length;i+=2)headers.append(res.rawHeaders[i],res.rawHeaders[i+1]);done({status:res.statusCode,headers,text:Buffer.concat(chunks).toString('utf8')});});res.on('error',reject);});req.on('error',reject);req.end(text);});let data;try{data=JSON.parse(r.text);}catch(cause){throw new Error('Invalid actual HTTPS authority response',{cause});}process.stderr.write('HTTPS '+path+' response '+r.status+'\n');calls.push({path,status:r.status});return{status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0],rawCookie:r.headers.get('set-cookie'),headers:r.headers};}
async function login(name,pass,key=randomUUID()){const r=await call('/api/auth/login',{account:name,password:pass},null,{'Idempotency-Key':key});assert.equal(r.status,200,r.data.error);assert.ok(/Secure/.test(r.rawCookie));assert.ok(/HttpOnly/.test(r.rawCookie));assert.ok(/SameSite=Strict/.test(r.rawCookie));assert.ok(/Path=\/api/.test(r.rawCookie));assert.ok(!/Domain=/.test(r.rawCookie));return{cookie:r.cookie,csrf:r.data.csrf,user:r.data.user};}
const checks=[];try{
 mf=build();assert.equal((await call('/api/health')).status,200);assert.equal((await call('/api/session')).status,401);
 assert.equal((await call('/api/auth/login',{account:'tianyi',password:initial},null,{Origin:'https://other.invalid'})).status,403);
 assert.equal((await call('/api/auth/login',{account:'tianyi',password:initial},null,{Origin:origin+'/'})).status,403);
 assert.equal((await call('/api/auth/login',{account:'tianyi',password:initial},null,{Origin:''})).status,403);
 const loginKey=randomUUID(),first=await login('tianyi',initial,loginKey),again=await login('tianyi',initial,loginKey);assert.equal(JSON.stringify(again)===JSON.stringify(first),true);assert.equal(first.user.mustChangePassword,true);
 assert.equal((await call('/api/admin/accounts',undefined,first)).status,403);
 assert.equal((await call('/api/auth/password',{oldPassword:initial,newPassword:adminPassword},first,{'X-CSRF-Token':'é'.repeat(64)})).status,403);
 for(const invalid of ['x'.repeat(16)+'\ud800','x'.repeat(16)+'\udfff','x'.repeat(16)+'\0'])assert.equal((await call('/api/auth/password',{oldPassword:initial,newPassword:invalid},first)).status,422);assert.equal((await call('/api/auth/login',{account:'tianyi',password:'x'.repeat(20000)})).status,413);
 const changed=await call('/api/auth/password',{oldPassword:initial,newPassword:adminPassword},first);assert.equal(changed.status,200,changed.data.error);const admin={cookie:changed.cookie,csrf:changed.data.csrf,user:changed.data.user};assert.equal(admin.user.mustChangePassword,false);assert.equal((await call('/api/session',undefined,first)).status,401);checks.push('real scrypt login, exactOrigin/CSRF, encrypted idempotent login, mandatory change and old-epoch revoke');
 const createKey=randomUUID(),created=await call('/api/admin/accounts',{account:'author_a'},admin,{'Idempotency-Key':createKey});assert.equal(created.status,200);assert.deepEqual((await call('/api/admin/accounts',{account:'author_a'},admin,{'Idempotency-Key':createKey})).data,created.data);assert.equal((await call('/api/admin/accounts',{account:'author_b'},admin,{'Idempotency-Key':createKey})).status,409);
 assert.equal((await call('/api/admin/accounts',{account:'author_b'},admin)).status,200);let a=await login('author_a',initial),b=await login('author_b',initial);
 for(const s of [a,b]){assert.equal((await call('/api/admin/accounts',undefined,s)).status,403);const r=await call('/api/auth/password',{oldPassword:initial,newPassword:authorPassword},s);assert.equal(r.status,200);if(s===a)a={cookie:r.cookie,csrf:r.data.csrf,user:r.data.user};else b={cookie:r.cookie,csrf:r.data.csrf,user:r.data.user};}
 assert.equal((await call('/api/admin/accounts',undefined,a)).status,403);assert.equal((await call('/api/admin/accounts/'+b.user.id+'/reset',{expectedVersion:b.user.version},a)).status,403);
 let disabled=await call('/api/admin/accounts/'+a.user.id+'/disable',{expectedVersion:a.user.version,disabled:true},admin);assert.equal(disabled.status,200);assert.equal((await call('/api/session',undefined,a)).status,401);assert.equal((await call('/api/session',undefined,b)).status,200);
 const enabled=await call('/api/admin/accounts/'+a.user.id+'/disable',{expectedVersion:disabled.data.account.version,disabled:false},admin);assert.equal(enabled.status,200);assert.equal((await call('/api/session',undefined,a)).status,401);a=await login('author_a',authorPassword);assert.equal(a.user.mustChangePassword,false);
 assert.equal((await call('/api/admin/accounts/'+a.user.id+'/reset',{expectedVersion:a.user.version-1},admin)).status,409);
 const reset=await call('/api/admin/accounts/'+a.user.id+'/reset',{expectedVersion:a.user.version},admin);assert.equal(reset.status,200);assert.equal((await call('/api/session',undefined,a)).status,401);const resetLogin=await login('author_a',initial);assert.equal(resetLogin.user.mustChangePassword,true);
 assert.equal((await call('/api/admin/accounts/'+admin.user.id+'/disable',{expectedVersion:admin.user.version,disabled:true},admin)).status,403);checks.push('two actual author accounts, immutable admin, CAS account updates, disable/re-enable never revives sessions, reset mandates change');
 const concurrentKey=randomUUID(),concurrent=await Promise.all([call('/api/admin/accounts',{account:'author_c'},admin,{'Idempotency-Key':concurrentKey}),call('/api/admin/accounts',{account:'author_c'},admin,{'Idempotency-Key':concurrentKey})]);assert.deepEqual(concurrent.map(r=>r.status),[200,200]);assert.deepEqual(concurrent[0].data,concurrent[1].data);
 const listed=await call('/api/admin/accounts',undefined,admin);assert.equal(listed.status,200);assert.equal(listed.data.accounts.length,4);assert.ok(!JSON.stringify(listed.data).includes('password_hash'));assert.ok(!JSON.stringify(listed.data).includes(initial));
 await mf.dispose();mf=undefined;mf=build();assert.equal((await call('/api/session',undefined,admin)).status,200);assert.equal((await call('/api/admin/accounts',undefined,admin)).data.accounts.length,4);assert.equal((await call('/api/session',undefined,a)).status,401);assert.deepEqual((await call('/api/admin/accounts',{account:'author_a'},admin,{'Idempotency-Key':createKey})).data,created.data);checks.push('actual SQLite survives workerd restart including current sessions, revoked sessions and idempotent receipts');
 const logout=await call('/api/auth/logout',{},b);assert.equal(logout.status,200);assert.match(logout.rawCookie,/Max-Age=0/);assert.equal((await call('/api/session',undefined,b)).status,401);
 assert.equal((await call('/api/chapter-resources',{gameId:'anything'},admin)).status,404);assert.equal((await call('/api/admin/accounts',{account:'author_c',role:'admin'},admin)).status,422);checks.push('safe DTO, logout revoke, no old unauthenticated harness routes or role injection');
 await mf.dispose();mf=undefined;
 // Read only owned DB files AFTER disposal. No user database is opened.
 function find(dir){return readdirSync(dir,{withFileTypes:true}).flatMap(row=>{if(row.isDirectory())return find(join(dir,row.name));if(row.name.endsWith('.sqlite'))return[join(dir,row.name)];return[];});}
 const databases=find(join(own,'metadata')),authorityFiles=[];for(const path of databases){const probe=new DatabaseSync(path,{readOnly:true});try{if(probe.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='users'").get())authorityFiles.push(path);}finally{probe.close();}}assert.equal(authorityFiles.length,1);const db=new DatabaseSync(authorityFiles[0],{readOnly:true});try{const users=db.prepare('SELECT * FROM users').all();assert.equal(users.length,4);for(const user of users){let kdf;try{kdf=JSON.parse(user.password_hash);}catch(cause){throw new Error('invalid owned KDF JSON',{cause});}assert.equal(kdf.algorithm,'scrypt-32768-8-3');assert.ok(!user.password_hash.includes(initial));}const sessions=db.prepare('SELECT * FROM sessions').all();for(const row of sessions)assert.match(row.token_hash,/^[a-f0-9]{64}$/);const operations=db.prepare('SELECT * FROM operations').all();assert.ok(operations.length>5);for(const row of operations){assert.ok(!row.sealed_result.includes(initial));assert.ok(!row.sealed_result.includes(admin.cookie.split('=')[1]));}}finally{db.close();}checks.push('owned persisted DB: salted scrypt, only token hashes, AES-GCM operation results; no plaintext credentials');
 mf=build({EDITOR_ACCOUNT_LIMIT:'2',EDITOR_SOURCE_LIMIT:'3'},'rates');for(let i=0;i<2;i++)assert.equal((await call('/api/auth/login',{account:'missing_a',password:initial})).status,401);assert.equal((await call('/api/auth/login',{account:'missing_a',password:initial})).status,429);assert.equal((await call('/api/auth/login',{account:'missing_b',password:initial})).status,429);await mf.dispose();mf=undefined;mf=build({EDITOR_ACCOUNT_LIMIT:'2',EDITOR_SOURCE_LIMIT:'3'},'rates');assert.equal((await call('/api/auth/login',{account:'missing_a',password:initial})).status,429);await mf.dispose();mf=undefined;checks.push('persisted independent account/source login limits cannot reset by restarting process');
 mf=build({EDITOR_SESSION_MS:'700',EDITOR_IDLE_MS:'250'},'expiry');let expired=await login('tianyi',initial);await new Promise(r=>setTimeout(r,350));assert.equal((await call('/api/session',undefined,expired)).status,401);expired=await login('tianyi',initial);for(let i=0;i<3;i++){await new Promise(r=>setTimeout(r,150));assert.equal((await call('/api/session',undefined,expired)).status,200);}await new Promise(r=>setTimeout(r,300));assert.equal((await call('/api/session',undefined,expired)).status,401);await mf.dispose();mf=undefined;checks.push('actual-clock idle and absolute expiry; keepalive never extends absolute lifetime');
 for(const[p,h]of Object.entries(before))assert.equal(hash(p),h);const receipt={result:'PASS-REAL-WORKER-SQLITE-ACCOUNT-SESSIONS',checks,calls,sourceHashes:before,ownedPersistence:true,limits:'Not games/private blobs/compile jobs/release/UI/browser/production deployment; no cloud resources or user secrets. Full account UI/browser and deployment separately required; limits are engineering policy, not game rules.'};writeFileSync(join(own,'receipt.json'),JSON.stringify(receipt,null,2));process.stdout.write(JSON.stringify(receipt,null,2)+'\n');
}finally{await mf?.dispose();}
