// Actual HTTPS8787 launcher + real workerd/SQLite + fresh browser. No cloud/user stores.
import assert from 'node:assert/strict';import{readFileSync,writeFileSync,mkdtempSync}from'node:fs';import{join,resolve}from'node:path';import{tmpdir}from'node:os';import{randomBytes,createHash}from'node:crypto';import{spawnSync}from'node:child_process';import{pathToFileURL}from'node:url';import{startEditorBackend}from'./start_editor_backend.mjs';
const own=mkdtempSync(join(tmpdir(),'dragon-backend-ui-')),out=resolve(process.argv[2]);assert.ok(out.includes('.dragon-analysis'));const hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex');
function parse(text){try{return JSON.parse(text);}catch(cause){throw new Error('Invalid own configuration JSON',{cause});}}
const doc=parse(readFileSync('server/wrangler.jsonc','utf8'));doc.main=resolve('server/worker.js');writeFileSync(join(own,'wrangler.jsonc'),JSON.stringify(doc));const config=join(own,'wrangler.jsonc'),initial=randomBytes(24).toString('hex'),changed=randomBytes(24).toString('hex'),authorChanged=randomBytes(24).toString('hex'),env={};
for(const key of ['SystemRoot','SYSTEMROOT','WINDIR','COMSPEC','ComSpec','PATH','Path','PATHEXT','TEMP','TMP','USERPROFILE','LOCALAPPDATA','APPDATA','HOMEDRIVE','HOMEPATH'])if(process.env[key]!==undefined)env[key]=process.env[key];env.EDITOR_DEFAULT_PASSWORD=initial;
const init=spawnSync(process.execPath,['tools/start_editor_backend.mjs','--init','--config',config],{env,encoding:'utf8'});assert.equal(init.status,0);assert.ok(!init.stdout.includes(initial));const secretsBefore=hash(join(own,'.dev.vars'));const second=spawnSync(process.execPath,['tools/start_editor_backend.mjs','--init','--config',config],{env,encoding:'utf8'});assert.equal(second.status,1);assert.equal(hash(join(own,'.dev.vars')),secretsBefore);delete env.EDITOR_DEFAULT_PASSWORD;
const { chromium }=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);let server,browser;const errors=[],expected=[],outside=[],requests=[];let idbAccess=0;
try{server=await startEditorBackend(config);assert.equal(server.url.origin,'https://127.0.0.1:8787');browser=await chromium.launch({headless:true,env});
const admin=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1280,height:900}}),author=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1024,height:900}});
for(const context of [admin,author]){await context.addInitScript(()=>Object.defineProperty(globalThis,'indexedDB',{get(){globalThis.__idbAccess=(globalThis.__idbAccess??0)+1;throw new Error('User IDB forbidden');}}));await context.route('**/*',route=>{const url=new URL(route.request().url());if(url.origin!==server.url.origin){outside.push(url.origin);return route.abort();}return route.continue();});}
async function pageFor(context){const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error'){const text=message.text();const path=new URL(message.location().url||server.url.origin).pathname;if(path==='/api/session'&&text.includes('401')||/^\/api\/admin\/accounts\/[^/]+\/disable$/.test(path)&&text.includes('409')||path==='/favicon.ico'&&text.includes('404'))expected.push({path,text});else errors.push(text);}});page.on('request',request=>requests.push({path:new URL(request.url()).pathname,method:request.method()}));await page.goto(server.url.origin);await page.locator('#login').waitFor({state:'visible'});return page;}
const page=await pageFor(admin);
async function login(p,name,pw){await p.locator('#login [name=account]').fill(name);await p.locator('#login [name=password]').fill(pw);await p.locator('#login button').click();await p.locator('#session').waitFor({state:'visible'});await p.waitForFunction(()=>!document.querySelector('#logout').disabled);}
async function changePassword(p,old,newPw){await p.locator('[name=oldPassword]').fill(old);await p.locator('[name=newPassword]').fill(newPw);await p.locator('[name=confirmPassword]').fill(newPw);await p.locator('#password button').click();await p.waitForFunction(()=>document.querySelector('#status').textContent==='操作完成。'&&!document.querySelector('#logout').disabled);}
await login(page,'tianyi',initial);assert.equal(await page.locator('#admin').isVisible(),false);await changePassword(page,initial,changed);await page.locator('#admin').waitFor({state:'visible'});assert.equal(await page.locator('#login [name=password]').inputValue(),'');
const cookies=await admin.cookies(server.url.origin+'/api/session'),cookie=cookies.find(c=>c.name==='__Secure-dragon-editor');assert.ok(cookie?.secure&&cookie.httpOnly&&cookie.sameSite==='Strict');assert.equal(cookie.path,'/api');assert.equal(await page.evaluate(()=>document.cookie),'');
await page.locator('#create [name=account]').fill('browser-author');await page.locator('#create button').click();const row=page.locator('#accounts>div').filter({hasText:'browser-author'});await row.waitFor();assert.equal(await row.locator('img').count(),0);await page.waitForFunction(()=>!document.querySelector('#refresh').disabled);assert.equal(await page.locator('#accounts button').count(),2);
const other=await pageFor(author);await login(other,'browser-author',initial);assert.equal(await other.locator('#admin').isVisible(),false);await changePassword(other,initial,authorChanged);assert.equal(await other.locator('#admin').isVisible(),false);await other.reload();await other.locator('#session').waitFor({state:'visible'});assert.match(await other.locator('#identity').textContent(),/browser-author/);
// Author changed its password after the administrator captured version1: CAS must reject stale UI.
page.once('dialog',dialog=>dialog.accept());await row.getByRole('button',{name:'停用',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#status').textContent==='帳戶已被修改，請重新載入。'&&!document.querySelector('#refresh').disabled);await other.reload();await other.locator('#session').waitFor({state:'visible'});await page.locator('#refresh').click();await page.waitForFunction(()=>!document.querySelector('#refresh').disabled);
page.once('dialog',dialog=>dialog.dismiss());await row.getByRole('button',{name:'停用',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#refresh').disabled);assert.equal(await row.getByRole('button',{name:'停用',exact:true}).count(),1);
page.once('dialog',dialog=>dialog.accept());await row.getByRole('button',{name:'停用',exact:true}).click();await row.getByRole('button',{name:'恢復',exact:true}).waitFor();await other.reload();await other.locator('#login').waitFor({state:'visible'});
page.once('dialog',dialog=>dialog.accept());await row.getByRole('button',{name:'恢復',exact:true}).click();await row.getByRole('button',{name:'停用',exact:true}).waitFor();await other.reload();assert.equal(await other.locator('#login').isVisible(),true);await login(other,'browser-author',authorChanged);
page.once('dialog',dialog=>dialog.accept());await row.getByRole('button',{name:'重設密碼',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#accounts').textContent.includes('須改密碼')&&!document.querySelector('#refresh').disabled);await other.reload();await other.locator('#login').waitFor({state:'visible'});await login(other,'browser-author',initial);assert.match(await other.locator('#identity').textContent(),/請先變更密碼/);await other.locator('#logout').click();await other.locator('#login').waitFor({state:'visible'});
await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:join(out,'accounts.png'),fullPage:true});await server.close();server=await startEditorBackend(config);await page.reload();await page.locator('#admin').waitFor({state:'visible'});await row.waitFor();assert.equal(hash(join(own,'.dev.vars')),secretsBefore);await page.locator('#logout').click();await page.locator('#login').waitFor({state:'visible'});
for(const p of [page,other])idbAccess+=await p.evaluate(()=>globalThis.__idbAccess??0);assert.equal(idbAccess,0);assert.deepEqual(errors,[]);assert.deepEqual(outside,[]);
writeFileSync(join(out,'browser-receipt.json'),JSON.stringify({result:'PASS-REAL-HTTPS8787-ACCOUNT-UI',port:8787,checks:['actual init no overwrite; HTTPS8787 real launcher','forced change, Secure HttpOnly cookie and private credential inputs cleared','real author create/login, admin-only controls','stale UI CAS409 preserves target; manual refresh, cancel/confirm disable, epoch invalid after restore, reset forces change','SQLite survives actual launcher close/reopen, both logout','fresh isolated contexts, IDB access0, no outside network'],errors,expected,outside,idbAccess,requests,screenshotSha:hash(join(out,'accounts.png')),toolHashes:Object.fromEntries(['tools/start_editor_backend.mjs','tools/verify_editor_backend_browser.mjs','server/wrangler.jsonc','server/worker.js','server/security.js','server/public/index.html','server/public/client.txt','server/public/style.css'].map(p=>[p,hash(p)])),limits:'Local self-signed TLS ignores cert verification only in isolated context. No cloud deploy, full editor, game App, blob/jobs/publish or real user data.'},null,2),{flag:'wx'});process.stdout.write('PASS actual HTTPS8787 account UI and persisted launcher\n');
}finally{await browser?.close();await server?.close();}
