// Actual default Root, owned stores; native final-await controls separately labelled.
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { randomBytes, randomUUID, createHash } from 'node:crypto';
import { request as httpsRequest } from 'node:https';
import { DatabaseSync } from 'node:sqlite';
import { pathToFileURL } from 'node:url';
import { startEditorBackend } from './start_editor_backend.mjs';
const dir='.dragon-analysis/editor-phase/backend-fallback-api-session-r1/',round=process.argv[2]??'1';assert.match(round,/^[1-9][0-9]{0,3}$/);
const sha=b=>createHash('sha256').update(b).digest('hex');function json(b){try{return JSON.parse(b.toString());}catch(cause){throw new Error('owned fallback API JSON invalid',{cause});}}
const before=json(readFileSync(dir+'before.json')),protectedHashes={...before.inputs};for(const p of['server/worker.js','server/stageapi.js'])delete protectedHashes[p];assert.equal(Object.keys(protectedHashes).length,441);for(const[p,h]of Object.entries(protectedHashes))assert.equal(sha(readFileSync(p)),h,p);
const sources=['server/worker.js','server/stageapi.js','server/fallbackjobs.js','server/copyimages.js','server/jobs.js','server/blobs.js','tools/start_editor_backend.mjs','tools/verify_editor_backend_fallback_api.mjs',dir+'fixture-worker.js'],sourceHashes=Object.fromEntries(sources.map(p=>[p,sha(readFileSync(p))]));
const own=mkdtempSync(join(tmpdir(),'dragon-fallback-api-')),doc=json(readFileSync('server/wrangler.jsonc')),configPath=join(own,'worker.json'),origin='https://127.0.0.1:8787',initial=randomBytes(24).toString('hex'),password=randomBytes(24).toString('hex');doc.main=resolve('server/worker.js');doc.name='fallback-api-'+randomUUID();writeFileSync(configPath,JSON.stringify(doc),{flag:'wx'});writeFileSync(join(own,'.dev.vars'),'EDITOR_DEFAULT_PASSWORD='+JSON.stringify(initial)+'\nEDITOR_REQUEST_KEY='+JSON.stringify(randomBytes(32).toString('hex'))+'\n',{flag:'wx',mode:0o600});
const checks=[],calls=[],artifacts=[];let server;
async function call(path,value,session,extra={},raw=false){const headers={Origin:origin,Connection:'close',...extra};if(session){headers.Cookie=session.cookie;headers['X-CSRF-Token']??=session.csrf;}if(value!==undefined){headers['Content-Type']='application/json';headers['Idempotency-Key']??=randomUUID();}const r=await new Promise((done,reject)=>{const request=httpsRequest(new URL(path,server.url),{method:value===undefined?'GET':'POST',headers,rejectUnauthorized:false,agent:false},reply=>{const parts=[];reply.on('data',b=>parts.push(b));reply.on('error',reject);reply.on('end',()=>{try{const bytes=Buffer.concat(parts);done({status:reply.statusCode,bytes,data:raw?undefined:json(bytes),headers:reply.headers,cookie:reply.headers['set-cookie']?.[0]?.split(';')[0]});}catch(e){reject(e);}});});request.on('error',reject);request.end(value===undefined?undefined:JSON.stringify(value));});calls.push({path,status:r.status});return r;}
async function login(account){const a=await call('/api/auth/login',{account,password:initial});assert.equal(a.status,200);const b=await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:a.cookie,csrf:a.data.csrf});assert.equal(b.status,200);return{cookie:b.cookie,csrf:b.data.csrf};}
function files(path){return readdirSync(path,{withFileTypes:true}).flatMap(e=>{if(e.isDirectory())return files(join(path,e.name));if(e.name.endsWith('.sqlite'))return[join(path,e.name)];return[];});}
function database(){for(const path of files(join(own,'.local/metadata'))){const db=new DatabaseSync(path);if(db.prepare("SELECT name FROM sqlite_master WHERE name='compile_jobs'").get())return db;db.close();}throw new Error('owned fallback SQL absent');}
async function bucketMutation(action){await server.close();server=undefined;const{Miniflare}=await import(pathToFileURL(process.env.MINIFLARE_MODULE).href),mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response(null,{status:404})}}',compatibilityDate:doc.compatibility_date,compatibilityFlags:doc.compatibility_flags,r2Buckets:['EDITOR_BLOBS'],r2Persist:join(own,'.local/blobs'),host:'127.0.0.1',port:0});try{await mf.ready;await action(await mf.getR2Bucket('EDITOR_BLOBS'));}finally{await mf.dispose();}server=await startEditorBackend(configPath);}
try{
 server=await startEditorBackend(configPath,{stageSource:true});const admin=await login('tianyi');assert.equal((await call('/api/admin/accounts',{account:'fallback_api_author'},admin)).status,200);const author=await login('fallback_api_author');assert.equal((await call('/api/admin/source/install',{},admin)).status,200);const source=(await call('/api/admin/source',undefined,admin)).data,copyKey=randomUUID();assert.equal((await call('/api/admin/copies',{registryId:source.definition.registryId,name:'整圖入口',introduction:''},admin,{'Idempotency-Key':copyKey})).status,202);const copy=await call('/api/admin/copies/'+copyKey+'/run',{},admin,{'If-Match':'"1"'});assert.equal(copy.status,200,copy.data.error);const gameId=copy.data.gameId,base='/api/games/'+gameId+'/stage-jobs/',value={draftRevision:'1',scope:'all'},key=randomUUID();
 assert.equal((await call(base+'fallback-spring',value)).status,401);assert.equal((await call(base+'fallback-spring',value,author)).status,403);assert.equal((await call('/api/games/wolong-builtin/stage-jobs/fallback-spring',value,admin)).status,403);assert.equal((await call('/api/games/'+randomUUID()+'/stage-jobs/fallback-spring',value,admin)).status,404);assert.equal((await call(base+'fallback-spring',value,admin,{Origin:'https://127.0.0.1:8788'})).status,403);assert.equal((await call(base+'fallback-spring',value,admin,{'X-CSRF-Token':'wrong'})).status,403);
 for(const extra of[{season:'winter'},{path:'map_tiles_spring.png'},{valid:true}])assert.equal((await call(base+'fallback-spring',{...value,...extra},admin)).status,422);assert.equal((await call(base+'fallback-spring',{...value,scope:'bad'},admin)).status,422);assert.equal((await call(base+'fallback-spring',{...value,draftRevision:'99'},admin)).status,404);assert.equal((await call(base+'fallback-spring?valid=1',value,admin)).status,422);assert.equal((await call(base+'fallback-monsoon',value,admin)).status,404);
 const queued=await call(base+'fallback-spring',value,admin,{'Idempotency-Key':key});assert.equal(queued.status,202,queued.data.error);assert.equal(queued.data.admission,'stage-only');assert.equal(queued.data.purpose,'fallback-spring');const spring=queued.data.job,springPath=base+'fallback-spring/'+spring.operationId;assert.equal((await call(base+'fallback-spring',value,admin,{'Idempotency-Key':key})).data.job.operationId,spring.operationId);assert.equal((await call(base+'fallback-winter',value,admin,{'Idempotency-Key':key})).status,409);assert.equal((await call(base+'images',value,admin,{'Idempotency-Key':key})).status,409);assert.equal((await call('/api/admin/accounts',{account:'not_created'},admin,{'Idempotency-Key':key})).status,409);assert.equal((await call(springPath+'/artifacts/fallback_spring',undefined,admin)).status,409);assert.equal((await call(springPath+'/run',{},admin)).status,428);assert.equal((await call(springPath+'/run',{},admin,{'If-Match':'"99"'})).status,412);assert.equal((await call(springPath+'/run',{season:'winter'},admin,{'If-Match':'"1"'})).status,422);checks.push('default Root fixed season/auth/admin-owner/Origin/CSRF/builtin/body/query/snapshot, permanent crosspurpose/namespace keys, queued artifacts and428/412 gates');
 const saved=await call('/api/games/'+gameId+'/draft/save',{metadata:{name:'整圖第二修訂',introduction:'獨立修訂'},resourceEdits:[]},admin,{'If-Match':'"1"'});assert.equal(saved.status,200,saved.data.error);assert.equal(saved.data.draftRevision,'2');const current=(await call('/api/games',undefined,admin)).data.games.find(g=>g.gameId===gameId),runKey=randomUUID();
 const ready={},paths={},runKeys={spring:runKey};for(const season of['spring','summer','autumn','winter']){let job=spring;if(season!=='spring'){const q=await call(base+'fallback-'+season,value,admin);assert.equal(q.status,202,q.data.error);job=q.data.job;runKeys[season]=randomUUID();}const path=base+'fallback-'+season+'/'+job.operationId;paths[season]=path;process.stderr.write('fallback-api: actual '+season+' run and private artifact\n');const done=await call(path+'/run',{},admin,{'If-Match':'"1"','Idempotency-Key':runKeys[season]});assert.equal(done.status,200,done.data.error);assert.equal(done.data.job.state,'ready');assert.equal(done.data.job.draftRevision,'1');assert.equal(done.data.purpose,'fallback-'+season);const outputs=done.data.job.checkpoint.flatMap(r=>r.outputs);assert.equal(outputs.length,2);const image=outputs.find(o=>o.assetId==='fallback_'+season);assert.ok(image);const raw=await call(path+'/artifacts/'+image.assetId,undefined,admin,{},true);assert.equal(raw.status,200,raw.bytes.toString().slice(0,60));assert.equal(raw.bytes.length,image.byteLength);assert.equal(sha(raw.bytes),image.sha256);assert.equal(raw.headers['x-content-sha256'],image.sha256);assert.equal(raw.headers['cache-control'],'no-store');assert.equal(raw.headers['x-content-type-options'],'nosniff');assert.equal(raw.headers['content-type'],'application/octet-stream');assert.equal(raw.headers['content-disposition'],'attachment; filename="'+image.assetId+'"');const old='.dragon-analysis/editor-phase/backend-fallback-rows-session-r1/r1-'+season+'-worker.png';assert.equal(sha(readFileSync(old)),image.sha256);const file=dir+'artifact-r'+round+'-'+season+'.png';writeFileSync(file,raw.bytes,{flag:'wx'});artifacts.push({path:file,season,sha256:image.sha256,byteLength:image.byteLength,oldPixelEvidence:old});ready[season]=done.data;}
 const reportResponse=await call(springPath+'/artifacts/fallback_report',undefined,admin,{},true);assert.equal(reportResponse.status,200);const report=json(reportResponse.bytes);assert.equal(report.season,'spring');assert.equal(report.draftRevision,'1');assert.equal(report.admission,'single-season-stage-outputs-only');assert.equal(report.sourceReport.outputs[0].width,6144);assert.equal(report.sourceReport.outputs[0].height,4096);const reportPath=dir+'report-r'+round+'.json';writeFileSync(reportPath,reportResponse.bytes,{flag:'wx'});artifacts.push({path:reportPath,sha256:sha(reportResponse.bytes),byteLength:reportResponse.bytes.length});checks.push('four default Root independent pipelines/twooutputs each, exact saved1 whilecurrent2, private full-source+checkpoint+R2 downloads fullSHA equal previously sealed Pillow bytes, stageonly report');
 assert.equal((await call(base+'fallback-winter/'+spring.operationId,undefined,admin)).status,409);assert.equal((await call(springPath,undefined,author)).status,403);assert.equal((await call(springPath+'/artifacts/fallback_spring',undefined,author)).status,403);assert.equal((await call(springPath+'?latest=1',undefined,admin)).status,422);assert.equal((await call(springPath+'/artifacts/fallback_winter',undefined,admin)).status,404);assert.equal((await call(springPath+'/run',{},admin,{'If-Match':'"2"','Idempotency-Key':runKey})).status,409);assert.equal((await call(springPath+'/run',{},admin,{'If-Match':'"1"'})).status,412);
 let db=database();const row=db.prepare('SELECT * FROM compile_jobs WHERE job_id=?').get(spring.operationId),snapshot=db.prepare('SELECT * FROM content_snapshots WHERE game_id=? AND revision=?').get(gameId,'1');db.prepare('UPDATE compile_jobs SET pipeline_digest=? WHERE job_id=?').run('0'.repeat(64),spring.operationId);db.close();assert.equal((await call(base+'fallback-spring',value,admin,{'Idempotency-Key':key})).status,409);db=database();db.prepare('UPDATE compile_jobs SET pipeline_digest=? WHERE job_id=?').run(row.pipeline_digest,spring.operationId);db.prepare('UPDATE content_snapshots SET source_digest=? WHERE game_id=? AND revision=?').run('0'.repeat(64),gameId,'1');db.close();assert.equal((await call(springPath,undefined,admin)).status,409);db=database();db.prepare('UPDATE content_snapshots SET source_digest=? WHERE game_id=? AND revision=?').run(snapshot.source_digest,gameId,'1');const checkpoint=json(Buffer.from(row.checkpoint_json));checkpoint[0].digest='0'.repeat(64);db.prepare('UPDATE compile_jobs SET checkpoint_json=? WHERE job_id=?').run(JSON.stringify(checkpoint),spring.operationId);db.close();const damaged=await call(springPath+'/artifacts/fallback_spring',undefined,admin);assert.equal(damaged.status,503,damaged.data.error);assert.equal(damaged.data.error,'FALLBACK_JOB_CHECKPOINT_CORRUPT');db=database();db.prepare('UPDATE compile_jobs SET checkpoint_json=? WHERE job_id=?').run(row.checkpoint_json,spring.operationId);db.close();checks.push('fixedpurpose/CAS/requestbinding and actual SQL pipeline/snapshot/checkpoint damage deny rather than trust replay/ready');
 const descriptor=ready.spring.job.checkpoint[1].outputs[0],objectKey='private/'+gameId+'/'+descriptor.sha256;let backup;await bucketMutation(async bucket=>{const o=await bucket.get(objectKey);assert.ok(o);backup=new Uint8Array(await o.arrayBuffer());assert.equal(sha(backup),descriptor.sha256);const bad=backup.slice();bad[0]^=1;await bucket.put(objectKey,bad);});const badObject=await call(springPath+'/artifacts/fallback_spring',undefined,admin);assert.equal(badObject.status,503);assert.equal(badObject.data.error,'BLOB_CORRUPT');assert.equal((await call(springPath,undefined,admin)).data.job.state,'ready');await bucketMutation(async bucket=>{await bucket.put(objectKey,backup);});const replay=await call(springPath+'/run',{},admin,{'If-Match':'"1"','Idempotency-Key':runKey});assert.equal(replay.status,200,replay.data.error);assert.deepEqual(replay.data,ready.spring);checks.push('native same-size persisted R2 damage blocks readyartifact without state repair, actual restart terminal matchedcommand fullyrebuilds/reverifies facts');
 const winter=ready.winter.job;db=database();const failedRevision=String(BigInt(winter.rowRevision)+1n);db.prepare("UPDATE compile_jobs SET state='failed',stage_cursor=1,checkpoint_json=?,retryable=1,failure_code='CONTROL_API_FAILURE',row_revision=? WHERE job_id=?").run(JSON.stringify(winter.checkpoint.slice(0,1)),failedRevision,winter.operationId);db.close();assert.equal((await call(paths.winter+'/retry',{},admin)).status,428);assert.equal((await call(paths.winter+'/retry',{},admin,{'If-Match':'"1"'})).status,412);const retryKey=randomUUID(),retried=await call(paths.winter+'/retry',{},admin,{'If-Match':'"'+failedRevision+'"','Idempotency-Key':retryKey});assert.equal(retried.status,200,retried.data.error);assert.equal(retried.data.job.state,'queued');const retryReplay=await call(paths.winter+'/retry',{},admin,{'If-Match':'"'+failedRevision+'"','Idempotency-Key':retryKey});assert.deepEqual(retryReplay.data,retried.data);assert.equal((await call(paths.winter+'/run',{},admin,{'If-Match':'"'+retried.data.job.rowRevision+'"'})).data.job.state,'ready');assert.deepEqual((await call('/api/games',undefined,admin)).data.games.find(g=>g.gameId===gameId),current);assert.equal((await call('/api/games/'+gameId+'/compile',{},admin)).status,404);assert.equal((await call('/api/games/'+gameId+'/trial',{},admin)).status,404);checks.push('owned SQL valid failed-prefix control exercises actual explicitretry428/412/permanent-replay/newrun; metadata unchanged/fullcompileTrial closed, not an organic executor failure claim');
 await server.close();server=undefined;const controlled=join(own,'controlled.json');writeFileSync(controlled,JSON.stringify({...doc,main:resolve(dir+'fixture-worker.js')}),{flag:'wx'});server=await startEditorBackend(controlled);
 assert.equal((await call('/api/test/fallback-api/arm',{action:'snapshot',gameId},admin)).status,200);const changedAfterReturn=await call(springPath,undefined,admin);assert.equal(changedAfterReturn.status,409);assert.equal(changedAfterReturn.data.error,'JOB_SNAPSHOT_CHANGED');db=database();db.prepare('UPDATE content_snapshots SET source_digest=? WHERE game_id=? AND revision=?').run(snapshot.source_digest,gameId,'1');db.close();assert.equal((await call('/api/test/fallback-api/arm',{action:'bytes',gameId},admin)).status,200);const flipped=await call(springPath+'/artifacts/fallback_spring',undefined,admin);assert.equal(flipped.status,503);assert.equal(flipped.data.error,'STAGE_OUTPUT_CORRUPT');checks.push('separate native afteractualStageAPI-read-return snapshot mutation and response-byte flip rejected by Root finalactual-query/SHA fence, no stored R2 mutation');
 const finalPassword=randomBytes(24).toString('hex');assert.equal((await call('/api/test/fallback-api/arm',{action:'password',gameId,oldPassword:password,newPassword:finalPassword},admin)).status,200);const revoked=await call(springPath,undefined,admin);assert.equal(revoked.status,401);assert.equal(revoked.data.error,'SESSION_INVALID');assert.equal((await call('/api/session',undefined,admin)).status,401);const finalLogin=await call('/api/auth/login',{account:'tianyi',password:finalPassword});assert.equal(finalLogin.status,200);const fresh={cookie:finalLogin.cookie,csrf:finalLogin.data.csrf};assert.deepEqual((await call('/api/test/fallback-api/last-password',undefined,fresh)).data,{performed:true,status:200});assert.equal((await call(springPath,undefined,fresh)).status,409);assert.equal((await call(base+'fallback-spring',value,fresh,{'Idempotency-Key':key})).status,409);assert.equal((await call(base+'fallback-spring',value,fresh)).status,202);checks.push('native finalread await invokes actual passwordhandler200, Root401 and oldcookie401, realnewlogin oldJob/key revoked409/newexplicitenqueue202; not concurrent external HTTP');
 for(const[p,h]of Object.entries({...protectedHashes,...sourceHashes}))assert.equal(sha(readFileSync(p)),h,p);process.stdout.write(JSON.stringify({result:'PASS-ACTUAL-ROOT-FIXED-FALLBACK-API-SCOPED',checks,calls,sourceHashes,artifacts,protectedInputs:441,limits:'DefaultRoot main flows plus separately labelled native final-await controls. Stageonly/notruntime/Q69/Trial/Release/cloudSLA; bytes reuse previous independent Pillow proof; no new browser/color/DPR certification.'},null,2)+'\n');
}catch(error){writeFileSync(dir+'failure-state-r'+round+'.json',JSON.stringify({message:String(error.message).slice(0,2000),code:error.code??null,calls,checks,sourceHashes},null,2)+'\n',{flag:'wx'});throw error;}finally{await server?.close();}
