// Fixed full fallback pixels + bounded stream encoder, not Root/auth/runtime certification.
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, realpathSync } from 'node:fs';
import { resolve, relative, isAbsolute } from 'node:path';
import { pathToFileURL } from 'node:url';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { createFixedTileRows, TILE_PIXEL_REVISION } from '../web/src/content/authoring/tilepixels.js';
import { encodeRowPNG, RowPNGError, ROW_PNG_REVISION } from '../server/rowpng.js';
import { decodePNG } from '../server/pngio.js';
const round=process.argv[2];assert.match(round??'',/^[1-9][0-9]{0,3}$/);const d='.dragon-analysis/editor-phase/backend-fallback-rows-session-r1/',sha=bytes=>createHash('sha256').update(bytes).digest('hex');
function json(bytes){try{return JSON.parse(bytes.toString());}catch(cause){throw new Error('fixed JSON',{cause});}}
const before=json(readFileSync(d+'before.json'));assert.equal(Object.keys(before.inputs).length,437);for(const[p,h]of Object.entries(before.inputs))assert.equal(sha(readFileSync(p)),h,p);
const inputs=['server/rowpng.js','web/src/content/authoring/tilepixels.js','tools/verify_editor_fallback_rows.mjs','tools/verify_editor_fallback_rows_oracle.py',d+'fixture-worker.js','server/wrangler.jsonc','server/pinned/world-manifest.txt'];const sourceHashes=Object.fromEntries(inputs.map(p=>[p,sha(readFileSync(p))]));const inputHashes={},root=realpathSync('.');function read(path){const real=realpathSync(path),rel=relative(root,real);assert.ok(!rel.startsWith('..')&&!isAbsolute(rel));const bytes=readFileSync(real);inputHashes[path]=sha(bytes);return bytes;}
const manifestBytes=read('server/pinned/world-manifest.txt');assert.equal(sha(manifestBytes),'bde6dfc8a82da5597ef22786e46681c87f2fe21cd55dd23921b32e346efa95e9');const world=json(manifestBytes);function asset(name){const row=world.assets.find(row=>row.path===name);assert.ok(row);const bytes=read('web/'+row.url);assert.equal(bytes.length,row.byteLength);assert.equal(sha(bytes),row.sha256);return bytes;}
const plane=asset('terrain.bin'),checks=[],calls=[],outputs=[];let mf;
const expect=code=>error=>error instanceof RowPNGError&&error.code===code;
try {
  const {Miniflare}=await import(pathToFileURL(process.env.MINIFLARE_MODULE).href),cfg=json(readFileSync('server/wrangler.jsonc'));mf=new Miniflare({modules:true,modulesRules:[{type:'ESModule',include:['**/*.js','**/*.mjs']}],scriptPath:resolve(d+'fixture-worker.js'),compatibilityDate:cfg.compatibility_date,compatibilityFlags:cfg.compatibility_flags,host:'127.0.0.1',port:0});const origin=await mf.ready;
  async function worker(path,bytes){const response=await fetch(new URL(path,origin),{method:'POST',body:bytes});calls.push({path,status:response.status});assert.equal(response.status,200);return Buffer.from(await response.arrayBuffer());}
  function store(name,platform,bytes){const path=d+'r'+round+'-'+name+'-'+platform+'.png';writeFileSync(path,bytes,{flag:'wx'});outputs.push({path,sha256:sha(bytes),byteLength:bytes.length});}
  for(const season of['spring','summer','autumn','winter']){
    const atlas=decodePNG(asset('map_atlas_'+season+'.png'));assert.equal(atlas.width,256);assert.equal(atlas.height,256);asset('map_tiles_'+season+'.png');
    const layout=Uint8Array.from(plane),pixels=Uint8Array.from(atlas.pixels),rows=createFixedTileRows(layout,pixels);layout.fill(0);pixels.fill(0); // Immutable capture before first iteration.
    assert.equal(rows.revision,TILE_PIXEL_REVISION);assert.equal(rows.width,6144);assert.equal(rows.height,4096);const output=await encodeRowPNG(rows,rows.width,rows.height);store(season,'node',output);
    store(season,'worker',await worker('/full',Buffer.concat([plane,Buffer.from(atlas.pixels)])));
  }
  checks.push('four fixed seasons: actual Node and workerd full6144x4096 generation from exact98304 compiled plane and opaque256atlas; captured input mutation cannot change rows');
  const changed=Uint8Array.from(plane);for(const at of[1000,97000])changed[at]=(changed[at]+1)&255;const spring=decodePNG(asset('map_atlas_spring.png'));store('variant','node',await encodeRowPNG(createFixedTileRows(changed,spring.pixels),6144,4096));store('variant','worker',await worker('/full',Buffer.concat([changed,Buffer.from(spring.pixels)])));assert.notEqual(outputs[8].sha256,outputs[0].sha256);assert.deepEqual(plane,asset('terrain.bin'));checks.push('two explicit distant tile changes produce new full fallback without overwriting or mutating initial source/atlas; Node/workerd independently generated');
  const small=Array.from({length:7},(_,y)=>Uint8Array.from({length:36},(_,x)=>(y*41+x*17)%256));store('small','node',await encodeRowPNG(small,9,7));store('small','worker',await worker('/small'));checks.push('genericRGBA8 row encoding preserves transparent RGB and odd widths, no ambient RNG');
  let getters=0;const safe=Uint8Array.from(plane);for(const key of['buffer','byteLength','byteOffset'])Object.defineProperty(safe,key,{get(){getters++;throw new Error('caller accessor');}});assert.deepEqual(createFixedTileRows(safe,spring.pixels)[Symbol.iterator]().next().value,createFixedTileRows(plane,spring.pixels)[Symbol.iterator]().next().value);const safeRow=Uint8Array.from([1,2,3,4]);Object.defineProperty(safeRow,'byteLength',{get(){getters++;throw new Error('caller accessor');}});await encodeRowPNG([safeRow],1,1);assert.equal(getters,0);
  const badViews=[null,[],new DataView(new ArrayBuffer(98304)),new Uint8Array(new SharedArrayBuffer(98304)),new Uint8Array(new ArrayBuffer(98304,{maxByteLength:98305})),new Proxy(plane,{}),new Uint8Array(98303)];for(const view of badViews)assert.throws(()=>createFixedTileRows(view,spring.pixels),TypeError);const transparent=Uint8Array.from(spring.pixels);transparent[3]=0;assert.throws(()=>createFixedTileRows(plane,transparent),/opaque/);
  for(const[w,h]of[[0,1],[1,0],[6145,1],[1,4097],[1.1,1]])await assert.rejects(encodeRowPNG([],w,h),expect('ROW_PNG_DIMENSIONS'));
  await assert.rejects(encodeRowPNG([],1,1),expect('ROW_PNG_ROW_COUNT'));await assert.rejects(encodeRowPNG([new Uint8Array(4),new Uint8Array(4)],1,1),expect('ROW_PNG_ROW_COUNT'));
  for(const row of[new Uint8Array(3),new Uint8Array(5),new Uint8Array(new SharedArrayBuffer(4)),new Proxy(safeRow,{}),new DataView(new ArrayBuffer(4)),new Uint8Array(new ArrayBuffer(4,{maxByteLength:5}))])await assert.rejects(encodeRowPNG([row],1,1),expect('ROW_PNG_ROW'));
  let closed=false;function* throws(){try{yield new Uint8Array(4);throw new Error('owned row source failed');}finally{closed=true;}}await assert.rejects(encodeRowPNG(throws(),1,2),/owned row source failed/);assert.equal(closed,true);checks.push('intrinsic capture getter0/shared/resizable/proxy/nonbytes/length/alpha gates, dimensions/short-long-extra-missing rows, source exception closes iterator and rejects before any PNG return');
  let state=123456789,budgetClosed=false,consumed=0;function* noise(){try{for(let n=0;n<4096;n++){const row=new Uint8Array(24576);for(let i=0;i<row.length;i++){state^=state<<13;state^=state>>>17;state^=state<<5;row[i]=state&255;}consumed++;yield row;}}finally{budgetClosed=true;}}
  await assert.rejects(encodeRowPNG(noise(),6144,4096),expect('ROW_PNG_OUTPUT_BUDGET'));assert.equal(budgetClosed,true);assert.ok(consumed<4096);const budget=json(await worker('/budget'));assert.deepEqual(budget,{error:'ROW_PNG_OUTPUT_BUDGET',closed:true});checks.push('actualNode/workerd incompressible output crosses16MiB budget and rejects; backpressure pipeline destroys streams/returns owned iterator, no partialPNG installed');
  const env={};for(const k of['SystemRoot','SYSTEMROOT','WINDIR','COMSPEC','ComSpec','PATH','Path','PATHEXT','TEMP','TMP','USERPROFILE','LOCALAPPDATA','APPDATA','HOMEDRIVE','HOMEPATH'])if(process.env[k]!==undefined)env[k]=process.env[k];env.PYTHONUTF8='1';env.PYTHONDONTWRITEBYTECODE='1';const oracle=spawnSync('python',['-B','tools/verify_editor_fallback_rows_oracle.py',round],{env,encoding:'utf8',timeout:180000,maxBuffer:1048576});writeFileSync(d+'oracle-r'+round+'.stdout',oracle.stdout??'',{flag:'wx'});writeFileSync(d+'oracle-r'+round+'.stderr',oracle.stderr??'',{flag:'wx'});assert.equal(oracle.status,0,oracle.stderr);assert.equal(oracle.signal,null);assert.equal(oracle.error,undefined);const reference=json(Buffer.from(oracle.stdout));assert.equal(reference.results.length,12);for(const row of reference.results){const output=outputs.find(value=>value.path===row.path);assert.ok(output);assert.equal(output.sha256,row.byteSha);}checks.push('12 actual producedPNG independentPillow fullRGBA equality: four baseline maps plus explicittwo-tile edit plus oddRGBA rows onbothNode/workerd');
  for(const[p,h]of Object.entries({...before.inputs,...sourceHashes,...inputHashes}))assert.equal(sha(readFileSync(p)),h,p);process.stdout.write(JSON.stringify({result:'PASS-ROW-FALLBACK-NODE-WORKER-PILLOW',checks,calls,outputs,sourceHashes,inputHashes,rowRevision:ROW_PNG_REVISION,tileRevision:TILE_PIXEL_REVISION,getters,budgetConsumed:consumed,protectedInputs:437,limits:'Generator only; no source grant/Job persistence/full-runtime consumers/Q69/Trial/Release/cloud memoryCPU SLA.'},null,2)+'\n');
} finally {await mf?.dispose();}
