// Actual Root authority with owned SQL-only native quickcheck probes; no Source/provider/delete.
import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdtempSync} from 'node:fs';import {resolve,join} from 'node:path';import {tmpdir} from 'node:os';import {createHash,randomBytes,randomUUID} from 'node:crypto';import {request as httpsRequest} from 'node:https';import {startEditorBackend} from './start_editor_backend.mjs';
const d='.dragon-analysis/editor-phase/backend-sql-check-rows-session-r1/',round=process.argv[2],origin='https://127.0.0.1:8787';assert.match(round??'',/^[1-9][0-9]{0,2}$/);const hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex');function parse(b){try{return JSON.parse(b);}catch(cause){throw new Error('owned SQL quickcheck JSON',{cause});}}
const before=parse(readFileSync(d+'before.json'));for(const[p,h]of Object.entries({...before.inputs,...before.imports}))assert.equal(hash(p),h,p);const paths=['server/deletioncheckrows.js','tools/verify_editor_backend_sql_check_rows.mjs',d+'fixture-worker.js','server/deletionschemaintegrity.js','server/deletiondefinitions.js','server/worker.js','.dragon-analysis/editor-phase/backend-deletion-definitions-session-r1/fixture-worker.js'],sourceHashes=Object.fromEntries(paths.map(p=>[p,hash(p)]));
const own=mkdtempSync(join(tmpdir(),'dragon-quick-check-')),config=parse(readFileSync('server/wrangler.jsonc')),initial=randomBytes(24).toString('hex'),password=randomBytes(24).toString('hex');config.main=resolve(d+'fixture-worker.js');writeFileSync(join(own,'wrangler.jsonc'),JSON.stringify(config),{flag:'wx'});writeFileSync(join(own,'.dev.vars'),`EDITOR_DEFAULT_PASSWORD=${JSON.stringify(initial)}\nEDITOR_REQUEST_KEY=${JSON.stringify(randomBytes(32).toString('hex'))}\n`,{flag:'wx',mode:0o600});const checks=[],calls=[],facts=[];let server;
async function call(path,value,session,extra={}){const headers={Origin:origin,'Content-Type':'application/json','Idempotency-Key':randomUUID()};if(session){headers.Cookie=session.cookie;headers['X-CSRF-Token']=session.csrf;}Object.assign(headers,extra);const r=await new Promise((done,reject)=>{const req=httpsRequest(origin+path,{method:value===undefined?'GET':'POST',headers,rejectUnauthorized:false,agent:false},res=>{const chunks=[];res.on('data',b=>chunks.push(b));res.on('error',reject);res.on('end',()=>{try{done({status:res.statusCode,data:parse(Buffer.concat(chunks)),cookie:res.headers['set-cookie']?.[0]?.split(';')[0]});}catch(error){reject(error);}});});req.on('error',reject);req.end(value===undefined?undefined:JSON.stringify(value));});calls.push({path,status:r.status});return r;}
async function ok(path,v,s,x){const r=await call(path,v,s,x);assert.equal(r.status,200,r.data.error);return r.data.result??r.data;}const action=(v,s)=>ok('/api/test/check-rows',v,s),base=(v,s)=>ok('/api/test/definitions',v,s);
async function reject(v,s,status,code,extra){const r=await call('/api/test/check-rows',v,s,extra);assert.equal(r.status,status,r.data.error);assert.equal(r.data.error,code);}
async function login(account){const r=await call('/api/auth/login',{account,password:initial});assert.equal(r.status,200);const p=await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:r.cookie,csrf:r.data.csrf});assert.equal(p.status,200);return{cookie:p.cookie,csrf:p.data.csrf};}
function fact(x,input){assert.equal(Object.keys(x).length,12);assert.equal(x.gameId,input.gameId);assert.equal(x.rowRevision,input.expectedRowRevision);assert.match(x.schemaDigest,/^[a-f0-9]{64}$/);assert.equal(x.tablesVerified,35);assert.equal(x.indexesVerified,35);assert.equal(x.foreignKeyDeclarationsVerified,3);assert.equal(x.definitionsVerified,true);assert.equal(x.quickCheckVerified,true);assert.equal(x.rowIntegrityVerified,false);assert.equal(x.nativeDrainVerified,false);assert.equal(x.deleteAllowed,false);assert.equal(x.mode,'CURRENT_NATIVE_SQL_QUICK_CHECK_ONLY_LEGACY_UNKNOWN');facts.push(x);return x;}
try{
 server=await startEditorBackend(join(own,'wrangler.jsonc'),{stageSource:false,stageLibrary:false});const admin=await login('tianyi');await ok('/api/admin/accounts',{account:'check_owner'},admin);await ok('/api/admin/accounts',{account:'check_other'},admin);const owner=await login('check_owner'),other=await login('check_other');const g=await base({action:'create',name:'約束實查'},owner),first={gameId:g.gameId,expectedRowRevision:'1'};
 await reject({action:'observe',input:first},owner,409,'DELETE_FENCE_REQUIRED');await reject({action:'observe',input:first},other,404,'GAME_NOT_FOUND');await reject({action:'observe',input:{gameId:'wolong-builtin',expectedRowRevision:'1'}},admin,403,'BUILTIN_PROTECTED');await reject({action:'observe',input:{...first,plan:{}}},owner,422,'REQUEST_FIELDS');await reject({action:'observe',input:{gameId:[g.gameId],expectedRowRevision:'1'}},owner,422,'DELETE_SCHEMA_INPUT');const f=await base({action:'fence',input:{...first,confirmationName:g.name}},owner),input={gameId:g.gameId,expectedRowRevision:f.rowRevision};await reject({action:'observe',input:first},owner,409,'DELETE_SCHEMA_CHANGED');checks.push('actual owner/admin/foreign/builtin/UUID/strictfields/CAS/mandatoryfence; fixture SQL skeleton NOT normal creation or Source');
 await action({action:'seed',gameId:g.gameId},admin);const saved=await action({action:'state'},admin),x=fact(await action({action:'observe',input},owner),input);assert.deepEqual(fact(await action({action:'observe',input},admin),input),x);assert.equal((await action({action:'state'},admin)).digest,saved.digest);checks.push('native bounded quick_check twice reports ok under actual complete35-table70-object definitions and CHECK enforcement; exact12 owner/admin facts, no global size/rows/errors/IDs, all rows/seals/journal/audits unchanged');
 await action({action:'ignore',enabled:true},admin);await reject({action:'observe',input},owner,503,'DELETE_SQL_CHECK_ENFORCEMENT');await action({action:'ignore',enabled:false},admin);assert.equal((await action({action:'state'},admin)).digest,saved.digest);checks.push('actual ignore_check_constraints ON refusal, independent of old definition/FK pragma gate; fixture restores connectionflag explicitly, not product repair');
 await action({action:'corrupt'},admin);assert.equal((await base({action:'observe',input},owner)).definitionsVerified,true);await reject({action:'observe',input},owner,503,'DELETE_SQL_CHECK_ROWS');await action({action:'restore'},admin);assert.equal((await action({action:'state'},admin)).digest,saved.digest);checks.push('actual persisted invalid journal CHECK state inserted with controlled ignore ON then OFF; unchanged declarations pass but native quick_check refuses503, no SQLite error/bad value leaked; only fixture restores own pending row');
 for(const[kind,status,code]of [['index',503,'DELETE_SCHEMA_DEFINITION'],['row',409,'DELETE_FENCE_CHANGED'],['epoch',401,'SESSION_INVALID'],['tuple',401,'DELETE_SQL_CHECK_ACTOR_CHANGED'],['check',503,'DELETE_SQL_CHECK_ROWS']]){await reject({action:'observe',input,hook:kind},admin,status,code);const after=await action({action:'state'},admin);assert.equal(after.digest,saved.digest);assert.equal(after.lateIndexes,0);assert.equal(after.ignore,0);assert.equal(after.hook.fired,true);checks.push('after first nativequickcheck '+kind+' callback '+(kind==='tuple'?'synthetic returnedrole':'actual SQL')+' exact'+status+'/'+code+' and full rollback. Second finalnativequickcheck catches late CHECK-row drift, not a reusable certificate');}
 await reject({action:'budget',input},admin,503,'DELETE_SQL_CHECK_BUDGET');const budgetAfter=await action({action:'state'},admin);assert.equal(budgetAfter.digest,saved.digest);assert.equal(budgetAfter.databaseSize,saved.databaseSize);checks.push('actual34x1MiB engine-only BLOB metadata growth inside owned transaction exceeds32MiB native databaseSize; exactbudget503 and entire rows/pages rollback, no service cleanup/budget expansion/provider work');
 await reject({action:'observe',input},undefined,401,'LOGIN_REQUIRED');await reject({action:'observe',input},owner,403,'CSRF_REJECTED',{'X-CSRF-Token':'bad'});await reject({action:'observe',input},owner,403,'ORIGIN_REJECTED',{Origin:'https://example.invalid'});checks.push('actual Cookie/CSRF/Origin; no product route or deletion permission');
 await server.close();server=await startEditorBackend(join(own,'wrangler.jsonc'),{stageSource:false,stageLibrary:false});assert.deepEqual(fact(await action({action:'observe',input},owner),input),x);assert.equal((await action({action:'state'},admin)).digest,saved.digest);const changed=await call('/api/auth/password',{oldPassword:password,newPassword:randomBytes(24).toString('hex')},owner);assert.equal(changed.status,200);await reject({action:'observe',input},owner,401,'SESSION_INVALID');assert.deepEqual(fact(await action({action:'observe',input},{cookie:changed.cookie,csrf:changed.data.csrf}),input),x);assert.equal((await call(`/api/games/${g.gameId}/delete`,{},admin)).status,404);checks.push('actual workerd restart/current nativecheck and realpassword epoch replacement old401/newobserve; publicdelete404, whole rowIntegrity/nativeDrain/deletefalse');
 for(const[p,h]of Object.entries({...before.inputs,...before.imports,...sourceHashes}))assert.equal(hash(p),h,p);process.stdout.write(JSON.stringify({result:'PASS-ACTUAL-NATIVE-QUICK-CHECK-NOT-ALL-ROW-INTEGRITY',checks,calls,facts,protected:484,sourceHashes,limits:'Native quickcheck/ignoreflag with32MiB size budget only; no UNIQUE/indexcontents/FK/businessrefs/provider/body/CPU/legacy/delete. Real persisted CHECKbadrow and native late SQL rollback; role synthetic; engineered metadata notSource or nativePUT. All old484/98 unchanged.'},null,2));
}catch(error){writeFileSync(d+'failure-r'+round+'.json',JSON.stringify({message:String(error.message),checks,calls,facts},null,2),{flag:'wx'});throw error;}finally{await server?.close();}
