// Actual local workerd/R2/SQLite and HTTPS, owned bytes only. No public content API.
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { randomBytes, randomUUID, createHash } from 'node:crypto';
import { pathToFileURL } from 'node:url';
import { request as httpsRequest } from 'node:https';
const modulePath=process.env.MINIFLARE_MODULE;assert.ok(modulePath);const {Miniflare}=await import(pathToFileURL(modulePath).href);
const folder='.dragon-analysis/editor-phase/backend-blob-session-r1/',own=mkdtempSync(join(tmpdir(),'dragon-blobs-')),origin='https://127.0.0.1:8787',initial=randomBytes(24).toString('hex'),password=randomBytes(24).toString('hex'),secret=randomBytes(32).toString('hex');
const hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex'),digest=bytes=>createHash('sha256').update(Uint8Array.from(bytes)).digest('hex');
const files=['server/blobs.js','server/metadata.js','server/worker.js','server/security.js','server/wrangler.jsonc','tools/start_editor_backend.mjs','tools/verify_editor_backend_blobs.mjs',folder+'fixture-worker.js'],before=Object.fromEntries(files.map(p=>[p,hash(p)]));
let mf;const build=()=>new Miniflare({name:'blob-fixture',modules:true,scriptPath:resolve(folder+'fixture-worker.js'),compatibilityDate:'2026-01-01',compatibilityFlags:['nodejs_compat'],modulesRules:[{type:'ESModule',include:['**/*.js','**/*.mjs']},{type:'Text',include:['**/*.html','**/*.txt','**/*.css']}],host:'127.0.0.1',port:8787,https:true,durableObjects:{EDITOR_METADATA:{className:'BlobFixture',useSQLite:true}},durableObjectsPersist:join(own,'metadata'),r2Buckets:['EDITOR_BLOBS'],r2Persist:join(own,'blobs'),bindings:{EDITOR_ORIGIN:origin,EDITOR_DEFAULT_PASSWORD:initial,EDITOR_REQUEST_KEY:secret,EDITOR_ACCOUNT_LIMIT:'50',EDITOR_SOURCE_LIMIT:'100'}});
const calls=[];async function call(path,value,session,key=randomUUID()) {assert.equal((await mf.ready).origin,origin);const headers={};if(value!==undefined){headers['Content-Type']='application/json';headers.Origin=origin;headers['Idempotency-Key']=key;if(session)headers['X-CSRF-Token']=session.csrf;}if(session)headers.Cookie=session.cookie;
 const raw=await new Promise((done,reject)=>{const req=httpsRequest(origin+path,{method:value===undefined?'GET':'POST',headers,rejectUnauthorized:false},res=>{const chunks=[];res.on('data',chunk=>chunks.push(chunk));res.on('error',reject);res.on('end',()=>done({status:res.statusCode,cookie:res.headers['set-cookie']?.[0]?.split(';')[0],text:Buffer.concat(chunks).toString('utf8')}));});req.on('error',reject);req.end(value===undefined?undefined:JSON.stringify(value));});let data;try{data=JSON.parse(raw.text);}catch(cause){throw new Error('invalid owned blob HTTP response',{cause});}calls.push({path,status:raw.status});return{status:raw.status,data,cookie:raw.cookie};}
const fixture=(value,s)=>call('/api/fixture/blobs',value,s);
async function login(account) {const first=await call('/api/auth/login',{account,password:initial});assert.equal(first.status,200);const changed=await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:first.cookie,csrf:first.data.csrf});assert.equal(changed.status,200);return{cookie:changed.cookie,csrf:changed.data.csrf,user:changed.data.user};}
const checks=[];try {
 mf=build();const admin=await login('tianyi');for(const account of ['author_a','author_b'])assert.equal((await call('/api/admin/accounts',{account},admin)).status,200);let a=await login('author_a');const b=await login('author_b');
 const create=await fixture({action:'create',name:'測試A'},a);assert.equal(create.status,200,create.data.error);const gameId=create.data.result.gameId;const other=await fixture({action:'create',name:'測試B'},b);assert.equal(other.status,200);const records=[];
 for(const size of[0,1,257,4096]){const values=Array.from({length:size},(_,i)=>(i*17+size)%256),p=await fixture({action:'put',gameId,values,mutate:true},a);assert.equal(p.status,200,p.data.error);assert.equal(p.data.result.sha256,digest(values));assert.equal(p.data.result.byteLength,size);assert.equal(p.data.result.created,true);assert.equal(p.data.result.key,`private/${gameId}/${digest(values)}`);const r=await fixture({action:'read',...p.data.result},a);assert.equal(r.status,200);assert.equal(r.data.result.bytes,Buffer.from(values).toString('hex'));records.push({descriptor:p.data.result,values});}
 checks.push('actual R2 put/get/readback SHA and bytes0/1/257/4096, derived game keys and capture before await; no etag/hash assertion shortcut');
 const again=await fixture({action:'put',gameId,values:records[2].values},a);assert.equal(again.status,200);assert.equal(again.data.result.created,false);const parallelValues=[42,41,40],parallel=await Promise.all([fixture({action:'put',gameId,values:parallelValues},a),fixture({action:'put',gameId,values:parallelValues},a)]);assert.deepEqual(parallel.map(r=>r.status),[200,200]);assert.deepEqual(parallel.map(r=>r.data.result.created).sort(),[false,true]);checks.push('real R2 If-None-Match:* rejects overwrite and concurrent equal puts write exactly one new object');
 const priorIo=(await fixture({action:'io'},admin)).data.result;for(const s of[b,admin]){assert.equal((await fixture({action:'read',...records[2].descriptor},s)).status,404);assert.equal((await fixture({action:'put',gameId,values:[1]},s)).status,404);}assert.equal((await fixture({action:'put',gameId:'wolong-builtin',values:[1]},admin)).status,403);for(const id of['../escape',randomUUID()])assert.equal((await fixture({action:'put',gameId:id,values:[1]},a)).status,id.includes('/')?422:404);assert.equal((await fixture({action:'read',...records[2].descriptor,sha256:'../escape'},a)).status,422);assert.deepEqual((await fixture({action:'io'},admin)).data.result,priorIo);checks.push('real session/own SQLite authority before storage I/O; other author/admin/hash/path/builtin cannot read/write private objects');
 const scope=await fixture({action:'scope'},a);assert.equal(scope.status,200,scope.data.error);assert.equal(scope.data.result.rejected.length,3);assert.equal(scope.data.result.policyErrors.length,6);checks.push('new-game staging requires actual allocation object, not JSON/owner DTO; permanently used missing id cannot reopen; nonfinite/zero policy rejected');
 const quotaIo=(await fixture({action:'io'},admin)).data.result;assert.equal((await fixture({action:'put',gameId,values:Array(4097).fill(1)},a)).status,413);assert.equal((await fixture({action:'read',gameId,sha256:digest([1]),byteLength:4097},a)).status,413);assert.equal((await fixture({action:'read',gameId,sha256:digest([222,223,224]),byteLength:3},a)).status,404);assert.equal((await fixture({action:'read',...records[2].descriptor,byteLength:256},a)).status,503);const quotaAfter=(await fixture({action:'io'},admin)).data.result;assert.equal(quotaAfter.puts,quotaIo.puts);assert.equal(quotaAfter.gets,quotaIo.gets+2);checks.push('bounded configured size, declared length and missing key distinctions; no false game deletion or unsafe resource fallback');
 const corrupt=records[1];assert.equal((await fixture({action:'corrupt',...corrupt.descriptor,values:[99]},admin)).status,200);assert.equal((await fixture({action:'read',...corrupt.descriptor},a)).status,503);assert.equal((await fixture({action:'put',gameId,values:corrupt.values},a)).status,503);assert.equal((await fixture({action:'read',...corrupt.descriptor},a)).status,503);checks.push('owned native bucket fault injection proves full byte SHA rejects same-size corruption and conflicting-existing data never silently repaired/overwritten');
 assert.equal((await fixture({action:'delete',...records[2].descriptor},a)).status,503);assert.equal((await fixture({action:'read',...records[2].descriptor},a)).status,200);assert.equal((await call('/api/games/'+gameId+'/assets',{bytes:'not accepted'},a)).status,404);checks.push('owner alone is not deletion/reference authority; deletion503 and production upload/draft write routes still closed');
 const wait=async()=>{for(let i=0;i<50;i++){if((await fixture({action:'waiting'},admin)).data.result.waiting)return;await new Promise(done=>setTimeout(done,10));}throw new Error('owned I/O did not reach delay');};
 const pending=fixture({action:'read',...records[2].descriptor,delay:true},a);await wait();const disabled=await call('/api/admin/accounts/'+a.user.id+'/disable',{expectedVersion:a.user.version,disabled:true},admin);assert.equal(disabled.status,200);assert.equal((await fixture({action:'release'},admin)).status,200);assert.equal((await pending).status,401);assert.equal((await fixture({action:'read',...records[2].descriptor},a)).status,401);assert.equal((await fixture({action:'read',...records[2].descriptor,gameId:other.data.result.gameId},b)).status,404);const enabled=await call('/api/admin/accounts/'+a.user.id+'/disable',{expectedVersion:disabled.data.account.version,disabled:false},admin);assert.equal(enabled.status,200);const relogin=await call('/api/auth/login',{account:'author_a',password});assert.equal(relogin.status,200);a={cookie:relogin.cookie,csrf:relogin.data.csrf,user:relogin.data.user};
 const orphanValues=[77,78],pendingPut=fixture({action:'put',gameId,values:orphanValues,delay:true},a);await wait();const disabledAgain=await call('/api/admin/accounts/'+a.user.id+'/disable',{expectedVersion:a.user.version,disabled:true},admin);assert.equal(disabledAgain.status,200);assert.equal((await fixture({action:'release'},admin)).status,200);assert.equal((await pendingPut).status,401);assert.equal((await call('/api/admin/accounts/'+a.user.id+'/disable',{expectedVersion:disabledAgain.data.account.version,disabled:false},admin)).status,200);const loginAgain=await call('/api/auth/login',{account:'author_a',password});assert.equal(loginAgain.status,200);a={cookie:loginAgain.cookie,csrf:loginAgain.data.csrf,user:loginAgain.data.user};assert.equal((await fixture({action:'read',gameId,sha256:digest(orphanValues),byteLength:2},a)).status,200);const streamPending=fixture({action:'read',...records[2].descriptor,delay:'stream'},a);await wait();const streamDisabled=await call('/api/admin/accounts/'+a.user.id+'/disable',{expectedVersion:a.user.version,disabled:true},admin);assert.equal(streamDisabled.status,200);assert.equal((await fixture({action:'release'},admin)).status,200);assert.equal((await streamPending).status,401);assert.equal((await call('/api/admin/accounts/'+a.user.id+'/disable',{expectedVersion:streamDisabled.data.account.version,disabled:false},admin)).status,200);const streamLogin=await call('/api/auth/login',{account:'author_a',password});assert.equal(streamLogin.status,200);a={cookie:streamLogin.cookie,csrf:streamLogin.data.csrf,user:streamLogin.data.user};checks.push('actual disable during native R2 get/put and partially-consumed R2 stream rejects completion401; no stale principal/epoch delivery; private in-flight staging orphan not falsely rolled back/deleted');
 await mf.dispose();mf=undefined;mf=build();const restored=await fixture({action:'read',...records[2].descriptor},a);assert.equal(restored.status,200);assert.equal(restored.data.result.bytes,Buffer.from(records[2].values).toString('hex'));assert.equal((await fixture({action:'put',gameId,values:records[2].values},a)).data.result.created,false);assert.equal((await fixture({action:'read',...corrupt.descriptor},a)).status,503);checks.push('real workerd restart keeps separate durable R2 bytes and SQLite ownership/session; no process Map as persistence');
 for(const[p,h]of Object.entries(before))assert.equal(hash(p),h);const receipt={result:'PASS-REAL-R2-IMMUTABLE-BLOB-FOUNDATION',checks,calls,sourceHashes:before,ownedPersistence:true,limits:'Only actual owned local R2 and SQLite engineering bytes; no real GameSource/dependency/portrait admission, production snapshot verifier and writes closed, deletion fence/ref cleanup/backup/GC/jobs/release/Trial incomplete. Revoked pending put may leave private unreferenced staging, not transaction rollback/DRM. No cloud bucket creation/deployment.'};writeFileSync(join(own,'receipt.json'),JSON.stringify(receipt,null,2));process.stdout.write(JSON.stringify(receipt,null,2)+'\n');
} finally {await mf?.dispose();}
