// Actual Root authority with owned SQL-only native unique-key probes; no Source/provider/delete.
import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdtempSync} from 'node:fs';import {resolve,join} from 'node:path';import {tmpdir} from 'node:os';import {createHash,randomBytes,randomUUID} from 'node:crypto';import {request as httpsRequest} from 'node:https';import {startEditorBackend} from './start_editor_backend.mjs';
const d='.dragon-analysis/editor-phase/backend-index-projections-session-r1/',round=process.argv[2],origin='https://127.0.0.1:8787';assert.match(round??'',/^[1-9][0-9]{0,2}$/);const hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex');function parse(b){try{return JSON.parse(b);}catch(cause){throw new Error('owned unique-key JSON',{cause});}}
const before=parse(readFileSync(d+'before.json'));for(const[p,h]of Object.entries({...before.inputs,...before.imports}))assert.equal(hash(p),h,p);const paths=['server/deletionindexprojections.js','tools/verify_editor_backend_index_projections.mjs',d+'fixture-worker.js','server/deletionschemaintegrity.js','server/deletiondefinitions.js','server/worker.js','.dragon-analysis/editor-phase/backend-deletion-definitions-session-r1/fixture-worker.js','.dragon-analysis/editor-phase/backend-declared-unique-rows-session-r1/fixture-worker.js','server/deletionuniquerows.js'],sourceHashes=Object.fromEntries(paths.map(p=>[p,hash(p)]));
const own=mkdtempSync(join(tmpdir(),'dragon-unique-rows-')),config=parse(readFileSync('server/wrangler.jsonc')),initial=randomBytes(24).toString('hex'),password=randomBytes(24).toString('hex');config.main=resolve(d+'fixture-worker.js');writeFileSync(join(own,'wrangler.jsonc'),JSON.stringify(config),{flag:'wx'});writeFileSync(join(own,'.dev.vars'),`EDITOR_DEFAULT_PASSWORD=${JSON.stringify(initial)}\nEDITOR_REQUEST_KEY=${JSON.stringify(randomBytes(32).toString('hex'))}\n`,{flag:'wx',mode:0o600});const checks=[],calls=[],facts=[];let server;
async function call(path,value,session,extra={}){const headers={Origin:origin,'Content-Type':'application/json','Idempotency-Key':randomUUID()};if(session){headers.Cookie=session.cookie;headers['X-CSRF-Token']=session.csrf;}Object.assign(headers,extra);const r=await new Promise((done,reject)=>{const req=httpsRequest(origin+path,{method:value===undefined?'GET':'POST',headers,rejectUnauthorized:false,agent:false},res=>{const chunks=[];res.on('data',b=>chunks.push(b));res.on('error',reject);res.on('end',()=>{try{done({status:res.statusCode,data:parse(Buffer.concat(chunks)),cookie:res.headers['set-cookie']?.[0]?.split(';')[0]});}catch(error){reject(error);}});});req.on('error',reject);req.end(value===undefined?undefined:JSON.stringify(value));});calls.push({path,status:r.status});return r;}
async function ok(path,v,s,x){const r=await call(path,v,s,x);assert.equal(r.status,200,r.data.error);return r.data.result??r.data;}const action=(v,s)=>ok('/api/test/index-projections',v,s),base=(v,s)=>ok('/api/test/definitions',v,s);
async function reject(v,s,status,code,extra){const r=await call('/api/test/index-projections',v,s,extra);assert.equal(r.status,status,r.data.error);assert.equal(r.data.error,code);}
async function login(account){const r=await call('/api/auth/login',{account,password:initial});assert.equal(r.status,200);const p=await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:r.cookie,csrf:r.data.csrf});assert.equal(p.status,200);return{cookie:p.cookie,csrf:p.data.csrf};}
function fact(x,input){assert.equal(Object.keys(x).length,14);assert.equal(x.gameId,input.gameId);assert.equal(x.rowRevision,input.expectedRowRevision);assert.match(x.schemaDigest,/^[a-f0-9]{64}$/);assert.equal(x.tablesVerified,35);assert.equal(x.indexesVerified,35);assert.equal(x.foreignKeyDeclarationsVerified,3);assert.equal(x.definitionsVerified,true);assert.equal(x.indexProjectionsVerified,true);assert.equal(x.indexesCompared,35);for(const k of ['indexContentIntegrityVerified','rowIntegrityVerified','nativeDrainVerified','deleteAllowed'])assert.equal(x[k],false);assert.equal(x.mode,'CURRENT_DECLARED_INDEX_PROJECTIONS_ONLY_LEGACY_UNKNOWN');facts.push(x);return x;}
try{
 server=await startEditorBackend(join(own,'wrangler.jsonc'),{stageSource:false,stageLibrary:false});const admin=await login('tianyi');await ok('/api/admin/accounts',{account:'index_owner'},admin);await ok('/api/admin/accounts',{account:'index_other'},admin);const owner=await login('index_owner'),other=await login('index_other'),g=await base({action:'create',name:'索引投影'},owner),first={gameId:g.gameId,expectedRowRevision:'1'};
 await reject({action:'observe',input:first},owner,409,'DELETE_FENCE_REQUIRED');await reject({action:'observe',input:first},other,404,'GAME_NOT_FOUND');await reject({action:'observe',input:{gameId:'wolong-builtin',expectedRowRevision:'1'}},admin,403,'BUILTIN_PROTECTED');await reject({action:'observe',input:{...first,plan:{}}},owner,422,'REQUEST_FIELDS');await reject({action:'observe',input:{gameId:[g.gameId],expectedRowRevision:'1'}},owner,422,'DELETE_SCHEMA_INPUT');const f=await base({action:'fence',input:{...first,confirmationName:g.name}},owner),input={gameId:g.gameId,expectedRowRevision:f.rowRevision};await reject({action:'observe',input:first},owner,409,'DELETE_SCHEMA_CHANGED');checks.push('actual owner/admin/foreign/builtin/strictfield/UUID/fence/CAS gates; SQL skeleton not Source/normal creation');
 const oldAction=(v)=>ok('/api/test/unique-rows',v,admin);await oldAction({action:'seed',gameId:g.gameId});const saved=await oldAction({action:'state'}),x=fact(await action({action:'observe',input},owner),input);assert.deepEqual(fact(await action({action:'observe',input},admin),input),x);const unchanged=await oldAction({action:'state'});assert.equal(unchanged.digest,saved.digest);assert.equal(unchanged.schema,saved.schema);checks.push('actual35 COVERING INDEX plans and incremental INDEXED BY vs NOT INDEXED native rowid/type/hex/numeric projections compare; exact14 owner/admin facts, full physical/index/business integrity and drain/delete remainfalse, metadata unchanged');
 assert.deepEqual(fact(await action({action:'typed',input},admin),input),x);assert.equal((await oldAction({action:'state'})).digest,saved.digest);checks.push('native healthy nullable TEXT PK has two NULL rows plus BLOB x61 and TEXT a distinguished by rowid/storageclass/native bytes; service compares existing indexes, not businessID/null admission; only owned fixture removes engineering rows');
 for(const kind of ['bytes','missing','duplicate','rowid','plan']){await reject({action:'synthetic',kind},admin,503,kind==='plan'?'DELETE_INDEX_PLAN':'DELETE_INDEX_ROWS');checks.push('EXPLICIT SYNTHETIC '+kind+' cursor/plan transformation over actual SQLite result rejects; NOT native persisted corrupt-index evidence or product authority probe');}assert.equal((await oldAction({action:'state'})).digest,saved.digest);
 for(const [at,kind,status,code]of [[3,'index',503,'DELETE_SCHEMA_DEFINITION'],[3,'row',409,'DELETE_FENCE_CHANGED'],[3,'epoch',401,'SESSION_INVALID'],[37,'index',503,'DELETE_SCHEMA_DEFINITION'],[37,'row',409,'DELETE_FENCE_CHANGED'],[37,'epoch',401,'SESSION_INVALID'],[37,'expire',401,'SESSION_INVALID'],[37,'budget',503,'DELETE_INDEX_BUDGET']]){await reject({action:'observe',input,hook:kind,at},admin,status,code);const state=await oldAction({action:'state'});assert.equal(state.digest,saved.digest);assert.equal(state.schema,saved.schema);const hook=await action({action:'hook-state'},admin);assert.equal(hook.fired,true);assert.equal(hook.firedAt,at);checks.push('actual native '+kind+' at original principal '+at+' exact'+status+'/'+code+' full35 rows/catalog rollback; afterlastcallback final pure scan and internal actualsession/schema/fence recheck, no external callback after capturedDTO');}
 await reject({action:'observe',input},undefined,401,'LOGIN_REQUIRED');await reject({action:'observe',input},owner,403,'CSRF_REJECTED',{'X-CSRF-Token':'bad'});await reject({action:'observe',input},owner,403,'ORIGIN_REJECTED',{Origin:'https://example.invalid'});checks.push('actual Cookie/Origin/CSRF at own fixture route only, no new product API');
 await server.close();server=await startEditorBackend(join(own,'wrangler.jsonc'),{stageSource:false,stageLibrary:false});assert.deepEqual(fact(await action({action:'observe',input},owner),input),x);const changed=await call('/api/auth/password',{oldPassword:password,newPassword:randomBytes(24).toString('hex')},owner);assert.equal(changed.status,200);await reject({action:'observe',input},owner,401,'SESSION_INVALID');assert.deepEqual(fact(await action({action:'observe',input},{cookie:changed.cookie,csrf:changed.data.csrf}),input),x);assert.equal((await call(`/api/games/${g.gameId}/delete`,{},admin)).status,404);checks.push('real workerd restart and password handler oldepoch401/newsession; current facts only/publicdelete404/no completed410');
 for(const[p,h]of Object.entries({...before.inputs,...before.imports,...sourceHashes}))assert.equal(hash(p),h,p);process.stdout.write(JSON.stringify({result:'PASS-ACTUAL-DECLARED-INDEX-PROJECTIONS-NOT-PHYSICAL-INTEGRITY',checks,calls,facts,protected:490,sourceHashes,limits:'35 fixed covering implicit indexes/33 tables logical projected contents vs table only. Native healthy data/NULL/BLOB-text and strict SQL schema/authority/late mutation actual; broken index result transformations SYNTHETIC, never persisted native page corruption. Engineering budgets and no provider/fullbusinessrefs/physical-index-integrity/drain/delete.'},null,2));
}catch(error){writeFileSync(d+'failure-r'+round+'.json',JSON.stringify({message:String(error.message),checks,calls,facts},null,2),{flag:'wx'});throw error;}finally{await server?.close();}
