// Compiler → actual native initialization/rebind only; no App, Clock or rules.
import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{spawnSync}from'node:child_process';import{createHash}from'node:crypto';
import{initializeNativeFactionSlots,rebindNativeFactionViews}from'../web/src/game/nativefactions.js';
const env={};for(const key of ['SystemRoot','SYSTEMROOT','WINDIR','COMSPEC','ComSpec','PATH','Path','PATHEXT','TEMP','TMP','USERPROFILE','LOCALAPPDATA','APPDATA','HOMEDRIVE','HOMEPATH'])if(process.env[key]!==undefined)env[key]=process.env[key];env.PYTHONDONTWRITEBYTECODE='1';env.PYTHONUTF8='1';env.PYTHONOPTIMIZE='';
const result=spawnSync('python',['-X','utf8','-B','tools/verify_editor_money_compile.py'],{env,encoding:'utf8',maxBuffer:16*1024*1024,timeout:180000});assert.equal(result.status,0,result.stderr);let proof;try{proof=JSON.parse(result.stdout);}catch(cause){throw new TypeError('invalid money compile proof JSON',{cause});}assert.equal(proof.result,'PASS-MONEY-COMPILE-SIGNED24-FIXED-SOURCE');assert.equal(proof.chapters,20);assert.equal(proof.checks,70);assert.equal(proof.refusals,13);assert.equal(proof.cases.length,50);
let implicitIDB=0;const prior=Object.getOwnPropertyDescriptor(globalThis,'indexedDB');Object.defineProperty(globalThis,'indexedDB',{configurable:true,get(){implicitIDB++;throw new Error('native IDB forbidden');}});const rows=[];
try{for(const item of proof.cases){const sc=item.scenario,rawBefore=sc.nativeFactionSlotRaw.slice();initializeNativeFactionSlots(sc);assert.equal(sc.nativeFactionSlots.records.length,22);
 for(let slot=0;slot<22;slot++){const raw=Buffer.from(rawBefore[slot],'hex'),expected=raw.readIntLE(0x20,3),faction=sc.nativeFactionSlots.records[slot];assert.equal(faction.money,expected);assert.equal(faction.raw,rawBefore[slot].toLowerCase());if(slot<sc.factions.length)assert.equal(sc.factions[slot],faction);}
 for(const[slot,money]of item.changes)assert.equal(sc.factions[slot].money,money);
 const text=JSON.stringify(sc);let cold;try{cold=JSON.parse(text);}catch(cause){throw new TypeError('invalid own native cold JSON',{cause});}rebindNativeFactionViews(cold);for(let slot=0;slot<cold.factions.length;slot++)assert.equal(cold.factions[slot],cold.nativeFactionSlots.records[slot]);assert.deepEqual(cold,sc);assert.deepEqual(sc.nativeFactionSlotRaw,rawBefore);
 rows.push({idx:item.idx,changes:item.changes,unknownBytesPreserved:item.unknown,initializedAndColdRebound:true});
}}finally{if(prior)Object.defineProperty(globalThis,'indexedDB',prior);else delete globalThis.indexedDB;}assert.equal(implicitIDB,0);
const sha=path=>createHash('sha256').update(readFileSync(path)).digest('hex');for(const[path,hash]of Object.entries(proof.inputHashes))assert.equal(sha(path),hash,path);const toolHashes=Object.fromEntries(['tools/verify_editor_money_compile.mjs','tools/verify_editor_money_compile.py','tools/content_pipeline.py','web/src/game/nativefactions.js'].map(path=>[path,sha(path)]));
process.stdout.write(JSON.stringify({result:'PASS-MONEY-COMPILE-NATIVE-COLD',chapters:20,checks:70,refusals:13,nativeCases:50,implicitIDB,inputHashes:proof.inputHashes,toolHashes,rows,limits:'Shared native table initializer/rebind only, no full detached assembly/negative edit-domain approval/rule ticks/default install/legacy saves. Other named native faction fields remain separately unclosed.'},null,2)+'\n');
