// Actual Root authority with owned SQL-only native unique-key probes; no Source/provider/delete.
import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdtempSync} from 'node:fs';import {resolve,join} from 'node:path';import {tmpdir} from 'node:os';import {createHash,randomBytes,randomUUID} from 'node:crypto';import {request as httpsRequest} from 'node:https';import {startEditorBackend} from './start_editor_backend.mjs';
const d='.dragon-analysis/editor-phase/backend-name-bindings-session-r1/',round=process.argv[2],origin='https://127.0.0.1:8787';assert.match(round??'',/^[1-9][0-9]{0,2}$/);const hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex');function parse(b){try{return JSON.parse(b);}catch(cause){throw new Error('owned unique-key JSON',{cause});}}
const before=parse(readFileSync(d+'before.json'));for(const[p,h]of Object.entries({...before.inputs,...before.imports}))assert.equal(hash(p),h,p);const paths=['server/deletionnamebindings.js','tools/verify_editor_backend_name_bindings.mjs',d+'fixture-worker.js','server/deletionschemaintegrity.js','server/deletiondefinitions.js','server/worker.js','.dragon-analysis/editor-phase/backend-deletion-definitions-session-r1/fixture-worker.js','.dragon-analysis/editor-phase/backend-declared-unique-rows-session-r1/fixture-worker.js','server/deletionuniquerows.js','server/metadata.js','.dragon-analysis/editor-phase/backend-index-projections-session-r1/fixture-worker.js'],sourceHashes=Object.fromEntries(paths.map(p=>[p,hash(p)]));
const own=mkdtempSync(join(tmpdir(),'dragon-unique-rows-')),config=parse(readFileSync('server/wrangler.jsonc')),initial=randomBytes(24).toString('hex'),password=randomBytes(24).toString('hex');config.main=resolve(d+'fixture-worker.js');writeFileSync(join(own,'wrangler.jsonc'),JSON.stringify(config),{flag:'wx'});writeFileSync(join(own,'.dev.vars'),`EDITOR_DEFAULT_PASSWORD=${JSON.stringify(initial)}\nEDITOR_REQUEST_KEY=${JSON.stringify(randomBytes(32).toString('hex'))}\n`,{flag:'wx',mode:0o600});const checks=[],calls=[],facts=[];let server;
async function call(path,value,session,extra={}){const headers={Origin:origin,'Content-Type':'application/json','Idempotency-Key':randomUUID()};if(session){headers.Cookie=session.cookie;headers['X-CSRF-Token']=session.csrf;}Object.assign(headers,extra);const r=await new Promise((done,reject)=>{const req=httpsRequest(origin+path,{method:value===undefined?'GET':'POST',headers,rejectUnauthorized:false,agent:false},res=>{const chunks=[];res.on('data',b=>chunks.push(b));res.on('error',reject);res.on('end',()=>{try{done({status:res.statusCode,data:parse(Buffer.concat(chunks)),cookie:res.headers['set-cookie']?.[0]?.split(';')[0]});}catch(error){reject(error);}});});req.on('error',reject);req.end(value===undefined?undefined:JSON.stringify(value));});calls.push({path,status:r.status});return r;}
async function ok(path,v,s,x){const r=await call(path,v,s,x);assert.equal(r.status,200,r.data.error);return r.data.result??r.data;}const action=(v,s)=>ok('/api/test/name-bindings',v,s),base=(v,s)=>ok('/api/test/definitions',v,s);
async function reject(v,s,status,code,extra){const r=await call('/api/test/name-bindings',v,s,extra);assert.equal(r.status,status,r.data.error);assert.equal(r.data.error,code);}
async function login(account){const r=await call('/api/auth/login',{account,password:initial});assert.equal(r.status,200);const p=await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:r.cookie,csrf:r.data.csrf});assert.equal(p.status,200);return{cookie:p.cookie,csrf:p.data.csrf};}
function fact(x,input){assert.equal(Object.keys(x).length,13);assert.equal(x.gameId,input.gameId);assert.equal(x.rowRevision,input.expectedRowRevision);assert.match(x.schemaDigest,/^[a-f0-9]{64}$/);assert.equal(x.tablesVerified,35);assert.equal(x.indexesVerified,35);assert.equal(x.foreignKeyDeclarationsVerified,3);for(const k of ['definitionsVerified','nameBindingsVerified','usedIdBindingVerified'])assert.equal(x[k],true);for(const k of ['rowIntegrityVerified','nativeDrainVerified','deleteAllowed'])assert.equal(x[k],false);assert.equal(x.mode,'CURRENT_GAME_NAME_ID_BINDINGS_ONLY_LEGACY_UNKNOWN');facts.push(x);return x;}
try{
 server=await startEditorBackend(join(own,'wrangler.jsonc'),{stageSource:false,stageLibrary:false});const admin=await login('tianyi');await ok('/api/admin/accounts',{account:'name_owner'},admin);await ok('/api/admin/accounts',{account:'name_other'},admin);const owner=await login('name_owner'),other=await login('name_other'),g=await base({action:'create',name:'case'},owner),first={gameId:g.gameId,expectedRowRevision:'1'};
 await reject({action:'observe',input:first},owner,409,'DELETE_FENCE_REQUIRED');await reject({action:'observe',input:first},other,404,'GAME_NOT_FOUND');await reject({action:'observe',input:{gameId:'wolong-builtin',expectedRowRevision:'1'}},admin,403,'BUILTIN_PROTECTED');await reject({action:'observe',input:{...first,plan:{}}},owner,422,'REQUEST_FIELDS');await reject({action:'observe',input:{gameId:[g.gameId],expectedRowRevision:'1'}},owner,422,'DELETE_SCHEMA_INPUT');const f=await base({action:'fence',input:{...first,confirmationName:g.name}},owner),input={gameId:g.gameId,expectedRowRevision:f.rowRevision};await reject({action:'observe',input:first},owner,409,'DELETE_SCHEMA_CHANGED');checks.push('actual Root owner/admin/foreign/builtin/strictfields/UUID/fence/CAS gates; current SQL skeleton only, not Source/normal creation');
 const oldAction=v=>ok('/api/test/unique-rows',v,admin),state=()=>oldAction({action:'state'}),saved=await state(),x=fact(await action({action:'observe',input},owner),input);assert.deepEqual(fact(await action({action:'observe',input},admin),input),x);assert.equal((await state()).digest,saved.digest);checks.push('actual current draft-name single binding and permanent used-ID, exact13 minimal owner/admin facts; read-only full35 row/catalog fingerprint same; fullrefs/row/native/delete remainfalse');
 for(const[kind,n]of [['same',1],['distinct',2],['null',1]]){const r=await action({action:'formal',gameId:g.gameId,kind},admin);assert.equal(r.nameRows,n);assert.deepEqual(fact(await action({action:'observe',input},owner),input),x);checks.push('actual manual formal-name '+kind+' occupies exactly '+n+' BINARY names with draft, no release/publication or initialization certificate');}assert.equal((await state()).digest,saved.digest);
 await base({action:'create',name:'case'},other);const stable=await state();assert.deepEqual(fact(await action({action:'observe',input},owner),input),x);checks.push('same spelling by other real author/game does not contaminate target occupancy; no global other-game consistency claim');
 for(const kind of ['missing','extra','owner','game','case','type','used']){const code=kind==='used'?'DELETE_FENCE_CHANGED':'DELETE_NAME_BINDING_ROWS',status=kind==='used'?409:503;await reject({action:'negative',kind,input},admin,status,code);const now=await state();assert.equal(now.digest,stable.digest);assert.equal(now.schema,stable.schema);checks.push('native target '+kind+' binding exact'+status+'/'+code+' and entire35 SQL rows/catalog rollback; no fixture repair by product');}
 await action({action:'formal',gameId:g.gameId,kind:'distinct'},admin);const double=await state();await reject({action:'negative',kind:'extra',input},admin,503,'DELETE_NAME_BINDING_ROWS');assert.equal((await state()).digest,double.digest);await action({action:'formal',gameId:g.gameId,kind:'null'},admin);assert.equal((await state()).digest,stable.digest);checks.push('native third extra target name refuses bounded LIMIT3/cardinality; restored only explicit fixture formal samples, no new editor domain');
 for(const[at,kind,status,code]of [[3,'missing',503,'DELETE_NAME_BINDING_ROWS'],[3,'index',503,'DELETE_SCHEMA_DEFINITION'],[3,'epoch',401,'SESSION_INVALID'],[4,'extra',503,'DELETE_NAME_BINDING_ROWS'],[4,'case',503,'DELETE_NAME_BINDING_ROWS'],[4,'owner',503,'DELETE_NAME_BINDING_ROWS'],[4,'used',409,'DELETE_FENCE_CHANGED'],[4,'index',503,'DELETE_SCHEMA_DEFINITION'],[4,'row',409,'DELETE_FENCE_CHANGED'],[4,'epoch',401,'SESSION_INVALID'],[4,'expire',401,'SESSION_INVALID'],[4,'role',401,'DELETE_NAME_BINDING_ACTOR_CHANGED']]){await reject({action:'observe',input,hook:kind,at},admin,status,code);const hook=await action({action:'hook-state'},admin);assert.equal(hook.firedAt,at);const now=await state();assert.equal(now.digest,stable.digest);assert.equal(now.schema,stable.schema);checks.push('actual native late '+kind+' principalcallback'+at+' exact'+status+'/'+code+' full SQL rollback; afterlast externalcallback internal actualsession/schema/target names rechecked, capturedDTO not authority');}
 await reject({action:'observe',input},undefined,401,'LOGIN_REQUIRED');await reject({action:'observe',input},owner,403,'CSRF_REJECTED',{'X-CSRF-Token':'bad'});await reject({action:'observe',input},owner,403,'ORIGIN_REJECTED',{Origin:'https://example.invalid'});checks.push('actual Cookie/Origin/CSRF at owned fixture only, no product public route');
 await server.close();server=await startEditorBackend(join(own,'wrangler.jsonc'),{stageSource:false,stageLibrary:false});assert.deepEqual(fact(await action({action:'observe',input},owner),input),x);const changed=await call('/api/auth/password',{oldPassword:password,newPassword:randomBytes(24).toString('hex')},owner);assert.equal(changed.status,200);await reject({action:'observe',input},owner,401,'SESSION_INVALID');assert.deepEqual(fact(await action({action:'observe',input},{cookie:changed.cookie,csrf:changed.data.csrf}),input),x);assert.equal((await call(`/api/games/${g.gameId}/delete`,{},admin)).status,404);checks.push('actual workerd/DO restart and real password epoch old401/newfacts; publicdelete404, no410/cleanup/drain or reusable permission');
 const duplicateBefore=await state();await reject({action:'duplicate',input},admin,503,'DELETE_NAME_BINDING_ROWS');const duplicateAfter=await state();assert.equal(duplicateAfter.digest,duplicateBefore.digest);assert.equal(duplicateAfter.schema,duplicateBefore.schema);checks.push('temporary native removal of content_names unique declaration then duplicate identical target membership rejects exact503 in lowlevel binding cardinality; whole original schema/rows rollback, NOT persisted native index corruption or fullservice accepting drift');
 for(const[p,h]of Object.entries({...before.inputs,...before.imports,...sourceHashes}))assert.equal(hash(p),h,p);process.stdout.write(JSON.stringify({result:'PASS-ACTUAL-CURRENT-GAME-NAME-ID-BINDINGS-ONLY',checks,calls,facts,protected:492,sourceHashes,limits:'Target native TEXT game-id and draft/nullable current formal BINARY name occupancy + used-ID only. Manual formal states NOT releases, SQL skeleton NOT Source; no normalization/domain/allbusiness/historicalrefs/BLOB-ID aliases/provider/body/CPU/delete. Old gates unchanged.'},null,2));
}catch(error){writeFileSync(d+'failure-r'+round+'.json',JSON.stringify({message:String(error.message),checks,calls,facts},null,2),{flag:'wx'});throw error;}finally{await server?.close();}
