// Actual Root authority with owned SQL-only FK edge probes; no Source/provider/delete.
import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdtempSync} from 'node:fs';import {resolve,join} from 'node:path';import {tmpdir} from 'node:os';import {createHash,randomBytes,randomUUID} from 'node:crypto';import {request as httpsRequest} from 'node:https';import {startEditorBackend} from './start_editor_backend.mjs';
const d='.dragon-analysis/editor-phase/backend-declared-fk-rows-session-r1/',round=process.argv[2],origin='https://127.0.0.1:8787';assert.match(round??'',/^[1-9][0-9]{0,2}$/);const hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex');function parse(b){try{return JSON.parse(b);}catch(cause){throw new Error('owned FK probe JSON',{cause});}}
const before=parse(readFileSync(d+'before.json'));for(const[p,h]of Object.entries({...before.inputs,...before.imports}))assert.equal(hash(p),h,p);const paths=['server/deletionforeignkeyrows.js','tools/verify_editor_backend_declared_fk_rows.mjs',d+'fixture-worker.js','server/deletionschemaintegrity.js','server/deletiondefinitions.js','server/worker.js','.dragon-analysis/editor-phase/backend-deletion-definitions-session-r1/fixture-worker.js'],sourceHashes=Object.fromEntries(paths.map(p=>[p,hash(p)]));
const own=mkdtempSync(join(tmpdir(),'dragon-fk-rows-')),config=parse(readFileSync('server/wrangler.jsonc')),initial=randomBytes(24).toString('hex'),password=randomBytes(24).toString('hex');config.main=resolve(d+'fixture-worker.js');writeFileSync(join(own,'wrangler.jsonc'),JSON.stringify(config),{flag:'wx'});writeFileSync(join(own,'.dev.vars'),`EDITOR_DEFAULT_PASSWORD=${JSON.stringify(initial)}\nEDITOR_REQUEST_KEY=${JSON.stringify(randomBytes(32).toString('hex'))}\n`,{flag:'wx',mode:0o600});const checks=[],calls=[],facts=[];let server;
async function call(path,value,session,extra={}){const headers={Origin:origin,'Content-Type':'application/json','Idempotency-Key':randomUUID()};if(session){headers.Cookie=session.cookie;headers['X-CSRF-Token']=session.csrf;}Object.assign(headers,extra);const r=await new Promise((done,reject)=>{const req=httpsRequest(origin+path,{method:value===undefined?'GET':'POST',headers,rejectUnauthorized:false,agent:false},res=>{const chunks=[];res.on('data',b=>chunks.push(b));res.on('error',reject);res.on('end',()=>{try{done({status:res.statusCode,data:parse(Buffer.concat(chunks)),cookie:res.headers['set-cookie']?.[0]?.split(';')[0]});}catch(error){reject(error);}});});req.on('error',reject);req.end(value===undefined?undefined:JSON.stringify(value));});calls.push({path,status:r.status});return r;}
async function ok(path,v,s,x){const r=await call(path,v,s,x);assert.equal(r.status,200,r.data.error);return r.data.result??r.data;}const action=(v,s)=>ok('/api/test/fk-rows',v,s),base=(v,s)=>ok('/api/test/definitions',v,s);
async function reject(v,s,status,code,extra){const r=await call('/api/test/fk-rows',v,s,extra);assert.equal(r.status,status,r.data.error);assert.equal(r.data.error,code);}
async function login(account){const r=await call('/api/auth/login',{account,password:initial});assert.equal(r.status,200);const p=await call('/api/auth/password',{oldPassword:initial,newPassword:password},{cookie:r.cookie,csrf:r.data.csrf});assert.equal(p.status,200);return{cookie:p.cookie,csrf:p.data.csrf};}
function fact(x,input){assert.equal(Object.keys(x).length,13);assert.equal(x.gameId,input.gameId);assert.equal(x.rowRevision,input.expectedRowRevision);assert.match(x.schemaDigest,/^[a-f0-9]{64}$/);assert.equal(x.tablesVerified,35);assert.equal(x.indexesVerified,35);assert.equal(x.foreignKeyDeclarationsVerified,3);assert.equal(x.definitionsVerified,true);assert.equal(x.foreignKeyRowsVerified,true);assert.equal(x.foreignKeyEdgesVerified,3);assert.equal(x.rowIntegrityVerified,false);assert.equal(x.nativeDrainVerified,false);assert.equal(x.deleteAllowed,false);assert.equal(x.mode,'CURRENT_DECLARED_FOREIGN_KEY_ROWS_ONLY_LEGACY_UNKNOWN');facts.push(x);return x;}
try{server=await startEditorBackend(join(own,'wrangler.jsonc'),{stageSource:false,stageLibrary:false});const admin=await login('tianyi');await ok('/api/admin/accounts',{account:'fk_owner'},admin);await ok('/api/admin/accounts',{account:'fk_other'},admin);const owner=await login('fk_owner'),other=await login('fk_other');const g=await base({action:'create',name:'外鍵實查'},owner),first={gameId:g.gameId,expectedRowRevision:'1'};
 await reject({action:'observe',input:first},owner,409,'DELETE_FENCE_REQUIRED');await reject({action:'observe',input:first},other,404,'GAME_NOT_FOUND');await reject({action:'observe',input:{gameId:'wolong-builtin',expectedRowRevision:'1'}},admin,403,'BUILTIN_PROTECTED');await reject({action:'observe',input:{...first,plan:{}}},owner,422,'REQUEST_FIELDS');await reject({action:'observe',input:{gameId:[g.gameId],expectedRowRevision:'1'}},owner,422,'DELETE_SCHEMA_INPUT');const f=await base({action:'fence',input:{...first,confirmationName:g.name}},owner),input={gameId:g.gameId,expectedRowRevision:f.rowRevision};await reject({action:'observe',input:first},owner,409,'DELETE_SCHEMA_CHANGED');checks.push('actual Root owner/admin/foreign/builtin/UUID/strictfields/rowCAS and durablefence checks; SQL skeleton NOT GameSource/normal creation');
 await action({action:'seed-installed'},admin);const saved=await action({action:'state'},admin);const x=fact(await action({action:'observe',input},owner),input);assert.deepEqual(fact(await action({action:'observe',input},admin),input),x);assert.equal((await action({action:'state'},admin)).digest,saved.digest);checks.push('actual native bounded joins on three fixed declaredFK edges, positive owner/admin exact13 facts and unchanged all scopedrows/seals/journal/audit; no global session/user counts in DTO');
 for(const table of ['content_games','installed_sources','sessions']){await reject({action:'orphan',table,gameId:g.gameId},admin,503,'DELETE_FOREIGN_KEY_ROWS');assert.equal((await action({action:'state'},admin)).digest,saved.digest);checks.push('actual deferred transaction temporarily makes '+table+' child orphan; lowlevel fixed join rejects503 and all ownedrows rollback. NOT persisted corruption, normal Root FK bypass or fullservice admission');}
 await reject({action:'deferred',input},admin,503,'DELETE_SCHEMA_ENFORCEMENT');assert.equal((await action({action:'state'},admin)).digest,saved.digest);checks.push('actual fullservice refuses deferredenforcement before row queries; isolated lowlevel orphan probes do not bypass declaration/authority port');
 for(const [kind,status,code]of [['index',503,'DELETE_SCHEMA_DEFINITION'],['row',409,'DELETE_FENCE_CHANGED'],['epoch',401,'SESSION_INVALID'],['tuple',401,'DELETE_FOREIGN_KEY_ACTOR_CHANGED']]){await reject({action:'observe',input,hook:kind},admin,status,code);const after=await action({action:'state'},admin);assert.equal(after.digest,saved.digest);assert.equal(after.lateIndexes,0);assert.equal(after.hook.fired,true);checks.push('after first FK table '+kind+' callback: '+(kind==='tuple'?'synthetic principalrole':'actual native SQL')+' exact'+status+'/'+code+' and full outerrollback; current snapshots/digests never authority');}
 await action({action:'budget'},admin);await reject({action:'observe',input},owner,503,'DELETE_FOREIGN_KEY_BUDGET');await action({action:'clear-budget'},admin);assert.equal((await action({action:'state'},admin)).digest,saved.digest);checks.push('actual10001 additional engineered sessions with valid parent FK hit fixed10000 pertable budget; no budget expansion or SQLrepair by service, fixture exclusively removes its own rows');
 await reject({action:'observe',input},undefined,401,'LOGIN_REQUIRED');await reject({action:'observe',input},owner,403,'CSRF_REJECTED',{'X-CSRF-Token':'bad'});await reject({action:'observe',input},owner,403,'ORIGIN_REJECTED',{Origin:'https://example.invalid'});checks.push('real cookie/CSRF/Origin; owned route only, productRoot unchanged');
 await server.close();server=await startEditorBackend(join(own,'wrangler.jsonc'),{stageSource:false,stageLibrary:false});assert.deepEqual(fact(await action({action:'observe',input},owner),input),x);assert.equal((await action({action:'state'},admin)).digest,saved.digest);const changed=await call('/api/auth/password',{oldPassword:password,newPassword:randomBytes(24).toString('hex')},owner);assert.equal(changed.status,200);await reject({action:'observe',input},owner,401,'SESSION_INVALID');assert.deepEqual(fact(await action({action:'observe',input},{cookie:changed.cookie,csrf:changed.data.csrf}),input),x);assert.equal((await call(`/api/games/${g.gameId}/delete`,{},admin)).status,404);checks.push('actual workerd restart and password epoch replacement requery current FK/authority/definitions; oldepoch401 newauth reobserve, publicdelete404/nativeDrain-deletefalse');
 for(const[p,h]of Object.entries({...before.inputs,...before.imports,...sourceHashes}))assert.equal(hash(p),h,p);process.stdout.write(JSON.stringify({result:'PASS-ACTUAL-DECLARED-FK-ROWS-NOT-ALL-ROW-INTEGRITY',checks,calls,facts,protected:482,sourceHashes,limits:'Three declaration edges global bounded FK rows only; no whole row/reference/provider/body/CPU/legacy/delete permission. Deferred probes actual temporary SQL rollback, tuple synthetic; no Source/installed approval/session validity. Old all482 sources and97 imports untouched.'},null,2));
}catch(error){writeFileSync(d+'failure-r'+round+'.json',JSON.stringify({message:String(error.message),checks,calls,facts},null,2),{flag:'wx'});throw error;}finally{await server?.close();}
