// Web compile → actual native initializer/rebind; no App/Clock/rule ticks.
import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{spawnSync}from'node:child_process';import{createHash}from'node:crypto';import{initializeNativeFactionSlots,rebindNativeFactionViews}from'../web/src/game/nativefactions.js';
const env={};for(const k of ['SystemRoot','SYSTEMROOT','WINDIR','COMSPEC','ComSpec','PATH','Path','PATHEXT','TEMP','TMP','USERPROFILE','LOCALAPPDATA','APPDATA','HOMEDRIVE','HOMEPATH'])if(process.env[k]!==undefined)env[k]=process.env[k];env.PYTHONDONTWRITEBYTECODE='1';env.PYTHONUTF8='1';env.PYTHONOPTIMIZE='';
const execution=spawnSync('python',['-X','utf8','-B','tools/verify_editor_reserve_compile.py'],{env,encoding:'utf8',maxBuffer:32*1024*1024,timeout:180000});assert.equal(execution.status,0,execution.stderr);let proof;try{proof=JSON.parse(execution.stdout);}catch(cause){throw new TypeError('invalid reserve compile proof JSON',{cause});}assert.equal(proof.result,'PASS-RESERVE-COMPILE-FIXED-SOURCE');assert.equal(proof.checks,162);assert.equal(proof.refusals,33);assert.equal(proof.cases.length,142);assert.equal(proof.signatures,6);
let implicitIDB=0;const prior=Object.getOwnPropertyDescriptor(globalThis,'indexedDB');Object.defineProperty(globalThis,'indexedDB',{configurable:true,get(){implicitIDB++;throw new Error('native IDB forbidden');}});const rows=[];
try{for(const item of proof.cases){const sc=item.scenario,rawBefore=sc.nativeFactionSlotRaw.slice();initializeNativeFactionSlots(sc);
for(let slot=0;slot<22;slot++){const raw=Buffer.from(rawBefore[slot],'hex'),faction=sc.nativeFactionSlots.records[slot];for(const[field,offset]of [['reserve_cav',4],['reserve_arc',6],['reserve_inf',8]])assert.equal(faction[field],raw.readUInt16LE(offset));assert.equal(faction.money,raw.readIntLE(0x20,3));assert.equal(faction.raw,rawBefore[slot]);if(slot<sc.factions.length)assert.equal(sc.factions[slot],faction);}
for(const[slot,field,value]of item.changes)assert.equal(sc.factions[slot][field],value);let cold;try{cold=JSON.parse(JSON.stringify(sc));}catch(cause){throw new TypeError('invalid owned native cold JSON',{cause});}rebindNativeFactionViews(cold);assert.deepEqual(cold,sc);for(let slot=0;slot<cold.factions.length;slot++)assert.equal(cold.factions[slot],cold.nativeFactionSlots.records[slot]);assert.deepEqual(sc.nativeFactionSlotRaw,rawBefore);rows.push({idx:item.idx,changes:item.changes,unknown:item.unknown,nativeAndColdRebound:true});
}}finally{if(prior)Object.defineProperty(globalThis,'indexedDB',prior);else delete globalThis.indexedDB;}assert.equal(implicitIDB,0);
const sha=p=>createHash('sha256').update(readFileSync(p)).digest('hex');for(const[p,h]of Object.entries(proof.inputHashes))assert.equal(sha(new URL('../'+p,new URL('../',import.meta.url))),h,p);const toolHashes=Object.fromEntries(['tools/verify_editor_reserve_compile.mjs','tools/verify_editor_reserve_compile.py','tools/content_pipeline.py','web/src/game/nativefactions.js'].map(p=>[p,sha(p)]));process.stdout.write(JSON.stringify({result:'PASS-RESERVE-COMPILE-NATIVE-COLD',chapters:20,checks:162,refusals:33,nativeCases:142,implicitIDB,signatures:6,inputHashes:proof.inputHashes,toolHashes,rows,limits:'Representation/fixed-slot byte coherence only; no abnormal pool gameplay domain/App/JS author adapter/default install or rule steps'},null,2)+'\n');
